### ISSUE TITLE
Permitir usar emojis "inline" en Whatsapp

### ISSUE THREAD

**Issue by mautematico** [loqui/im#100]
De momento, cuando seleccionamos un emoji en el cuadro de emojis, éste es enviado como único contenido del mensaje a nuestro interlocutor.

Whatsapp para Android permite usar emojis "inline", como parte del mensaje.

Loqui podría permitir esto como una mejora de baja prioridad.

**Comment by aesedepece** [comment]
Para ello se necesitaría que el botón "+" coexistiese con el de envío, y de momento la solución actual de compartir el mismo espacio e intercambiarse me parece mejor con tal de que la caja de entrada de texto sea lo más amplia posible.

Pero todo es cuestión de ver cómo lo encajamos y dar con una solución óptima.

**Comment by Gioyik** [comment]
No veo tan necesario que los emoji se muestren en el cuadro de texto si se muestran en el listado de chats. Facebook no los renderiza hasta que son enviados y son mostrados en la parte de mensajes.

**Comment by TitanNano** [comment]
I can't understand this, but from the title I would say that this already got fixed...

**Comment by TitanNano** [comment]
this got fixed with https://github.com/loqui/im/commit/aef0ef507c7d248730e7aa449b991393033ca168 and https://github.com/loqui/im/commit/886f8c5462cac50553309d9cabc6996c79007fcc
