### ISSUE TITLE
Loqui im does not receive message from whatsapp after last update

### ISSUE THREAD

**Issue by dgs28iun** [loqui/im#1007]
Hello,

My ffos flame does not receive messages from whatsapp after last update,
and it also take much more internet traffic

version of Loqui is 0.5.2a

Thanks

**Comment by petzichen** [comment]
Same in #988 - It's mystical... I think the new end-to-end-encryption is the main problem.

**Comment by Honk2** [comment]
I did some test:
Groupchat (Android/iOS/FFOS) is working
Contact chat with iOS is working
Contact chat with Android, can send and is delivered, but cannot receive.

**Comment by cmeerw** [comment]
@Honk2 did you test with the marketplace version or github sources?

**Comment by Honk2** [comment]
@cmeerw I downloaded the source tagged 0.5.2 from github, compiled and istalled yesterday  and testet right before my comment.

**Comment by cmeerw** [comment]
Ok, I'll likely tag the current soures in github as 0.5.3 tomorrow evening unless someone finds a showstopper till then (even though it's not perfect, but text messages appear to be quite stable now).

**Comment by tibtab** [comment]
It still happens that i don't receive some personal messages. I'm sorry i don't have any logs because i don't have much time now.loqui/im schrieb:Ok, I'll likely tag the current soures in github as 0.5.3 tomorrow evening unless someone finds a showstopper till then (even though it's not perfect, but text messages appear to be quite stable now).

**Comment by Peio88** [comment]
Hi,

Sometimes I can't receive messages from whatsapp (Loqui IM 0.5.2 on Firefox OS 2.1) and I have read in github that some people have the same problem.
Is the 0.5.3 version already working ?
I don't know how to use sources from github to install the 0.5.3. version on my phone. Is it possible to explain me please ?

Thank you.

**Comment by Honk2** [comment]
@Peio88 you can download 0.5.3 from the [release section](https://github.com/loqui/im/releases) 
Unpack and copy to your phone using Firefox WebIDE.

**Comment by Peio88** [comment]
@Honk2 
Thank you !

**Comment by Zeus76** [comment]
Hello:

I would like to know when will be available the version 0.5.3. in the marketplace.

Thank you!

**Comment by Aelerinya-old** [comment]
Same for me, I don't receuve messages from my contacts but they receive mines. Also I don't receive the messages I send to myself, although the little box "Typing..." appear.

**Comment by dgs28iun** [comment]
Could you please fix this issue, and make release?

**Comment by cmeerw** [comment]
Have you tried with 0.5.3 or the github sources?

**Comment by Zeus76** [comment]
Hello everyone:

I'm hoping to rise update version 0.5.3 IM Loqui the marketplace. I sent an email to support@loqui.im but I get the following message:
"Sorry, We were unable to deliver your message to the following address."

They do not go up more updates to the Marketplace?

Have you gone Loqui support IM?

Firefox OS comprehensive plan:
https://docs.google.com/presentation/d/10CPNIc_gl4ZvgeDVs_CwVkZTR5mjTs95l2QdiqficFU/edit?pref=2&pli=1#slide=id.p5

It says: "only until June 2017 may continue sending applications for Firefox OS and its updates."

Waiting for your answers.

**Comment by cmeerw** [comment]
@Zeus76 Mozilla marketplace people are very slow reviewing updates. There is nothing anyone here can do about this.

**Comment by Honk2** [comment]
Yes the marketplace review speed is very annoying. 

@cmeerw just out of curiosity : what about the domain loqui.im? It seems that this domain is not available anymore. Do you know who was the owner or if it is permanently down?
Should/Could someone update the pages here?

**Comment by cmeerw** [comment]
@Honk2 Thanks for the reminder. The domain expired last month, but wasn't available to register again. It seems it has just become available for registration again, so I have just registered it now...

**Comment by pummeluff** [comment]
Many thanks for your ongoing support everyone! 
I would love to install v0.5.3 from the release section. But how am I proceeding? May anyone can assist please?!
![grithup_053](https://cloud.githubusercontent.com/assets/18550743/14636353/3adcf11a-062b-11e6-821f-a366c8973906.png)

**Comment by cmeerw** [comment]
Just click on the "run" (right arrow) button in the top toolbar to
install and run the app.

**Comment by pummeluff** [comment]
Lovely! Ashaming.. but thanks :)

**Comment by pummeluff** [comment]
Now I tried the v0.5.3, but unluckily I don't receive messages of all my contacts (only see "typing" but no text occurs).. Any idea?

**Comment by cmeerw** [comment]
Debug logs would help.

**Comment by pummeluff** [comment]
Pardon, I am not familiar with (your) technical procedures.. I assume something with WebIDE.. Is it possible to (get it) explain(ed)?
![grithup_debuglog](https://cloud.githubusercontent.com/assets/18550743/14654662/0fac3cd6-067f-11e6-93c4-466ee501ed87.png)

**Comment by cmeerw** [comment]
Go to the loqui settings and enable "Developer mode", then "Debug
mode" and "Write log files". This should then create log files under
/loqui/logs on the device. Alternatively, watch the debug console in
WebIDE (after enabling "Debug mode" in loqui).

**Comment by pummeluff** [comment]
Great, thanks cmeerw! :) May log files have to be written for at least a couple of hours.. If not, please find a first log as following:
[2016-04-19_0.txt](https://github.com/loqui/im/files/227334/2016-04-19_0.txt)

**Comment by cmeerw** [comment]
@pummeluff please attach logs as files instead of copy/pasting them into the text box...

These are encrypted group messages - this is a known problem. What phone does the sender of these group messages use? It looks like it's getting into a ping-pong loop with encrypted/error messages...

**Comment by pummeluff** [comment]
Not sure about all sender phones, but some definitely use iphone. 
PS: Ok, changed it into attachement.

**Comment by cmeerw** [comment]
also see #1053

**Comment by cmeerw** [comment]
v0.5.5 has been uploaded to the marketplace, closing this issue now - there is still #1053 for any remaining related issues...
