### ISSUE TITLE
[0.5.2] [FxOS 2.1] [XMPP] Can't go into chat

### ISSUE THREAD

**Issue by j12i** [loqui/im#1009]
So I added a Jabber account to a freshly installed Loqui IM.
It connects to the account, and even imports my contacts from the server.
However, when I click on the pen icon, and then on one of the contacts, nothing happens. I just get taken back to the screen with the pen icon.
Also when I send a message to the phone nothing happens in the app.
Here is the log, I censored the user parts of the account names.
[2016-04-07_0.log_1.zip](https://github.com/loqui/im/files/208914/2016-04-07_0.log_1.zip)
Thanks for your work!

~~PS: I found it a bit weird that B2G said that all data from the app will be deleted, but I had the developer options on and that persisted, even though I even rebooted before reinstalling.~~
It didn't, the log I originally uploaded was from before the reinstall.

**Comment by cmeerw** [comment]
Unfortunately, XMPP is broken in 0.5.2, will be fixed in 0.5.3 (already fixed in the github sources)

**Comment by j12i** [comment]
0.5.3 landed in Firefox Marketplace today, I confirmed it works again, closing.
