### ISSUE TITLE
Tick, doble tick y mensajes no enviados (sugerencia de "tick rojo") al chatear vía Whatsapp

### ISSUE THREAD

**Issue by mautematico** [loqui/im#101]
Al conversar con los contactos de Whatsapp, Loqui IM:

[x] Pone la hora del mensaje en los mensajes "en envío"
[x] Pone un indicador azul (tick) si el mensaje ha sido recibido en el servidor, junto a la hora.
[x] Pone un indicador verde (doble tick) si el mensaje ha sido recibido por nuestro contacto, reemplazando el indicador azul.

Eso está perfecto. El problema viene cuando uno cierra la conversación para, por ejemplo, conversar con otro contacto. Entonces, Loqui IM:
[x] Borra los indicadores azules o verdes y deja exclusivamente la hora.

Esto ocurre también cuando la conexión se pierde y se recupera, y aparece la confirmación de sincronización de contactos.

Adicionalmente, Loqui IM **no**:
[] Re-intenta enviar los mensajes escritos durante una pérdida de conexión o, en general, los mensajes que no han recibido indicador azul.

Lo que imposibilita al usuario distinguir los mensajes que sí fueron entregados de los que no, una vez que los indicadores azules o verdes han desaparecido.

A muchos molesta el doble tick y sabemos que ha causado rupturas amorosas, pero más peligrosos son todavía los mensajes que no reciben confirmación de entrega al servidor (tick azul) o un indicador de no-entrega (potencial tick rojo).

Loqui IM debería:
[] Preservar los indicadores azules o verdes, es decir, no borrarlos cuando la conversación sale de pantalla. o:
[] Marcar con indicador especial (tick rojo) los mensajes no entregados al servidor (y preservar este indicador, aunque la conversación salga de pantalla). Idealmente el tick rojo servirá para re-intentar enviar el mensaje manualmente.
[] Re-intentar indefinidamente la entrega de mensajes no entregados. Para lo cual Loqui IM debe preservar en la memoria del teléfono (o la tarjeta externa) un log con los mensajes no entregados.

**Comment by aesedepece** [comment]
El reintento de envío de mensajes funciona con Facebook/Hangouts/etc., pero no con WhatsApp porque aún no he hallado un método 100% fiable para detectar si realmente la conexión a WhatsApp sigue viva o no (con XMPP+BOSH es más fácil).

Respecto a preservar los marcadores, se abordará en breve.
