### ISSUE TITLE
Opening emojis crashes Loqui IM

### ISSUE THREAD

**Issue by dodziahnert** [loqui/im#1018]
Hi!
I'm using Loqui 0.5.2 on Firefox OS 1.3.0 (downloaded from Marketplace).
Everytime i try to open emojis, my Loqui crashes. Can you please check it?

**Comment by Honk2** [comment]
Hi @dodziahnert 
I checked with the emulator V1.4 which is the oldest FXOS version available to me and it is working.
Can you provide a logfile?

**Comment by cmeerw** [comment]
@dodziahnert in what way does Loqui crash? Is it the whole browser process? Could be a resource limit then, maybe rendering all the emojis is too resource intensive for your phone...

**Comment by dodziahnert** [comment]
@Honk2 I've activated logfile generation but no log is written.
@cmeerw yes, it is the whole browser process. i'm using Alcatel Onetouch Fire c 2G with 128 MB of RAM...

**Comment by cmeerw** [comment]
I guess 128 MB of RAM is the issue then and the process gets killed
because it's running out of memory.

**Comment by dodziahnert** [comment]
So, no more emojis for me... T_T
@Honk2 , @cmeerw , thanks for your help!

**Comment by Zeus76** [comment]
Hello:

I would like to know when will be available the version 0.5.3. in the marketplace.

Thank you!

**Comment by bryanjhv** [comment]
Similar problem as @dodziahnert here. The phone is the same, an Alcatel OneTouch Fire C, with 512 MB of RAM. When I first start Loqui IM, open any conversation and try to add emoji's, the screen gets like in the picture for about 2-5 seconds. If I use them later (after this wait) in any conversation, everything works as expected.
Loqui IM version: v0.5.3
![2016-04-20-20-43-03](https://cloud.githubusercontent.com/assets/2767941/14695639/9cdb6806-0739-11e6-973d-fd7e52a06c03.png)

**Comment by Honk2** [comment]
This behaviour is normal. Because the images are not preloaded. The first tap on the emoji icon triggers the loading routine. If the images would be loaded during app start, the app start will delay.

**Comment by cmeerw** [comment]
Would it be possible to load each group on demand? So when opening the
emojis only the "people" group is loaded/rendered and other groups are
only loaded/rendered when needed.

**Comment by Honk2** [comment]
I will think about it and also try something else....

**Comment by bryanjhv** [comment]
Loqui already has a big delay when starting up, so seconds more, seconds less...
Or maybe the approach @cmeerw describes can be applied, so from 5 seconds loading it reduces to just 1 or 0.5. Or, in the last case, at least with a bit of CSS an icon of "loading" should be shown while they're loading. If not, it really seems like a crash.

**Comment by Honk2** [comment]
With pr #1042 the emojis are oaded on demand. This reduces the display delay a lot.
Also I removed the tone-emojis (skin colors), as this reduced the number of emojis in the people category by more than 100.
I tryed with a emojifont as well, but it is not displayed correctly.

**Comment by Honk2** [comment]
Fixed in 0.5.4. @cmeerw please close

**Comment by bryanjhv** [comment]
Thank you, @Honk2. Common users will not notice the change by now (in Marketplace it's still 0.5.3), but for sure the update will be uploaded soon.
