### ISSUE TITLE
Not available in my region?

### ISSUE THREAD

**Issue by vitalyster** [loqui/im#102]
I'm using FirefoxOS ROM on my android device, when I trying to install LOQUI - Firefox Marketplace says something like "not available in your region" (Russian Federation), and "ask developer to add it"
Also I have "Mrktpl dev" icon, where LOQUI available but "LOQUI install failed" when I trying to install.
I have successfully install LOQUI previously on B2G PC emulator

**Comment by Gioyik** [comment]
Not sure if the Marketplace has restrictions for Russia (i don't think so), I need to ask. If you like to try Loqui on your phone, you can clone/download the repo and push the app using the Firefox OS Simulator or the App Manager. Not really necessary download from the Marketplace to use it.

**Comment by aesedepece** [comment]
At the moment the only banned country is USA, so you should be able to download it from everywhere else.

May be this a Marketplace bug?

**Comment by vitalyster** [comment]
Maybe my phone reports it is USA, don't know where to change it, "location" is set to Europe/Moscow.

**Comment by Gioyik** [comment]
@vitalyster Are you logged in the Marketplace with a PersonaID account? Probably that's the problem and the accounts is saved with preferences filled as USA. Other question is, did you bought it by ebay?

**Comment by vitalyster** [comment]
Just installed Firefox OS Simulator 1.3 and got the same problem with Marketplace. I have install now with App Manager

**Comment by dimasv** [comment]
Saludos, lo estoy instalando en firefox OS, y cuando quiero configurar whatsapp no logro seleccionar mi pais Venezuela, el scroll de paises no funciona, que puedo hacer?

**Comment by aesedepece** [comment]
I've changed the selection of available countries to "All but China". Now it should be available for everyone as no restrictions are applied.

Can you @vitalyster check if you can download it now? Thanks.

**Comment by vitalyster** [comment]
Yes, now it available and successfully installed via Marketplace :)

**Comment by shokoshokoshoko** [comment]
Why is this app restricted in some countries?
