### ISSUE TITLE
notifications when inside a chat window

### ISSUE THREAD

**Issue by tibtab** [loqui/im#1024]
when you are reading some messages or writing something in one group, an while this receiving messages, it will make a sound, but the messages are not added to the number of unread messages shown in the right upper corner.

**Comment by Honk2** [comment]
@titab as far as I can read the code, the only location I find where the number of unread messages is shown is the chat list. I do not see any other element holding the number of unread messages.
The chat itself never shows the number of unread messages.

**Comment by Honk2** [comment]
I will try to fix this together with #1026
