### ISSUE TITLE
swipe right move often happens accidently

### ISSUE THREAD

**Issue by tibtab** [loqui/im#1027]
sometimes when I write a message and scroll through the chat history to refere to some older messages or something like this, the chat suddenly disappears and the chat-list fades in. Then I usally swipe left  to get back to the chat I was before, complete my messages and send it, but sometimes through this hole swiping right and swiping left thing I land in other chat. It happend to be embrassing when a more or less private massege finaly landed in a group chat with about 60 members xD
So maybe its possible to require the swipe right move to be bigger bevore it reacts

**Comment by Honk2** [comment]
Not sure I understand correctly, but selecting a chat is done by a tap not swipe.
Please confirm if your finger comes close the upper left corner while scrolling.

**Comment by tibtab** [comment]
when you are in a chat it is possible to swipe right to get back to the chat-list, when you are in the chat list and swipe left usually the last chat is opened. My problem is, that the gesture that is required for the swipe right move is so small that it happens quite often by accident to swipe right

**Comment by Honk2** [comment]
Ah, never saw that feature before.
I just tryed and think that this is an useless feature. Especially as swiping from the side switches the active app. So if the swipe the leave/enter a chat is longer than now there is a higher potential that it will switch to the previous active app.
So I would prefere to remove this feature. How do others think of it?

**Comment by tibtab** [comment]
I think this feature is helpfull and the gesture don't have to be sooo big but at the moment it is just very small. Changing between apps requires me to start swiping at the edge of the screen not a bigger swipe gesture.

**Comment by Honk2** [comment]
With pr #1048 the swipe detection distance is adapted to the screen resolution.
The original hard coded distance was 30 pixels. A shaky tap is the same than a swipe on higher resolution screens.

**Comment by Honk2** [comment]
Fixed in 0.5.4 @cmeerw please close
