### ISSUE TITLE
[Whatsapp] Scrollbar & Pictures

### ISSUE THREAD

**Issue by Peio88** [loqui/im#1031]
Hy everybody,

I've Loqui IM 0.5.3 with Firefox OS 2.1 on my ZTE Open C.
I've seen two problems with whatsapp :
- scrollbar does'nt work in chat windows
  so I can't see old messages
- I don't receive picture from foreign numbers
  I live in Belgium, I receive pictures from belgian numbers but with other numbers I don't receive...

Is their somebody who have same problems ?
Is their any solution ?

Thanks,

P.

**Comment by Peio88** [comment]
Anybody have these problems ?

**Comment by nezarjor** [comment]
also me have the same problem in klif phone

**Comment by saimonn** [comment]
Same problem with Loqui IM 0.5.6 and FFOS 2.1 on ZTE Open C:
- I can not scroll chat windows. 

I did not test receiving picture from foreign numbers, so I can't confirm this part.

**Comment by Ray-ne** [comment]
Same problem with Loqui IM 0.5.6  on my Lg Fx0.       -I cannot scroll up or down in chat windows.              -i cannot tell if some of my messages are sent or not

**Comment by saimonn** [comment]
unlike the subject of the issue, the scroll problem also applies to others protocols (tested with XMPP chat).

The display scrolls to bottom when I send a new message, but the elevator or drag'n'drop up/down doesn't work.

**Comment by Ray-ne** [comment]
so can it be fixed please

**Comment by TitanNano** [comment]
This is a platform issue. Nothing inside Loqui. Duplicate of #910, #881 and #742.
