### ISSUE TITLE
fixed: Can't send anything in WhatsApp after current changes in code

### ISSUE THREAD

**Issue by MaleCat** [loqui/im#1032]
Hi everyone,

after including current changes (Apr 17, 6.07 pm UTC) it is not possible to send anything in whatsapp any more. Additional no emoji icons can't be listed any more :(

My System: Firefox OS 1.3 at a ZTE Open C

Last running version of Loqui IM was 0.5.3 with code from Apr 12 as far as I can follow...

Could the reason be some substitution of "div" instruction by "span" in code?

Using rollback to previous code version now...

Thanks for help

**Comment by MaleCat** [comment]
Update: can't receive messages from existing contacts in whatsapp until I send a new message first after re-installing Loqui IM

**Comment by cmeerw** [comment]
When you re-install Loqui IM you lose the encryption state which kind of explains the behaviour. Loqui IM tries to recover from these situations, but it might not always work (probably depends on the other client).

**Comment by Honk2** [comment]
I tested the current source in the simulator with OS 1.4 and setting the hardware to ZTE Open C and it works fine. 
Regarding the emojis, there are no breaking changes from 12th Apr until now.
The div/span thing has no effect on the communication itself.
Did you try the latest source from today?

**Comment by MaleCat** [comment]
The latest source from today shows this result exactly :( (No send possible)

Trying once again now..

Update: the same result. Sending not possible. Send button does not appear. Adjusts tried: send with enter and w/o enter

No emojis will be listed (so can't be choiced)

**Comment by Honk2** [comment]
Can you look into the log file or connect to WEBIde to see if there are any error messages?
Not sure, maybe loqui is not working with 1.3 anymore.
If you dare, maybe upgrading to 2.0 would do the trick.

**Comment by MaleCat** [comment]
were can I find them?

Upgrading to 2.0 seams not practicable (at the moment)...

**Comment by tibtab** [comment]
Loqui-settings -> developer-mode -> write log files
/
enable developer mode in your phones settings -> enable debugging in your phones settings -> enable debug mode in loqui developer settings -> connect your phone to the pc -> start firefox browser (pc) -> "SHIFT"+"F8" -> select your phone on the right side -> allow debugging (phone) -> select loqui on the left side -> click on the tool icon -> change to the categorie console

Good upgrading instructions here: http://builds.firefoxos.mozfr.org/doc/en/devices/zte-open-c-eu
At the Moment I'm using 2.2, there are some Bugs, but I think what you gain through the update weighs more than the little unstablebility

**Comment by MaleCat** [comment]
[2016-04-17_0.zip](https://github.com/loqui/im/files/222859/2016-04-17_0.zip)

**Comment by Honk2** [comment]
@MaleCat there are no errors inside the log. I just can see that the emoji button is triggered 4 times within 3s and than the trugger to close the emojis is 5 seconds after the first trigger.
If there is no crash, try to be more patient. On my phone it takes about 10s to open the emoji pane for the first time. This is because all images (1600+) will be loaded during the first opening of the emoji pane. From that time on, opening the pane only takes 2s.

**Comment by MaleCat** [comment]
..in the previous code it works fine and takes a couple of seconds too. But here no reaction at no time...

I'll post a longer log and I hope for more informative content

**Comment by MaleCat** [comment]
[2016-04-17_0.zip](https://github.com/loqui/im/files/222876/2016-04-17_0.zip)

**Comment by Honk2** [comment]
Just to be sure:
By previous code you mean already the new full width emoji panel with the category select buttons?
And you can see the emoji button, the pprer clip and mic?

**Comment by MaleCat** [comment]
left the emoji button and right paperclip and mic. Right!

In the previous code all was fine. Full emoji panel with all category were available and could be used.

Touching the emoji button now takes no effect. Simply nothing happenes.

Usually during entering text the paper clip and mic changed to the button for sending. But in this code no symbol change occures and so the message text can't be sent. Tried to send a file (pic or so) and this seams working. But no text message able to send. And no emoji can't be listet and so not sent too.

Tried adjust settings for sending with enter key or without it. Both were not successful. Sending text is not possible (because of send button missing)...

**Comment by MaleCat** [comment]
With this new Version 0.5.4 this issue seams fixed now. All works fine :)

Thank you a lot

**Comment by Honk2** [comment]
Issue fixed in 0.5.4 @cmeerw please close
