### ISSUE TITLE
Unable to receive message

### ISSUE THREAD

**Issue by shalu02** [loqui/im#1034]
Message can be sent but no message is received while we still see the typing sign yet no message comes in

**Comment by cmeerw** [comment]
Log files? Loqui version?

**Comment by cmeerw** [comment]
closing as duplicate

**Comment by shalu02** [comment]
But the issue isnt solved yet

**Comment by cmeerw** [comment]
How do you know? Have you tried with the current github sources? Have you provided debug logs?
