### ISSUE TITLE
Initial wizard only works in FF

### ISSUE THREAD

**Issue by popey** [loqui/im#1037]
Trying to test loqui in chrome / chromium, the initial wizard with the horizontal animation doesn't work in those browsers, but works fine in Firefox. The result is you get a completely blank (dark coloured) window content in those browsers. While I realise loqui was originally intended to be for Firefox OS, perhaps we could use something more browser agnostic?

**Comment by cmeerw** [comment]
Feel free to work on it.

**Comment by popey** [comment]
I took a look and it seems there is use of Javascript which is unsupported by Chrome/Chromium such as script type="text/javascript;version=1.7" . So looks like it will be quite a bit of work.

**Comment by cmeerw** [comment]
Well, yes... As I said, feel free to work on it...

**Comment by cmeerw** [comment]
Most of this has been fixed in #1071 - the remaining version=1.7 are needed for Firefox OS 1.3 support, but can be removed when using Chrome. Closing this one, there is #944 for anything related...
