### ISSUE TITLE
Facebook queda en Sincronización y no avanza

### ISSUE THREAD

**Issue by deimidis** [loqui/im#104]
¿Cuál sería la mejor forma de conseguir información sobre el error que pueda estar pasando para poder enviarlo?

Gracias

**Comment by willyaranda** [comment]
`adb logcat | grep Gecko`

Para ello, activa las trazas en el menú desarrollador.

**Comment by Gioyik** [comment]
Hola Guillermo,

Ya hay un bug relacionado #98 con su solucion, probablemente estes usando la version que esta en la Marketplace la cual es la tiene el error (0.2.1) y aun no se ha subido la update (0.2.2) con los ultimos cambios hechos. Supongo que hoy se envia una actualizacion a la Marketplace con estos ultimos cambios. O puedes descargar el repo y usar el simulador o el app manager para probar los ultimos cambios hechos.

Saludos

PD: Lo cierro por ahora, pero si despues de la update continua el problema Ping me @deimidis y abrimos el issue de nuevo.
