### ISSUE TITLE
No uses tanta memoria

### ISSUE THREAD

**Issue by willyaranda** [loqui/im#105]
https://github.com/waalt/loqui/blob/master/scripts/anonymous/coseme.js#L4932

Sólo cuando nos damos de alta, mira el comentario

**Comment by aesedepece** [comment]
No termino de pillar lo que quieres decir...

**Comment by willyaranda** [comment]
El comentario de ese fichero es "Pon este fichero sólo en el momento del
registro". Hay unas cadenas del copón, que además hay que transformar para
poder hacer el registro. No sé cuánto se podría salvar, pero supongo que
igual 1 mega sí.

On Sat, Nov 30, 2013 at 3:42 AM, Adán Sánchez de Pedro Crespo <
notifications@github.com> wrote:

> No termino de pillar lo que quieres decir...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/waalt/loqui/issues/105#issuecomment-29544441
> .

## 

Guillermo López Leal - @willyaranda
http://www.pijusmagnificus.com/

**Comment by bdcomp** [comment]
@aesedepece It looks like this issue been fixed months ago...
