### ISSUE TITLE
Getting bad token

### ISSUE THREAD

**Issue by noumansami83** [loqui/im#1059]
https://v.whatsapp.net/v2/code?method=sms&in=3123456785&cc=92&
id=%29%f8%86%97%99%e8%09nt%a6%d3%b1%8d%2f%ee9f%d0%fdc&lg=en&lc=PK&
token=b6549fecee984eb90a5f1d50156e1ba0
&sim_mcc=410&sim_mnc=01

upon this request I am seeking bad token...I have got this by debug mode in WART.exe

**Comment by cmeerw** [comment]
What does WART.exe have to do with LoquiIM?

**Comment by noumansami83** [comment]
I just want to get password and got this from debug mode...I don't know whats the issue

**Comment by cmeerw** [comment]
Well, it's not related to LoquiIM...

**Comment by noumansami83** [comment]
I want to make use of watsapp API in .net so need a password for my Watsapp number but unable to get code so getting above eerror of TOKEN
