### ISSUE TITLE
Boton seccion codigo de activacion

### ISSUE THREAD

**Issue by Gioyik** [loqui/im#106]
Muchas veces he recibido ya el codigo de activacion para activar mi telefono con Whatsapp, pero por cuestion de la vida desinstalo/termino el proceso/reinicio el telefono y cuando intento abrir Loqui de nuevo me encuentro con que tengo que enviar de nuevo la solicitud para que me llegue el codigo de nuevo y lo mas probable es que Whatsapp me ponga a esperar miles de millones de horas para que llegue de nuevo. Seria bueno tener un boton en la parte donde se pone el numero que diga algo como `Ya tengo un codigo` para ir directamente a poner el codigo que desde un principio nos llego.

He estado mirando el archivo `coseme.js` y he intentado esto:

``` javascript
  var smsReq = $('<button/>').data('role', 'submit').style('backgroundColor', data.color).text(_('SMSRequest'));
  var confirmCode = $('<button/>').data('role', 'submit').style('backgroundColor', data.color).text(_('ReConfirmCode'));
  var back = $('<button/>').data('view-section', 'back').text(_('GoBack'));
```

y agregando mas abajo 

``` javascript
  smsReq.bind('click', function () {
    ====some awesome code here that @aesedepece did====
  });

  confirmCode.bind('click', function () {
    var article = this.parentNode.parentNode.parentNode;
    var provider = article.parentNode.id;
    sms.addClass('hidden');
    code.removeClass('hidden');
  });
```

pero no ha funcionado del todo. Podrias decirme que se tiene que tener en cuenta para agregar el boton? Ya me habia acostumbrado a la estructura anterior en donde todo estaba en el `bindings.js` :S

**Comment by aarizkuren** [comment]
Buenas,
he estado mirando esta issue, y con el código que tu has puesto, y añadiendole:
<code>ReConfirmCode=I've code</code>
en /l10n/en.ini
ya puedes ver el boton.

El problema es que no se exactamente que es lo que se necesita para hacer el login en el servidor de whatssap, he visto que crea un deviceId que lo guarda en la SD como ".coseme.id", y creo que utiliza este id para hacer el registro, pero no se como se genera, o si es un id que lo devuelve el servidor.

Si para registrarse únicamente necesitamos el deviceId y el code que nos dan, se podria llegar a reutilizar el código. Si alguien me puede aclarar como funciona lo del deviceId, creo que puedo ponerlo en funcionamiento.
gracias y un saludo

**Comment by aesedepece** [comment]
El deviceId sirve para que una vez se halla confirmado el número en ese dispositivo, si se reinstala la app, no haga falta recibir un nuevo código por SMS; lo que ocurre en su lugar es que al pedirle el código, el servidor de WhatsApp automáticamente nos da el número por válido.

Es una cadena aleatoria porque si fuera fija, podrías robar la cuenta a cualquier otro usuario de Loqui o Wassap.

**Comment by Gioyik** [comment]
@aarizkuren Claro, ya estaba agregada esa linea, sin embargo seguia sin mostrarse. Lo unico que se necesitaba era agregar esta linea:

``` javascript
  smsButtons.append(confirmCode).append(back);
  sms.append(smsButtons);
```

Voy a hacer un commit con el fix para esto :)

**Comment by aesedepece** [comment]
Genial, gracias a ambos por poneros con ello tan rápido.

BTW creo que voy a dedicar un día entero a comentar cada una de las funciones aparecidas recientemente, porque hay partes bastante chungas que entiendo que cuestan bastante intuir como trabajan y a más de uno les echará atrás a la hora de colaborar...

**Comment by Gioyik** [comment]
@aesedepece Podriamos usar la Wiki que trae integrada Github, no? O podriamos hacerlo interesante:

http://ricostacruz.com/flatdoc/

**Comment by aesedepece** [comment]
@Gioyik LOL that link crashes my Firefox UX 28.0a1

**Comment by Gioyik** [comment]
@aesedepece WTF??? I am using that version and it doesn't crash me. 

Just to ask, at this moment with the last changes, Loqui is running you without any problem? I ask because I continue getting stuck in "Connecting" when i try to add an account.

**Comment by aesedepece** [comment]
Yes, it works in on both 1.3 and 1.1

**Comment by Gioyik** [comment]
Ok, i think that Loqui is trolling me. :P

**Comment by aesedepece** [comment]
¿Puede ser que nos hayamos cargado algo?
https://twitter.com/CodingFree/status/406911468815130624

**Comment by Gioyik** [comment]
Parece que si, no esta funcionando :S

**Comment by Gioyik** [comment]
Parece que no ha sido que me hemos tocado algo que no se debia, mas bien parece que me ha faltado codigo para implementar en la funcion. :P

**Comment by Gioyik** [comment]
@aesedepece La cuestion es la siguiente. El procedimiento esta bien, el boton muestra lo que tiene que mostrar y tal cual como funciona, funciona bien. Sin embargo quien tiene el problema es la funcion que valida el codigo, ya que en la funcion se valida toda la informacion que ha dado el usuario anteriormente, en pocas palabras al validar toma lo que ingresas en los campos de telefono, pais, codigo, etc... 

Lo que se me ha ocurrido es que al momento en que se ingresen estos datos, se guarden en el archivo `.coseme.id` y que al validar el codigo tome los datos que hay alli y no que pida los tenemos que ingresar para que nos llegue el codigo de nuevo, que es justo lo que no queremos.

Se me ocurrio esto pensando en que el archivo `.coseme.id` se genera al momento de validar el codigo de activacion, pero tal parece que no es asi. Y aun sigue faltando el resto de codigo que iria en el `else` de la funcion validar para que tome los datos del archivo y no los del input. Quedaria mas o menos asi:

``` javascript
   validate.bind('click', function () {
    var article = this.parentNode.parentNode.parentNode;
    var provider = article.parentNode.id;
    var user = $(article).find('[name="user"]').val();
    var cc  = $(article).find('[name="country"]').val();
    var rCode = $(article).find('[name="rCode"]').val().replace(/\D/g,'');
    var deviceId = $(article).data('deviceId');
    if (cc && user && rCode && deviceId) {
      var onready = function (data) {
        console.log(data);
        if (data.type == 'existing') {
          var account = new Account({
            user: user,
            cc: cc,
            data: data,
            provider: provider,
            resource: App.defaults.Account.core.resource,
            chats: []
          });  
          account.test();    
        } else {
          console.log('Not valid', 'Reason:', data.reason);
          Lungo.Notification.error(_('CodeNotValid'), _('CodeReason_' + data.reason, {retry: data.retry_after}), 'exclamation-sign', 5);
        }
      } else {
          //Funcion que tome los dato del archivo guardado anteriormente y los valide sin problema
      }
      var onerror = function (error) {}
      Lungo.Notification.show('copy', _('CodeValidating'));
      CoSeMe.registration.register(cc, user, rCode, onready, onerror, deviceId);
    } 
  });
```

Hice un commit pero creo que no es la solucion, o almenos por ahi va la cosa. Lo que si quisiera es saber un poco acerca de cuando se genera el archivo `.coseme.id`, y si es posible que lo que este alli valide con el codigo no mas. Si tienes una mejor solucion encantado de escucharla, la mia la tengo clara ahorita, y al segundo me dio cuenta que no funciona.

**Comment by aarizkuren** [comment]
Buenas,
Creo que deberiais de darle prioridad a este asunto, para así permitir a la gente que queremos colaborar en el desarrollo o simplemente, en testear la aplicación, una forma más fácil de poder hacerlo. Yo ahora mismo estaba intentando solucionar un error que me ocurria, y tambien estaba mirando para implementar las imagenes en el chat, pero como whatsapp ya no me manda mensajes hasta pasado 2 dias, no puedo hacerlo.
Por esto creo que si solucionamos este tema, podremos avanzar más rapidamente con los demás

un saludo
PD: Ya lo siento, pero me explico con el culo

**Comment by aesedepece** [comment]
@aarizkuren Estoy de acuerdo, alta prioridad a esto.

No obstante, ten en cuenta que aunque tengas el código de activación, este no es válido una vez pasado unos minutos desde que te lo enviaron, y de hecho sólo se puede utilizar una vez cada código.

**Comment by aesedepece** [comment]
@Gioyik El archivo `.coseme.id` contiene un código aleatorio que se envía al servidor de WhatsApp como identificador del dispositivo.
Una vez que el servidor comprueba la validez del número telefónico mediante el SMS, almacena ese deviceID para que la próxima vez que le vuelvas a pedir el SMS desde ese mismo dispositivo, no te lo envíe sino que directamente te responda la petición toda la información de la cuenta.
Dentro de esa información de la cuenta está la contraseña, pues en definitiva todo este proceso de "registro" sirve para obtener una nueva contraseña que usar en el proceso de autenticación a la hora de conectarse.

**Comment by aarizkuren** [comment]
Hay una cosa que no me queda clara, 
Entiendo que en <code>.coseme.id</code> se guarda un codigo aleatorio que se manda en el primer request al servidor de whatsApp, con el nº de telefono y algun dato más imagino.
El servidor hace sus comprobaciones y decide que tiene que mandarte un sms
Se introduce el codigo que nos dan, y se vuelve a mandar a whatsapp para que valide.
Una vez validado whatsapp te devuelve algo? algun id? algo que podamos exportarlo/importarlo? No termino de ver como hace luego la aplicación para autenticarse en whatsapp. Imagino que guardara algun dato, y si lo guarda, me imagino que podemos exportar/importar esa información no?

**Comment by aesedepece** [comment]
WhatsApp devuelve un objeto con el fullJid de la cuenta (34666123456@s.whatsapp.net), la fecha de expiración, el tipo de cuenta, la contraseña y algún dato más.
En cuanto se reciben esos datos, se guardan en `App.accounts[n].core.data`, y eso basta para probar la cuenta con `App.accounts[n].test()` o iniciar sesión con `App.accounts[n].connect()`.

**Comment by aarizkuren** [comment]
Y ves factible poder hacer algun tipo de importación / exportación de esos datos? aunque sea de una forma más manual, para evitar robo de datos, o que sea algo que se pueda desactivar/activar dependiendo si estas debuggeando o no.
Con esto tambien estaria bien, añadirle a la aplicación un estado (debug/produccion), para que no guarde todos los logs estando en producción por ejemplo.

**Comment by aesedepece** [comment]
Cuando estuve haciendo las primeras pruebas con WhatsApp, aún no existía el formulario de registro y directamente tomaba los datos de un JSON. La verdad es que para debugging, no estaría mal recuperarlo.

+1 a la flag de debugging/producción. ¿Cómo lo veis mejor, como opción de "compilación" o como ajuste dentro de la aplicación?

**Comment by Gioyik** [comment]
:+1: a la flag.

A mi me pareceria mejor como ajuste dentro de la aplicacion. Si podemos tener esta funcionalidad tan solo activando y desactivando un boton pues mucho mejor, a veces se vuelve aburridor estar haciendo Push para ver un cambio minimo y debuggear todo denuevo.

**Comment by aesedepece** [comment]
¿Qué decisión tomamos respecto a esta feature? ¿La pulimos o la dejamos para más adelante? Ya he explicado que su utilidad es hasta cierto punto limitada:

> Aunque tengas el código de activación, este no es válido una vez pasado unos minutos desde que te lo enviaron, y de hecho sólo se puede utilizar una vez cada código.

Ahora me asalta una duda: ¿Existe esta opción en el cliente original de WhatsApp?

**Comment by aarizkuren** [comment]
Ni idea si existe en el original.

Yo creo que se tendría que poder exportar de alguna forma lo que el programa guarda para conectarse a whatsapp, para poder importarlo/copiarlo, aunque sea un proceso manual. Siendo como es firefoxOS una plataforma bastante Beta, creo que puede ser bastante frecuente que la gente actualice la plataforma, y es posible que te quedes sin los datos.
Por esto decía que aunque sea en una forma de debugging o algo así, estaría bien tener esta feature. Por lo menos a mi me facilitaria mucho las cosas, porque suelo desarrollar desde diferentes maquinas, y en cada una de ellas el app manager de firefox, mete la app como si fuese otra nueva, y claro vuelve a pedir el sms...

Pero como veáis, si veis que es mucho lío, mejor pulir otras cosas antes :D

**Comment by aesedepece** [comment]
@aarizkuren  Si quieres llevarte una cuenta de un equipo a otro, puedes exportarla con:

``` javascript
JSON.stringify(App.accounts[0].core);
```

E importar en el otro con:

``` javascript
App.accounts[0] = (new Account(JSON.parse(/* Pon aquí el JSON de la exportación */)));
App.accounts[0].save();
location.reload();
```

No sé si se me escapa algo, creo que con eso debería bastar...

**Comment by aarizkuren** [comment]
Ok, gracias, 
con esto a mi me vale :laughing:

**Comment by Gioyik** [comment]
Realmente la cuestion con este issue es que al ser un poco inestable el soporte de Whatsapp en Loqui esta funcionalidad hace un poco mas facil el testeo y mas aun con la cosa de tener que hacer los request al servidor de Whatsapp y que llegue o no el mensaje, bla, bla, bla. En el cliente original no existe esta opcion, siempre he querido que la agreguen, pero no lo esta. 

Creo que podriamos quitar este issue gracias a que los issue #112, #99 y #97 han sido solucionados, supongo que ya tendria mas estabilidad la integracion con Whatsapp. Mejor trabajariamos en una funcionalidad que nos permita importar cuentas, igualmente hay un issue abierto desde hace tiempo para ello (#18). Con lo que ha explicado @aesedepece creo que es mas que suficiente para hacer esta funcionalidad.

Ahora es cerrar este issue, y revertir los cambios que se han hecho gracias a este issue. Realmente me parece que esta mejor la integracion con Whatsapp y los problemas se reduciran mucho mas ahora con los issues resueltos. Les parece parece la decision?

review? @aarizkuren @aesedepece

**Comment by aarizkuren** [comment]
por mi sin problema, cuando necesite importar la cuenta, con lo que ha puesto ahí @aesedepece creo que ya podré hacerlo.

**Comment by aesedepece** [comment]
:+1 Si vemos más adelante que sigue haciendo falta el botón, lo recuperamos.
