### ISSUE TITLE
Issue in Getting Code : Bad Token

### ISSUE THREAD

**Issue by noumansami83** [loqui/im#1060]
https://v.whatsapp.net/v2/code?method=sms&in=3123456785&cc=92&
id=%29%f8%86%97%99%e8%09nt%a6%d3%b1%8d%2f%ee9f%d0%fdc&lg=en&lc=PK&
token=b6549fecee984eb90a5f1d50156e1ba0
&sim_mcc=000&sim_mnc=00

I am getting above message from WART.exe, on setting debug mode I found "Bad Token". I am using WART.exe to get code but its not working.  its

**Comment by cmeerw** [comment]
You have to ask this question the WART.exe developers, this has nothing to do with LoquiIM, please stop opening issues here that are not related to LoquiIM!
