### ISSUE TITLE
Problems with App.importData

### ISSUE THREAD

**Issue by tibtab** [loqui/im#1062]
can't import my data at the newest build, I enter the right password, but loqui says that the pw is false
also could be a problem with exporting at 0.5.3?
my backup file now has a size of 17.649 KB maybe it is to big to get ex- and imported properly?

**Comment by tibtab** [comment]
seems to be the first thing. 0.5.4 can't import any backups

**Comment by Honk2** [comment]
Well, probaply it is because of the new background image export. Seems I missed the case of importing a backup without images. I will check later.

**Comment by Honk2** [comment]
@titab you are using the latest source with image export? Or the release 0.5,4?

I just tries to reprocue this, ny saving a backup with 0.5.3 and importing into 0.5.4. It works.

**Comment by Honk2** [comment]
@titab pr #1063 fixes this issue

**Comment by tibtab** [comment]
Have this problem again, can't import Data at 0.5.6
BTW since fix-1029 it takes very much time to imort and export Data. It seems to have problems with something. Backups from 0.5.5 are much smaller than these before.

**Comment by tibtab** [comment]
hey, @cmeerw do you have an idea what could be done about this? I would love to test the newest build but since I can't import my data... :/

**Comment by Honk2** [comment]
@titab The the background images are increasing the backup size. The images are converted to JSON object and encrypted. This takes time and increases the size of the backup. This is due to your request #1029 It is not possible to just store the image path.

**Comment by Honk2** [comment]
I just did some test.
If I bypass the encryption, it is working. The decryption fails...
Thus this issue is not related to the latest changes regarding Backup or to the backup file size.
Interrestingly I do not see any error messages...

**Comment by Honk2** [comment]
The problem are accounts without own avatar. These accounst cause a decryption error.
Until this is fixed, try adding an avatar to all of your accounts.

**Comment by cmeerw** [comment]
the decrypt failure should be fixed with #1105

**Comment by tibtab** [comment]
Yes, it is, thanks! :D

Am 06.06.2016 um 20:50 schrieb Christof Meerwald:
