### ISSUE TITLE
[WhatsApp] suddenly don't receive any messages in some groups any more

### ISSUE THREAD

**Issue by tibtab** [loqui/im#1076]
I even don't find them in the logs

**Comment by sagardahale** [comment]
I'm facing same since i updated loqui to 0.5.5

**Comment by tibtab** [comment]
This problem occured for me even befpre I updated to 0.5.5
loqui just stopped receving messages from this group but the others still receive my messeges

**Comment by ElPopi** [comment]
Me too, BUT today i've quit all non-working groups and then re-joined them. Now groups are working fine...

**Comment by cmeerw** [comment]
Closing, if there is any issue remaining we need to have debug logs
