### ISSUE TITLE
[WhatsApp] Can't receive verification SMS

### ISSUE THREAD

**Issue by 03927e9c** [loqui/im#1095]
FF OS 2.2 latest Loqui version (from MK) as today.

I don't get any error, it just wont arrive.

**Comment by cmeerw** [comment]
I keep repeating myself... any debug logs?

btw, didn't you want to move to pidgin?

**Comment by 03927e9c** [comment]
I don't know what is a debug log or how to get it.

I won't engange in any questions that's not related to fix this issue. Thanks.

**Comment by 03927e9c** [comment]
@cmeerw Thanks for the help buddy
