### ISSUE TITLE
canny receives new chats 

### ISSUE THREAD

**Issue by moathkh** [loqui/im#1098]
When any contact try to chat with me it doesnot  pop up any message, even saved or in saved.
FX0 Firefox OS 2.6 liquid. 5.6

**Comment by cmeerw** [comment]
Please see https://github.com/loqui/im/wiki/Reporting-Bugs

**Comment by moathkh** [comment]
I don't received any chat so how the log can detect it.
the other side send by one tick but the double tick not appears even the last seen is online.
so the log file will never detect anything .

please help

**Comment by moathkh** [comment]
i already send the log files

**Comment by cmeerw** [comment]
The is the possibility that there is an issue on the receiving side of
Loqui which prevents the message from being displayed (but which would
still show up in the log file).

So please provide a log file covering the time period where you are
sure a message has been sent to you.

**Comment by cmeerw** [comment]
Ok, just seen the log files...

Please try sending that contact a message and see if you can then get
a reply.

**Comment by 03927e9c** [comment]
I can't receive any groups message.

**Comment by moathkh** [comment]
any updates guys

**Comment by cmeerw** [comment]
@moathkh please see https://github.com/loqui/im/issues/1098#issuecomment-222783504

**Comment by moathkh** [comment]
its opened by me sir,
#1098

**Comment by cmeerw** [comment]
yes, and I did ask for additional information.

**Comment by moathkh** [comment]
what info do you ask for 
you can try there is not any chat received from any contact.
you can try sir

**Comment by cmeerw** [comment]
As mentioned "Please try sending that contact a message and see if you
can then get a reply." (with debug logs)

**Comment by moathkh** [comment]
I send log file ,
after send chats from FX0 to another device then it received chats.

**Comment by cmeerw** [comment]
Ok, so sounds like it's working now... Not sure if there is any other/better way to recover from this situation...

**Comment by moathkh** [comment]
so no way to recived  new msgs is that a right solution

**Comment by cmeerw** [comment]
Well, this is just a one-off to recover from a missing crypto session.

But the main question is, how did you get into that state? Last week's
log file suggests that you must have sent that contact an encrypted
message at some point, but then lost the crypto session information
resulting in decryption errors when receiving encrypted messsages from
that contact...

**Comment by bofelo2** [comment]
I also cannot see any received messages

**Comment by bofelo2** [comment]
Loqui 1.5,whatsapp

**Comment by cmeerw** [comment]
@bofelo2 there is no Loqui 1.5 and as everyone else you'll need to provide the exact same information as requested here

**Comment by moathkh** [comment]
guys what exact data that you want me to provide ?????

**Comment by cmeerw** [comment]
Well, the log files suggest that at some point you did send an
encrypted message to that contact, but then lost the crypto session
state and therefore couldn't decrypt any messages from that contact
any more (until you sent another message to that contact again). So it
would be helpful if you could explain what you did that could have
resulted in the loss of session information.
