### ISSUE TITLE
[WhatsApp] Decrypt Error in direct message

### ISSUE THREAD

**Issue by jambolo1970** [loqui/im#1117]
I 
[2016-06-28_1.log.zip](https://github.com/loqui/im/files/341795/2016-06-28_1.log.zip)
[2016-06-28_0.log.zip](https://github.com/loqui/im/files/341796/2016-06-28_0.log.zip)

receive direct messages labeled "decrypt error" attach log files

I do not know why but I have used the same number on Android for one day, without deleting the user but making postpone activation sms loquiIM

**Comment by cmeerw** [comment]
And if you send that contact a message, can you then get a reply to
that?

**Comment by jambolo1970** [comment]
in some tests done last night, with a phone number on Android and on my firefox os, if I active OTR i see the messages, just that OTR whenever you re-run loquiIM,this  sends a message to open chat with the inscription ?OTRv26?, and this and unnecessary for those who receive.
I don't have tried to follow the steps to unistall my number from whatsapp with Android and then Reinsert with loquiIM to disable encryption on my user

**Comment by marcfp** [comment]
i have the same problem. I recive "decrypt error" while i don't leave the group and join again ... If i make it ... leave and join again, i recive messages correctly.
I don't know if it can help ...

**Comment by linganitafa** [comment]
I have the same problem,i receive decrypt error.please help

**Comment by jambolo1970** [comment]
[2016-07-04_0.log.zip](https://github.com/loqui/im/files/528810/2016-07-04_0.log.zip)same problem of @marcfp and @linganitafa  and i attach the log file.
both groups both direct message with some users out DECRIPT ERROR.
I hope can help to find problem.

**Comment by cmeerw** [comment]
I don't see any DECRYPT ERRORs in those log files.

In fact the log files show that 2 encrypted messages have been
received that were both successfully decrypted.

If you were a member of a group when you (re-)installed LoquiIM then
you can expect decrypt errors due to missing encryption session
information. (don't do that - leave and re-join the group after
re-installing LoquiIM).

**Comment by jambolo1970** [comment]
to last summer I uninstalled loquiIM  (ver. 5.4) and I only recently reinstalled it from the app store (ver. 5.9), where I had the same problems.
since you gave me the same advice, I did want in the group with a different number, but the problem persists.

for the first problem "direct message" I'm not sure the flag was active on the log

for the second problem, however, he was active in the group and the administrator of the group add me in it group with an another number, but not solved
[2016-10-14-09-50-25.png.zip](https://github.com/loqui/im/files/528958/2016-10-14-09-50-25.png.zip)
attach the screenshot of error and log

**Comment by cmeerw** [comment]
The logs don't show any messages being received.

BTW, the screenshot shows the last message received with a DECRYPT
ERROR for the 6th October, the logs start from the 10th...

**Comment by cmeerw** [comment]
anyone tested this yet?

**Comment by nfsprodriver** [comment]
Yes, but the DECRYPT ERROR problem persists, possibly because of the upper reasons. So you should reopen this issue. Any Firefox OS testers?

**Comment by cmeerw** [comment]
For Ubuntu the reason is completely unrelated, I believe it's not
happy about String.fromCharCode or something similar...

**Comment by jambolo1970** [comment]
in firefoxOS I attach my log file and screenshot
[2016-10-17_0.log.zip](https://github.com/loqui/im/files/536264/2016-10-17_0.log.zip)
for the problem of Decrypt Error

**Comment by cmeerw** [comment]
@jambolo1970 which version of LoquiIM did you use for that log? 0.5.9 from the marketplace or a current build from github? It looks like it wasn't the current build from github.

**Comment by cmeerw** [comment]
@jambolo1970 so your log is definitely not with the current github sources...

**Comment by jambolo1970** [comment]
@cmeerw 
the version of LoquiIM is 0.5.9a from marketplace, the smartphone is 6015x alcatel fireE and the versione of OS is 1.3.0.0-01001

**Comment by cmeerw** [comment]
@jambolo1970 well, ok... but as I have closed this issue with #1153 I was interested in test results with that fix included... any logs with versions that don't include that fix aren't really useful at that point anymore (it's just confusing and can delay releasing the fix to the marketplace).

**Comment by jambolo1970** [comment]
@cmeerw  I'm sorry I thought it was still persistent the problem, wait for the update at this point, 
I hope very soon

**Comment by cmeerw** [comment]
Well, Mozilla has now shut down the Marketplace to updates, see https://wiki.mozilla.org/Marketplace#App_Submissions

**Comment by jambolo1970** [comment]
the update at 5.10 are OK !, for now no error decrypt. good job.
