### ISSUE TITLE
Google hangouts

### ISSUE THREAD

**Issue by aticat** [loqui/im#1122]
Möchte gern Liqui IM mit Google Hangous verbinden.
Warum funktioniert das nicht?

Why I can't connect Loqui IM with Google Hangouts?
I can't translate the tip in Tage Marketplace.

**Comment by eitzi1701** [comment]
When you are going to connect on Google Hangouts by this app there's a small text saying that you must turn on something on your Google account(i think: "Two Steps auth..something) search this on Google, turn it on and then you're done!!(I thing it's something that allows you to use Google Hangouts with someother app different than Google's!)

**Comment by jambolo1970** [comment]
@ Programmers:
To solve the problem, you could use the same authentication system used by some KDE widgets?
For example "Event Calendar"it synchronizes with google calendar , to join it, asking autorizzation from web in the same mode you join www.google.com email and pwd. 
it could be an idea?
