### ISSUE TITLE
 [WhatsApp] Decrypt Error in Group Chat, v0.5.8

### ISSUE THREAD

**Issue by MaleCat** [loqui/im#1125]
After Update to v0.5.8:

Normal Chats: first incoming message is substituted with "Decrypt Error". One can reply and the dialoge can continued normal again. It works from this point.

Group Chats: all incoming nessages of all group members are substituted with this error message. Own replys can be readen by all group members but their answers stays unreadable.

Hardware ZTE Open C with FireFox OS 1.3.0.0
Previous used working version was 0.5.5

**Comment by cmeerw** [comment]
You could try leaving and re-joining the groups.

**Comment by MaleCat** [comment]
Leaving and re-joining was successful (good contact to the group's admin required :P)

Is this procedure required after every software update from now?

Current running version is v0.5.8 with last edits from Aug 22 included now. Everything looks working good.
Thank you!

**Comment by cmeerw** [comment]
Re-joining was required because session encryption keys weren't
handled by old Loqui versions, but there is no known way to get those
resent...
