### ISSUE TITLE
[Whatsapp] Cant't erase contacts

### ISSUE THREAD

**Issue by juaneladio** [loqui/im#113]
When I choose a Contact there is a button in order to Remove that contact, but when I press it nothing happens: no error message, no remove.

If the feature is not ready it's better to hide it.

**Comment by rick110** [comment]
The same problem on my Peak with FFOS 1.2.0.0-prerelease. No reacting when I hit the red remove-button.

**Comment by Gioyik** [comment]
On what kind of account is happening this? Whatsapp, Google, Jabber....

**Comment by rick110** [comment]
The whatsApp contacs are unremovable. I cant test the others, because by now I use only the whatsapp network.

**Comment by jcatumba** [comment]
Same issue within ZTE Open. WhatsApp contacts can't be erased. Other service providers are ok.
