### ISSUE TITLE
Whatsapp doesn't open for Firefox os 1.3

### ISSUE THREAD

**Issue by eitzi1701** [loqui/im#1141]
Hello everyone! I have Firefox OS 1.3 and yesterday(about 20:00-22:00 hour of Greece) was the last day I signed on my Whatsapp account, and sent messages(I didn't receive any answer from my friends that I sent the messages) Today in the morning I tryed to log in and it wasn't openning!! After I turned off my device and open it again 2 times!! It didn't open(Whatsapp) The yellow button was still yellow and it didn't turn green! So I deleted the app and upload it again on my device!(After I deleted my Whatsapp account!!) Then I created a new Whatsapp account and when I pressed the button "send SMS" It showed to me a message saying this: {SMSreason_old_version}}
![blob](https://cloud.githubusercontent.com/assets/22254203/18607431/c50d65ac-7cd4-11e6-803c-6450e68012ad.png)
(here is a screenshot! The greek words mean: Anavailable send of SMS) So, I thoughg that the app wasn't anymore available on Firefox OS 1.3 And I searched for any issues like mine in this help site and I didn't see anything. I also searched on my Firefox Marketplace on my device for any new description about Loqui app saying that wasn't available anymore on Firefox 1.3 but I didn't see anything!! Can somebody tell me what is going on and what I'm doing wrong perhaps?? (Sorry for the big issues and my but English) (I have Alcatel One Touch Firefox OS 1.3 and I bought it from Greece, I also live in Greece and my phone number is greek, oh, and I'm Greekwoman! I'm saying all this if the problem is my country, and the app is not availabke on my country anymore!!(but I still can search and upload it!!) THANK YOU!! PLEASE TELL ME ANYTHING!! THAT COULD HELP!!! 17-9-2016 12:21p.m.

**Comment by marcfp** [comment]
I have the same issue/problem. It doesn't log in loqui im. I have tried developer version and it throws the same issue. I tried to voice call but i can't log in neither

**Comment by eitzi1701** [comment]
+marcfp oh! What's your phone model? Is it Alcatel One Touch Firefox OS 1.3 version? Or it's some other device and you've just have the app? Also, are you from Greece too? Because maybe country is the problem! I don't know! Do you know how we can find some kind of help in this site? :/

**Comment by TitanNano** [comment]
The marketplace is dead, therefore if you want to update Loqui IM you need to download the source-code and install the app to your phone manually with your computer.

**Comment by marcfp** [comment]
I'm from catalonia, for to be more epecific i'm from spain. I have alcatel one touch fire c too.

**Comment by marcfp** [comment]
I tried to install it from source, from github, but it fails too… any suggestion?

**Comment by TitanNano** [comment]
> but it fails too

can you be more specific? what's your error?

Please follow the build instructions https://github.com/loqui/im/wiki/Build-Loqui

**Comment by shalu02** [comment]
Am also having the same problem. Will this problem be solved please?

**Comment by Zeus76** [comment]
TitanNano can put as Loqui IM application is installed from the Mozilla Firefox web browser using WebIDE.

**Comment by marcfp** [comment]
i have builded it from source, i have Firefox OS 1.3 on alcatel onetouch fire c, but i can't login to loqui im.
It loops always when i start the program at this point 
![loqui hangs here](https://cloud.githubusercontent.com/assets/13907189/18610277/34d5fc08-7d18-11e6-86d0-f9066eadcaed.png)
I try to debug loqui im ... but i don't find where it fails.
Thanks for all and excuse that i'm late.

**Comment by cmeerw** [comment]
seeing old_version does not make sense to me (bad_token might make sense as I think the timestamp in the token data was wrong for the past 2 days).

BTW, the host name to connect to needed to be updated...

The current version in git is supposed to work - can anyone confirm? (I can connect to WhatsApp and receive messages)

**Comment by marcfp** [comment]
![error](https://cloud.githubusercontent.com/assets/13907189/18610896/1146c18a-7d29-11e6-97c3-ad74e8059d22.png)

i'm trying to connect ... but it seems identical state as before.
// I have reinstalled the source ...

**Comment by cmeerw** [comment]
@marcfp that looks more like it isn't built/installed correctly - what
error messages do you get in the WebIDE?

**Comment by marcfp** [comment]
cmeerw  i don't see any error message. Where i can see them ? I'm a new baby on it.
When i build the sources i must download git, then join into im directory and then npm install. When it is finished, i write "grunt --force"  and it shows to me it : 
Running "compress:firefoxos" (compress) task
Created package/LoquiIM-v0.5.8-firefoxos.zip (4177588 bytes)

Running "compress:ubuntutouch" (compress) task
Created package/LoquiIM-v0.5.8-ubuntutouch.zip (4224512 bytes)

Done, but with warnings.
I decompress firefox zip file and execute directory of it using open packaged app.
Now i have this kind of error. Where does i make something wrong ? Excuse my dummy question, but sincerally, i don't know.

**Comment by eitzi1701** [comment]
Guys I don't understand what is happening! I'm tired of all this! I'm not a professional, and I don't understand what are you talking about! (I only get some parts!) This is a problem that the owner of the application should solve! Right?? So, should we wait, or should we just report this to the owner someway? And who exactly is the owner?? I'm confused!......please, help us with simple english! Thank you!!

**Comment by TitanNano** [comment]
@eitzi1701 
- the "Loqui Community" Team is the owner of this application
- Firefox OS is dead. You can't receive any updates through the marketplace anymore
- If you want to use the latest version of this application, you need the technical know-how to manually install it
- The problem has been fixed, but we can't deliver it to you since Mozilla discontinued Firefox OS

**Comment by eitzi1701** [comment]
@TitanNano PROBLEM SOLVED!! :-D I tried to connect for a last desperate time and first I choose my county Greece but pressing the name of my country which was written in greek words:Ελλάδα but nothing hapoened. So I pressed the name of my country which was written in english: Greece, and then suddenly, I connected without any: Verify SMS code, etc. And my deleted account was still there and my photo profile, my messages were all gone, and I could text and send my messages and I also RECEIVED messages!! I'm so glad!!! Thank's for fixing the problem! But what do you mean by saying:  We can't deliver it to you since Mozilla discontinued Firefox OS?? What do you mean? I finally connected before reading your message! What do you mean?? P.S. Thank's a lot for fixing this problem!!

**Comment by TitanNano** [comment]
@eitzi1701 The marketplace hast been almost completely shut down. New updates can't be published anymore.

**Comment by tigu511** [comment]
my loqui im cannot conect to whatsapp, i use firefox webIDE with firefox os 3.0, https://pbs.twimg.com/media/Csh1HNMWYAAG-do.png:large
 the button is only on yellow.

edit: finally connect itself.

**Comment by ellimon** [comment]
hola titanNano... can you tell me ¿ how can I manually install it.. I mean the loqui im beta v0.5.8???  pleasee?? I'm from venezuela ;)

**Comment by eitzi1701** [comment]
@ellimon you are from venezuela?? O.O Oh my god you guys have no food there with this bastard Madoro and you have internet and mobiles?? Jesus!! P.S. Marketplace has been almost completely shut down as @TitanNano said. New updates can not be published anymore!

**Comment by eitzi1701** [comment]
@cmeerw how you can close an issue when you haven't start it?

**Comment by cmeerw** [comment]
In https://github.com/loqui/im/issues/1141#issuecomment-247811846 you said "PROBLEM SOLVED". And yes, LoquiIM does work fine with Firefox OS 1.3.

**Comment by marcfp** [comment]
I continues with the same problem ... for me, it doesn't been solved ...
i tried to reinstall it again into my alcatel onetouch fire c from git, but it is failing again...
Can anyone explain how i can solve it ? 
A lot of thank's to all :)
(i'm using debian gnu/linux stable)
Loqui im remains in this screen 
![index](https://cloud.githubusercontent.com/assets/13907189/18615002/dbe44c2a-7d9a-11e6-9e50-f9c505e252e4.png)

Now i see it : 
[l10n] #contactAdd is undefined. l10n.js:68
asmCrypto seems to be load from an insecure origin; this may cause to MitM-attack vulnerability. Consider using secure transport protocol. asmcrypto.js:5
TypeError: App is undefined
into console 
Any idea about it ?
@ellimon do you have the same problem  ?
You can install it using firefox and developers / webide, then you must install adb (android developer) and you can use your mobile with your firefox browser.
@eitzi1701 do you can run loqui im ?
How do you install it ?
I'm losed :- |
SOLVED!!!!!!
Only need restart/reinitiate phone ... and install loqui from github ... it runs fine now. Thank's

**Comment by marcfp** [comment]
For me it doesn't work fine ...
I continues with the same problem ...

El dg 18 de 09 de 2016 a les 02:23 -0700, en/na Christof Meerwald va
escriure:

**Comment by shalu02** [comment]
Problem actually solved !!!
I downloaded the source code from laptop and transferred it to the phone via usb. Loqui im was reinstalled  and now it works perfectly

**Comment by Zeus76** [comment]
@TitanNano The marketplace Firefox is into maintenance mode.

Website: [https://wiki.mozilla.org/Marketplace/FutureofMarketplaceFAQ](url)
This website says: 
"Where will applications be hosted if marketplace is shut down?
Marketplace is not shutting down. Packaged apps will continue to be hosted on Marketplace and continue to serve Firefox OS users at least until January 2018. Future plans will be reviewed around mid-2017. "

And this website says: [https://wiki.mozilla.org/Marketplace](url)
"Marketplace no longer accepts submissions for Android, Desktop and Tablet, and has removed all apps that don’t support Firefox OS. However we will continue to accept Firefox OS app submissions until mid-2017. Apps that run on Desktop and Android no longer function on those platforms since the Web Runtime (WebRT) is removed and is no longer able to install or launch apps." 

Thank you.

**Comment by TitanNano** [comment]
@Zeus76 that's why I wrote "almost". I also know that they said they will continue to accept submissions for Firefox OS, but the actual situation is that no one is reviewing these submissions. 

It was discussed on IRC that they should communicate this situation, so people don't waste their time with submitting new applications, but I don't know the actual outcome of that.

**Comment by cmeerw** [comment]
0.5.9 is now available from the marketplace

**Comment by decode-dev** [comment]
@TitanNano 
The Firefox Marketplace is still working and also there are people who have been reviewing the applications which are submitted to Firefox OS platform.
Since the Firefox OS is been transitioned but still the marketplace is active with the Firefox OS Platform Apps.
Marketplace to allocate resources to other areas of Connected Devices and working closely on "Progressive Web Apps" with other parties on the shared goal of improving the web’s ability to meet the needs of mobile users and, along with Google, Opera, and others.
