### ISSUE TITLE
how can I update to beta v.0.5.9

### ISSUE THREAD

**Issue by ellimon** [loqui/im#1144]
hi everybody! I would want know-how update my loqui im to the latest version beta v.0.5.9 ¿¿ somebody can you help me?? pleaseee

**Comment by Zeus76** [comment]
@ellimon Hello!

You can see it on this website:

[https://developer.mozilla.org/es/docs/Tools/WebIDE](url)

First, download the latest version of 'Loqui IM'
Second, extract the files in same download folder.

Third: Open the browser "Mozilla Firefox" and press "Shift + F8". (WebIDE)
If you do not have installed "Mozilla Firefox", install it.

Follow the steps on the website:
[https://developer.mozilla.org/es/docs/Tools/WebIDE](url)

USB devices have to show your phone. (Up to the right).

Select Project -> Install and run.
Follow the step and select the download folder Loqui IM.

It is in several languages.

Sorry for the translation is made by a translator Internet.

**Comment by cmeerw** [comment]
0.5.9 is now available from the marketplace
