### ISSUE TITLE
[whatsapp] messages are not sent to contacts

### ISSUE THREAD

**Issue by tigu511** [loqui/im#1145]
loqui works on groups, but not send messages to contacts; the messages only takes a red outline; never shown indicative sent or read (simple and double check)
![captura de pantalla de 2016-09-20 11-01-06](https://cloud.githubusercontent.com/assets/22267213/18678410/939b8c16-7f21-11e6-8c42-f5efd9c0e6de.png)
and the contact will not receive the message .
i has loqui 0.5.6a in firefox os 3.0

**Comment by cmeerw** [comment]
Use the current version 0.5.9 and provide log files
