### ISSUE TITLE
[Whatsapp] Weird chats appear as contacts (apparently groups)

### ISSUE THREAD

**Issue by juaneladio** [loqui/im#115]
I have two 'chats', both of one word ('Toc' and 'Calabazas') that appears as contacts. When I choose to see them as conversations there is no messages, and when I choose to see the contact details nothing happens. I will add an screenshot.

**Comment by juaneladio** [comment]
![2013-11-30-10-39-19](https://f.cloud.github.com/assets/547722/1649663/0c0b4770-5a1a-11e3-9605-80cb83c14623.png)

**Comment by Gioyik** [comment]
Calazas and Toc is on your contact list?

**Comment by juaneladio** [comment]
No, there is no contacts in my phone with those names, but them appears as Loqui contacts, as the screenshot shows.

**Comment by deimidis** [comment]
I think there are Group chats, at least I saw my Group chats in the same way

**Comment by Gioyik** [comment]
@juaneladio tell me to add this screenshot:

![1426250_10202918885117242_1627884750_n](https://f.cloud.github.com/assets/1834718/1649781/fa0b94b6-5a29-11e3-9e49-9c00aa9671da.jpg)

@deimidis that seems to be a more clear explanation for the problem.

**Comment by aesedepece** [comment]
Ah ok, your point is that they should have a default avatar showing a group of people and not only a dummy person, isn't it?

**Comment by juaneladio** [comment]
Yes, probably they are groups without conversations and there is no way to see if that is a group or just a lost text, a bug. In addition, when I enter a "group" and tap the profile picture nothing happens. It should inform that this is a group and provide details.

**Comment by Gioyik** [comment]
Fixed #189
