### ISSUE TITLE
[WhatsApp][Ubuntu] ContactsGetError: No way to start a chat, no contacts to display.

### ISSUE THREAD

**Issue by ghost** [loqui/im#1156]
I successfully configured my accound, however no contacts are loaded, I have no way to manually add them.

![screenshot20161029_110518894](https://cloud.githubusercontent.com/assets/5044321/19831818/77bd991a-9dc8-11e6-8fff-2224524bbfb0.png)

If there is any kind of logging I can add please tell me where to find it and I will post it here.

**Comment by cmeerw** [comment]
Ubuntu Touch is not fully supported yet

**Comment by cmeerw** [comment]
If you got this version with another expectation than as a developer preview for developers, then the download site is wrong and should be corrected!

**Comment by ghost** [comment]
OK now I have read more carefully the OpenStore entry for Loqui 
which says 
- (WhatsApp) Adding new contacts (people have to send you a message before you can send messages to them)

I first thought was adding new contacts over what is already in my contact list, now I get that is about adding any contact.

You can close this, and I can hide somewhere from the shame of not knowing how to read :P

**Comment by vfr400racing** [comment]
I have the same behaviour on my Ubuntu phone. I registered to WhatsApp and typed in the verification code which has been sent to me. Although my friends can't send me a message over WhatsApp because I'm not in their list of contacts. Any ideas what I can do now?

**Comment by petermalcom** [comment]
av got the same problem with me cant someone help also

**Comment by vfr400racing** [comment]
It started working for me after a few days. I have no idea what triggered that.

**Comment by nfsprodriver** [comment]
Contact feature implemented since 0.5.12
