### ISSUE TITLE
[Whatsapp] Doesn't update current chats

### ISSUE THREAD

**Issue by juaneladio** [loqui/im#116]
I noticed that I don't receive conversations while I'm connected. I have to close the app and reopen it in order to get new messages.

**Comment by aesedepece** [comment]
This bug has been reported to the developers in charge of the whatsapp connection library and will likely be fixed by monday or tuesday. Thanks.

**Comment by aesedepece** [comment]
This is duplicate of #112

**Comment by Gioyik** [comment]
Closed. 

Reason: Duplicated
