### ISSUE TITLE
[ubuntu touch] platform seem to be "PC"

### ISSUE THREAD

**Issue by TronFortyTwo** [loqui/im#1163]
When should be somethng like "ubuntu touch" or "ubuntu". I found this because my state has been updated, and says "... from PC"

**Comment by nfsprodriver** [comment]
Looks like the problem are the strings here: https://github.com/loqui/im/blob/dev/src/scripts/loqui/app.js#L228 and here: https://github.com/loqui/im/blob/dev/src/scripts/loqui/app.js#L395

**Comment by TronFortyTwo** [comment]
Thanks!
I corrected and opened a pull request.

**Comment by nfsprodriver** [comment]
That's thing of opinios. We can 'fix' this in another way.
