### ISSUE TITLE
Incremental notification number not working

### ISSUE THREAD

**Issue by Gioyik** [loqui/im#117]
This is the incremental variable working in v0.1.0:

![2013-11-30-19-34-43](https://f.cloud.github.com/assets/1834718/1649719/a11cc3d2-5a21-11e3-9e56-e2e6d6a79c0a.png)

and this is the incremental variable (working but is not showed) in v0.2.2:

![2013-11-30-19-35-14](https://f.cloud.github.com/assets/1834718/1649718/88b207a8-5a21-11e3-93ee-04dafe54a2f7.png)

@aesedepece did you know what could be happening here? If you give me a quick explanation i can make a fix for that, and you can focus in other issues related to whatsapp ;)

**Comment by aesedepece** [comment]
I know where the bug is, I'm sending a fix in some minutes. You'll see it's a completely dumb bug.
