### ISSUE TITLE
Some strings missing in all .ini files (not in English,italian,germany files)

### ISSUE THREAD

**Issue by pharaone** [loqui/im#1170]
In all .ini files there aren't missing strings (not in English,italian,germany files)
( #1168 is a fix for the problem only in it.ini)
these are the missing strings(based on en.ini Ex line 14 of en.ini is missing in all the others):
line 14 of en.ini is missing in all the others (but is also present in Italian one and Germany one)
line 127 of en.ini is missing in all the others (but is also present in Italian one and Germany one)
line 128 of en.ini is missing in all the others (but is also present in Italian one and Germany one)
line 129 of en.ini is missing in all the others (but is also present in Italian one and Germany one)
line 130 of en.ini is missing in all the others (but is also present in Italian one and Germany one)
line 170 of en.ini is missing in all the others (but is also present in Italian one and Germany one)
line 172 of en.ini is missing in all the others (but is also present in Italian one and Germany one)
line 212 of en.ini is missing in all the others (but is also present in Italian one and Germany one)
line 213 of en.ini is missing in all the others (but is also present in Italian one and Germany one)
line 220 of en.ini is missing in all the others (but is also present in Italian one and Germany one) 
line 221 of en.ini is missing in all the others (but is also present in Italian one and Germany one)
line 227 of en.ini is missing in all the others (but is also present in Italian one and Germany one)
line 267 of en.ini is missing in all the others (but is also present in Italian one and Germany one)
line 268 of en.ini is missing in all the others (but is also present in Italian one and Germany one)
line 269 of en.ini is missing in all the others (but is also present in Italian one and Germany one)
line 270 of en.ini is missing in all the others (but is also present in Italian one and Germany one)
line 271 of en.ini is missing in all the others (but is also present in Italian one and Germany one)
line 272 of en.ini is missing in all the others (but is also present in Italian one and Germany one)
line 273 of en.ini is missing in all the others (but is also present in Italian one and Germany one)
line 274 of en.ini is missing in all the others (but is also present in Italian one and Germany one)
line 275 of en.ini is missing in all the others (but is also present in Italian one and Germany one)
line 276 of en.ini is missing in all the others (but is also present in Italian one and Germany one)
line 277 of en.ini is missing in all the others (but is also present in Italian one and Germany one)
line 278 of en.ini is missing in all the others (but is also present in Italian one and Germany one)
line 279 of en.ini is missing in all the others (but is also present in Italian one and Germany one)
line 280 of en.ini is missing in all the others (but is also present in Italian one and Germany one)
line 281 of en.ini is missing in all the others (but is also present in Italian one and Germany one)
line 282 of en.ini is missing in all the others (but is also present in Italian one and Germany one)
line 283 of en.ini is missing in all the others (but is also present in Italian one and Germany one)
line 284 of en.ini is missing in all the others (but is also present in Italian one and Germany one)
line 285 of en.ini is missing in all the others (but is also present in Italian one and Germany one)

**Comment by nfsprodriver** [comment]
This an appell to complete the translations ;)
