### ISSUE TITLE
[Ubuntu touch] LoquiM chrash randomly

### ISSUE THREAD

**Issue by TronFortyTwo** [loqui/im#1172]
LoquiM chrash often on ubuntu touch. I'm on E5 rc channel. Doesn't chrash in particular situation, but randomly. Sometimes when is loading, sometimes after some use...

**Comment by looooo** [comment]
For me loquIM works quite good (nexus4, ut ota 14) but crashes always when I switch application.

**Comment by nfsprodriver** [comment]
Use UT tweak tool and prevent LoquiIM from suspending. This should basically fix the random crashes.

**Comment by looooo** [comment]
thx, now I am totally satisfied.

**Comment by nfsprodriver** [comment]
This hint is given in the UT stores...
