### ISSUE TITLE
emojiRender not working

### ISSUE THREAD

**Issue by Gioyik** [loqui/im#118]
The emojiRender is not working at all, it is searching emojis in `img/emoji`, see the screenshot:

![2013-11-30-19-54-15](https://f.cloud.github.com/assets/1834718/1649736/7bf41338-5a23-11e3-95ac-57b3ef3c23d5.png)

This is the code affected in `xmpp.js`:

``` javascript
  this.emojiRender = function (img, emoji) {
    img
      .attr('src', '/img/emoji/' + emoji[0] + '.png')
      .data('emoji', emoji[0]);
  }.bind(this);
```

@aesedepece did you know what could be happening here? If you give me a quick explanation i can make a fix for that, and you can focus in other issues related to whatsapp ;)

**Comment by aesedepece** [comment]
Not tested with WhatsApp. Let's test it and close it.

**Comment by Gioyik** [comment]
Tested and everything works great!
