### ISSUE TITLE
[ubuntu touch] ContentHub implementation

### ISSUE THREAD

**Issue by nfsprodriver** [loqui/im#1185]
To make LoquiIM run on UT more properly, it is necessary to implement the ContentHub feature (-> contact- and multimedia im/export). Feel free to post your ideas here!

**Comment by TronFortyTwo** [comment]
Yes, it will be great. About videos, Loqui downloads it but there is no way to open it.

**Comment by nfsprodriver** [comment]
Now I see, this is a secondary problem for overordinary problems. May be closed for now...
