### ISSUE TITLE
Can't clone on Windows

### ISSUE THREAD

**Issue by vitalyster** [loqui/im#119]
As I understand, there are prohibited symbols in filenames:

error: unable to create file img/emoji/fb/8|.png (Invalid argument)
error: unable to create file img/emoji/fb/:'(.png (Invalid argument)
error: unable to create file img/emoji/fb/:(.png (Invalid argument)
error: unable to create file img/emoji/fb/:).png (Invalid argument)
error: unable to create file img/emoji/fb/:*.png (Invalid argument)
error: unable to create file img/emoji/fb/:3.png (Invalid argument)
error: unable to create file img/emoji/fb/:D.png (Invalid argument)
error: unable to create file img/emoji/fb/:O.png (Invalid argument)
error: unable to create file img/emoji/fb/:P.png (Invalid argument)
error: unable to create file img/emoji/fb/:.png (Invalid argument)

**Comment by aesedepece** [comment]
Our Linux minds always forget those Windows limitations... 

Don't worry, we'll figure out a smart fix for this as soon as possible as every contribution is welcome regardless of what OS it comes from ;)

**Comment by Gioyik** [comment]
If you use Cywin this must not be a problem. Is a small linux in a box. :)

**Comment by Gioyik** [comment]
@aesedepece I was thinking in convert all the png images of smiles to base64 images. What you think? Are you agree? Do you think that this could affect somethings? I think that is not a problem convert from png to base64, and it will solve this issue btw.

**Comment by aesedepece** [comment]
@Gioyik I have only one objection: when you encode binary data to base64 its size increases in 37% aprox.

**Comment by Gioyik** [comment]
@aesedepece Jummmm and there are many png files, so the increase will be notorious. So, keep the png images for now? Are you thinking in replace the ones from base64 to png in coseme.js?

**Comment by aesedepece** [comment]
@Gioyik Maybe. FYI: CoSeMe emoji icons are in fact .gif pics.

**Comment by Gioyik** [comment]
@aesedepece I can get them as png. There are a lot of libraries that helps to support to emoji icons and they use the ones in whatsapp, most of them are using png files.

**Comment by Gioyik** [comment]
Fixed! Patch will be landed for the next version (0.2.5).

**Comment by vitalyster** [comment]
why reverted?

**Comment by Gioyik** [comment]
It's not reverted at all. We are trying to put every change on a Pull Request first to review with all the team instead of send direct commits. I made a direct commit to waalt/loqui [master] for error, so I reverted. But I added the changes again to the Pull Request to the next version (#178). Don't worry, the issue will be solved for the next version.

**Comment by vitalyster** [comment]
Ah, then why you not use git branches? :)

**Comment by Gioyik** [comment]
Yes, you're right (see #176). We have a development branch (devel) to work on, but it's too out of date. After all Pull Request will be landed and the v0.2.5 published, we will organize all again to work with branches and defining contribute paths.

Thanks for the comments. :)
