### ISSUE TITLE
[ubuntu touch] [whatsapp] Sent and received images are blurry

### ISSUE THREAD

**Issue by TronFortyTwo** [loqui/im#1195]
Images are displayed with low resolution and are blurry.

**Comment by Honk2** [comment]
That is normal.
If you tap the images they are displayed in full resolution on FFOS.
Guess that the Storage access fails.

**Comment by nfsprodriver** [comment]
sap_nocops is currently working on a download function for UT. This is the current dev focus...

**Comment by nfsprodriver** [comment]
Preview possibillity available since 0.5.13. Downloads not possible yet due to oxide restrictions...
