### ISSUE TITLE
[ubuntu touch] Can't log in in a google hangout account

### ISSUE THREAD

**Issue by TronFortyTwo** [loqui/im#1196]
Press new account, press google hangout then insert details but when connecting finishes the account isn't added and the "insert detail" page remains there. It's like the problem in whatsapp that block the user to add an account.

**Comment by TronFortyTwo** [comment]
Older bugs about google hangout
#1149 
#1122
#978
#926 
#519
#435

**Comment by speexy** [comment]
same here

**Comment by nfsprodriver** [comment]
Please leave out 'same here' comments. Thanks for understanding ;)

**Comment by TronFortyTwo** [comment]
This is caused (as you can see in src/script/loqui/providers.js) because loqui try to connect to https://bosh.loqui.im, that doesn't exist. I am not sure about it because something in some specific hangout file could override it, I don't know.
