### ISSUE TITLE
[ubuntu touch] [whatsapp] Sent messages cannot be correctely received

### ISSUE THREAD

**Issue by TronFortyTwo** [loqui/im#1200]
From Loqui 0.5.12 in ubuntu touch send a message to someone; no problem, all works fine. BUT him (the one you sent a message) will get a message saying 'Waiting for the message, it could take a while'.

**Comment by TronFortyTwo** [comment]
This bug seems to be from the same source as the "DECRYPT ERROR", as nfs_provider pointed out.

**Comment by nfsprodriver** [comment]
Problems of this kind are very mystic and not solved yet. To reduce the demands on that topic I'll close this issue for now.
