### ISSUE TITLE
when I try to send message not go

### ISSUE THREAD

**Issue by jambolo1970** [loqui/im#1209]
I write the message, and when i tap to send it, it's not go, 
on firefoxOS 1.3
with Loqui  5.13
[2017-03-10-08-42-10.png.zip](https://github.com/loqui/im/files/833280/2017-03-10-08-42-10.png.zip)

**Comment by Honk2** [comment]
Yes you are right. See pr #1207 
If you are looking for a stable version for FFPS use 0.5.11 or wait until the merge and FFOS is running again.
You can also try the new branch Attempt-rework-multiOS

**Comment by jambolo1970** [comment]
looks to test upgrades

**Comment by Honk2** [comment]
@jambolo1970 does 0.5.14 work for you? Please confirm abd close this issue.

**Comment by jambolo1970** [comment]
now it's work, thanks

**Comment by jambolo1970** [comment]
They work even special characters, with *abc  _abc  ~abc
much good work 👍 💯

**Comment by nfsprodriver** [comment]
Sorry, need to publish the release here. I'll do this later today and close this issue...
