### ISSUE TITLE
Loqui 0.5.12 doesn't start on FFOS 1.3

### ISSUE THREAD

**Issue by ibinshoid** [loqui/im#1210]
I have installed loqui 0.5.12 on my Alcatel OTF with FFOS 1.3 on it.
When it starts it askes for acess to my contact, after allowing it nothing happens any more.
On the console in WebIde there are this messages:

SyntaxError: let is a reserved identifier  tools.js:347:6
SyntaxError: let is a reserved identifier  app.js:489:16
SyntaxError: let is a reserved identifier  activity.js:95:6
ReferenceError: App is not defined  bindings.js:238
ReferenceError: Tools is not defined  events.js:136
SyntaxError: let is a reserved identifier  xmpp.js:300:4
SyntaxError: let is a reserved identifier  coseme.js:2282:11
ReferenceError: App is not defined  bindings.js:17

The same happens in the Simulator.

**Comment by Honk2** [comment]
Yes you are right.
At the moment 0.5.11 is the highest version running on FFOS. Some changes for 0.5.12 broke FFOS support. It is under investigation.

**Comment by Honk2** [comment]
@ibinshoid 0.5.14 is released. This should fix the issue. Could you try, confirm and close this issue?

**Comment by nfsprodriver** [comment]
Sorry, need to publish the release here. I'll do this later today and close this issue...
