### ISSUE TITLE
[Ubuntu Touch] Voice message not work

### ISSUE THREAD

**Issue by Gabriele69** [loqui/im#1232]
Hello to all. 
My Aquaris e4.5 does not work for voice messages. 
The messages can not be opened when they are received and can not be sent.
Received voice messages are just an icon.
If I hold down the microphone button to send the message, the record can't be stopped even if I leave the button.

Gabriele

**Comment by nfsprodriver** [comment]
Voice messages by mic generally don't work anymore. Please record audio with another app and use file upload... Duplicate...
