### ISSUE TITLE
I receive private messages that are actually sent to groups I'm in

### ISSUE THREAD

**Issue by 03927e9c** [loqui/im#1233]
I'm not sure if I have v0.5.14 or v0.5.16. But it is one of them for sure.

The thing is that I receive private messages that are actually sent by other people to other groups.

Example: I'm in a 5 people group, and someone sends "Hello everybody" and I receive that message as a private chat, and that particular message I can't see it in the group chat. It's completly random.

The privacy concern that I have is that if I'm privatly chatting with a contact and some messages are sent to someone inside the group

**Comment by nfsprodriver** [comment]
I heared about current group messaging problems. Anyway, please try latest version 0.5.17. 0.5.16 was a broken version.

**Comment by 03927e9c** [comment]
But 0.5.17 won't send activation SMS so I can't use it.

**Comment by nfsprodriver** [comment]
I can't imagine the reason is in the version because the code for that kept unchanged. Can't you update old version keeping your chats? Which OS do you use?

**Comment by 03927e9c** [comment]
Firefox OS simulator. When I tried to update I couldn't use it because the SMS won't arrive. There's a thread about this.

**Comment by 03927e9c** [comment]
Can you confirm that my private messages don't arrive as a private chat to the numbers that are inside a group?

**Comment by TronFortyTwo** [comment]
The bug has been fixed by @honk2 and the fix landed on 0.5.17

**Comment by TronFortyTwo** [comment]
link to the fix commit
https://github.com/loqui/im/commit/36f677ee2e4c195564e385e2e4dea0ce8698fd0e

**Comment by 03927e9c** [comment]
I have now v0.5.14 and it's the same problem.

I won't try 0.5.17 because I cannot chat with that version. The activation doesn't work.

**Comment by TronFortyTwo** [comment]
The fix anyway has been committed and released

**Comment by 03927e9c** [comment]
I understand. But I can't activate with 0.5.17, therefor I won't be able to use Whatsapp chat at all

**Comment by arkonia** [comment]
I had the same activation problem with v0.5.17. So i used an old activation code sent for a previous version, and that worked.
