### ISSUE TITLE
[WhatsApp] SMS or phone call verification doesn't work in v0.5.14 or older versions

### ISSUE THREAD

**Issue by 03927e9c** [loqui/im#1234]
The error I get is "Could not send SMS ((SMSreason_old_version))"

So right now I can't use Loqui what so ever... because the lastest version doesn't have a working verification either and the older ones have the same problem.

**Comment by 03927e9c** [comment]
Why did you close this?

**Comment by nfsprodriver** [comment]
Sorry, it's a multiple duplicate. There's also no support for 0.5.14 anymore. Please wait for 0.5.19, a new token for Auth is coming ;)

**Comment by 03927e9c** [comment]
Ok. When do you estimate 0.5.19 will be available?

**Comment by nfsprodriver** [comment]
Right now. You can build it or wait until it's uploaded here ;)

**Comment by 03927e9c** [comment]
I think I'll wait until the release is ready. I'm not that expert to build. Thanks

**Comment by nfsprodriver** [comment]
Released ;)

**Comment by 03927e9c** [comment]
Awesome! Thank you!

If I spot some issue I'll put it here!

**Comment by jcerdan** [comment]
Hi, 
I have just checked this new version and it does not work. SMS never arrives and error displays:
SMS could not be sent
{{SMSreason_undefined}} 

Regards.
