### ISSUE TITLE
DECRYPT ERROR

### ISSUE THREAD

**Issue by C0pperhead** [loqui/im#1237]
Hi,
I use FFOS 2.0 on a Fire E. I installed the beta v0.5.19 but i dont know if the other users (whatsapp) can see my messages and wenn they send me one i juste become a "DECRYPT ERROR" message.
What should i do ?
And another question, why Hangout and the other has been removed ?

**Comment by nfsprodriver** [comment]
Duplicate

**Comment by C0pperhead** [comment]
:( i tried with the 0.5.17 and it does wotk but in group my messges are not send
