### ISSUE TITLE
Verification with Ubuntu and 0.5.21 beta

### ISSUE THREAD

**Issue by Naturalbornhippy** [loqui/im#1241]
Hi Everyone,

im just playing around with loqui on my ubuntu phone. installed it from the open store and trying to get a verification code. but it always says cant send sms reason old version.

Same for phone call, any idea?

**Comment by TronFortyTwo** [comment]
This is a known issue... Temporany workaround is to obtain the code somewhere else. This issue is being worked on in the 0.6 branch (still in alpha)

**Comment by Naturalbornhippy** [comment]
Ok, than I will have to wait, thnx for the answer
