### ISSUE TITLE
version v0.5.23

### ISSUE THREAD

**Issue by jambolo1970** [loqui/im#1248]
is not possible to access at service, look screenshot
in first case the request of SMS is not accessible
in second case  "I have a code" don't accept 123456 code (This is the old way I could always access the service without having the whatsapp code)
[screenshot_setup.zip](https://github.com/loqui/im/files/1266066/screenshot_setup.zip)

I can not give you the log file because it does not allow me to start the program with valid access, sorry :(

**Comment by arkonia** [comment]
I just installed this new version (in Firefox OS 2.0) and had the same problem, but in the end using my old code worked.

This version has still the same two problems i had with v0.5.19 beta: I cannot write to groups, and i cannot send images or videos at all.

**Comment by jambolo1970** [comment]
I think it is due to the fact that the service on which is connected for loqui for whatsapp, it's ended last June, and so the programmers are looking for a good alternative to rewrite the program. The'idea to find the solution I seemed, it only takes a little patience :D
