### ISSUE TITLE
where to download loqui im

### ISSUE THREAD

**Issue by shalu02** [loqui/im#1249]
I am having great issues with loqui im
as the application is no longer available on marketplace am unable to find the site to download it. Can you please help. Thanking you in advance

**Comment by nfsprodriver** [comment]
You can download it from the releases tag on this github page. You must install it manually via Firefox's WebIDE.

**Comment by shalu02** [comment]
I have already downloaded the releases however i'm still not able to use the application. I have the version 0.5.9. I'm not able to send messages to my whatsapp contacts neither can i receive any message from them however i can see their last seen and status. Can you help please

**Comment by nfsprodriver** [comment]
I meant here from github. The Marketplace is deprecated so you must download it from here and install it by hand. https://github.com/loqui/im/releases/download/v0.5.23/LoquiIM-v0.5.23-firefoxos.zip
