### ISSUE TITLE
building loqui im 0.6

### ISSUE THREAD

**Issue by florianloqui** [loqui/im#1252]
Hi! 

I am a newbie but I'd like to still use my firefox OS phone with whatsapp.

Issue 0.523 doesn't get the sms.

I wanted to try to install the 0.6 issue, and tried to build this.

At the last step (launching grunt), I got this : 

~/loqui/im$ grunt
Loading "sass.js" tasks...ERROR
>> Error: ENOENT: no such file or directory, scandir '/home/florian/loqui/im/node_modules/node-sass/vendor'
Warning: Task "sass" not found. Use --force to continue.

do you  have any idea of what I can do to get the zip file in order to install it on my phone with Web IDE ? 

Thanks for help!

florian

**Comment by nfsprodriver** [comment]
Stopped the work on 0.6, so I'll close this for now. Thanks for understanding!
