### ISSUE TITLE
App and Phone Crash when using multiple apps

### ISSUE THREAD

**Issue by lnoble237** [loqui/im#1258]
I'm running Ubuntu Touch on Fairphone 2. I downloaded Loqui from the Ubuntu Openstore.

Steps to recreate:
Open LoquiIM.
Switch between scopes (Ubuntu home screen) and Loqui by swiping from right.
If this doesn't crash the app (sometimes the phone as well) then open any new app and swipe from right.
Crashes the app about 70% of the time.

**Comment by nfsprodriver** [comment]
That's something many users stuck at. To tease you, please read the instructions in the OpenStore for LoquiIM :P
