### ISSUE TITLE
Error message displayed on empty WhatsApp account

### ISSUE THREAD

**Issue by lnoble237** [loqui/im#1259]
![screenshot20171230_104916873](https://user-images.githubusercontent.com/20361294/34453801-d168a478-ed54-11e7-8c99-ac0e685ef927.png)

Here is a screenshot of the error message that displays after a new empty WhatsApp account is registered.

This message appears on the WhatsApp homescreen everytime LoquiIM is opened.

Running Ubuntu Touch on Fairphone 2.

**Comment by nfsprodriver** [comment]
This is not a real error. It's code meant to be run by FFOS, which gives that message on UT. Parallely UT runs its working code. But thanks to report it ;)
