### ISSUE TITLE
[WhatssApp] Automatic sync contacts

### ISSUE THREAD

**Issue by aarizkuren** [loqui/im#126]
I think that we need to sync whatsapp contacts with our phone contacts all times that we start app.

**Comment by aesedepece** [comment]
Having the app constantly prompting you for permission to access your contacts list is kinda annoying.

I think a smarter solution (the same as in Android WhatsApp) is to have an option in the app contacts list for syncing contacts on demand. What do you reckon?

**Comment by aarizkuren** [comment]
Agree with you, that is the better solution to do easily

**Comment by aarizkuren** [comment]
This throws an error:

TypeError: this.connector.contactsSync is not a function (account.js:238)

**Comment by Gioyik** [comment]
@aarizkuren Please, test again and the us if the error continue, i think that the error was produced by the commit in #106 and i have been reverted.

**Comment by aarizkuren** [comment]
its ok now
