### ISSUE TITLE
algunos mensajes no llegan con facebook chat

### ISSUE THREAD

**Issue by v3rlain3** [loqui/im#130]
Me a pasado en unas cuantas ocasiones desde que actualice a la 0.2.2 que algunos de los mensajes no llegan al destino usando facebook chat

**Comment by Gioyik** [comment]
Es dificil saber si algo esta pasando o no, podrias pasarnos algun log en donde podamos ver si pasa algo raro y lo podamos identificar?

**Comment by YukiteruAmano89** [comment]
Uso loquiim 0.2.3 y me pasa exactamente lo mismo, estoy conversando con una persona, y luego de 2 o 3 mensajes, ejo de recibir mensajes de esa conversacion, aunque por la apps de facebook se registran los nuevos. Si realizo otra conversacion con otra persona, presenta el mismo cuadro, 2 o 3 mensajes y luego deja de recibir mensajes. Un caso extrañó pero así, en lo que puedo instalarme adb en mi Windows sacare los logs y lo pasare.

**Comment by Gioyik** [comment]
Te sigue sucediendo esto? Has actualizado a la version v0.2.4? En que dispositivos/simulador usas Loqui? Podrias proveernos algun log que nos de vistazos de que pasa con tu caso?

**Comment by v3rlain3** [comment]
Hola, uso loqui desde Firefox (navegador) ya que en mi país no los 
venden y por internet es imposible y desde el simulador no he podido ya 
que estoy detrás de un proxy, desde q me paso dejé de usarlo; lo retome 
hoy para darte respuesta y al parecer todo funciona bien. Tambien me 
daba problemas a pantalla completa que no funcionaban los Atras, y lo 
solucione usando (vista de diseño adaptable) en las herramientas para 
desarrolladores que posee el navegador. Gracias por tu preocupación.

El 04/01/14 02:36, Giovanny Andres Gongora Granada escribió:

> Te sigue sucediendo esto? Has actualizado a la version v0.2.4? En que 
> dispositivos/simulador usas Loqui? Podrias proveernos algun log que 
> nos de vistazos de que pasa con tu caso?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/waalt/loqui/issues/130#issuecomment-31573534.

## 

Este mensaje le ha llegado mediante el servicio de correo electronico que ofrece Infomed para respaldar el cumplimiento de las misiones del Sistema Nacional de Salud. La persona que envia este correo asume el compromiso de usar el servicio a tales fines y cumplir con las regulaciones establecidas

Infomed: http://www.sld.cu/

**Comment by Gioyik** [comment]
Que bueno que te funcione. :)
