### ISSUE TITLE
Whatsapp Contacts Venezuela

### ISSUE THREAD

**Issue by Reston** [loqui/im#131]
Cuando se sincronizan los contactos de mi teléfono con los de whatsapp, si el número que tengo es 04145557777 loqui sincroniza 5804145557777@s.whatsapp.net y no elimina el 0, normalmente en Venezuela se agregan los números de celulares con un 0 al inicio y en el formato internacional se elimina, no sé si otros países sea así. Claro que uno podría simplemente agregar los numeros sin el 0, pero quizás haya gente que piense que no funciona y la verdad es que simplemente tienen que quitar el 0 si no se puede hacer nada quizás en un FAQ quedaría bueno colocar la información.

**Comment by aesedepece** [comment]
Related to #99 and #96

**Comment by bdcomp** [comment]
As #96 and #99 are closed, this issue need to be tested on the recent version.

@Reston Can you please take a look?
