### ISSUE TITLE
Time to re try confirmation Whatsapp

### ISSUE THREAD

**Issue by deimidis** [loqui/im#132]
I don't know if it's a Loqui problem or Whatsapp, but trying to test the application with a new account is almost impossible. I wait 80 thousands seconds, and after a new try the first message is too many tryes, please try again in 60 thousands seconds. 

Do we have a solution for this thing?

**Comment by Gioyik** [comment]
Hi @deimidis 

Are you using the latest version from master or just using the one in the Marketplace? Just to know if was a problem in some commit or just is a normal case getting time out from Whatsapp server.

**Comment by Gioyik** [comment]
btw 80000 seconds are just 1 minute and 20 seconds, i was thinking that you spend hours waiting :P

**Comment by 8la** [comment]
80000 seconds = 1minute 20 seconds? omg! xD  https://www.google.es/search?client=ubuntu&channel=fs&q=8000+seconds+to+minutes&ie=utf-8&oe=utf-8&gws_rd=cr&ei=efWeUuMTw6vSBYLTgZgC

**Comment by aesedepece** [comment]
We have nothing to do with validation SMS sending. Loqui ask for them to the WhatsApp server and it answers whether it was successfully sent or you have to wait N seconds.

**Comment by deimidis** [comment]
All my last tries gave me the same answer, too many tries, try again later. I beginning to think there's another problem here :)

And Gioyik, I'm using git version

**Comment by Gioyik** [comment]
This is on Whatsapp server side, so there's nothing that Loqui can do.
