### ISSUE TITLE
Reload button

### ISSUE THREAD

**Issue by Gioyik** [loqui/im#133]
Creo que esto es importante y puede funcionar como una solucion parcial para el issue #112. Es tan solo un boton que recarga todas las cuentas por si se presenta el problema de que se ha quedado pegado o no las recarga.

**Comment by Gioyik** [comment]
@aesedepece Podrias agregar el icono para el boton en `img/providers/squares/reload.svg`? Una vez lo hagas, podrias cerrar el issue para saber que todo esta bien?

**Comment by nukeador** [comment]
@Gioyik ¿Y cómo sabe el usuario que la conexión no funciona? Te deja escribir mensajes pero no sabes si llegan o no, no hay forma de saberlo excepto escribirte desde otro terminal y ver que efectivamente no llega.

¿No sería mejor algo que comprobara si estás online cada X tiempo y si no lo estás que reconectara?

**Comment by aesedepece** [comment]
@nukeador Ese es precisamente el problema que estamos teniendo con WhatsApp, no sabemos muy bien cómo identificar cuándo la conexión se ha perdido para reconectar de forma automática.

**Comment by nukeador** [comment]
¿Y si Loqui reinicia la conexión con Whatsapp cada X tiempo para evitar esto (5 min.)? ¿Tiene un coste muy grande en el rendimiento/uso de batería?

**Comment by Gioyik** [comment]
@nukeador Supongo que si, algunas veces los usuarios se molestan porque tratan de cerrar la aplicacion y se vuelve abrir automaticamente. Imaginate que estes escribiendo y se recargue la app sin ningun aviso, o peor, sin que tu lo quieras. De igual forma es una solucion parcial mientras se nos ocurre algo respecto al issue #112 

Yo me doy cuenta de que se han desconectado mis cuentas cuando el botoncito verde (o de X color) en la parte superior de cada foto de perfil no esta.

**Comment by willyaranda** [comment]
@nukeador sí, una burrada. Lo que se quiere es que sea lo más eficiente posible. Igualmente, whatsapp hace pings automáticos desde su servidor durante un tiempo fijo (180 segundos), que mata tu batería igualmente.

lo que habría que hacer es realmente identificar si la conexión se ha perdido y que loqui se enterara.

**Comment by nukeador** [comment]
@Gioyik Y la bolita esa ¿cómo sabe que tiene que cambiar de color? ¿Para reiniciar la conexión hay que matar todo la app/UI?

**Comment by Gioyik** [comment]
@nukeador la bolita esta, refleja el estado en que estas. Si es verde es que estas disponible, si es roja es que estas ocupado y asi cambia de color por el estilo. Yo, me he dado cuenta (personalmente y alguien tambien lo ha mencionado en el issue #112), que cuando no aparece esta bolita es porque se ha desconectado, y la unica forma de que vuelva a reconectar es "matando" la aplicacion desde el administrador de aplicaciones que se abre con el boton de menu sostenido. Para evitar que tener que "matar" la app de ese modo para que reconecte de nuevo, es por eso que hice un boton que reconecte de nuevo solo con un presionandolo y sin terminar nada, ni la app, ni el proceso.

**Comment by Gioyik** [comment]
Mira estas dos capturas de pantalla, esta es en donde muestra el circulito gris que indica que el contacto no esta disponible: 

![2013-12-04-13-32-27](https://f.cloud.github.com/assets/1834718/1675996/c22cd12c-5d12-11e3-85ea-b4f7ff891dfd.png)

y aqui es cuando esta desconectado, ya no muestra el circulito gris:

![2013-12-04-13-32-37](https://f.cloud.github.com/assets/1834718/1676007/de66c69a-5d12-11e3-82c9-c9e61857b459.png)

Lo unico que necesito para que vuelvan a reconectar y que aparezca de nuevo el circulito diciendome el estado de mis contactos es presionar el boton de reconectar y ya esta. No es necesario tener que cerrar la app desde el Administrado de aplicaciones de Firefox OS.

**Comment by nukeador** [comment]
¿No se puede detectar cuando esa bolita desaparece? Porque supongo que desaparecerá en base a algo.

**Comment by Gioyik** [comment]
Supongo que si, aunque si logramos seria una solucion para las conexiones XMPP, ya que veo que en las cuentas Whatsapp no aparece esta bolita. Voy a revisar si encuentro algo que se me ha ocurrido con lo que has dicho.

**Comment by aesedepece** [comment]
El color y la presencia de la bolita está determinada en el CSS. Las condiciones para que aparezcan son:
- Que la cuenta soporte notificaciones de presencia
- Que el WiFi / 3G esté conectado
- Que la sesión de BOSH siga abierta

Estoy trabajando en un parche para que se funcione también con WhatsApp, que a priori no da información de los puntos 1 y 3.

**Comment by Gioyik** [comment]
@aesedepece en que issues estas trabajando? pregunto para no pasar por la situacion de estar trabajando los dos en lo mismo cada uno por su lado.

**Comment by aesedepece** [comment]
@Gioyik  Ahora mismo, #97 y #112.

**Comment by Gioyik** [comment]
Vale, yo voy a trabajar en otros, a ver si de una vez se envia la nueva version a la Marketplace. o/
