### ISSUE TITLE
Doesn't start when offline

### ISSUE THREAD

**Issue by jeena** [loqui/im#140]
I didn't realize that my phone was offline, when I started LOQUI I only got a black screen and nothing more. It should at least show some hint that this is because of the fact that my phone is offline.

**Comment by Gioyik** [comment]
seems a rare behavior, on which version are you working on? could you provide us a log?

**Comment by aesedepece** [comment]
Did this happen with Marketplace release or GitHub nightly?

**Comment by jeena** [comment]
I tested it again and I think you can't do anything about, this is was happened:
- While I still had Internet I downloaded and installed the application.
- I use prepaid card, when the money is gone I don't have internet anymore but Cellular & Data is still on, so the phone thinks it is online, but in fact the provider doesn't allow sending or getting any packages to the internet.
- Many applications, including the Marketplace think they're online but they can not send or receive data
- Therefor many apps behave undefined

Interestingly when I tried it again today then Loqui did show everything until I tried to connect, then obviously it waited until my jabber server would respond which it couldn't because I have to pay for another month for my provider.

In my opinion this should be handled better by the OS.

**Comment by aesedepece** [comment]
I'll pass the bug and the suggestion to the B2G and Gaia people. Many thanks!
