### ISSUE TITLE
Error al recibir mensajes multiples

### ISSUE THREAD

**Issue by aarizkuren** [loqui/im#146]
When i received big amount of messages, the behaviour was not correct, it duplicates chats and when 

Cuando recibo una cantidad considerable de mensajes, el comportamiento de la aplicación no es correcto. Multiplica varias veces cada chat, o "pisa" chats anteriores y los cambia de nombre/foto. Luego al entrar en ese chat, no siempre salen los mensajes, a veces se queda vacio todo.

A ver si mañana puedo subir algun log.

**Comment by aesedepece** [comment]
Espero los logs, a ver qué puede estar ocurriendo.

**Comment by aarizkuren** [comment]
Los logs al final no voy a poder ponerlos, sale demasiada info privada (telefonos, nombres y esas cosas) y no tengo tiempo para poder filtrarlo adecuadamente. Como mucho podría pasartelos de forma privada, de todas maneras, subo un pantallazo para que se pueda ver lo que me esta pasando, que creo que es lo suficientemente claro.
![repeated_chats](https://f.cloud.github.com/assets/476141/1710250/1457e6da-612d-11e3-8258-4179a520638e.png)

Todos los chats que aparecen difuminados deberian de ser el mismo, pero al ir recibiendo muchos mensajes, ha ido sobreescribiendo otros chats que estaban ahí antes, perdiendo esas conversaciones.

Si se os ocurre algo, yo podría mirarlo, pero no se exactamente en que punto es en el que escribe esto...

EDIT:
Se me olvidaba, al acceder al interior de los chats, no siempre aparecen las conversaciones, bastante a menudo, aparecen en blanco.
