### ISSUE TITLE
The app i sno more available in my region.

### ISSUE THREAD

**Issue by kkdeep** [loqui/im#147]
![2013-12-09-21-12-56](https://f.cloud.github.com/assets/1812737/1706071/2a84a6ee-60e9-11e3-9b0a-e270fdb73c3b.png)

I had uninstalled the app few weeks ago since it was having some issues. Few days back i again tried to give it a shot but its showing that its not available in my region. Had any changes been made due to which its not available in my region?

**Comment by willyaranda** [comment]
So, what's your region?

**Comment by kkdeep** [comment]
India,Asia.

**Comment by aesedepece** [comment]
For some reason, Firefox Marketplace seems to think that your IP belongs to USA or China, which are the two only countries where the app is not available.

**Comment by kkdeep** [comment]
![ip](https://f.cloud.github.com/assets/1812737/1711297/0d4f5716-614a-11e3-89c7-7275ebf22718.png)

Is it Firefox Marketplace bug? coz when i check my IP it shows the proper one.

**Comment by thallian** [comment]
Same problem here on a Geeksphone Peak, country is Switzerland.
I still have Loqui installed and get updates but I can't even find it in the marketplace.

**Comment by aesedepece** [comment]
I've changed the selection of available countries to "All but China". Now it should be available for everyone as no restrictions are applied.

Can you @kkdEEP and @thallian check if you can download it now? Thanks.

**Comment by kkdeep** [comment]
Yes! Now its available. Just installed it and testing it again. :)

**Comment by thallian** [comment]
perfect, thanks :)

**Comment by eMBee** [comment]
why is the app not available in china?

**Comment by aesedepece** [comment]
@eMBee Following the Mozilla Marketplace terms, availability in China is subject of an special and separate review process. We'll make sure we check that option the next time we send a new update. Sorry for the inconveniences.

**Comment by eMBee** [comment]
managed to install it today, thank you!
