### ISSUE TITLE
Login can't tell if WA password is no longer valid

### ISSUE THREAD

**Issue by aesedepece** [loqui/im#148]
Reported by @devja4a in #145 

The issue is that when you login to WhatsApp and the auth fails it continues as if nothing happened.

The expected behaviour is to return to account setup screen and let the user reset the password through the validation process. The chats and contacts should remain untouched.

Any suggestions on a more natural UX?

**Comment by Gioyik** [comment]
There's any way to know if the connection with Whatsapp is lost?

**Comment by Gioyik** [comment]
Wohooooo! I commited in the Pull Request for v0.2.5 (#178) a UX fix for this. It just redirects to the providers section and shows a notification for 8 sec (sometimes notifications are very faster, and this one is very important) when auths fails.
