### ISSUE TITLE
Conversaciones duplicadas

### ISSUE THREAD

**Issue by cargabsj175** [loqui/im#149]
en whatsapp, se duplican los mensajes de un mismo contacto https://twitter.com/willicab/status/411550817728991232/photo/1

Saludos

**Comment by Gioyik** [comment]
Adjunto algunas mias que lo confirman: 

![2013-12-13-10-26-08](https://f.cloud.github.com/assets/1834718/1744641/a33c0a98-6420-11e3-9a8d-2789002b552f.png)
![2013-12-13-10-27-42](https://f.cloud.github.com/assets/1834718/1744642/a3633640-6420-11e3-8081-e5634290e595.png)
![2013-12-13-10-35-18](https://f.cloud.github.com/assets/1834718/1744643/a365e340-6420-11e3-90ad-e226d4660ac9.png)
![2013-12-13-10-35-24](https://f.cloud.github.com/assets/1834718/1744644/a36caf22-6420-11e3-91e7-8f9ff87e748c.png)

**Comment by nukeador** [comment]
A mi me ha pasado, tenía 2 conversaciones individuales y un grupo. Con la última actualización cuando me llegó un mensaje de un grupo, todas las conversaciones se transformaron en la de ese grupo.

**Comment by YukiteruAmano89** [comment]
A mi tambien me ha pasado lo de las conversaciones duplicadas, especificamente cuando estoy chateando con una persona, no he probado si en grupo pasa lo mismo.

**Comment by aarizkuren** [comment]
A mi me sigue pasando, tal como dije en #146 , y con los cambios que se pusieron ahí no se soluciono el problema.
No se podría crear algún tipo de cola de mensajes que se procesen uno a uno? es decir, ir cargando a la cola de mensajes, y aunque sea asincronamente, cuando termine de cargar uno, empezar con el siguiente, porque si se van lanzando todos a la vez, imagino que la app se vuelve loca con los índices de los chats y ahí sale el error.

**Comment by DiegoErnesto** [comment]
pienso lo mismo que aarizkuren.

**Comment by aesedepece** [comment]
El caso es que el problema actual apareció tras los commits 1d13fa7cb364b9b46de06fd875b5d9c76f1b8a80 y 8c02137611f6efce3ae4587b4308428319810609, que precisamente lo que hacen es poner los mensajes en una cola e ir procesando uno a uno para finalmente pasarlos al almacenamiento. Vamos a revisarlo cuanto antes porque en algún lugar se me debió de escapar algo bien gordo.

**Comment by aarizkuren** [comment]
He estado mirando un poco, y si no he entendido mal, en https://github.com/waalt/loqui/blob/master/scripts/waalt/chat.js#L50 hace un async.queue();
y segun la documentacion del async (https://github.com/caolan/async#queue), esta función trabaja en paralelo. No seria mejor añadir ahí una que funcione en serie? es decir, que vaya procesando mensaje a mensaje.

**Comment by aesedepece** [comment]
@aarizkuren El método `async.queue()` toma automáticamente concurrencia 1 cuando no se especifica esta, por lo que es equivalente a procesarlas en serie.
