### ISSUE TITLE
why Loqui connects to its own XMPP server instead of connecting to the real service server?

### ISSUE THREAD

**Issue by soapdog** [loqui/im#155]
Hi,

Checking out the source code for Loqui, I've noticed that all providers except whatsapp appears to connect to http://app.loqui.im/http-bind/ which appears to be a XMPP server (probably ejabberd). I want to understand why you are connecting to your own server instead of connecting directly to the real provider server.

Cheers
andre

**Comment by qmx** [comment]
xmpp requires something like a BoSH gateway (what loqui provides) which not all providers allow, or tcp connections, currently not available.

**Comment by vitalyster** [comment]
"http://app.loqui.im/http-bind/" is a gateway or "session manager", which maintain persistent connection on a behalf of user. With current XMPP specs mobile application can not maintain connection directly, there are many issues with background keep-alive, notifications, etc. So http-bind(BOSH) gateway is a good solution to solve these issues somehow.

**Comment by soapdog** [comment]
Thanks for the heads up on that. Is your session manager on GitHub? It would be great if instead of using BOSH it could stop the client and wake it using simple push... (a lot of work probably).

**Comment by aesedepece** [comment]
For more information:
https://github.com/waalt/loqui/issues/50
https://github.com/waalt/loqui/issues/124
