### ISSUE TITLE
emoticons within hyperlinks at chat 

### ISSUE THREAD

**Issue by enapupe** [loqui/im#160]
This is the rendered html of a hyperlink with a :/ (emoticon) inside it:

```
<a href="http&lt;img src=&quot;img/emoji/fb/:\.png&quot; alt=&quot;:/&quot; /&gt;/www.youtube.com/watch?v=1no4ysWxyNg" target="_blank">http<img src="img/emoji/fb/:\.png" alt=":/">/www.youtube.com/watch?v=1no4ysWxyNg</a>
```

The issue seems to be located at xmpp.js:343 @fy function which renders text to emoji;

**Comment by aesedepece** [comment]
Funny bug. Links work though.
We'll see how to make the emoticon processor not read URLs.
Thanks for reporting!

**Comment by enapupe** [comment]
The link is NOT following through the emojized URL on 0.2.3

**Comment by aesedepece** [comment]
This is not happening any more as of 0.2.5 after solving #166 ;)
