### ISSUE TITLE
Implementar Telegram

### ISSUE THREAD

**Issue by mautematico** [loqui/im#161]
http://telegram.org/
https://github.com/vysheng/tg/

https://github.com/vysheng/tg/issues/25

**Comment by aesedepece** [comment]
TIene toda la pinta de ser el siguiente protocolo en ser implementado en LoquiIM. :+1: 
¿Que tal si cambiamos el título del issue por "Implementar Telegram" y empezamos a discutirlo?

**Comment by Gioyik** [comment]
http://www.cryptofails.com/post/70546720222/telegrams-cryptanalysis-contest

**Comment by mautematico** [comment]
"Luego" es tarde. ;)

**Comment by Gioyik** [comment]
Creo que tiene mas ciencia de la que parece. La documentación hasta ahora es muy poca y la api no esta del todo libre, puede llevar un tiempo hasta que se considere viable experimentar con el nuevo protocolo. Podemos ver como avanza y ver que posibilidades tenemos, de igual manera hay una cola de cosas por hacer para LoquiIM aún. ;)

**Comment by sebasmagri** [comment]
Como comenté en https://github.com/vysheng/tg/issues/25#issuecomment-32672277 creo se que podría utilizar el código de tg y llevarlo a JS con emscripten. Sin embargo, este es un protocolo TCP, no HTTP, haría falta un puente a HTTP o WebSockets para hablarlo desde el cliente.

Saludos.

**Comment by aesedepece** [comment]
Para eso está la TCPsockets API → https://developer.mozilla.org/en-US/docs/WebAPI/TCP_Socket

**Comment by sebasmagri** [comment]
@aesedepece Gracias, hasta ahora lo ignoraba por completo.

**Comment by jorgeuve** [comment]
Yo esta gente no se a que juega.. A que viene esto de reinventar la rueda? Porque no usan OTR en vez de hacerse pajas mentales con un sistema de cifrado evidentemente vulnerable. No hacen sino dar que pensar que su modelo de negocio se basará en vender el acceso a los chats secretos dejando su implementación  vulnerable.

**Comment by aesedepece** [comment]
@jorgeuve :+1:

**Comment by nukeador** [comment]
Quizá esto os sirva: https://github.com/zhukov/webogram/blob/master/app/js/lib/mtproto.js

**Comment by opensas** [comment]
+1
aquí hay un cliente en html5 https://github.com/zhukov/webogram

**Comment by nileane** [comment]
This should definitely be implemented !

**Comment by suoko** [comment]
Implement appear.in and thus enable video chat

**Comment by TitanNano** [comment]
I think Telegram support is really unnecessary, the [Webogram](http://github.com/zhukov/webogram) has created a fine port of the telegram Application for Firefox OS. We would just waste time and resources on this. I'll close this since this issue didn't get any update for a while.
