### ISSUE TITLE
Error al Agregar una cuenta nueva

### ISSUE THREAD

**Issue by JCVega** [loqui/im#165]
Loqui IM V0.2.4
Esta instalado sobre el Simulador de Firefox OS, me parece que la version es 1.1.0.

cree una cuenta de Facebook sin problema, pero al una segunda cuenta, en este caso de Hangust, no me deja navegar hacia ella, solo se queda en la primera, puedo acceder a cualquier otro elemento del menu.
Cuando selecciono el boton de Facebook me aparece que el indice es un 0
y en Hangust un -1
Algo como esto [espero se suba la imagen]
![bug error agregar cuenta](https://f.cloud.github.com/assets/6250173/1807522/e7035268-6cf4-11e3-95fc-8565bb32c781.png)

Despues cerre y volvi a abrir loqui, y en Facebook me sigue cargando un 0, pero ahora en Hangust me manda un -1.
![bug error agregar cuenta 2](https://f.cloud.github.com/assets/6250173/1807537/990da2c4-6cf5-11e3-808b-c473dafc7f4b.png)

Reinstale Loqui, despues insatale mis dos cuentas nuevamente e indague un poco en el codigo, y parece que se esta cargando dos veces el nuevo boton, uno con el indice correspondiente(en este caso -1) y otro mas con el indice -1
![bug error agregar cuenta 3](https://f.cloud.github.com/assets/6250173/1807521/e6fd5c96-6cf4-11e3-840a-e1d65d4effc5.png)

**Comment by Gioyik** [comment]
El Pull Request ya ha sido aceptado y los cambios hechos, asi que esto deberia estar solucionado.
