### ISSUE TITLE
Error al recibir Emoticon

### ISSUE THREAD

**Issue by JCVega** [loqui/im#166]
Loqui IM v0.2.4
Esta correindo bajo el simulador de Firefox OS, me parece que la vercion es 1.1.0

Al recibir un emoticon de facebook en loqui im no me aparece el emoticon, creo que es cuestion de cuando viene solo el emoticon, sin mas texto.
(Izquierda chat de Facebook, derecha Loqui)
![bug error recivir emoticon](https://f.cloud.github.com/assets/6250173/1807548/f13beedc-6cf6-11e3-9900-4933576f2256.png)
(Izquierda Loqui, derecha Facebook)
![error emoticon](https://f.cloud.github.com/assets/6250173/1807553/97ec7b0c-6cf7-11e3-89af-2db7bafab004.png)

**Comment by Gioyik** [comment]
Podrias poner algun error de consola que nos muestre algo del error?

**Comment by JCVega** [comment]
Claro que si esto es lo que me aparece al mandar el emoticon
![error emoticon consola](https://f.cloud.github.com/assets/6250173/1808787/eefdf4a4-6d77-11e3-80d3-677cb575a299.png)

Me parece que el detalle es el <<"PUSHING" 425 [object undefined]>>
Al parecer el objeto chunk no es declarado, el archivo que lo utiliza es chats.js aproximadamente en la linea 54.

Esto es a mi parecer no estoy totalmente seguro que sea esto.
¡¡Feliz Navidad!!

**Comment by JCVega** [comment]
Una disculpa, al parecer no todos los emoticones se copiaron, o se copian en mi carpeta, al parecer son los nombres que tienen. Pero si manda bien los emoticones

**Comment by Gioyik** [comment]
Ahora entiendo que usas WIndows, y probablemente tengas problemas como el mencionado en este issue #119. LO abro de nuevo ya que es un issue nuevo y no se ha solucionado aun.

**Comment by JCVega** [comment]
Jaja si tendre que instalar una particion de Ubuntu,
Y si, es el mismito problema.
Quiza deberias dejarlo así, solo advertirlo en el Readme, sugerir el uso de otro sistema operativo, y dejarlo como una limitacion. No se que opinen.

**Comment by Gioyik** [comment]
No tanto eso, como se hablaba en el otro issue tenemos que tener en cuenta que necesitamos pensar en los usuarios y en que no todos usan Linux, MacOS y derivados de Unix. Voy a solucionarlo, y te pongo el link del comit que haga aqui.

**Comment by JCVega** [comment]
Ok me parece bien.
Gracias Gio.

**Comment by Gioyik** [comment]
Este commit soluciona el problema con el nombre de los emoji:

https://github.com/Gioyik/loqui/commit/9fd5325d49ebae812ed1c1da7df1c33e45d04f37

Se agrega en el proximo Pull Request para la proxima version. (0.2.5)

Gracias

**Comment by JCVega** [comment]
Va gracias Gio.
