### ISSUE TITLE
Bienvenida Pasmada

### ISSUE THREAD

**Issue by JCVega** [loqui/im#167]
Loqui IM: v0.2.4
Dispositivo: Lanzado desde Simulador Firefox OS
Cuando se lanza la aplicacion por primera vez, te muestra el menu de servicios a los que te puedes conectar. Pero si le das en cancelar te regresa a la pantalla de bienvenida, y ahi se queda, no vuelve a mandar nada, hasta que cierras y vuelves a abrir la aplicacion.
No es el gran error pero talvez alguien se llegue a confundir en este menu

**Comment by Gioyik** [comment]
Hay un problema y es que si retiramos el boton de alli cuando se intente agregar una cuenta nueva usando el boton que tiene un +, y por X o Y motivos ya no queremos agregar dicha cuenta e intentemos regresar a la pantalla principal ya no es posible.

**Comment by aesedepece** [comment]
Supuestamente pulsando en cualquier lugar de la splash screen se podía volver al menú de selección de proveedor, pero parece que ya no está funcionando.

**Comment by JCVega** [comment]
Pues yo pensaba en verificar si ya tenia alguna cuenta, en caso contrario ocultar el boton de regresar, pero me parece mucho mas economico hacer que al darle click regrese al menu de seleccion de provedor.
Me parece que de esta ultima forma ya lo tengo solucionado en un momento hago la solicitud de pull y me dicen si hay que cambiarle algo mas.

**Comment by Gioyik** [comment]
Venga! Ando pendiente del pull para cuando lo hagas, lo miramos. :)

**Comment by JCVega** [comment]
Parece que ya pude subirla.
Creo que voy a necesitar un manual de JS y otro de Github jaja.

**Comment by Gioyik** [comment]
Ya he pasado los cambios que has hecho, gracias por el Pull Request. Hice un cambio minimo a lo que modificaste solo para que tenga la estructura que llevamos en todo el codigo.

**Comment by JCVega** [comment]
De nada, del cambio no te preocues.
Seguire buscando errores y a ver si los puedo apoyara resolver algunos.
