### ISSUE TITLE
Sending WhatsApp images

### ISSUE THREAD

**Issue by aesedepece** [loqui/im#168]

**Comment by aesedepece** [comment]
Still needs work on UI/UX:
- Progress bar
- Success / error messages
- Show sent message in chat
- Show "John Doe has sent you a image" in system notifications
- Show "Image" as last message in chats list
- Send image from Gallery app

**Comment by Gioyik** [comment]
See this commit 972f1c867d91f9590a64e1443890c4022d99aa28

**Comment by aesedepece** [comment]
I think this is done. Further works might be done in order to improve UX (e.g. progress bar instead of notification).
