### ISSUE TITLE
Use Store.SD.save instead imageSave and videoSave

### ISSUE THREAD

**Issue by Gioyik** [loqui/im#173]
#169

**Comment by Gioyik** [comment]
Pregunta, en que momento se deberia guardar la imagen?

**Comment by aarizkuren** [comment]
En mi opinion, cuando se recibe hay que mostrar el thumbnail (mediaPreview) y si se le da click, guardar la original (mediaUrl) en la sdcard, para que si no quieres no tengas que bajartela

**Comment by aesedepece** [comment]
@aarizkuren Exacto, así es como está ahora mismo.

**Comment by Gioyik** [comment]
Una pregunta, cuando usamos el imageSave, videoSave, AudioSave?

**Comment by aesedepece** [comment]
Pues en principio, ninguno de esos métodos son necesarios teniendo `Store.SD.save`, siempre que se le pase un blob lo guarda sin problemas.

**Comment by aesedepece** [comment]
¿Esto ya está hecho, cierto?

**Comment by Gioyik** [comment]
No se si para el envio de archivos ya esta hecho, que yo sepa ya esta hecho cuando se reciben imágenes. Voy a revisar.
