### ISSUE TITLE
Sugerencias

### ISSUE THREAD

**Issue by aarizkuren** [loqui/im#176]
Buenas, 
vengo con un par de sugerencias para poder llevar adelante mejor este proyecto, a ver que os parecen:

1.- Crear una rama de desarrollo, y usar la master solo cuando una versión funcione, porque está pasando que se hacen desarrollos a medias, y esto hace que no funcione correctamente lo que antes si lo hacia. Haciendo esto conseguiriamos un poco más de estabilidad para la gente que utilice el programa en el día a día, y no solo para programarlo.

2.- Utilizar la herramienta que nos da github, los pull request. Hacer el desarrollo en nuestros forks particulares, y cuando tengamos un bug completamente solucionado, o una nueva funcionalidad hecha, mandar un PR. Con esto creo que vamos a conseguir que colaborar con el proyecto sea más fácil, porque se ven todos los cambios que se añaden de un golpe, y no como ahora, que si haceis push varios a la vez, los commits se entremezclan y es mas dificil tener la foto completa de la aplicación.

3.- Definir una guia de estilo para programar, es decir, numero de espacios de los tabuladores, formato para usar las funciones, las llaves...

pues eso, a ver que os parece esto, y si lo veís factible o tenéis mejores ideas.
saludos

**Comment by Gioyik** [comment]
Hay una branch devel que se supone que esta para esto, pero se dejo de usar desde que el soporte para Whatsapp salio a la luz. Yo estaba empezando a usar los Pull Request y dejar de hacer commits directos, pero me dieron mas de un dolor de cabeza al ver que enviaba un Pull Request, luego hacian cambios y si se aplicaba el Pull Request se sobre escribian cosas y se formaba otra mas grande (realmente no se porque me sucedia esto).

Me parece bien mejorar la forma en que se envian los cambios. Tal vez tambien deberiamos definir unas lineas de contribucion en el Readme.

Podria volver a poner activa la branch devel con los cambios que hay en este momento en master removiendo los cambios que hice yo y poniendolos en un Pull Request para despues, y dejar en la master dejar solo el codigo que queda listo para enviar a la Marketplace, en este caso quedaria el codigo de la v0.2.4. Que dices?

**Comment by Gioyik** [comment]
Ya he creado un branch Dev para trabajar despues de que salga la version v0.2.5, y estoy documentando todo en la wiki:

https://github.com/waalt/loqui/wiki

Lo que quisiera que definieramos son los tiempos para cada version, definir fechas o lapsos de tiempo para el versionado y no estar sacando versiones a veces a los dos dias de haber sacado la otra, o por el contrario tomarnos dias o semanas para sacar alguna otra version. Alguno tiene una sugerencia para esto?

**Comment by aesedepece** [comment]
Respecto al punto 3, la guía de estilo, intentamos seguir la de mozilla:
https://developer.mozilla.org/en-US/docs/Developer_Guide/Coding_Style#JavaScript_practices

Ejemplo:

``` javascript
function foo () {
  console.log('bar'); // There are two trailing spaces acting as tab
}
```

**Comment by Gioyik** [comment]
Cof, cof, cof... Alguien por ahi dijo una vez que se iba a encargar de comentar todo el codigo para que fuera mas entendible, no @aesedepece?

**Comment by aesedepece** [comment]
Ooops... ya lo pillo :+1:

**Comment by Gioyik** [comment]
Esto ya lo podemos discutir en la lista. :)
