### ISSUE TITLE
Some XMPP acounts stay in 'Syncrhonizing'

### ISSUE THREAD

**Issue by ghost** [loqui/im#181]
I have tried with different accounts but some remain in 'Syncrhonizing'

Log: app.loqi.im/http-bind/ [HTTP/1.1 200 OK 213ms]

I test in FirefoxOS 1.2, 1.3 and FirefoxOS Simulator 4.0 (1.2)

**Comment by Gioyik** [comment]
Which accounts did you try to log in with?

**Comment by ghost** [comment]
My account: distopico [at] riseup [dot] net (Work)

Account of my wife:  ziggvegan [at] riseup [dot] net (Not working)

**Comment by Gioyik** [comment]
Are you testing on phones or just in the simulator? If yes, which phone (and which version) are you using?

However I was trying to create an account in Riseup to test, but the official site is not loading me, well, probably not loading for nobody:

http://www.isitdownrightnow.com/riseup.net.html

The site is maker as down, so probably you can't connect because in Riseup sever side there's nothing to answer. The rare thing here, is that we have a function for connections timeout. Please, test again and tell us.

**Comment by ghost** [comment]
Test in Simulator and phone Alcatel One Touch Fire version 1.1 and 1.2

The register in Riseup is by invitation code.
I tried in two accounts in deferents moments.

My account: distopico [at] riseup [dot] net (always Work)

Account of my wife: ziggvegan [at] riseup [dot] net (always Not working)

I also tried the facebook account of my wife (accion.visual.1) and Not working

**Comment by achintangal** [comment]
I have the same problem too.
@Gioyik , it doesn't seem like their server problem, I use their service daily on my machine via pidgin. 
btw, I am using firefox 1.1.

**Comment by aesedepece** [comment]
There are reported problems when connecting to some servers:
- riseup.net
- kdetalk.net

I have yet to investigate what's special in that servers and why they refuse connections from Loqui.

**Comment by ghost** [comment]
.... so let's contintue tracking this issue here.

In the version 0.2.5c (and older) the problem was not occuring.

Do you need any logs? You can creat an account there if you want to test it by yourself:
http://www.jabber.de/register/

As I mentioned in the closed isse #343, jabber.de has migrated few days ago from Openfire to Prosody 0.9.3. Well this server has always been very stable and has a very good grade from the  IM Observatory (https://xmpp.net/index.php). That is why it would be great if have the time to check why it is not working.

Thank you a lot!

**Comment by ghost** [comment]
Thanks a lot :)

**Comment by ghost** [comment]
Any news concerning this issue?

@aesedepece do you need some logs or any other infos?

Edit: How can I extract the logs of loqui?

I get nothing with: adb logcat | grep GeckoConsole, alothough Debug mode is activated.

**Comment by ghost** [comment]
Friendly reminder! @aesedepece @Gioyik 

The Admin of jabber.de is ready to help, he asked for the logs of loqui. Can you please tell me how to extract them?

Thank you.

**Comment by Gioyik** [comment]
I can't understand, when someone try to login with a jabber.de account it stuck on Synchronizing part?

**Comment by ghost** [comment]
Yes it does. This happened after the update to 0.2.6.  But as i wrote in older posts, the admin has switched the server to prosody, so i can't tell wich update causes this problem, loqui: 0.2.5c -> 0.2.6, or jabber.de: openfire -> Prosody.

**Comment by ghost** [comment]
That is why the logs are needed to clarify the root of the problem. can you please tell me how to get them?

**Comment by hotzeplotz** [comment]
same issue here - Loqui 0.2.6, Firefox OS 1.1.0.0. connecting to my own (Prosody, Debian package version 0.8.2-4) XMPP server.
Loqui authenticates (if i try with an invalid password, i get an Authentication failed message straight away), and then gets stuck on the "Synchronizing" popup.

Prosody logs only show, eg.:
Mar 18 10:18:48 c2s1834ef0  info    Client connected
Mar 18 10:18:48 c2s1834ef0  info    Authenticated as user@example.com

then nothing else (no information, no error messages). Not sure how to get to Loqui's own logs on FFOS device to check if anything informative is being logged on the actual FFOS device.

**Comment by ghost** [comment]
Could it be related to Prosody?

@Gioyik @aesedepece can you please tell us how to extract the logs?

Well Loqui is totaly unusable because of this issue and this #358

**Comment by ghost** [comment]
Any updates on this issue?

@aesedepece can you please tell us how to extract the logs? Is it a prosody issue?

**Comment by KThand1** [comment]
Dukgo.com and blah.im does not allow me to log in - jabber.me/jabber.org seem to be okay though. (On latest)

**Comment by aesedepece** [comment]
Just tested and worked with both my existent dukgo.com account and a just-created blah.im account, so it's not about the providers but the account itself (probably something in the XMPP roster).

**Comment by ghost** [comment]
@aesedepece can you please create an account on http://www.jabber.de/register/ and try if it works?

**Comment by aesedepece** [comment]
With jabber.de, It seems to halt in here:

Client → Server

``` xml
<iq type='get' from='adansdpc@jabber.de/Loqui' xmlns='jabber:client' 
id='1681:sendIQ'>
  <vCard xmlns='vcard-temp'/>
</iq>
```

Server → Client

``` xml
<iq id="1681:sendIQ" type="error" to="adansdpc@jabber.de/Loqui" 
xmlns:stream="http://etherx.jabber.org/streams" version="1.0" 
xmlns="jabber:client">
  <error type="cancel">
    <item-not-found xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
  </error>
</iq>
```

According to xmpp.org/extensions/xep-0054.html (3.1 Example 3), the account doesn't have an associated vcard.

So the fix to this issue will need to:
- Catch the "item-not-found" error
- Stop waiting for an existent vcard
- Publish a new vcard
- Move on with the setting up process

I take personally the commitment of fixing it asap because this issue has been inexplicably unresolved for way too long and affects quite a bunch of servers. I'll keep you updated!

**Comment by aesedepece** [comment]
PRO-TIP: if you want you accounts to work inmediately in Loqui, set them in Pidgin and change your profile image to will create a vcard for your account. (That's why my dukgo and blah accounts worked on the first go: they had been created in Pidgin)

**Comment by ghost** [comment]
The Pro-Tip is working!! thank you very much!

**Comment by rafaelmr2** [comment]
@aesedepece, not work for me. I set my profile image in Pidgin, but still in "Syncrhonizing" on my riseup account.

**Comment by lenod** [comment]
Anyway this is not a fix. 
I am affected by this bug too.

**Comment by lenod** [comment]
For information, I run a prosody server too, and here is my log : 

Jul 22 14:37:41 c2s1198de0  info    Client connected
Jul 22 14:37:42 c2s1198de0  info    Authenticated as foo@bar.com
Jul 22 14:37:42 c2sf3e4b0   info    c2s stream for foo@bar.com/Loqui closed: Replaced by new connection
Jul 22 14:37:42 c2sf3e4b0   info    Client disconnected: connection closed

**Comment by plop3** [comment]
@lenod same problem for me (prosody server)
