### ISSUE TITLE
Confirm Location recieve support

### ISSUE THREAD

**Issue by Gioyik** [loqui/im#186]
Based on commit 6acd7c2 just test the latest changes to see if this feature is working or not.

**Comment by aarizkuren** [comment]
He hecho unas modificaciones que hacian que fallara el recibir la localizacion.
Lo unico ahora cuando te mandan una, se muestra una imagen en blanco, hay que modificar el Message.preRender() para que en caso de que this.core.media.type == url, muestre un enlace, o un iframe, al gusto
pero recibir ya lo recibe bien :D

**Comment by Gioyik** [comment]
No deberia mostrar el blob de la imagen que he agregado?

https://github.com/waalt/loqui/blob/master/scripts/waalt/connectors/coseme.js#L627

El comportamiento seria que aparezca la imagen del blob y que al seleccionarla se abriera una ventana en modo _external, que habra un link como este: 

http://maps.google.com/maps?q=mlatitude+','+mlongitude

Que dices?

**Comment by aarizkuren** [comment]
Esta todo funcionando, excepto la imagen, que por lo que he visto, la aplicacion en vez de coger el blob tal como se lo paso (con la modificacion que le he hecho, para añadir el header "data:image/png;base64,") lo que hace es algun tipo de filtro, y lo añade como si fuese una url relativa a la app, del tipo "app://id-del-app/blob-sin-header"

Ahora no tengo tiempo para mirar esto, si se os ocurre que es lo que falla dadle, sino, mañana intento mirarlo.

Por lo demas, ya le he añadido el url, y ya entra bien a gmaps con la posicion indicada.

**Comment by Gioyik** [comment]
El problema esta en que has olvidado agregarle el data:image/png;base64, en:

https://github.com/aarizkuren/loqui/blob/d3048b2f2b4d2013249986c07c9703671175ca63/scripts/waalt/connectors/coseme.js#L678

Creo que con ese cambio ya queda arreglado y se puede hacer merge. :)

Podrías comentarme en donde esta la URL que procesa con la geolocalización?

**Comment by Gioyik** [comment]
Dejo que hagas los cambios tu para no pisarnos luego entre Pull Request.

**Comment by Gioyik** [comment]
No me hagas con lo de la url, ya he visto donde la has puesto. :)

**Comment by Gioyik** [comment]
Ya ha quedado bien con los ultimos cambios?

**Comment by aarizkuren** [comment]
Sí, ya esta funcionando correctamente
