### ISSUE TITLE
Test new Whatsapp features

### ISSUE THREAD

**Issue by Gioyik** [loqui/im#187]
We added some new features related to Whatsapp, and now that the code is landed, is time to see if it is working or not. Check that we are receiving photos, videos, audio and locations.

Code to send photos, videos... etc is not landed yet, but we can test it too of course. :)

**Comment by jorgeuve** [comment]
Hi all (HOLA A TODOS)
Whats app tests ON ZTE-OPEN from telefónica to iphone ios7 ios 7.0.4
:-) :-) -photos yes (receive a transmit)

:-) -videos zte not receiving tipical joke videos (after restat and quit usb debug begins to work ?¿?¿)

:-( -videos zte not sending a short video captured moments ago with the zte camera. Choosing file from gallery.  Appears video on chat whit "0% loading" endless message (tryed two times) 

:-) -videos zte works well sending a short video captured at the same moment that you compose message

:-( videos played badly when yo put the phone in landscape. Video appear not in the center and not resize to greater size

:-( -Sound recorded on message time at iphone  arrive to zte open but is not possible to listen.  A cd icon appear but no playing icon. 

:-( -Sound recorded by other people and resended to zte open is not possible to listen.  A cd icon appear but no playing icon. 

:-) :-) emoticons receive and transmit working 

:-( ubication sending not implemented (icon doesn´t appear) receive ubication  from iphone doesn´t work (appears a white box with nothing inside)

:-( Sound sending from iphone for example  a mp3 file from the phone library is not possible  , from Loqui im its possible but app close suddenly while triying 

Best regards

**Comment by Gioyik** [comment]
@jorgeuve Which version are you testing? the latest on master? we made some changes right now related to Geolocation and other fixes.

@aesedepece It's impossible to know if something is working or not, if on a ZTE phone something works, in an Alcatel doesn't. The best as we can do is release the v0.2.5 and let the users (and a few compromised Mozillians) test and report us whats happening on their phones. It's a little bit annoying this situation where CSP violations and the problems are different on each phone. The solution is release and wait for user reports. What you think?

**Comment by aesedepece** [comment]
- For audio: there's no play button, just touch the message or the CD icon and it will play.
- We are not responsible of issues with video playing, they belong to the video player bundled with FirefoxOS.
- The location sending function wasn't merged to the master branch until some minutes ago.
- The message you receive when you send yourself a location could be a CSS issue, I tested it with a Geeksphone Peak which is quite bigger, so I'll check it.
- The problem with crashes when trying to send big audio files has just been fixed.

**Comment by aesedepece** [comment]
@Gioyik :+1: to releasing right now. Let's upload it to the Marketplace. Any issue that may appear will be much smaller than the awful existing ones in 0.2.4.

**Comment by Gioyik** [comment]
I will send a message to the mailing list related to this.

@jorgeuve We really appreciate the time you spend on comment this issue. We are going to release the v0.2.5. If you continue feeling any problem with Loqui, feel free to create an issue reporting it. Thanks.

I am going to close this one.

**Comment by jorgeuve** [comment]
Ok, my tests were over 0.2.5 installed sunday afternoon from master branch. I think Im rigth but i will look again my github config.
