### ISSUE TITLE
Typing method for Whatsapp

### ISSUE THREAD

**Issue by Gioyik** [loqui/im#188]
We landed code for this feature in commit 26c14c6 and needs testing to confirm if it is working or not.

**Comment by aarizkuren** [comment]
Lo he probado y no funciona, me devuelve los siguientes errores
<code>
Error invoking false with ["346XXXXXXXX@s.whatsapp.net"] ~ call@app://xxxxxxxxxxxx/scripts/anonymous/coseme.js:6166 [yowsupAPI]" coseme.js:3377

23:41:29.786 "Error details: 
TypeError: "CoSeMe.yowsup.connectionmanager.methods[aMethod] is undefined" at 
call@app://xxxxxxxxxx/scripts/anonymous/coseme.js:6164 >
 App.connectors.coseme/this.events.onContactPaused@app://xxxxxxx/scripts/waalt/connectors/coseme.js:389 >
 fireEvent/</<@app://xxxxxxxxxx/scripts/anonymous/coseme.js:7059 >  
~ call@app://xxxxxxx/scripts/anonymous/coseme.js:6167 [yowsupAPI]"
</code>

Así que por las pintas, el error esta en Coseme, y eso en principio tendrian que arreglarlo ellos. Yo puedo echarles una mano, pero no se cual es la web del proyecto. @aesedepece puedes mandar un enlace? gracias

De todas formas, cuando nosotros escribimos desde loqui, sí que sale en el cliente de tu amigo el "escribiendo"

**Comment by Gioyik** [comment]
No hay página del proyecto, tenemos que informar por privado. No te preocupes, vamos avisarlo.

**Comment by willyaranda** [comment]
El código de Giovanny está mal, hago los comentarios en el commit

**Comment by Gioyik** [comment]
@aarizkuren puedes probar ahora con el ultimo commit?

**Comment by aarizkuren** [comment]
Ahora funciona perfecto, gran trabajo @Gioyik @willyaranda !!!

**Comment by Gioyik** [comment]
Wohoooooo!!!
