### ISSUE TITLE
Style for group chats

### ISSUE THREAD

**Issue by Gioyik** [loqui/im#189]
As reported in #115 #134 we landed some code in commits 44a0dda6e7f9aaa088e556df1dd1875f21b7d038 and d887b2062f31432261ed7e084b4ea527959e2dd6 to make this work. But is not working at all. The code adds the attribute data-muc to every chat (someone could test this to be sure that is true?) but the value is false all the time.

See the line with the important code and read #178 to get background about this issue:

https://github.com/waalt/loqui/blob/master/scripts/waalt/account.js#L150

**Comment by Gioyik** [comment]
@aesedepece is working with the last commits. :)

**Comment by Gioyik** [comment]
@aarizkuren Podrias probar y confirmar que los grupos esten funcionando normalmente?

**Comment by aesedepece** [comment]
Creo que ahora mismo si te llega un mensaje de un grupo del cual no tienes previo chat, no lo reconoce como grupo. Me ocupo de ello ahora mismo, sé dónde está el patón.

**Comment by Gioyik** [comment]
Si eso mismo estaba viendo, por eso pedi que lo revisaran por si era solo a mi que me fallaba.
