### ISSUE TITLE
Cannot disconnect

### ISSUE THREAD

**Issue by Gioyik** [loqui/im#19]
Hi,

Today I installed loqui. I log in and all is OK. The problem is when I try to disconnect. I click on the disconnect menu but It doesn't disconnect me, I continue connected. Could someone confirm if is this a Bug?

Thanks

PD: Tested in a Samsung Galaxy S3 with Firefox for Android and a Unagi phone with FirefoxOS

**Comment by aesedepece** [comment]
Does the "Disconnecting" black notification even appear or not?

**Comment by Gioyik** [comment]
Yes, but I can continue be connected and chatting after I click on the Disconnect menu.

**Comment by aesedepece** [comment]
CONFIRMED

In fact disconnection is made properly. It's just the other phone not rendering you as disconnected. So it's a presence rendering issue actually.

**Comment by Gioyik** [comment]
Cool, you detect the real bug.

**Comment by aesedepece** [comment]
I will tackle the issue as soon as tomorrow. Thanks for all the feedback!

**Comment by Gioyik** [comment]
Awesome! I will be testing if the problem is fixed.

**Comment by aesedepece** [comment]
After performing a set of tests against last nightly, it seems that this does not happen any more.
I'll update the online app version from 006 to 007 later today and close the issue once you confirm it is solved.
