### ISSUE TITLE
Testing Loqui on production devices

### ISSUE THREAD

**Issue by Gioyik** [loqui/im#194]
Most of the errors in Loqui are present in production devices like the ZTE Open and Alcatel One Touch Fire. I have one of both so I will test to be prepared for probably issues from users that buy those phones and install Loqui there.

**Comment by aesedepece** [comment]
Thanks, since I only own Geeksphones... and they tend to trick us, you know.

**Comment by Gioyik** [comment]
Related to #187, so close this.
