### ISSUE TITLE
Error de grabación?

### ISSUE THREAD

**Issue by DiegoErnesto** [loqui/im#197]
Me he dado cuenta (ver 0.2.4), que en algunas conversaciones, mientras tengas el chat abierto, se muestran todos los mensajes (los que recibes y los que envías), pero sin embargo, a partir de cierto momento, al salir de ese chat y volver a entrar los últimos mensajes ya no se "recargan", y todo lo que se escriba o llegue, aunque se vea en el chat , al volver a salir y entrar, ya no existe.., es como si no grabase las conversaciones desde algún punto en concreto.

eliminas el chat entero con ese contacto, y vuelve a hacerlo bien.

aún no he tenido mucho tiempo para darle una vuelta a todo el código, si me orientáis por donde mirar, puedo dedicarle un ratito al final de día a ver si lo fixeo..:)

un saludo

**Comment by DiegoErnesto** [comment]
por ahora solo he tenido conversaciones lo suficientemente largas para que pase con Whatsapp

**Comment by DiegoErnesto** [comment]
es posible que el Issue #158 sea lo mismo, 
pero como el chat no se queda vacío, no estoy seguro

**Comment by Gioyik** [comment]
Confirmed! This happens to me not only with Whatsapp accounts. :)

**Comment by DiegoErnesto** [comment]
he estado haciendo varias pruebas con whatsapp y hangouts, y el problema empieza desde el mensaje 30
en todos los casos

**Comment by aesedepece** [comment]
Ok, el número 30 no es casual, pues 30 son los mensajes que se guardan seguidos en memoria.
Vamos a revisar la función que se encarga de guardar los mensajes porque debe de haber algún problema con esto.
Gracias por avisar.

**Comment by DiegoErnesto** [comment]
asyncStorage...
me estoy pegando con este js  para entender como funciona.. supongo que es aquí después de seguir..
desde chat.js (account.save()--> App.smartupdate() -->Store.put()-->asyncStorage.setItem()...)

**Comment by Gioyik** [comment]
https://github.com/loqui/im/blob/master/scripts/loqui/app.js#L43
https://github.com/loqui/im/blob/master/scripts/loqui/chat.js#L64

**Comment by aarizkuren** [comment]
@aesedepece cual es el comportamiento que tiene que haber aquí?
me explico, tal como creo que esta hecho ahora, cuando pasa del limite de 30 mensajes, se borra el 1º para meter el ultimo. es asi?
no seria mejor, almacenar todos, pero a la hora de abrir el chat, recuperar unicamente los ultimos 30? incluso si se subiera por la ui del chat hasta arriba, poner un enlace de "ver mas" y recuperar los siguientes 30

porque para el 1º ya tengo cura hecha, pero no me termina de convencer... Sobre todo porque a mi me ha pasado que vas a mirar los mensajes, y hay grupos que a 30 llegan a la que te despistas un rato.

De todas formas, subo un PR para la 1ª forma, por ahora, y he incrementado a 50 el valor, si preferis a 30 pues es cambiarlo :P

**Comment by aesedepece** [comment]
Los mensajes se guardan en el storage en bloques de 30, es lo que se llaman "chunks".
Cuando entras en una conversación, carga y pinta el último chunk de esa conversación.
Si se recibe/envía un mensaje y hay hueco en el último chunk de la conversación, se añade el mensaje a ese mismo.
Por el contrario, si al enviar/recibir el último chunk está lleno, se crea un nuevo chunk y se añade a la lista de chunks de esa conversación.

Toda la magia ocurre en la función que ha referido @Gioyik: https://github.com/loqui/im/blob/master/scripts/loqui/chat.js#L64

**Comment by aesedepece** [comment]
Me faltó decir que en el caso de que el último chunk tenga menos mensajes que la mitad del tamaño máximo (30), automáticamente se carga y pinta también el penúltimo chunk.

BTW, el límite está puesto en 30 porque garantiza que al acceder a una conversación se van a poder ver bastantes mensajes pero que no tarde demasiado en pintarlos.

**Comment by DiegoErnesto** [comment]
entonces no es un problema de guardar, si no de mostrar?
y lo que hace cada vez que entras en el chat es mostrar solo el primer bloque en vez del último?

**Comment by aesedepece** [comment]
Claro, el que muestra es siempre el último bloque, que es el más reciente.

**Comment by aarizkuren** [comment]
Ok ahora comprendo, habia entendido mal la funcion :S 

el PR no vale :P
