### ISSUE TITLE
Coseme methods misuse causing some issues

### ISSUE THREAD

**Issue by aesedepece** [loqui/im#198]
The `this.events.onContactTyping` event is intended to process incoming typing notifications (CSN), so you shouldn't call `typing_send` from it.

The same happens with `this.events.onContactPaused` and `this.events.onMessageDelivered`. They are just listeners and need no answer!

Only the "success events" such as `this.events.onUploadRequestSuccess` should make answers or perform calls with `MI.call()`.

Working on a fix...

**Comment by Gioyik** [comment]
Fixed!
