### ISSUE TITLE
TypeError: html is null

### ISSUE THREAD

**Issue by aesedepece** [loqui/im#201]
A la hora de recibir una imagen, hay ocasiones que ocurre lo siguiente:

```
TypeError: html is null
```

El fallo salta en `message.js:161`

**Comment by Gioyik** [comment]
CC'ing #192

**Comment by aesedepece** [comment]
This has nothing to do with #192 xD

**Comment by Gioyik** [comment]
Jajajajjaa Hasta ahora me vengo a dar cuenta, ultimamente los issues, los pull request y todo Github me anda trolleando y me muestra cosas que luego se desaparecen y se convierten en otras totalmente distintas. :P
