### ISSUE TITLE
Use asyncStorage (indexedDB wrapper) instead of localStorage

### ISSUE THREAD

**Issue by willyaranda** [loqui/im#21]
localStorage is syncronous, so it blocks UI. You should use asyncStorage[1], which is a localStorage-like wrapper for indexedDB (so it's asynchronous).

[1] https://github.com/mozilla-b2g/gaia/blob/master/shared/js/async_storage.js

**Comment by aesedepece** [comment]
Shut up and take my money!!!
That would avoid the little UI freeze when entering a chat with lots of messages inside. It will be implemented ASAP :)

**Comment by aesedepece** [comment]
Fixed by commits 6f82fe33ef5b3e139a2196ce6a2d98fbddc27a44 and a9c97b5d80520a6402c5891f0374e2077314049f

In addition if it detects that there is data from a previous version of LOQUI, it imports the data.
