### ISSUE TITLE
If you tap the play icon in a video message, it won't play

### ISSUE THREAD

**Issue by aesedepece** [loqui/im#212]
Video messages are being downloaded and played only if you tap on the thumbnail picture but not on the play icon itself.

**Comment by Gioyik** [comment]
Como hacemos para asignarle una accion ya que esta inserada con :after la imagen?

**Comment by aesedepece** [comment]
Pensando, pensando... he recordado un truquillo de CSS que nos podría valer:

``` css
pointer-events: none;
```

Lo que hace es volver al elemento insensible a los clicks, de modo que lo atraviesan y van a parar a la imagen, que es la que tiene el evento. Creo que puede funcionar.

**Comment by Gioyik** [comment]
Voy a probarlo y si algo, hago Pull Request

**Comment by Gioyik** [comment]
hice el commit con el fix en el mismo PR de los emoji ya que hice los cambios en master y se me vuelve todo una nada si intento hace cambios con otras branches.

**Comment by aarizkuren** [comment]
Buenas,
Ando bastante liado esta semana y no he podido acabar esto,
aunque lo tengo perfilado ya.

El metodo este de css a mi no me funciona, y yo habia pensado en 
coger el evento click del div padre (data-type:video) y hacer algo asi:

``` javascript
div.onclick = function (e) {
  var target = $(e.target);
  e.preventDefault();

  target.firstChild.lastChild.click();
}
```

Cuando tenga un rato libre, lo paso :P

saludos
