### ISSUE TITLE
Download progress bar

### ISSUE THREAD

**Issue by aesedepece** [loqui/im#213]
We need a download progress bar, at least for letting the user know that the picture/video/audio has started to be downloaded. For the sake of UX!!!

I assign this to myself if you don't care :wink:

**Comment by Gioyik** [comment]
What about if we use the UX that I used when we upload something?

https://github.com/loqui/im/blob/master/scripts/loqui/connectors/coseme.js#L566

This could be an easy solution and we can save the UX surprises for other versions. :P
