### ISSUE TITLE
You can't open a media message you have sent

### ISSUE THREAD

**Issue by aesedepece** [loqui/im#214]
If you tap on a picture/video/audio you have sent, it doesn't open. This happens because it tries to open `/loqui/files/TIMESTAMP+RANDOM.ext` instead of the original path of the file.

Do you think that we should store the original path in the media message so we can open it afterwards, or maybe just copy the file to the `/loqui/files/` path?

**Comment by Gioyik** [comment]
Copy the file to `/loqui/files/` path, not sure why, but Whatsapp do it and other clients too.
