### ISSUE TITLE
It's back!

### ISSUE THREAD

**Issue by Gioyik** [loqui/im#215]
Issues #149 and #146 are back in latest version from master.

**Comment by aesedepece** [comment]
Not for me. Anyone else?

**Comment by DiegoErnesto** [comment]
In simulator firefox OS yes for me

**Comment by DiegoErnesto** [comment]
But is diferent there are one chat for evry msg for The same contact and evry chat has only one msg

**Comment by DiegoErnesto** [comment]
curioso, solo pasa con un chat, y siempre el menor en orden de creación, con el resto lo hace bien

**Comment by aesedepece** [comment]
¿Podéis describir el problema actual en un sólo párrafo? Gracias :)

**Comment by DiegoErnesto** [comment]
encontré la línea que está mal, 
es en message.js en la línea 111 , en la función addToChat 
el  if (chatIndex > 0) debería ser  if (chatIndex >= 0).

**Comment by aesedepece** [comment]
Con razón a mí no me ocurría el problema: ese mismo bug lo solucioné ayer con el commit d817701aa16ff4fb44efd89e4c75e4d51b1e35fb.
Así que salvo oposición, puede considerarse cerrado. Gracias @DiegoErnesto por el seguimiento :)
