### ISSUE TITLE
Ability to sign out and forget login details

### ISSUE THREAD

**Issue by willyaranda** [loqui/im#22]
So it's possible to switch accounts :)

**Comment by willyaranda** [comment]
AFAIK: this should be easy if you disconnect user and clear the localStorage (soon asyncStorage :) )

**Comment by aesedepece** [comment]
It seems logic to feature a menu options for that.
As soon as you perform `localStorage.clear()` or `localStorage.removeItem("xsettings")` and reload app, the login form is offered again.
