### ISSUE TITLE
XMPP Priority

### ISSUE THREAD

**Issue by rafaelmr2** [loqui/im#223]
Default resource priority is higher than desktop. Is there plans to change this? The applicattion has plans to support XEP-0168 (Priority)?

http://xmpp.org/extensions/xep-0168.html

**Comment by aesedepece** [comment]
Default priority is currently 127, which is the maximum value as defined by RFC3921 2.2.2.3:

_The OPTIONAL <priority/> element contains non-human-readable XML character data that specifies the priority level of the resource. The value MUST be an integer between -128 and +127. A presence stanza MUST NOT contain more than one <priority/> element. The <priority/> element MUST NOT possess any attributes. If no priority is provided, a server SHOULD consider the priority to be zero._

XEP-0168 is deferred, so I think a more proper behaviour could be the one described in this article:
http://blog.jdconley.com/2007/05/xmpp-presence-priority.html

**Comment by rafaelmr2** [comment]
Sounds great. :)

**Comment by Gioyik** [comment]
Is :+1:  to me.
