### ISSUE TITLE
Downloaded audio is not reproduced

### ISSUE THREAD

**Issue by Gioyik** [loqui/im#228]
You receive an audio message and it's downloaded but when it finish the download it doesn't reproduce the audio in the audio player.

**Comment by aesedepece** [comment]
Maybe some function changed with the last Coseme update (565da21c578c9a84f04d6a24765880e81c92cece) or we broke something somewhere else.

**Comment by aarizkuren** [comment]
A mi esto no de da fallo, se reproduce bien, lo que si he visto que me ocurre, es que cuando te envian el audio a un grupo, lo trata como si te lo enviase 1 persona y te lo mete o crea un nuevo chat con esa persona

**Comment by aesedepece** [comment]
Esto es porque hay algún problema con `coseme.processAudio`. Las fotos y vídeos funcionan porque usan `coseme.processFile`. Creo que deberíamos unificar los tres en `coseme.processFile` para evitar problemas.

**Comment by aesedepece** [comment]
Este error creo que ya no está presente, al menos para mí, ¿@Gioyik, cerramos?

Y el que menciona @aarizkuren del audio en los grupos ya quedó corregido por el commit d5db505a896407cbbabc691c5da4cc447047fead.

**Comment by Gioyik** [comment]
Por ahora todo me va bien. Cerramos :+1:
