### ISSUE TITLE
null Object for video

### ISSUE THREAD

**Issue by Gioyik** [loqui/im#229]
You receive a video message and the console shows you this:

   "SAVING" "loqui/files/20140114T225407ZAGULL.mp4" tools.js:7
   null [null, undefined]

**Comment by Gioyik** [comment]
Added to this, the video has data-type-downloaded=false, and i got this trying to download it again:
<query xmlns="jabber:iq:last" seconds="1737">
</query>
</iq>
 ~ BinaryReader.prototype._readNextTree@app://89c8d896-e637-452e-a7f3-097ae7ba0ebf/scripts/anonymous/coseme.js:4639 [BinaryReader]" coseme.js:3377
"SAVING" "loqui/files/20140114T225407ZAGULL.mp4" tools.js:7
"SAVE ERROR" DOMError {name: "NoModificationAllowedError", message: ""}

**Comment by Gioyik** [comment]
seems that is trying to save the video with the same name. Everything is happening thanks to the null. I think!

**Comment by aesedepece** [comment]
El error "NoModificationAllowedError" quiere decir que ese archivo ya lo has descargado, luego el problema es que no se ha llegado a marcar como `downloaded=true` por la razón que sea.

**Comment by Gioyik** [comment]
Sin embargo el archivo al descargarse muestra un null [null, undefined], y no un Object como deberia.
