### ISSUE TITLE
Suspicious sign in prevented

### ISSUE THREAD

**Issue by cosenal** [loqui/im#23]
I tried to sign in with my gmail account, but Google prevented the access and send me an email with the following text:

> We prevented the sign-in attempt in case this was a hijacker trying to access your account. Please review the details of the sign-in attempt:
> ...

**Comment by aesedepece** [comment]
Do you have 2-step login enabled for that account? If so, you have to issue an app password from here: https://accounts.google.com/IssuedAuthSubTokens?hide_authsub=1

If that's not your case, let us know and we'll make further enquiries.

**Comment by cosenal** [comment]
Yes, 2-step worked. I will close this.
