### ISSUE TITLE
[Kontalk] support proposal

### ISSUE THREAD

**Issue by pravi** [loqui/im#230]
It is a natural choice for a Free Software messenger app like Loqui. See http://kontalk.org/

**Comment by aesedepece** [comment]
They are moving to XMPP, right? → As soon as they do, it will be supported straight-away ;)

**Comment by pravi** [comment]
you'll still need to implement their xmpp extension, see http://code.google.com/p/kontalk/wiki/XMPP 

edit: only server side will need this extention

**Comment by pravi** [comment]
The landing page could be different as we just need the phone number like whatsapp and server details could be auto-filled when they choose kontalk.

**Comment by aesedepece** [comment]
Oh!!! They have drawed a good bunch of quite interesting extensions, as seen here → http://code.google.com/p/kontalk/wiki/XMPPExtensions

I think that, in example, the one the related to PUSH could be really useful... so they and we should join forces to turn that "non-standard" extensions into XEP documents.

**Comment by daniele-athome** [comment]
Hello guys! It's nice to see interest building up around Kontalk. I really would like to make some custom extensions into XEPs (especially the push capability extension), but I lack some skills on other push notification systems (ie iOS, Blackberry, etc... a XEP like this would be useful if it'd support any kind of push notifications in a reasonable way). I've never drafted a XEP... would anyone be up to the task? Or by helping me at least.

Also I'd like to discuss opinions and comments about the live presence subscription system, which would break RFC 6121 in a way... I'll write some more documentation in that wiki page.

**Comment by Gioyik** [comment]
It's an interesting project, and I think that @aesedepece should be really interested to work on a draft related to XEP's (he has more experience on this). I think that now we need a different way to communicate us different to issues, something to discus with other developers (topics like this),could be a public mailing list. And other for us, sure. ¬¬ (non-public).

**Comment by daniele-athome** [comment]
We could use the xmpp standards mailing list at standards@xmpp.org that is actually the place where xmpp discussions take place. But we should first be prepared for it... we should at least study a bit of APN and Windows Phone notification APIs, just to see what parameters and other stuff they need.
If you want Kontalk has also 2 Google groups: kontalk-devel and kontalk-users (a google account is NOT required to subscribe, you can use any e-mail address).

**Comment by daniele-athome** [comment]
I know this isn't the right place, but since no one subscribed to other lists... :P
http://mail.jabber.org/pipermail/standards/2014-January/028482.html

**Comment by webratte** [comment]
Hi Loqui developers,
what do you think?
Will you implement Kontalk into Loqui?
Of course Kontalk XMPP is in Alpha yet. But maybe you could in this state work together. So it will be possible to help each other. 
OK, I'm only a user and not developer. Maybe I'm wrong.
But I hope, soon I can chat with Kontalkusers they use firefoxOS.

Thank you

**Comment by aesedepece** [comment]
The supported services list is frozen by now as we are focused on improving overall performance of the app and XMPP support in the 0.3 branch. Nevertheless, we encourage every developer to take Loqui's source code and hack it to support any service they may find interesting.

On our side, we won't consider adding new service providers (Kontalk, Instagram, etc.) until working in the 0.4 branch by 2014Q3.

**Comment by webratte** [comment]
Hi Loquidevelopers,
Kontalk XMPP Version is already released to public:
 https://github.com/kontalk/androidclient/releases

What do you think about to start implementing it in Loqui now?

I think it's a great idea ;-)

**Comment by pravi** [comment]
@aesedepece I think kontalk use client certificate based authentication http://blog.casaricci.it/2014/02/49/how-to-use-kontalk-30-with-a-desktop-xmpp-client

and also sms verification during registration. These two things needs to be added to loqui to support kontalk. Can we expect this soon? This would be a great addition as we have no other fully free software based asynchronous encrypted chat on Firefox OS.

**Comment by daniele-athome** [comment]
What Loqui would need:
- SASL EXTERNAL authentication with SSL certificate on either STARTTLS or direct SSL (the latter still has problems with Tigase though)
- phone number based registration (a small extension to jabber:iq:register which I will document soon on the project's wiki) or importing an existing key from an Android device (which requires the jabber:iq:register process anyway)
- a builtin "server list" for a given network (kontalk.net for now is the only one) for bootstrapping
- OpenPGP encryption for messages
- minimal key management for public keys

I'm not including media exchange stuff, that can come later.

I can't actively work on it, but of course I can lend you a hand for some technical aspects. Contact me or post a comment here if someone is interested in making this.

**Comment by balasankarc** [comment]
Does the "rejected" label mean that Kontalk support will be never added for Loqui? Please clarify.

**Comment by TitanNano** [comment]
yes see https://github.com/loqui/im/issues/230#issuecomment-40707366

**Comment by pravi** [comment]
@TitanNano , @aesedepece said "until working in the 0.4 branch by 2014Q3.", which is already over. I think this needs a reconsideration as XMPP is not a very good replacement for WhatsApp for unreliable connections.

**Comment by ghost** [comment]
@pravi maybe 'On our side, we won't consider adding new service providers' is meant as the supported service providers and the maintains of Loqui IM is taking 100% of the developers time, feel free to add additional services by yourself.

**Comment by TitanNano** [comment]
well we already finished the work for v4. I don't know if the status for additional providers changed, but right now I don't know anyone who works on any new providers. If we will add it in the future we can remove the label.

**Comment by TitanNano** [comment]
@bobcanthelpyou right :+1:

**Comment by webratte** [comment]
Hi,
I understand you and your arguments.
But I would like to change from Android to Firefox OS. And all my friends use Kontalk. 
And so I would like if Loqui supported Kontalk.

I'm sorry, I'm not a developer. The only way to help is donate and translate.

I hope you think about support for Kontalk if you have enough manpower :-)

**Comment by TitanNano** [comment]
I close this now. In case someone wants to provide an implementation, feel free to reopen.
