### ISSUE TITLE
Consola de Trazado

### ISSUE THREAD

**Issue by JCVega** [loqui/im#235]
Cuando ejecuto en mi telefono Loqui IM, no funciona de la misma manera que en el Simulador.
Hice una especie de consola, para visualizar las salidas de Tools.log(), con esto me ayuda en el trazado de la aplicacion. No se si a ustedes les seria util, esto para mejorar la programacion y la interfaz, para mi uso reo que no le cambiaria mucho.
Anexo algunas imagenes.
![screen shot 2014-01-15 at 6 24 38 pm](https://f.cloud.github.com/assets/6250173/1932532/534b119c-7ecd-11e3-8727-e45c0e72131a.png)
![screen shot 2014-01-15 at 6 25 06 pm](https://f.cloud.github.com/assets/6250173/1932533/534c7528-7ecd-11e3-8839-29f96ccca1a2.png)
![screen shot 2014-01-15 at 6 25 35 pm](https://f.cloud.github.com/assets/6250173/1932535/534f596e-7ecd-11e3-8e82-098151605b50.png)

**Comment by aesedepece** [comment]
Explicación de por qué no funciona en el teléfono: has utilizado atributos `onclick` inline, que están prohibidos por la CSP que aplica el teléfono al tratarse de una aplicación de tipo "privileged".

En lugar de usar `onclick`, puedes asignar los eventos desde el archivo `bindings.js` y verás como no dan ningún problema.

**Comment by willyaranda** [comment]
Y por qué usas esa consola en el simulador? Usa la que está en Firefox directamente ;)

**Comment by JCVega** [comment]
Orale no creí que fuera privilegiado `onclick`, de echo estaba pensando en cambiarlos por los `tab` de tapquo, en unos momentos los agrego desde `bindings.js`

En el simulador utilizo el Firebug. Pero cuando ejecuto la aplicacion en mi telefono (Loqui IM 0.2.4 desde el MarcketPlace), funciona muy diferente que en el simulador, en el simulador me manda y recive mensajes sin problemas, si cierro la aplicacion y llega un mensaje, me notifica, cosa contraria en mi Alcatel Fire. Por eso pensaba trazarlo de esta forma.

**Comment by Gioyik** [comment]
El Alcatel aun no recibe la v1.2 asi que no puede hacer uso del App Manager aun. Sin embargo puedes usar el simulador de siempre, que funciona sin problemas y usas la herramienta connect:

https://developer.mozilla.org/es/docs/Tools/Simulador_Firefox_OS#Activar_el_registro_de_consola

A mi me parece una buena funcion para el modo desarrollador, aveces tengo que probar algo o sale algun error y tengo que vermelas para sacar el log o peor buscar un equipo en donde conectarlo. Lo que seria bueno es en trabajar un poco en la UX, pero como feature en el modo desarrollador para mi :+1:

**Comment by JCVega** [comment]
Lio que me he metido por tener una version diferente del simulador. voy a checar eso porque el Alfa no  lo incluye
Falta componerle mucho, incluso la legibilidad del codigo, si creen que les seria util lo voy a mejorar, no se si tengan alguna sugerencia más

**Comment by Gioyik** [comment]
Como dije, como feature a mi me parece bien, incluso me parece bueno poder ver el log sin tener que conectar a un equipo. Puedes hacer un Pull Request con el codigo y vamos viendo que cambios hacerle y como te ayudamos. Aunque falta el voto de los demas, por mi ya tienes un :+1: 

r -----> @aesedepece @aarizkuren

**Comment by JCVega** [comment]
Pregunta, porque cambio de Waalt a Loqui.
Listo el Pull Request en `master`.

**Comment by aesedepece** [comment]
La explicación está en la Política de Privacidad [https://marketplace.firefox.com/app/loqui/privacy] :

_Loqui IM es desarrollado por una comunidad de programadores de diversos países del mundo que aportan su granito de arena de forma desinteresada para crear una aplicación de chat totalmente libre, abierta y neutral._

_El papel de la empresa Waalt Communications (Waaltcom) es el de dotar al proyecto del soporte económico y la infraestructura de servidores y red para que Loqui IM sea viable._

**Comment by JCVega** [comment]
Muchas gracias por la informacion, bastante interesante.
