### ISSUE TITLE
Botón del menú.

### ISSUE THREAD

**Issue by CodingFree** [loqui/im#237]
Hola,

Cuando se pulsa el botón del menú, ese que es como tres rallitas horizontales, sufre un pequeño rebote (al menos en mi dispositivo) que hace que el botón crea que ha sido pulsado dos veces. Al ocurrir eso, se despliega el menú y se cierra rápidamente.

Para que funcione normalmente, por lo general tengo que pulsar el botón, esperar un segundo y soltar el botón.

**Comment by JCVega** [comment]
Bastante curioso, seria bueno que proporcionaras el modelo de tu telefono, la versión de Loqui.

**Comment by CodingFree** [comment]
Geeksphone Keon, usando B2G 1.4, latest release tanto de B2G como de Loqui.

**Comment by Gioyik** [comment]
Esto me ha pasado algunas veces solo cuando he agregado alguna cuenta que tiene bastantes contactos a sincronizar por lo que la interfaz se queda un poco colgada y los toques reaccionan un poco despues. En que situaciones te pasa esto?

**Comment by CodingFree** [comment]
Pensaba que ocurría cuando la aplicación estaba muy poco cargada, al contrario de lo que decías Gio, pero me parece que es justamente tal y como indicas. Voy a intentar colgar un poco la interfaz.

**Comment by Gioyik** [comment]
Por lo general se cuelga un poco cuando son muchos los contactos que tiene que sincronizar. Prueba conectando una cuenta con muchos contactos.

**Comment by Gioyik** [comment]
La interfaz a cambiado en la v0.3.0 asi que no deberia seguir pasando.
