### ISSUE TITLE
Sonido infinito en Whatsapp

### ISSUE THREAD

**Issue by Gioyik** [loqui/im#242]
Hay momentos en los que Whatsapp empieza hacer el sonido de Connected demasiadas veces, casi infinitas. Parece que es a causa de los cambios hechos en #203, la cuestion es que reproduce el sonido cada segundo y muestra la notificacion de Autenticacion fallida, lo cual es molesto, Whatsapp no conecta y el telefono suena como si fuese a explotar en cualquier momento. :P

**Comment by Gioyik** [comment]
Cuando pasa esta situacion Loqui con Whatsapp queda desconectado y los mensajes que se envian pues nunca llegan o se reciben.

**Comment by aesedepece** [comment]
A mí me ha ocurrido alguna vez también y hasta que no cierras y vuelves a abrir sigue en ese bucle perverso.

Quick fix: si recibe aviso de que el socket ha fallado tres veces seguidas (`connector.events.onDisconnected`), que reinicie la app.

**Comment by Gioyik** [comment]
Va me pongo a ello. Como seria para decirle que a las 3 reinicie? Tengo la duda es en saber como hago para decirle que son 3 los intentos no mas.

**Comment by Gioyik** [comment]
Me habia acordado como hacerlo y estaba apunto de enviar el commit :P Ahora veo que has hecho un PR con el fix. :+1:

**Comment by Gioyik** [comment]
Aun no esta resuelto esto, el problema continua. Llegue a contar 50 veces en las que se reprodujo el sonido y Loqui no se reinicio ni nada, como se supone deberia hacerlo.

**Comment by aesedepece** [comment]
Cierto, a mí me funciona el parche la mayoría de las veces pero sí que en una ocasión volvió a ocurrir el bucle loco. Voy a echarle un vistazo...

**Comment by Gioyik** [comment]
Hoy por primera vez me ha funcionado, pero tomo mas de 3 veces para se reiniciara, el resto de las veces anteriores nunca funciono. Lo que alcanzo a ver en la consola cuando pasa esto es:

CONNECTED
RECONNECTED
CONNECTED
RECONNECTED
CONNECTED
RECONNECTED
CONNECTED
RECONNECTED
CONNECTED
RECONNECTED

Ademas, ya se como reproducirlo en mi caso. Simplemente desactivo el WiFi, vuelvo y lo activo, Loqui hace el sonido que conecta las cuentas correctamente, luego doy en el boton de actualizar y alli empieza el buble infinito.

**Comment by Gioyik** [comment]
Esto es lo que se ve por Logcat:

I/Gecko   ( 4179): TCPSocket: content process: true
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: window init: 4
I/Gecko   ( 4179): TCPSocket: startup called
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: Host info: c2.whatsapp.net:443
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: SSL: false
I/Gecko   ( 4179): 
I/Gecko   (  140): TCPSocket: content process: false
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: window init: undefined
I/Gecko   (  140): TCPSocket: startup called
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: Host info: c2.whatsapp.net:443
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: SSL: false
I/Gecko   (  140): 
I/GeckoDump(  140): JRD_key keyButton :audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :visible-audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :visible-audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :visible-audio-channel-changed
I/Gecko   ( 4179): TCPSocket: content process: true
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: window init: 4
I/Gecko   ( 4179): TCPSocket: startup called
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: Host info: c2.whatsapp.net:443
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: SSL: false
I/Gecko   ( 4179): 
I/Gecko   (  140): TCPSocket: content process: false
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: window init: undefined
I/Gecko   (  140): TCPSocket: startup called
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: Host info: c2.whatsapp.net:443
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: SSL: false
I/Gecko   (  140): 
I/GeckoDump(  140): JRD_key keyButton :audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :visible-audio-channel-changed
I/Gecko   ( 4179): TCPSocket: content process: true
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: window init: 4
I/Gecko   ( 4179): TCPSocket: startup called
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: Host info: c2.whatsapp.net:443
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: SSL: false
I/Gecko   ( 4179): 
I/Gecko   (  140): TCPSocket: content process: false
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: window init: undefined
I/Gecko   (  140): TCPSocket: startup called
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: Host info: c2.whatsapp.net:443
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: SSL: false
I/Gecko   (  140): 
I/GeckoDump(  140): JRD_key keyButton :audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :visible-audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :visible-audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :visible-audio-channel-changed
I/Gecko   ( 4179): TCPSocket: content process: true
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: window init: 4
I/Gecko   ( 4179): TCPSocket: startup called
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: Host info: c2.whatsapp.net:443
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: SSL: false
I/Gecko   ( 4179): 
I/Gecko   (  140): TCPSocket: content process: false
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: window init: undefined
I/Gecko   (  140): TCPSocket: startup called
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: Host info: c2.whatsapp.net:443
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: SSL: false
I/Gecko   (  140): 
I/GeckoDump(  140): JRD_key keyButton :audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :visible-audio-channel-changed
I/Gecko   ( 4179): TCPSocket: content process: true
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: window init: 4
I/Gecko   ( 4179): TCPSocket: startup called
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: Host info: c2.whatsapp.net:443
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: SSL: false
I/Gecko   ( 4179): 
I/Gecko   (  140): TCPSocket: content process: false
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: window init: undefined
I/Gecko   (  140): TCPSocket: startup called
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: Host info: c2.whatsapp.net:443
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: SSL: false
I/Gecko   (  140): 
I/GeckoDump(  140): JRD_key keyButton :audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :visible-audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :visible-audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :visible-audio-channel-changed
I/Gecko   ( 4179): TCPSocket: content process: true
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: window init: 4
I/Gecko   ( 4179): TCPSocket: startup called
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: Host info: c2.whatsapp.net:443
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: SSL: false
I/Gecko   ( 4179): 
I/Gecko   (  140): TCPSocket: content process: false
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: window init: undefined
I/Gecko   (  140): TCPSocket: startup called
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: Host info: c2.whatsapp.net:443
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: SSL: false
I/Gecko   (  140): 
I/GeckoDump(  140): JRD_key keyButton :audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :visible-audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :visible-audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :visible-audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :visible-audio-channel-changed
I/Gecko   ( 4179): TCPSocket: content process: true
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: window init: 4
I/Gecko   ( 4179): TCPSocket: startup called
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: Host info: c2.whatsapp.net:443
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: SSL: false
I/Gecko   ( 4179): 
I/Gecko   (  140): TCPSocket: content process: false
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: window init: undefined
I/Gecko   (  140): TCPSocket: startup called
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: Host info: c2.whatsapp.net:443
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: SSL: false
I/Gecko   (  140): 
I/GeckoDump(  140): JRD_key keyButton :audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :visible-audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :visible-audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :visible-audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :visible-audio-channel-changed
I/Gecko   ( 4179): TCPSocket: content process: true
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: window init: 4
I/Gecko   ( 4179): TCPSocket: startup called
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: Host info: c2.whatsapp.net:443
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: SSL: false
I/Gecko   ( 4179): 
I/Gecko   (  140): TCPSocket: content process: false
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: window init: undefined
I/Gecko   (  140): TCPSocket: startup called
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: Host info: c2.whatsapp.net:443
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: SSL: false
I/Gecko   (  140): 
I/GeckoDump(  140): JRD_key keyButton :audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :visible-audio-channel-changed
I/Gecko   ( 4179): TCPSocket: content process: true
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: window init: 4
I/Gecko   ( 4179): TCPSocket: startup called
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: Host info: c2.whatsapp.net:443
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: SSL: false
I/Gecko   ( 4179): 
I/Gecko   (  140): TCPSocket: content process: false
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: window init: undefined
I/Gecko   (  140): TCPSocket: startup called
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: Host info: c2.whatsapp.net:443
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: SSL: false
I/Gecko   (  140): 
I/GeckoDump(  140): JRD_key keyButton :audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :visible-audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :visible-audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :visible-audio-channel-changed
I/Gecko   ( 4179): TCPSocket: content process: true
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: window init: 4
I/Gecko   ( 4179): TCPSocket: startup called
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: Host info: c2.whatsapp.net:443
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: SSL: false
I/Gecko   ( 4179): 
I/Gecko   (  140): TCPSocket: content process: false
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: window init: undefined
I/Gecko   (  140): TCPSocket: startup called
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: Host info: c2.whatsapp.net:443
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: SSL: false
I/Gecko   (  140): 
I/GeckoDump(  140): JRD_key keyButton :audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :visible-audio-channel-changed
I/Gecko   ( 4179): TCPSocket: content process: true
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: window init: 4
I/Gecko   ( 4179): TCPSocket: startup called
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: Host info: c2.whatsapp.net:443
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: SSL: false
I/Gecko   ( 4179): 
I/Gecko   (  140): TCPSocket: content process: false
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: window init: undefined
I/Gecko   (  140): TCPSocket: startup called
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: Host info: c2.whatsapp.net:443
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: SSL: false
I/Gecko   (  140): 
I/GeckoDump(  140): JRD_key keyButton :audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :visible-audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :visible-audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :home-button-press
I/GeckoDump(  140): JRD_key keyButton :audio-channel-changed
I/GeckoDump(  140): JRD_key keyButton :visible-audio-channel-changed
I/Gecko   ( 4179): TCPSocket: content process: true
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: window init: 4
I/Gecko   ( 4179): TCPSocket: startup called
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: Host info: c2.whatsapp.net:443
I/Gecko   ( 4179): 
I/Gecko   ( 4179): TCPSocket: SSL: false
I/Gecko   ( 4179): 
I/Gecko   (  140): TCPSocket: content process: false
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: window init: undefined
I/Gecko   (  140): TCPSocket: startup called
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: Host info: c2.whatsapp.net:443
I/Gecko   (  140): 
I/Gecko   (  140): TCPSocket: SSL: false
I/Gecko   (  140):

**Comment by Gioyik** [comment]
Voy a probar con los ultimos cambios.
