### ISSUE TITLE
Group chats are not showed correctly

### ISSUE THREAD

**Issue by Gioyik** [loqui/im#251]
Los mensajes son de distintas personas. A. Crespo me ha pasado la imagen.

![index](https://f.cloud.github.com/assets/1834718/1948213/f6572e40-8083-11e3-882b-7a0b7479c27f.png)

**Comment by aesedepece** [comment]
Esto supongo que es con la 0.2.4, ¿verdad?
Si es así, ya quedó arreglado hace semanas.

**Comment by Gioyik** [comment]
No estoy seguro, si mal no recuerdo que dia probe con la master y tenia este problema. Voy a revisarlo.

**Comment by Gioyik** [comment]
Parce que si, es la version anterior porque en la ultima de master todo parece bien.
