### ISSUE TITLE
Add feature to send Geolocation position

### ISSUE THREAD

**Issue by Gioyik** [loqui/im#253]
We know how to receive it, now it's time to create a way to send it.

**Comment by aesedepece** [comment]
:+1: I agree, we should support both receiving/sending.

BTW: audio and video sending is working for you? It never worked for me in B2G1.4.0 on GP Peak.

**Comment by Gioyik** [comment]
It shows that upload the audio and video, but it never send it to the contact and it's not showed in the conversation as the images when you send one.

**Comment by aesedepece** [comment]
I am fixing this (nearly complete now), but I'll test it with a mock location provider, because I never got the GPS in my Peak to actually work.
