### ISSUE TITLE
Video and Audio not sent or displayed in chat list

### ISSUE THREAD

**Issue by Gioyik** [loqui/im#254]

**Comment by Gioyik** [comment]
The audio and video is not sent.

**Comment by aarizkuren** [comment]
Los archivos se suben al servidor de whatsapp (imagino) pero por lo que sea no los envia al destinatario, y por supuesto no devuelve nada en el callback. No he mirado si devuelve algo en el callback de error, pero creo que no llega nada.

A ver si tengo esta semana algo de tiempo para dedicarle, pero a ojo, pienso que el problema esta en coseme.

saludos

**Comment by aesedepece** [comment]
Yo estoy con este tema. No es problema de coseme, tan sólo nos hemos dejado algunas cosas por coser con vidUnblob y demás :wink:

**Comment by aesedepece** [comment]
A ver, el problema es con las miniaturas. He hecho una función para extraer una miniatura del vídeo, pero de poco sirve porque al como la etiqueta <video> no soporta 3gp, con la mayoría de los vídeos no va a servir de nada.

Solución por ahora: usemos una miniatura predeterminada para vídeo y otra para audio. ¿Como lo veis?

**Comment by Gioyik** [comment]
Podríamos hacer lo mismo que hice con el audio y localización, un fondo blanco y el icono en el centro, no?

**Comment by aesedepece** [comment]
Sí, es exactamente lo mismo pero para los mensajes salientes en lugar de los entrantes.

**Comment by aesedepece** [comment]
Mañana por la mañana lo termino y mando el PR.

**Comment by Gioyik** [comment]
Si es así por mi :+1:. Otra pregunta, tenemos el mismo problema de los 3gp cuando se reciben?

**Comment by aesedepece** [comment]
No, porque lo que hace es abrirlo con la app de vídeo que por razones que desconozco sí que es capaz de reproducirlos.
