### ISSUE TITLE
No contacts imported (whatsapp)

### ISSUE THREAD

**Issue by bidaian** [loqui/im#258]
I'm runing FirefoxOS 1.3.0 on a Keon device. It is the original build. After I install LoquiIM v0.2.4 from the MarketPlace and create the Whatsapp account the list of contacts is empty. I tried to add a contact manually 59898xxxxxx@s.whatsapp.net but it does nothing, it just stays there at the same screen.

Could be a number formatting issue in Contacts? 598 is the country code for Uruguay and all contacts share that prefix.

Just in case, I turned the debugging on and tried to do a logcat from the adb shell, but nothing related to the loquiIM showed up.

**Comment by aesedepece** [comment]
Please check come of your contacts numbers against this test [1] and tell us if the national and international numbers are right. Thanks.

[1]  http://logofid.es/phonenumberjs_test/

**Comment by bidaian** [comment]
It looks good. Is there a way to debug what happens when Loqui tries to import the contacts?

Also, at the bottom of the (empty) list of contacts, my own number is shown without the country code, just the local part after a grey circle. Where does loqui get my phone number from?

Still, I guess it is connected to Whatsapp because I see the profile image I had set from Connecta2.

**Comment by aesedepece** [comment]
I've reviewed your issue. I think you tried to add the contact directly from the app, which never worked for WhatsApp. Sorry for the inconveniences.

By now, the only way to add contacts to Loqui is adding them to your phone's address book and them taping the "sync" button in the Loqui contacts list.

**Comment by Dr-Fate** [comment]
Este muchacho Eduardo es Uruguayo (por el 598, ya pueden hablar todos en español jaja), yo tengo exactamente el mismo problema, no me importa casi ningún contacto de mi celular, sólo 3.... que son casualmente 1 amigo español y 2 argentinos, evidentemente el problema es con los números uruguayos.
He leido que Brasil tiene el mismo problema para sincronizar contactos.

**Comment by Dr-Fate** [comment]
Este problema quedó resuelto en la v.0.2.6!
Se puede cerrar el issue.

**Comment by aesedepece** [comment]
@Dr-Fate Gracias por confirmarlo :)
