### ISSUE TITLE
Desconectado automatico 

### ISSUE THREAD

**Issue by v3rlain3** [loqui/im#259]
en la version 0.2.5 de loqui gracias al modo desarrollador con la consola pude ver lo que pasaba, con la cuenta de facebook funcionando; pasado un tiempo (minutos) loqui se desconecta solo y no se vuelve a reconectar hasta que le das un reload.

-1000???????????@chat.facebook.com,@,-1
Disconnecting
-1000???????????@chat.facebook.com,@,-1
NEW
PUSHING,36,[object Object]
SAVING accountsCores
Disconnecting
-1000???????????@chat.facebook.com,@,-1
Disconnecting
-1000???????????@chat.facebook.com,@,-1
NEW
PUSHING,37,[object Object]
SAVING accountsCores
Disconnecting
Disconnecting
Loqui IM has been reloaded
Connecting
Connected
SAVING accountsCores
-100????????????@chat.facebook.com,@,3
Disconnecting
Disconnected

**Comment by aesedepece** [comment]
Parece que el reconectado automático falle en el conector de XMPP.
Lo reviso, gracias.

**Comment by Gioyik** [comment]
Lo sabia, la consola como feature es increible! o/

**Comment by Gioyik** [comment]
@v3rlain3 Could you check if with the latest changes on master this is present?

**Comment by v3rlain3** [comment]
@Gioyik checking....

**Comment by v3rlain3** [comment]
@Gioyik hasta ahora todo ok; no ha habido más desconexiones. Gracias

**Comment by Gioyik** [comment]
Que bueno! Si el problema persiste avisanos.
