### ISSUE TITLE
v0.2.5b not offered to users of v0.2.5

### ISSUE THREAD

**Issue by bdcomp** [loqui/im#276]
v0.2.5 on GP Peak, B2G 1.1.1.0hd-GP (stable).

v0.2.5b not offered to me as an update.
Just in case it's related - no update with Wi-Fi on and off; Loqui IM and Marketplace opened and closed.

Although this probably a Marketplace issue, Loqui IM should consider to avoid using letters in versions and upload v0.2.5b once again as v0.2.6

**Comment by Gioyik** [comment]
The reason for the use of letter in the last version is because was just only one fast fix for one problem. We will increase the number as always to the v0.2.6 when more fixes will be included.

**Comment by bdcomp** [comment]
@Gioyik The reason is fully reasonable and understandable, but it prevents from updating.

**Comment by Gioyik** [comment]
So wire. I receive the update and no problems.

**Comment by bdcomp** [comment]
Could you check for updates rate of v0.2.5b?
Just to be sure it's only me...

**Comment by aesedepece** [comment]
Firefox Marketplace statistics have been out for weeks, so we can't check at the moment.

**Comment by aesedepece** [comment]
And yesterday I was able to update successfully from 0.2.5 to 0.2.5b via OTA.

**Comment by bdcomp** [comment]
As I still not received the update, this bug just been opened:
https://bugzilla.mozilla.org/show_bug.cgi?id=965733

**Comment by aesedepece** [comment]
Obvious question, just for discarding: have you tried with the "Check now" button under Settings app > Information > Software updates ?

**Comment by bdcomp** [comment]
If you mean Settings > Device information > Software updates > Check now, then yes.
Although, doesn't it only about OS updates?

**Comment by aesedepece** [comment]
It checks for installed app updates as well. :wink:

**Comment by bdcomp** [comment]
@aesedepece Can you please provide a link confirming it?

As the output message of "Check now" is "This is already the latest version of B2G OS", I am still pretty sure it's only about OS.
Also, never received an app update after checking here, but after reloading Marketplace. Or close to other interaction with it.

**Comment by aesedepece** [comment]
My experience is completely the opposite.

I always checked for app updates and received them by using the _"check now"_ button.
Then I realized that reloading Marketplace also checked for new updates just a few weeks ago. 

In http://mzl.la/17nfVtn you can see that it mentions that the button checks for _"system and app updates"_.

**Comment by jorgeuve** [comment]
There´s not much time as I can remember, ubuntu (  and debian I suppoused )  change the versión policy to avoid letters in versión numbers. I discover this making a old  port from a package whith letters in the versión last year.  As I can remember this is due to simplify administration scripts and to avoid dependencies mistakes. 
I recomend  not to use letters to avoid future problems. 
Maybe like this one. 
Its free and easy.
Sorry but I was not able to find the discussion I read. 
Best

**Comment by bdcomp** [comment]
I just received an update to v0.2.5c (from v0.2.5).

**Comment by aesedepece** [comment]
@bdcomp Enjoy :)
