### ISSUE TITLE
Whatsapp Instant audio recorded don´t arrives at all to zte open

### ISSUE THREAD

**Issue by jorgeuve** [loqui/im#277]
v0.2.5b instant audio record a sent  from iphone ios7 and from android 4.2.1 don´t arrives to zte open at all.

**Comment by Gioyik** [comment]
It shows the audio icon on the message list? Could you see on the console what shows to you when someone sent you an audio message?

**Comment by jorgeuve** [comment]
Yes it shows the audio icon both in direct message and in group chat. But no sound at all. looking for console in device now. (I ´v never been done)

**Comment by aesedepece** [comment]
Nothing pops up when you touch the message or the CD icon?

**Comment by jorgeuve** [comment]
No. Nothing pops up

**Comment by aesedepece** [comment]
Can you maybe tell the format of the file you sent?

**Comment by jorgeuve** [comment]
is the format that whatsapp use itself when recording and audio message from the icon near the input textbox
I have tested both from iphone and android

**Comment by Gioyik** [comment]
The record is not saved? There's no way to see the file extension?

**Comment by jorgeuve** [comment]
.aac format, quictime shows this file info 
AAC, Mono, 22,050 kHz

**Comment by aesedepece** [comment]
According to the Firefox page [1] on supported formats:
_Firefox OS supports the [AAC] format in some cases, but only when a third-party decoder is available, and the device hardware can handle the profile used to encode the MP4._

[1]  https://developer.mozilla.org/es/docs/HTML/Formatos_admitidos_de_audio_y_video_en_html5

**Comment by jorgeuve** [comment]
Thanks for the help, :) I will look how to install aac support on this devices. Don´t work more for now on this issue
Best regards

**Comment by Gioyik** [comment]
Well, now the thing is that we need a way to reproduce this, not?

**Comment by jorgeuve** [comment]
ok firefox os can not reproduce acc raw format.. 
As I can understand this is only due to political reasons that nobody knows. read more at https://bugzilla.mozilla.org/show_bug.cgi?id=809186

But surprisingly if the raw acc is into a m4a container ... YES is firefox supported. 
I have tested sucessfully whith MP4Box 
apt-get install gpac 
MP4Box -add prueba.aac#audio prueba.m4a 

The result file it works in my ZTE OPEN
This operation can be made with ffmpeg too but Is not so easy

The question is, if it´s possible to convert this files whit javascript on air since the procees only adds a beguin and a tail to the file.
I will continue working on it.

**Comment by aesedepece** [comment]
I'll investigate if we can make the transcodification from the app itself. Thanks for all the info!

**Comment by jorgeuve** [comment]
Thanks a lot, Your are great¡¡¡
:-)
