### ISSUE TITLE
No sale mensaje

### ISSUE THREAD

**Issue by JCVega** [loqui/im#278]
he probado la aplicacion sobre el simulador y sobre mi OT, el problema es que no salen los mensajes.
en el simulador al enviar me sale esto.-
![screen shot 2014-01-28 at 9 45 55 am](https://f.cloud.github.com/assets/6250173/2023973/4c01a1fe-8863-11e3-8db9-eb99cc5f7d77.png)

Pero en el OT, no me sale nada
![2014-01-28-09-48-53](https://f.cloud.github.com/assets/6250173/2023979/59a033e8-8863-11e3-8d0f-2857f5cb65ae.png)

Se que parecera broma, pero por lo menos a mi no me salen los mensajes.

**Comment by aesedepece** [comment]
¿Qué versión de Loqui es la que estás probando? Me resulta muy inquietante. ¿Te ocurre siempre? ¿Sólo con Facebook o con otros proveedores también?

**Comment by JCVega** [comment]
Es Loqui IM v0.2.5
Siempre me sucede.
Voy a tratar de hacer un Trazado mas continuo para poderle mandar mas info. para ampliar la info.
Tengo entendido que si lo han probado sobre ZTE y Alcatel, lo cual igual me intriga pues es la version descargada del Market Place, que tambien podria ser un caso aislado del telefono.
No lo he intentado con otra cuenta mas que con la de Facebook.

**Comment by JCVega** [comment]
Una duda Adán, los mensajes de 'NEW', 'PUSHING' y 'SAVING' ¿Los envia de manera asincrona?
Me parece que no esta entrando a esta parte.
¿Comó puedo comprovar que trabaje de manera asincrona?

**Comment by TitanNano** [comment]
Is this still relevant?
