### ISSUE TITLE
crash after logging with gtalk account

### ISSUE THREAD

**Issue by cosenal** [loqui/im#28]
The app crashed after I logged in with my gtalk account. And after I force-quit and restart it, the app gets stuck at the boot screen 

I am new to Firefox OS, so I don't know how to get more debug information, sorry.

**Comment by aesedepece** [comment]
This happens only sometimes and I guess is caused by a mismatch between versions.

I pushed a new version of LOQUI (pa007) a few hours ago. After restarting the app your phone should have downloaded the updated files but instead it seems to be still retaining old files from pa006.

Currently, the only way to go back to normal is reinstalling the app. Sadly, as message archiving is not yet implemented, you'll loss past conversations.

I am studying how to improve caching and prevent these "accidents".

**Comment by cosenal** [comment]
I just reinstalled, it logged in and after 20 seconds of playing with the app, it crashed again. As soon as i start it, it crashes.

(Note: not a critics, I understand what pre-alpha means, just trying to help here ;) )

**Comment by aesedepece** [comment]
I'll continue to investigate what could cause that crash and the subsequent frozen boot.

It would be great if you could provide logcat output. It's done by connecting phone to PC and running `adb logcat | grep GeckoConsole`.

Thanks for your feedback, I really esteem it :pray:

**Comment by cosenal** [comment]
As I said in the bug report, I am very new to Firefox OS. Where should I run adb? Do I need the Android SDK for that?

**Comment by aesedepece** [comment]
Here you  have a tutorial on how to install and run adb: http://forum.xda-developers.com/showthread.php?t=1751439

Anyway, could you describe the crash more accurately? Does it closes or just freeze and don't respond to any user action at all?

Thanks.

**Comment by cosenal** [comment]
I finally found the time to do this.
I get a lot of lines like the following:
`"E/GeckoConsole( 8861): Content JS LOG at https://app.loqui.im/scripts/waalt/app.js:114 in anonymous: SAVING"`

No error when the crash happens though.

**Comment by cosenal** [comment]
And if i don't filter for `GeckoConsole`, I also see lines like this:

`I/Gecko   (  118): ###!!! [Parent][RPCChannel] Error: Channel error: cannot send/recv`

I don't know if it's related at all

**Comment by aesedepece** [comment]
Thanks for taking the time to debug this. At first sight your logs don't point out anything wrong.

The good news are that I'm working in a deep revision of how the app manages memory that eventually will stop this crash and similar ones. I'll keep you informed.

Anyway, which B2G and Gaia versions are you using? Subsequent LOQUI releases will be optimized for B2G 1.1 as that's the one to be shipped on first FirefoxOS commercial devices from ZTE and Alcatel.

**Comment by cosenal** [comment]
Thank you for helping with debug instructions.

I am running B2G 1.0.1.0-prerelease on my new GP Peak

**Comment by aesedepece** [comment]
Can you confirm it is solved / still happening as of pa009? Thanks.

**Comment by cosenal** [comment]
@aesedepece I am still not using loqui on a regular basis, but I can confirm that the issue seems to be gone now
