### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by CodingFree** [loqui/im#294]
E/GeckoConsole( 1155): [JavaScript Warning: "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.loqui.im/http-bind/. This can be fixed by moving the resource to the same domain or enabling CORS." {file: "https://app.loqui.im/http-bind/" line: 0}]

**Comment by Gioyik** [comment]
Esto me salia en las ultimas builds the nightly pero no pense que en FirefoxOS apareciera tambien, supongo que sale en las ultimas builds ahora, no lo habia visto antes.

**Comment by aesedepece** [comment]
Os cuento: al ir a cerrar / reiniciar la app, intenta cerrar la sesión de XMPP de la forma más digna posible, enviando un paquete por POST a https://app.loqui.im/http-bind/ con el siguiente contenido:

``` XML
<body rid='2596324405' xmlns='http://jabber.org/protocol/httpbind' sid='cc89d51bf92ca48c42f75c89ab6d278bf5ccca4a' type='terminate'>
  <presence xmlns='jabber:client' type='unavailable'/>
</body>
```

El tema está en que como la app se recarga, todas las conexiones se cortan, y por lo tanto jamás llega la respuesta a tal paquete; pues es en la respuesta donde va la cabecera que le indica al navegador que permita CORS:

```
Access-Control-Allow-Origin: "*"
```

No tiene más misterio ;)
