### ISSUE TITLE
infinite restart loop when connected to HSDPA / 3.5G

### ISSUE THREAD

**Issue by ghost** [loqui/im#299]
Loqui IM v0.2.5c
Firefox OS 1.1.0.0-prerelease

When Firefox OS is connected to HSDPA / 3.5G and Loqui IM is started, Loqui IM is stuck in an infinite restart loop, there is a small time frame of 9 to 20 seconds i could use Loqui IM but after some seconds Loqui IM is restarting itself (welcome screen is shown). Sometime a message appear that my authentication is invalid (whatsapp).

When connected to wireless lan, such problems do not appear. And i could use the whatsapp account normally.

**Comment by bdcomp** [comment]
Maybe related to https://github.com/loqui/im/issues/298 ?

@bobcanthelpyou What device it is?

**Comment by ghost** [comment]
@bdcomp the device is an Alcatel One Touch Fire

the error message could be related to #298

**Comment by ghost** [comment]
When connected to EDGE / 2G such problems do not appear, too.

**Comment by Gioyik** [comment]
@bobcanthelpyou this continue happening in last versions?

**Comment by ghost** [comment]
Loqui IM v0.3.1a
Firefox OS 1.2.0.0

The problem seems to be disappeared
