### ISSUE TITLE
Implement language selection

### ISSUE THREAD

**Issue by bdcomp** [loqui/im#305]

**Comment by Gioyik** [comment]
Nice feature for DevMode section.

**Comment by bdcomp** [comment]
I think it's not only about the developers.

How about an additional "Advanced" tab?

**Comment by bdcomp** [comment]
Firetext just implemented this:
https://github.com/Codexa/Firetext/commit/12cfb79b6a18395a31880b8953bd477ffc71f655

Is it possible to reuse some code?

**Comment by aesedepece** [comment]
@bdcomp Sure.

**Comment by bdcomp** [comment]
@aesedepece As you just merged Hebrew, I am wondering how it would be available?
In other words, who will see the Hebrew interface?

**Comment by willyaranda** [comment]
People who has Hebrew as a default locale in their FirefoxOS phone. (Unless @aesedepece has developed a locale picker in LoquiIM)

**Comment by bdcomp** [comment]
Hebrew is not available on B2G 1.1.x as a local (only as keyboard language), so language selection will be welcome.

**Comment by bdcomp** [comment]
Also, take a look at this Firetext commit https://github.com/Codexa/Firetext/commit/5b045d0f9e8320568fefbd65d86ecb138ac262b0
