### ISSUE TITLE
[Firefox Marketplace] Problem with Manifest

### ISSUE THREAD

**Issue by Gioyik** [loqui/im#31]
Hi,

You have been sent the Loqui manifest to the Firefox Marketplace to publish Loqui, but there's a problem in your manifest file because it's a Hosted webapp. So you need put the complete launch path (ej: https://www.server.com/path/app.htm), for that reason i can't approve it.

Please fix this to approve your app.

Regards,
Gio

**Comment by aesedepece** [comment]
I have changed that line to:
`"launch_path": "https://app.loqui.im/app.htm",`

Thanks for your help.

**Comment by Gioyik** [comment]
Please, add a Category in your manifest file for your app if you like see LOQUI listed in the Marketplace.

Regards,
Gio

**Comment by Gioyik** [comment]
Please provide more metadata about your app, such as a summary and/or description that explains the functionality of your app, add screenshots, a category and more usefull info, to aprrove it again.

Regards,
Gio

**Comment by aesedepece** [comment]
I provided all the data you mention: categories, summary, screenshots and descriptions. :open_mouth: 
![Listing](http://loqui.im/img/listing.png)

**Comment by Gioyik** [comment]
I am seeing the manifest for the Version pre-alpha004. Probably, thats the problem. Let me check again.

**Comment by Gioyik** [comment]
Please delete and send again your application. I have problems with your manifest, i see this:

![captura de pantalla de 2013-05-15 15 34 50](https://f.cloud.github.com/assets/1834718/509237/f2957206-bd9e-11e2-8a34-e2806525248b.png)

Regards,
Gio

**Comment by aesedepece** [comment]
Re-submitted :+1:

**Comment by Gioyik** [comment]
Do you see your webapp published in the Marketplace?

**Comment by aesedepece** [comment]
Not yet...

**Comment by Gioyik** [comment]
Let me report it, because It shows me the content of 0.4 version and the manifest shows the 0.7 version.

**Comment by Gioyik** [comment]
Hey! Good news, now loqui is approved and fixed. Please check it in the marketplace.

Regards

**Comment by aesedepece** [comment]
Thanks a lot @Gioyik !

By the way, I have a question regarding Firefox Marketplace,

In subsequent releases, LOQUI won't be a hosted app any more but a packaged app. I can't see such option from switching from hosted to packaged in the Developer Hub. How should I proceed for submitting the packaged one without deleting the listing for the hosted one? Should I upload it as a separate app and when approved remove the old one and switch the App URL?

**Comment by Gioyik** [comment]
I asked and this is the answer:

13:11        eviljeff   he will have to submit it again as a new app - you can't switch from hosted to packaged (or back)
13:11   eviljeff    he can delete the hosted app if he wants (though remember packaged apps don't work on Desktop or release Android yet)
13:15   Gioyik  So it's impossible switch from Hosted to packaged
13:16   eviljeff    correct

Could i help you in something more?

Regards,
Gio
