### ISSUE TITLE
Improve the quality of providers icons

### ISSUE THREAD

**Issue by bdcomp** [loqui/im#310]
v0.2.5c on GP Peak, B2G 1.1.1.0hd-GP (stable).

Most small providers icons, for example on the "Add accounts" page, looks bad, not sharp.
Just to explain the issue - the icons looks like if we take some small jpg picture and try to scale it to a bigger size.

I am wondering if it's related to the svg files.
Won't it be better to use png files instead?

**Comment by aesedepece** [comment]
The 1.1.1.0hd B2G release was the first one to support qHD screens like the GP Peak's one. But the way it did it was kind of patchy and not neutral.

This means it had some flaws like the one you are commenting. The SVG processor renders the icons for a 320x480 resolution and then they are scaled up to 540x960.

In later releases, the SVGs are rendered properly and look nifty, thus succeeding the purpose of using such format: small file size and sharp rendering at any resolution.

**Comment by bdcomp** [comment]
OK. Great to hear an additional improvement of the next version of B2G.

@aesedepece As a follow up - for the purpose you mentioned, may it be possible to replace the png icons to svg?
Should a new issue be opened?
