### ISSUE TITLE
Implement 1st time experience

### ISSUE THREAD

**Issue by bdcomp** [loqui/im#311]
A little tutorial overlay to show users how to get started.

For example:
- Left panel (settings, reload...)
- Chats, contacts
- Account actions
- Sending picture/video...

**Comment by Gioyik** [comment]
This sound good to implement for v0.3.0 with the new UI, if we do this on v0.2.x tree will be a waste of time. Pointed for v0.3.0.

Thanks

**Comment by TitanNano** [comment]
I think this proposal is obsolete. The v4 UI is well designed and self-explaining. Anyone who still wants this?
