### ISSUE TITLE
Investigate bad Marketplace reviews

### ISSUE THREAD

**Issue by bdcomp** [loqui/im#312]
Let's try to learn something from bad Marketplace reviews.

This will help to debug the app and to increase the average rating (that in turn will bring more users).

**Comment by Gioyik** [comment]
It's more than hard than someone can imagine. There are different problems on every phone. One of the common problems when we develop Loqui is that on our phones everything works great, but on production devices the CSP levels are different, and probably if to a X person with an Alcatel phone has a problem, other person with other Alcatel doesn't. That's our main problem, the CSP levels on every phone. Inclusive LINE doesn't work well on all the Firefox OS phones, and it's a partner app. 

However we regularly check reviews to investigate what is the most common problem of users.

**Comment by Gioyik** [comment]
I think we can close this issue. Let's see what are the comments with new v0.3.0
