### ISSUE TITLE
Add to the app a link "Report an issue"

### ISSUE THREAD

**Issue by bdcomp** [loqui/im#313]
This will minimize bad rated, unhelpful reviews (like "Not work").

**Comment by Gioyik** [comment]
We have future plans for this on future versions. I was thinking on this too, but we need to reorganize our UI first.

**Comment by bdcomp** [comment]
@Gioyik How about if I will add it now, and once the new UI will be live, I will move/fix it?

I think that the advantage of adding this link now is bigger than holding it till the new UI, even if I will need to move these 1-2 lines of html.
