### ISSUE TITLE
Add a changelog inside the app

### ISSUE THREAD

**Issue by bdcomp** [loqui/im#314]
A small changelog, inside the app, will help users to discover new features and important fixes.

Also may be implemented as an overlay displayed after any update.

**Comment by Gioyik** [comment]
We have a roadmap to be updated (this is a task for us), maybe for now is necessary just put a link to that roadmap.

**Comment by bdcomp** [comment]
Where is the roadmap?

I think a roadmap and a changelogs are different by design.

Beside the description of the issue, a changelog may explain why updates are important (and many people don't like updates or just think they don't need it).

**Comment by Gioyik** [comment]
https://github.com/loqui/im/wiki/Roadmap

**Comment by Gioyik** [comment]
@bdcomp do you think this is necessary to have in Loqui? Just to push code with a fix for this. :)
