### ISSUE TITLE
only import mobile phone numbers

### ISSUE THREAD

**Issue by TitanNano** [loqui/im#334]
hey,
Is it possible that we only import mobile phone numbers in to WhatsApp contacts? At the moment I have some people two or more times in my contacts and the duplicates are absolutely useless because they are no mobile numbers.

A will make a pull-request as a possible fix...

**Comment by aesedepece** [comment]
Tip: we can't rely on numbers being correctly tagged as "fixed-line" and "cellular" in the address book as people often mix them up.

**Comment by aesedepece** [comment]
We have already adopted another approach: when the app starts, it requests presence of every contact to the WhatsApp server. If a contact has no presence information, it is marked as "not available" (na) so that you can hide them all by switching on the "hide unavailable contacts" option in the settings menu.

**Comment by TitanNano** [comment]
but sometimes I want to write a message to a person which is not online at the moment. But would it be possible to hide contacts which never connected to WhatsApp before?

**Comment by aesedepece** [comment]
Contacts that are not connected at the moment are marked as "away" ;)

**Comment by TitanNano** [comment]
Two of my contacts are not marked as "away"... Is this a bug?

**Comment by aesedepece** [comment]
Do they appear at all?

**Comment by TitanNano** [comment]
yes, but their status is also not loaded....
![loqui2](https://f.cloud.github.com/assets/4500858/2188809/fbdbbb70-980b-11e3-98f9-132d58f43703.png)
![loqui1](https://f.cloud.github.com/assets/4500858/2188810/fe8d958c-980b-11e3-94c5-3ff581bea8ad.png)

**Comment by aesedepece** [comment]
Ok, that's because at the moment we can't automatically tell contacts that are not registered to WhatsApp from those whose status message is "Hey there ! I am using whatsapp".

I'm thinking of a little fix, and will post later today.

**Comment by TitanNano** [comment]
okay I will close the pull-request...

**Comment by TitanNano** [comment]
Contacts which are using WhatsApp have a "last time" date/time. Could this be a possible indicator?
