### ISSUE TITLE
Menu options not responsive

### ISSUE THREAD

**Issue by bdcomp** [loqui/im#341]
v0.2.6 on GP Peak, B2G 1.1.1.0hd-GP (stable).

After a restart of my phone, Loqui behave very strange:
1. A few seconds after launch, the main screen looks OK, including profile pictures, without the blue dots.
But all the buttons (like menu, contacts) not clickable.
2. Few seconds later, profile pictures disappear, while the blue dots on the grey default image appear.
Now all buttons are clickable.
3. All menu options not responsive (like settings, restart).
4. My own profile picture not clickable at all.

As it's very strange, I am wondering if it's related to https://github.com/loqui/im/issues/255

**Comment by uvox74** [comment]
That's exactly what is happening with my ZTE OPEN FFOS 1.1. I didn't have any problems with v0.2.5c. This issue started with 0.2.6

**Comment by jansegre** [comment]
I'm also experiencing this issue. I use an Alcatel OneTouch Fire with Firefox OS 1.1, it's really bothering me.

**Comment by uvox74** [comment]
Update:
After uninstalling and reinstalling a couple of times v0.2.6 seems stable but:
1)
- No profile picture, neither contacts nor mine.
- No blue dots.
- No dots confirmating reception of the message (but I know they are delivered).

2) However, sometimes, If blue dots on grey default images appear, I experience again the issues metioned by bdcomp...... -> Uninstall and reinstall -> go to 1) 
Weird, huh?

**Comment by pavi** [comment]
Its the same here on FF 1.3 unreleased build. The app goes un responsive but takes its sweet time to get stable after which it works. Sometimes for me a restart also doesnt fix much as the app goes to its old state but as mentioned before comes slowly to its normal state.

**Comment by uvox74** [comment]
Hi pavi. How long does it take? I waited for one hour but it didn't work... still non responsive

**Comment by uvox74** [comment]
New update:
So far, this issue only happens when, at least,  a one-to-one chat is active. If only group chats are active this issue doesn't occur.

**Comment by aesedepece** [comment]
What's the current status of this issue? Have you experienced this in 0.3.0d? Thanks!

**Comment by uvox74** [comment]
No problem so far. Sometimes  (seldom) IT gets non responsive , but  after rebooting the app everything seems to work fine (FFOS1.1)
