### ISSUE TITLE
CHATS title on the contacts page

### ISSUE THREAD

**Issue by bdcomp** [loqui/im#342]
v0.2.6 on GP Peak, B2G 1.1.1.0hd-GP (stable).

From time to time, the contacts page title is "CHATS".

Please note that this issue is not new to v0.2.6, as it was so at least once earlier.

**Comment by aesedepece** [comment]
I've seen this happen sometimes. It's the localization library failing for unknown reasons.

**Comment by aesedepece** [comment]
Fixed.
