### ISSUE TITLE
Loqui gets stuck at "synchronizing" while signing in with an XMPP account

### ISSUE THREAD

**Issue by ghost** [loqui/im#343]
Hello all,

while singing in with an XMPP account Loqui gets stuck at "sychronizing".

Version 0.2.6, Firefox OS 1.1.1.0 Stable.

If any logs are needed please mention how to extract them. Thank you all!

**Comment by bdcomp** [comment]
@baccu It's been reported already - #181.

Thanks for confirming :)

**Comment by ghost** [comment]
Further info:

jabber.de has migrated few days ago from Openfire to Prosody 0.9.3.

The account from jabber.ccc.de is working fine.

**Comment by aesedepece** [comment]
Let's track this at  #181.
