### ISSUE TITLE
The "x" in the filter bar does not do anything

### ISSUE THREAD

**Issue by ghost** [loqui/im#344]
See title.

Further suggestion: Is it possible to have the ability to hide/unhide the filter bar?

**Comment by bdcomp** [comment]
@baccu Are you talking about the Contacts -> search bar and this sign ↺ ?

**Comment by ghost** [comment]
I mean the "x" on the right side in the search bar above the contacts. 

When you type a letter, the contacts starting with this letter are filtered. If you tap the "x" on the right, nothing happens.

**Comment by bdcomp** [comment]
Confirmed, the x does not do anything.
v0.2.6 on GP Peak, B2G 1.1.1.0hd-GP (stable).

**Comment by aesedepece** [comment]
This is a symptom of any other bug causing a javascript error.
When javascript reaches an unhandled exception it halts and stop the execution of any further code, including bindings to tap events like the one behind the X button.
We need to figure out the scenarios under which this issue happens.

The button works for me (I try it at least twice a day just to make sure) with the following setup:
v0.2.6 on GP Peak, B2G 1.4.0.0-prerelease

**Comment by aesedepece** [comment]
The filter bar is to be replace by a global search function.
