### ISSUE TITLE
Add additional languages to localization platform

### ISSUE THREAD

**Issue by bdcomp** [loqui/im#348]
According to Mozilla [1], Firefox OS will expand this year to: Argentina, Costa Rica, Ecuador, El Salvador, Germany, Guatemala, Nicaragua, Panama, Croatia, Czech Republic, Macedonia and Montenegro.

To make sure we are ready to launch in this countries, please add the missing languages to localization platform: Croatian, Czech, Macedonian and Serbian.

[1] https://blog.mozilla.org/blog/2014/02/23/firefox-os-unleashes-the-future-of-mobile/

**Comment by aesedepece** [comment]
Done, thanks!
