### ISSUE TITLE
Agregar una pantalla para elegir cuales cuentas conectar.

### ISSUE THREAD

**Issue by mautematico** [loqui/im#350]
Es muy bueno que podamos usar Loqui IM para todas las cuentas de mensajería instantánea que querramos, pero en algunas ocasiones podría resultar inconveniente estar conectado
"en todas ⊕ a ninguna cuenta"

Sería buenísimo tener una pantalla en el apartado de configuración donde poder "activar o desactivar" cada una de las cuentas que tenemos configuradas.

Otra forma, quizás menos eficiente, sería agregar un botón junto a "desconfigurar esta cuenta", en el apartado de configuración de cada cuenta. Dicho botón serviría para desconectar/conectar la cuenta en cuestión.

Saludos. :)

**Comment by aesedepece** [comment]
Esto está pensado para la 0.3.0, con un nuevo intercambiador de cuentas. Estoy trabajando la forma de hacerlo lo más cómodo y sencillo posible, en unos días te muestro la propuesta a ver qué te parece.

**Comment by mautematico** [comment]
Se me ha ocurrido otra forma:
En la barra lateral,
un toque en el icono de la cuenta para mostrar los contactos (como hace ahora)
otro toque para activar/desactivar.

Estaré encantado de ver la propuesta. =)

**Comment by aesedepece** [comment]
Hecho, en la v0.3.0 ya se pueden activar/desactivar las cuentas desde el panel lateral ;)
