### ISSUE TITLE
can not read or send messages

### ISSUE THREAD

**Issue by eMBee** [loqui/im#352]
on the ZTE open with FFOS 1.1 i can receive jabber messages and add manually add contacts. i can see the list of chats with the first words of the latest message, but i can't select a chat to see the messages.

if i manually add a contact then i can tap and hold on a chat to get to the contact page.
i can clear the chat for registered contacts, but not delete the contact.

**Comment by bdcomp** [comment]
@eMBee Are you on the current v0.2.6?

**Comment by eMBee** [comment]
yes, info tab in settings says it's v0.2.6

**Comment by GordonLesti** [comment]
Hello,
I have the same issue on a Alcatel One touch Fire with Firefox OS 1.1.0.0-prerelease and Loqui IM v0.2.6 when I use XMPP/jabber. Jabber-server: jabber.de

**Comment by mcepl** [comment]
The same issue with Geeksphone Peak (and FxOS 1.1.1.0hd-GP and the latest LoquiIM from the Marketplace). My own server: prosody-0.8.2-6.el6.i686

**Comment by aesedepece** [comment]
We assume this issue is not present any more as of v0.3.0.
Let us know if it does.
