### ISSUE TITLE
Loqui IM hidden on the Marketplace

### ISSUE THREAD

**Issue by bdcomp** [loqui/im#354]
GP Peak, B2G 1.1.1.0hd-GP (stable).

It looks like the Loqui IM is hidden on the Marketplace, as it's missing from:
- The "Popular" list
- "Social" category
- Search results, "Loqui" term

Although, it's available by browsing with Firefox to the direct url:
https://marketplace.firefox.com/app/loqui

**Comment by aesedepece** [comment]
This is not a Loqui IM issue but a Marketplace one. It seems all privileged apps have disappeared mysteriously from the public listings (ConnectA2, Loqui IM, LINE, etc.)

We have reported the situation to them by many ways, and we are currently waiting for a formal explanation and solution.

**Comment by bdcomp** [comment]
LINE is visible as usual.

**Comment by aesedepece** [comment]
I can't see LINE and some other people reported the same. This is weird :S

**Comment by bdcomp** [comment]
So maybe it's not about privileged apps?

**Comment by bdcomp** [comment]
Just a thought - may it be related to ESRB?
https://bugzilla.mozilla.org/show_bug.cgi?id=929812

**Comment by uvox74** [comment]
If anyone else see this and want to reinstall Loqui the only thing you have to do to avoid this problem is: open your browser and Google "loqui im". Then, click on marketplace link. You will be able to download and install the app :)

**Comment by Gioyik** [comment]
This was an error on the Marketplace and it's not present now.
