### ISSUE TITLE
Error de logado

### ISSUE THREAD

**Issue by DiegoErnesto** [loqui/im#355]
Hola, coincidiendo con la "desaparición" en el marketplace, en whatsapp, no me deja "trabajar", al cerra y volver a entrar me da error :
error de autenticación...

la des-instalé, y la volví a instalar pero después de recibir el sms y poner el código.. me sigue dando el mismo error. ¿es general o solo a mi?

v 0.2.6, y 111.0-GP

**Comment by cargabsj175** [comment]
Con whatsapp, en la versión 0.3.0b no termina de sincronizar, y regresa de nuevo a la pagina de registro

**Comment by aesedepece** [comment]
@cargabsj175 Queda arreglado en la 0.3.0c, disculpad todo el terremoto de actualizaciones.

**Comment by aesedepece** [comment]
Con la 0.3.0c/d debería funcionar correctamente. Corregidme si me equivoco ;)

Saludos y muchas gracias por aguantar el caos de las últimas versiones, @DiegoErnesto y @cargabsj175 .
