### ISSUE TITLE
We need per chat sound settings

### ISSUE THREAD

**Issue by soapdog** [loqui/im#356]
Hi,
Its pretty common when using whatsapp groups to have a lot of people talking all the time. Users from official Whatsapp client and some clones can mute/unmute the sound of each chat, which comes in handy in such cases.

Right now on Loqui we can only switch sound off in the whole app. I would like to see per chat settings for sound.

cheers

**Comment by Gioyik** [comment]
Targeted for v0.3.0

**Comment by aesedepece** [comment]
Done in v0.3.0 ;)
