### ISSUE TITLE
[WhatsApp] Loqui disconnects and doesn't know it

### ISSUE THREAD

**Issue by soapdog** [loqui/im#359]
Hi Folks,

Every now and then, loqui will lose the connection to whatsapp and not notice it. You will notice because msgs stop arriving and your outgoing msgs are not acknowledged by your friends. Closing loqui and restarting it fixes the problem and then you have all msgs arriving at once.

Loqui needs a better way to figure out when it loses connection. Or if the case is not a broken connection but something else such as a race condition then it need some sanity checks inside.

**Comment by aesedepece** [comment]
What's the current status of this issue? Have you experienced this in 0.3.0d? Thanks!

**Comment by bdcomp** [comment]
In fact, it's still here, on v0.3.1a B2G 1.3 GP Peak.
Sometimes, even the WhatsApp connection status is green, only after restarting Loqui new messages appear.

**Comment by cmeerw** [comment]
Sending group chat messages in such a state results in the messages being silently dropped (they don't get sent to the group and there is no indication that they weren't sent). To me this is a very critical bug (btw, in OpenWapp I get an indication that the message couldn't be sent and I can resend it)

**Comment by aarizkuren** [comment]
+1

**Comment by TitanNano** [comment]
I think that's the same as what I reported in the second part of #522

**Comment by TitanNano** [comment]
Okay, since we track this here, I copy my observations:

> I just did some tests and analyzed the data log in the console. I found two problems.
> 1. if there is no user interaction and the app is in the background the stream breaks (WhatsApp drops the connection?) and no new data arrives. Only when a new stream write attempt (mostly the status change from unavailable to available) from Loqui results in a write error, the app does a reconnect.
>    So two suggestions, either try to catch the stream drop or maybe easier, regularly write something to the stream (request the contacts presence) so that WhatsApp doesn't drop the connection.
> 2. When my Peak isn't connected to the console, it constantly turns off the wifi after a couple of minutes and back on when the phone gets unlocked. It didn't happen the entire time while the phone was connected, but I simulated the behavior by manually turning wifi on and off.
>    If wifi gets turned off, loqui reconnects as soon as it recognizes that the stream got interrupted (as explained in 1).
>    If wifi gets turned on, loqui wents crazy. I don't really know what exactly happens, but after the connection drop gets recognized, the app starts to send a lot of different messages, I didn't understand everything. After some time the app just restarts and connects successfully.
>    So maybe someone can investigate what exactly happens when wifi gets turned on and how this can be fixed...
