### ISSUE TITLE
Add person: select textarea

### ISSUE THREAD

**Issue by MiguelSchneider** [loqui/im#36]
It is impossible to directly select the textarea to provide the information of the address or JID and nickname in the "add person" window. It is only possible to select the text area by clicking on the text labels ("Adress or JID" and "Nickname"). Tested on a Peak and a Keon.

![loqui](https://f.cloud.github.com/assets/2051119/550841/8963ef92-c31b-11e2-9831-38a70fce3d1b.png)

**Comment by aesedepece** [comment]
Those fields are supposed to be selectable as expected.

But this is a very odd issue. I have observed it only happens sometimes with some FirefoxOS versions in some devices, which lead me to think that is more attributable to Gaia than to LOQUI itself. (It never happened to me in desktop Firefox or Firefox for Android)

**Comment by Gioyik** [comment]
This is not happening any more. I tested in FirefoxOS phones with 1.1 and 1.0 versions. Probably now is fixed with the changes in last commits.

Regards,
Gio

**Comment by aesedepece** [comment]
Yes, it does not happen, but it's not really fixed.

Indeed I made a workaround for this by dynamically replacing every input field by a `<div contenteditable data-pretend='input-text'></div>` and then styling it to look like a input field. it's at the bottom in /scripts/waalt/bindings.js
