### ISSUE TITLE
Can't log in to Google Hangouts account

### ISSUE THREAD

**Issue by soapdog** [loqui/im#360]
Hey Folks,

I can't log in to Google Hangouts from a Google Apps account. My hangout account is under my own domain email. On loqui it keeps saying there is an authentication failure but it works fine on the desktop.

cheers

**Comment by Gioyik** [comment]
Strophe uses PLAIN-AUTH for XMPP connections. So, it let connect only main domain accouns (gmail.com). We are working on a fix for this implementing OAuth. 

Thanks for the report

**Comment by aesedepece** [comment]
Duplicate of #79. Let's track it there.
