### ISSUE TITLE
Can't open contact on XMPP

### ISSUE THREAD

**Issue by rafaelmr2** [loqui/im#363]
Sometimes I can't open a contact listed on my XMPP account. I click and nothing happens. Sometimes I receive a message from a contact and I can't read. I tested the latest version of branch dev.

**Comment by pravi** [comment]
when a contact has not accepted your request, loqui stops you from messaging them, only when they accept you can talk to them.

**Comment by rafaelmr2** [comment]
I have a contact that I see as accepted in Pidgin and not in Loqui. I received a broadcast message from the server (in this case, riseup) and can't open it too.

**Comment by rafaelmr2** [comment]
Doesn't occurs anymore in newer versions. Closing.
