### ISSUE TITLE
Abrir desde PC

### ISSUE THREAD

**Issue by netomx** [loqui/im#369]
Yo sé que no es un problema de Loqui, no está hecho para PC. Hay alguna forma que pueda correrlo desde mi PC? Usaría mi número, claro está.

**Comment by Pablo2m** [comment]
Estube haciendo alguna pruebas y algunas cosas no son comodas de usar, pero poder se puede.
Bajate el zip, descomprimilo y abri el index.html.

**Comment by netomx** [comment]
Lo hice, pero se queda en "Bienvenido a Loqui"

**Comment by Pablo2m** [comment]
¿Que versión de firefox usas? , a mi me tardo unos minutos la primera vez por que se estaba actualizando pero luego se abrió

**Comment by netomx** [comment]
Use Firefox (el mas nuevo, no estoy en la PC ahorita) portable, Chrome, y
el IE. Solo el Chrome y el Firefox lo mostraban

**Comment by Pablo2m** [comment]
Bueno tenes 3 opciones:
La mejor es usar el simulador, aca tenes un articulo http://elbinario.net/2014/04/12/el-simulador-de-firefoxos/.
Básicamente haces lo que dice salvo lo de instalar firefox , es medio trabajoso pero es lo que mejor anda

**Comment by netomx** [comment]
Si lo he usado, pero queria algo mas portable. Gracias como sea :)

Por cierto, el firefox que he usado es el v28

Ernesto Villarreal

**Comment by Pablo2m** [comment]
​¿Mas portable en que sentido?​
Si queres evitar firefox podes probar usar b2g
https://developer.mozilla.org/es/docs/Mozilla/Firefox_OS/usando_el_B2G_escritorio_cliente
Hay otras opciones pero solo funcionan algunas cosas por lo que no te las
recomiendo.

**Comment by netomx** [comment]
Pues abrirlo desde cualquier dispositivo. Lo puse en un servidor mío.

**Comment by Pablo2m** [comment]
Ya entiendo,  para usarlo desde cualquier navegador necesita modificaciones, por lo que leí en algún lado hacer esas modificaciones no es prioritario, al menos por ahora.

**Comment by netomx** [comment]
Gracias!

**Comment by Gioyik** [comment]
Hay planes de sacar un cliente web y posiblemente uno Desktop. Keep informed!
