### ISSUE TITLE
Broken UI

### ISSUE THREAD

**Issue by bdcomp** [loqui/im#374]
v0.3.0 on GP Peak, B2G 1.1.1.0hd-GP (stable).

The top part of the app is totally broken.
Screenshot:
![2014-04-30-08-17-08](https://cloud.githubusercontent.com/assets/6454391/2837955/9dc7d1e6-d027-11e3-8eb9-0164c7dfc98f.png)

**Comment by aesedepece** [comment]
The problem was that the Gecko version in FFOS 1.1 didn't recognize yet the new CSS units (vw, vh, vmin, vmax), so some elements were wrongly positioned.

**Comment by bdcomp** [comment]
@aesedepece May I ask for a quick fix release of the app?

**Comment by aesedepece** [comment]
@bdcomp It will arrive in the next hours, fixing this and a sync problem with Mexico numbers. Sorry for the inconvenience.

**Comment by bdcomp** [comment]
Thanks!

**Comment by liezie** [comment]
i'm having the same issue. i did a system update but there were no updates. how should i proceed to get this fix?

**Comment by aesedepece** [comment]
@liezie The 0.3.0b update should be now available.

**Comment by liezie** [comment]
@aesedepece : thanks, that solved the issue. 
(srr for late reply)
