### ISSUE TITLE
Can't see online contacts on XMPP

### ISSUE THREAD

**Issue by rafaelmr2** [loqui/im#376]
Hi, I'm using the new Loqui IM 0.3. I can't see who is online anymore on XMPP, I see all contacts (even the offlines) and just on I open a contact I can see the status. I use Firefox 1.3 on GeeksPhone.

**Comment by aesedepece** [comment]
We disabled it for WhatsApp and probably it also broke XMPP. We'll recover it.

**Comment by unor** [comment]
> We'll recover it.

It [seems](https://github.com/loqui/im/issues/381#issuecomment-42094032) that this feature won’t come back for XMPP.
