### ISSUE TITLE
No contacts shown

### ISSUE THREAD

**Issue by Zeriuno** [loqui/im#38]
Got a [dukgo.com XMPP account](https://dukgo.com/blog/xmpp-services-at-duckduckgo).
I have 4 contacts, 1 of them being an ever-on-line bot. No contacts is shown on Loqui, nor online or offline.

**Comment by aesedepece** [comment]
This happens when your account's vCard does not include a "FN" field, which is the default behaviour in dukgo.com accounts.

This is fixed in pre-alpha008, to be released on June 15.

Thanks for the issue report and sorry for the inconveniences.

**Comment by Zeriuno** [comment]
Bueno: ¡espero la próxima version de loqui!
