### ISSUE TITLE
Minor versions not visible on Info page

### ISSUE THREAD

**Issue by bdcomp** [loqui/im#382]
v0.3.0d on GP Peak, B2G 1.1.1.0hd-GP (stable).

On the just updated app (I suppose v0.3.0d), Info page say "Loqui IM v0.3.0".

It's important for bug reports and debug to be sure that is the version we are talking about.

**Comment by aesedepece** [comment]
Thanks for you suggestion, it's really appreciated. We'll take it into account for future releases.
