### ISSUE TITLE
Keyboard resize

### ISSUE THREAD

**Issue by destanyol** [loqui/im#383]
Why Loqui does that when there is a keyboard? This makes a lot of lag. Other apps are more smoother because doesn't have this resize and are more easy to read too.

Loqui
![ndesx](https://cloud.githubusercontent.com/assets/2753657/2872956/556d3fce-d385-11e3-955f-4c6b8ea67756.png)
![ndex](https://cloud.githubusercontent.com/assets/2753657/2872957/5571fc80-d385-11e3-9e54-831c52d81614.png)
ConnectA2
![ndedx](https://cloud.githubusercontent.com/assets/2753657/2872955/5524d392-d385-11e3-8100-920ed82fa5f4.png)
![ndexf](https://cloud.githubusercontent.com/assets/2753657/2872958/5575f63c-d385-11e3-90af-364f0e603f72.png)

**Comment by aesedepece** [comment]
We're still trying to figure out why. Thanks for filing the issue so that we can track any progress.

It happens only in certain devices (mostly those with 320x480 screens) and certain versions of FxOS.

**Comment by destanyol** [comment]
Ok, I will be looking out too in my free time, thanks!
