### ISSUE TITLE
[XMPP] Can not receive msgs

### ISSUE THREAD

**Issue by ghost** [loqui/im#389]
When receiving msgs, only the network activity symbol of ffos shows activity. The messages are not shown in the chat in loqui.

@aesedepece 
Thank you for giving xmpp attention now, after the whatsapp avalanche in the last few months!

0.3.0d ffos 1.1 Peak

**Comment by ghost** [comment]
Could the cause be the fact that the xmpp account somtimes  just goes offline because of a weak internet connection?

**Comment by aesedepece** [comment]
@baccu I absolutely agree with you: adding WhatsApp has delayed our plans to heighten the XMPP user experience. But now is the moment to keep showing our support for open standards :fist:

**Comment by ghost** [comment]
@aesedepece  exactly ;-)

maybe implementing XEP-0280 & XEP-0198 ? This could increase the reliability of xmpp on mobile phones using loqui?

**Comment by rafaelmr2** [comment]
@aesedepece Thanks. I'm using WhatsApp in FFOS because XMPP support is not OK. I can't receive messages too. I'm glad you are working on XMPP. :)

**Comment by aesedepece** [comment]
This is allegedly fixed by 6fcc6c2c6e7d08b2aefbbb5fc6b2efa85c3a0dcb. It was a silly fail when reattaching XMPP stanza handlers.

**Comment by ghost** [comment]
Great news! Thank you very much! 

Can you please push an Update so we, the jabber users, can re-start using loqui?
