### ISSUE TITLE
Manifest file in Github

### ISSUE THREAD

**Issue by MiguelSchneider** [loqui/im#39]
Include a valid manifest file in github, so that the very latest version of Loqui can be downloaded from Github and installed on the Firefox OS Simulator or on a developer device through the simulator.

This might help the dogfooding testing of Loqui a lot!

**Comment by aesedepece** [comment]
Current version on GitHub (pa007) is just the same as the one you see live on http://app.loqui.im, so the manifest for it is this → http://app.loqui.im/loqui.webapp

Anyway, I'll take your advice and include the manifest when I upload LOQUI pa008, whose development is not being tracked in GitHub yet ;)
