### ISSUE TITLE
[XMPP] Initiation of OTR

### ISSUE THREAD

**Issue by ghost** [loqui/im#390]
How to initiate OTR?

After tapping on the "+" sign the key generation starts. After few seconds the window with the notification (Generating key) is gone. and then nothing happens! 

Is the key generated now? 

Is OTR active?

What about the verification of the fingerprint? (Check ChatSecure)

@aesedepece 
Can you please give us more infos on how to handle otr on loqui?

**Comment by aesedepece** [comment]
The "Generating key" notification itself explains that the key is generated in background and you'll be notified when it's ready. It should take between 10s and 5m depending on your phone (GP Revolution vs. ZTE Open).

If after some minutes the key hasn't been generated, please tell me and I'll check if there's something wrong with FFOS 1.1 that I believe you are using. Maybe it lacks full WebWorker support or something.

**Comment by ghost** [comment]
The "Generating key" notification disappears about 5-6 seconds, and then noting happens at all.

Is there any other notification when key generation succeeds?

loquiim 0.3.0d ffos 1.1 Peak

**Comment by aesedepece** [comment]
Yes, when the key generation succeeds another notification is fired and the fingerprint appears like you see in the picture:
![otr](https://cloud.githubusercontent.com/assets/1316439/2874186/e51d4a1a-d3da-11e3-83f2-2233bfebe28f.png)

**Comment by ghost** [comment]
Key generation is not succeeding on 1.1 Peak
