### ISSUE TITLE
[XMPP] Difference between diactivated account and closed Loqui concerning offline messages

### ISSUE THREAD

**Issue by ghost** [loqui/im#391]
Step one: Deactivate xmpp on loqui (do not close loqui!)
Step two: Send a msg to the deactivated account from another account on pidgin (or any other client)
Step three: re-activate account on loqui

The offline message does not arrive.

But if you close Loqui first, send from pidgin a msg and then start loqui, the offline message arrives!

So it seems there is something different beween deactivating an xmpp account and closing loqui. can you please check it?

loquiim 0.3.0d ffos 1.1 Peak

**Comment by aesedepece** [comment]
Ok, it seems that after disabling and re-enabling an account (or loosing connection and then reconnecting), the message stanza handlers are not being set any more.

I suppose it has something to do with the modifications I made to avoid duplicating handlers as often happened in 0.2.6.

I'll take a look at it asap. Thanks @baccu, @kastedo and @Gioyik !
