### ISSUE TITLE
Loqui will stop displaying messages after having lost mobile data connection

### ISSUE THREAD

**Issue by kastedo** [loqui/im#396]
ZTE OPEN
OPEN_FFOS_V1.1.0B01_TME
Loqui IM v0.3.0e
Protocol: XMPP

Loqui will stop displaying messages from a contact in a conversation (already started or not) after having lost mobile data connection and having recovered it back. However, it seems the messages actually get to the phone (at least when the conversation had already started) because the data traffic icon still shows traffic movement every time the contact tries to send a new message.

After restaring the app, messages reception will work fine again.

**Comment by Gioyik** [comment]
Maybe its the same problem described on #391

**Comment by aesedepece** [comment]
Definitively it's the same issue than #391. I'll close this and explain there what's happening. Thanks!
