### ISSUE TITLE
No way to enter verification code for Whatsapp if Loqui is not on the verification screen

### ISSUE THREAD

**Issue by soapdog** [loqui/im#399]
Hey,

If loqui is closed when you receive the SMS message and you open it again there is no way to bypass the number verification screen and go directly to the enter code screen.

Now, I can't enter my SMS verification code because Loqui thinks it needs to send it again and thanks to Whatsapp horrible practices I will only be able to send a new SMS tomorrow.

There should be a button "Verify number" and another "Enter verification code"

**Comment by aesedepece** [comment]
We had this feature in the past but I'm not sure why now we don't.
Pinging @Gioyik ... he worked on this then.

**Comment by Gioyik** [comment]
Please, check #415, is a PR for this. It SHOULD work, so, don't be bad with me after test it. :)

**Comment by Gioyik** [comment]
We have this feature on v0.3.1
