### ISSUE TITLE
[XMPP] XEP-0333: Chat Markers

### ISSUE THREAD

**Issue by ghost** [loqui/im#400]
I suggest the implementation of xep-0333 as opt-in feature.
http://xmpp.org/extensions/xep-0333.html
The chat experience is far away from being perfect (very unreliable) so chat markers should be a must have feature.

**Comment by aesedepece** [comment]
_XEP-0333: Chat Markers_ is still experimental.
We'll try _XEP-0184: Message Delivery Receipts_, which is in Standard Track and works in a more similar fashion to WhatsApp's _ack_ receipts.
Thanks for the suggestion! :+1:

**Comment by aesedepece** [comment]
Commit 22a9a88e0f15c0e40864aa6a0e416b921c66840f introduces support for _XEP-0184: Message Delivery Receipts_ :wink:

**Comment by ghost** [comment]
:+1:
