### ISSUE TITLE
Cross-Origin Request Blocked.

### ISSUE THREAD

**Issue by CodingFree** [loqui/im#402]
E/GeckoConsole( 2237): [JavaScript Warning: "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://bosh.loqui.im/. This can be fixed by moving the resource to the same domain or enabling CORS." {file: "https://bosh.loqui.im/" line: 0}]

**Comment by willyaranda** [comment]
(quick comment to post this:
https://bugzilla.mozilla.org/show_bug.cgi?id=1012240

**Comment by CodingFree** [comment]
Oh, sorry then :)
