### ISSUE TITLE
Error de autentificación en Google Hangouts.

### ISSUE THREAD

**Issue by josegfff** [loqui/im#403]
Error authentication in Google Hangouts

Despite intorducir data can not connect well.
In google mail message "prevented an unauthorized connection attempt" appears.

**Comment by aesedepece** [comment]
You can authorize your account by accessing the following site from your phone:
 http://www.google.com/accounts/DisplayUnlockCaptcha

We are still figuring out a better way to override this issue by using OAuth authentification.

**Comment by nito11** [comment]
No funsiona

**Comment by aesedepece** [comment]
@nito11 ¿Puedes ser un poco más específico? Gracias.

**Comment by Cabalo** [comment]
Entra en gmail por web, comprueba si tienes un correo con el asunto "Se ha evitado un inicio de sesión sospechoso" y en ese caso sigue las instrucciones que verás en el mensaje para autorizar esa actividad.
Yo estoy intentando conectar con Google Hangouts utilizando una cuenta de Google Apps (no usuario@gmail.com sino usuario@ejempo.com) y solo consigo hacerlo configurandola como XMPP/Jabber después de haber añadido los registros DNS que se indican en http://www.mabingenieros.com/conversar-mediante-gtalk-o-hangouts-con-firefox-os.htm
¿Alguien ha conseguido hacerlo sin tener que realizar esos cambios de dns?
