### ISSUE TITLE
Sounds should activate/desactivate with FirefoxOS sound

### ISSUE THREAD

**Issue by deimidis** [loqui/im#404]
I used to have my phone on «Vibrator» mode and with no sound, but Loqui didn't recognize that option and use it's option instead

**Comment by aesedepece** [comment]
By default, any sounds played by an app will be played in the "normal" or "content" audio channel. This means that muting the media volume in your phone should completely squelch all apps. 

What version of FirefoxOS are you using? Maybe there's something wrong with it :suspect:

**Comment by pzwart** [comment]
I can confirm this bug for v0.3.1a If the phone is muted (dialed down by the volume buttons on my Firefox Flame) and I receive a WhatsApp message (my only used protocol), the phone vibrates and gives a "pring" sound.

**Comment by bdcomp** [comment]
@deimidis @pzwart What version of Firefox OS are you using?

**Comment by pzwart** [comment]
I'm using the 'standard' release channel for the Flame. The current OS version is 1.3.0.0-prerelease.

**Comment by TitanNano** [comment]
this is not a loqui issue. We can't control the audio volume set by the user.
