### ISSUE TITLE
can't connect to dukgo.com service

### ISSUE THREAD

**Issue by Kaor** [loqui/im#408]
i have an account on dukgo.com xmpp services,
but i can't connect it on my phone,
nothing special on console,
it start synchronisation but come back to login.
It's stange because, i can see this account connected on my computer.
on pidgin or other no problem.
Thanks

**Comment by aesedepece** [comment]
I think this is a duplicate of https://github.com/loqui/im/issues/181

**Comment by Kaor** [comment]
it is !
thanks
