### ISSUE TITLE
[Lync] Add Advanced Options

### ISSUE THREAD

**Issue by jwhipp** [loqui/im#413]
Some Lync servers require advanced options such as adding the server manually when auto discovery doesn't work.  This is basically a request to allow the user add the server, port, etc. manually when adding an account.

Also might be useful to have the user agent as a configurable field (as described in Pidgin-Sipe wiki).

**Comment by Gioyik** [comment]
Could you give us a server example to test and implement this feature?

Thanks

**Comment by jwhipp** [comment]
My company is using a cloud provider for lync.  As of right now, the DNS service record for this only seems to work with official Lync clients (and even then, not really).

I've attached a screen shot of Pidgin's advanced account configuration for Lync/Office Communicator.

![pidgin-sipe-advanced-tab](https://cloud.githubusercontent.com/assets/556332/3250574/8681f998-f1a7-11e3-80a2-6240cf3bc24c.png)

http://sipe.sourceforge.net/

**Comment by Gioyik** [comment]
Thanks so much @jwhipp I will investigate about this. I hope this could be more easier than Google Apps Hangouts configuration. :)

**Comment by Milarespa** [comment]
Hi, 
My company has on-premises lync server and requires domain\user as login information.
For us, that's the only additional info to give, as server autodiscovery works fine with other clients (ipad, ...), email address domain is used and we provide a standard subdomain (lync.domain.tld)
I think that's a similar request.
Thanks
