### ISSUE TITLE
Whatsapp messages not working on Firefox OS

### ISSUE THREAD

**Issue by japerez** [loqui/im#416]
Whatsapp messages (sent and received)are not working on Firefox OS. On the other I had a fully functional Whatsapp on an iphone

**Comment by Gioyik** [comment]
Which version are you using? And which FirefoxOS version?

**Comment by japerez** [comment]
Loqui IM I'm 0.3.0 and Firefox OS 1.3

**Comment by japerez** [comment]
The whatsapp account wasn't enabled on the app. I enabled it and everything began to work.

**Comment by aesedepece** [comment]
Ok, pretty obvious xD
