### ISSUE TITLE
loqui on android, xmpp authentication failed

### ISSUE THREAD

**Issue by vitalyster** [loqui/im#418]
After reading https://hacks.mozilla.org/2014/06/firefox-os-apps-run-on-android/ I have try to run loqui on Android device. It is installed and run correctly, but I can't add my XMPP account and always get "authentication failed", even when I triple-checked my password and loqui works on Firefox OS Simulator with the same credentials.

**Comment by aesedepece** [comment]
We'll try to confirm if XMPP has issues on Android.
Could you provide your Android and Firefox version?
Thanks!

**Comment by vitalyster** [comment]
Firefox 28 (from google play) and android 4.4.3(cm11). I have access to android logs and can find any interesting info in.

**Comment by Gioyik** [comment]
It works for me on Firefox Nightly Android.

**Comment by vitalyster** [comment]
Well, I have successfully logged in when enter credentials with standard Android keyboard, so something wrong when using custom keyboard. I think it is not loqui, but firefox problem, so it should be closed.

**Comment by aesedepece** [comment]
@vitalyster Thanks for all the feedback. Happy chatting!

**Comment by moshpirit** [comment]
How did you install it on Android? any .apk that you could share, please?

**Comment by vitalyster** [comment]
@moshpirit just install Firefox, go to Marketplace, search Loqui and install it

**Comment by moshpirit** [comment]
It worked!! thank you! :D

Edit: OK, it doesn't work so good, I mean, it's installed but it only shows the blue welcome screen and a white screen that hold forever :(
