### ISSUE TITLE
Adding WhatsApp account does not work

### ISSUE THREAD

**Issue by versae** [loqui/im#419]
When trying to add my Canadian number as a WhatsApp acount, I get an error saying that the SMS could not been sent. I opened the console and no much information is shown.

```
Reason:blocked,withDiD,hu07y7ucke4
```

I regularly use the same number in a different phone with WhatsApp.

Loqui IM v0.3.0e
Firefox OS 18.1
Boot2Gecko 1.1.1.0-GP

**Comment by willyaranda** [comment]
Whatsapp has blocked you. It happened to me in the past and I needed to wait for 3 days to be unblocked.

**Comment by versae** [comment]
I see, but does it make sense that I can use the number in a different phone? Anyway, I'll try again in 3 days.

**Comment by ghost** [comment]
It should not be possible to use Whatsapp at different devices at the same time.

**Comment by versae** [comment]
I am closing the issue, never worked again, though.
