### ISSUE TITLE
[XMPP] Loqui opens a group chat window when a message is received after connecting

### ISSUE THREAD

**Issue by ghost** [loqui/im#422]
Hello all, 

thank you for the last update.

Step 1: Close loqui
Step 2: Send a msg to your xmpp account from another client
Step 3: Open Loqui.

Issue: After connecting, the message sent from the other client (when loqui was closed) is not shown. Instead of that, a new empty group chat window openes.

@aesedepece @Gioyik @aarizkuren  Can you please check this issue?

Edit: And the whole UI breaks, in order to fix that you have to remove the account and create it again.

**Comment by aesedepece** [comment]
Sorry for the delay on the fix. I'm moving to a new home so these weeks I have little time.
Thanks for reporting. I think we'll be pushing a v0.3.1b later this week.

**Comment by ghost** [comment]
@aesedepece:  Thank you for fixing this issue!

It would be great if you can push the fix, because xmpp on loqui is unusable since 2.6.
With this update we will go back to the stable version of 2.5, wich was good enough for daily use.

**Comment by ghost** [comment]
I am using Loqui IM v0.3.1 from Github (2014-07-05) and i noticed that problem together with unknown contacts again #425

And at the moment it happend again (groups created, contactprofile not accessable) with a contact out of my contactlist
