### ISSUE TITLE
[XMPP] Can't access several contact profiles

### ISSUE THREAD

**Issue by ghost** [loqui/im#425]
I can't access several XMPP contact profiles, this affects only some profiles with open chat conversations. It is not possible for me to access the profile and e.g. remove the conversation. 

```
TypeError: chat.core.participants is undefined
```

Loqui IM v0.3.1a / Firefox OS 1.2.0.0 / hamachi

**Comment by ghost** [comment]
Maybe this is related to the issue that there are groups created for the some contacts, mentioned here: #427

**Comment by aesedepece** [comment]
This is for sure a consequence of #422, which has already been solved and will be shipped soon.

**Comment by ghost** [comment]
When i receive a message from an unknown contact (not in my contact list) i can't access the profile, too

```
TypeError: chat.core.participants is undefined messenger.js:125
```

Edit: Also a Group with the unknown contact name is created

Loqui IM v0.3.1 (Github) / Firefox OS 1.2.0.0 / hamachi
