### ISSUE TITLE
XMPP account stuck in yellow mode

### ISSUE THREAD

**Issue by ghost** [loqui/im#427]
One of my XMPP account is stuck in "yellow mode" it is not shown as green connected and not grey as disconnected. 

When pressing the switch the following message appears in the debug window:

```
"SAVING" "accountsCores" [object Array] tools.js:7
"JOINING" "oneofmycontacts@ajabberserver.com" tools.js:7
"JOINING" null tools.js:7
TypeError: jid is null strophe.js:1346
```

I wrote some messages to the contact `oneofmycontacts@ajabberserver.com`, when he was (shown) as offline. 

And now there are also several groups available (under the Groups tab, "`oneofmycontacts@ajabberserver.com`" is listed there, beside "null" and an other contact name), but when i try to access the profile icon of a group, i receive the message "Error There are no chats for this contact". Maybe this is related to #425

**Comment by aesedepece** [comment]
This is as well a consequence of #422.

**Comment by ghost** [comment]
using Loqui from Github the problems "stuck in yellow mode" and "created groups" are gone
