### ISSUE TITLE
OTR Support

### ISSUE THREAD

**Issue by unknowndevice** [loqui/im#43]
OTR is a pretty standard feature in most third party IM clients (Gibberbot, Pidgin, Adium). Is there any plans to implement OTR support? 

http://www.cypherpunks.ca/otr/

**Comment by aesedepece** [comment]
Yes, I also think It should be implemented ASAP. Thanks for reporting, I'll post further progress in this same issue.

**Comment by unknowndevice** [comment]
Thanks! :)

This might help the process http://arlolra.github.io/otr/ Though I can't vouch for it's security, it is used in cryptocat.

**Comment by murr4y** [comment]
Is there any progress on this? Would be a great feature!

**Comment by aesedepece** [comment]
Don't worry - OTR is on its way.

Nevertheless, there are many other features yet to be implemented first, so you probably won't see this until December.

**Comment by garrettr** [comment]
> Don't worry - OTR is on its way.

I've started working on adding OTR support using the arlolra library - can we join forces?

**Comment by aesedepece** [comment]
> can we join forces?

Sure, any colaboration is welcome! :+1: 

Loqui v0.1 will be released next Tuesday 15th. There are substantial changes to the source code because of the multi-account thing, so we should wait for it before starting to code anything.

**Comment by ghost** [comment]
If someone is interested in contributing to a bounty: https://www.bountysource.com/issues/1181815-otr-support

**Comment by mahomedalid** [comment]
OTR is a must! :)

I want to help to, implementing this feature.

**Comment by aesedepece** [comment]
@garrettr What's the current status of your work on enabling OTR? What difficulties did you find? How can we help you to finish it?
Now that all the WhatsApp shit is over, we'd like to focus all our available resources on landing OTR in the upcoming 0.3.0 release!
THANKS!

**Comment by unknowndevice** [comment]
TextSecure is now Federated so you might want to take a look at what they're doing https://whispersystems.org/blog/the-new-textsecure/

**Comment by garrettr** [comment]
@aesedepece Didn't get very far, and it probably needs rebasing anyway. Would be happy to push to my fork if you think that would help.

I also agree with @unknowndevice that it might be better to pursue integration with TextSecure in the long run - their client has a lot of users on Android, their protocol makes security and privacy improvements on the original OTR, and their long-run goal is to support federation and clients across all platforms.

**Comment by rafaelmr2** [comment]
Why OTR in 0.3 needs geolocalization?

**Comment by aesedepece** [comment]
@rafaelmr2 It doesn't. Maybe in your device the OTR button is too close to the Location one and you pressed it accidentally?

**Comment by aesedepece** [comment]
BTW... OTR is already here. It needs yet to be improved (enabling/disabling message logging, SMP, etc.) but it just works :dancer: :dancer: :dancer:
