### ISSUE TITLE
Adding Marathi Language to Loui IM

### ISSUE THREAD

**Issue by djaniketster** [loqui/im#430]
I am also Localizing Firefox OS and other Firefox products. Loqui IM is a fantastic app and Localizing will make it more amazing. I want to localize this for Marathi language from India (mr). This is the link for my contribution (http://mozilla.locamotion.org/mr/). my handle is same that of github.
Thanks.

**Comment by aesedepece** [comment]
Hi @djaniketster. This is the link for translating Loqui IM to Marathi:
http://translate.loqui.im/project/loqui/mr

Thanks a lot!

**Comment by djaniketster** [comment]
Thank you! @aesedepece
