### ISSUE TITLE
Lags and hangs randomly on FFOS 1.1.1 for jabber accounts

### ISSUE THREAD

**Issue by gusrub** [loqui/im#431]
Hello, just got me one of those mexican movistar huawei devices. Pitty, they only have FFOS 1.1 and as far as I researched there are no updates available soon unless Huawei or movistar releases new roms which seems almost imposible given the poor interest they really have besides selling the thing...

That being said, I noticed lag and random hangs of the app, I'm using the latest version from the marketplace which I think is the 0.3.1a I set up a facebook and hangouts account and they both connect but as soon as I'm connected I cannot do anything. Clicking the gear button or event the shutdown button to close the app does nothing.

I uninstalled and installed again several times trying different aproaches, all of them failed; using jabber instead of a hangouts account or facebook acount etc.

If I wait enough I can see the "contacts imported screen" and can return to the account list but that's about it. I have to wait a long time again to be able to click on any of the accounts and get to the contact list.

One thing I noticed is that the app starts hanging as soon as it connects to any of the account networks. 

I tried both accounts on the FFOS 1.3 simulator and this does not happen. I'd love to give you debug info but have no idea where to start.

Thanks in advance.

**Comment by aesedepece** [comment]
This was fixed by the commit 786728a.
We'll push an upgrade in the following days. Please try then and confirm if we can close the issue.

Sorry for the inconveniences and thanks for your report.

**Comment by gusrub** [comment]
Sure will do. Looking forward for the update to hit the marketplace. Gracias!
