### ISSUE TITLE
[Facebook] unable to connect

### ISSUE THREAD

**Issue by schmerten** [loqui/im#438]
When I insert my Facebook username and my password then the connecting and synchronising symbol appears. After this nothing happens. I hope you can help me. (sorry for my bad english)

**Comment by schmerten** [comment]
I'm using the zte open c with firefox os 1.3.0.0

**Comment by ghost** [comment]
Is there your Facebook account under accounts when you start Loqui IM? Or is it empty like before?

**Comment by schmerten** [comment]
Its empty like before

**Comment by ghost** [comment]
Which Loqui IM version do you use? And does this problem affect other protocols/accounts, too?

**Comment by schmerten** [comment]
0.3.1

**Comment by ghost** [comment]
I run in the same situation with version 0.3.3a of Loqui IM. There are several timeouts and undefined messages on the debugging console. But it seems that the login is working, i could see some usernames of facebook contacts on the debugging console, too. And there is still some traffic to facebook shown on the console after cancel the facebook account creation, but no account under accounts was created.
