### ISSUE TITLE
WhatsApp label inconsistency

### ISSUE THREAD

**Issue by bdcomp** [loqui/im#441]
WhatsApp is written as "WHATSAAP" and "WhatsApp" at different screens.

Let's remove the inconsistency and make it only "WhatsApp".

**Comment by aesedepece** [comment]
Can you pose some examples? Thanks! :smile:

**Comment by bdcomp** [comment]
WHATSAAP:
- On the main conversation screen, left top corner
- Accounts screen

WhatsApp:
- Add accounts screen

I think I just realized how WHATSAAP issue born - "accounts" title is also full capitalized, so probably some css just applied.

**Comment by aesedepece** [comment]
Yep, it is CSS `text-transform: uppercase;`.

Do you think it is too inconsistent?

**Comment by bdcomp** [comment]
Yes, because:
- "WhatsApp" is a word about 2 parts, combined
- It's how it's originally written

I can take a look on it.
