### ISSUE TITLE
Welcome screen text blink

### ISSUE THREAD

**Issue by bdcomp** [loqui/im#442]
0.3.1a on GP Peak, B2G 1.3.0.

While Loqui starts, it looks like some text appear for a very short time before the "Welcome to Loqui!".

There should be a longer delay before the welcome text, or the former text should be just removed.

**Comment by Gioyik** [comment]
We need and screenshot or know which text appears.

**Comment by bdcomp** [comment]
As it's appear for less than a second, I only see that the text is longer than "Welcome to Loqui!".

Maybe it just "Welcome to Loqui!" before some css/js applied?

**Comment by Gioyik** [comment]
Maybe is just only a retard when l10n.js renders the strings. It's common.

**Comment by bdcomp** [comment]
My Loqui in English.
And in fact there is no such blink elsewhere.

Maybe someone with a very low-end device could see that actually displayed on startup?

**Comment by ghost** [comment]
I could confirm that behavior. Using Loqui IM with an English UI, too. 

"Welcome to Loqui IM" (appear for less than a second)

![welcome loqui im](https://cloud.githubusercontent.com/assets/4523264/3507243/4f8ac106-067c-11e4-91d7-de2c9fde096a.png)

**Comment by bdcomp** [comment]
I am wondering if it's worth to fix only this issue, as the app is probably flickering on every string, on every language other than English, because of #446.
