### ISSUE TITLE
[XMPP] problems receiving and sending (Otr) messages 

### ISSUE THREAD

**Issue by ghost** [loqui/im#443]
I am using a Github version of loqui and Firefox OS 1.2 (Alcatel one touch)

The opposite side is a pidgin 2.10.9 client with pidgin-otr 4.0.0

When sending messages, sometimes these messages are delayed, not sure if this is a problem of the wws or anywhere else, i already receive new messages from the opposite but my messages are not yet delivered 

Sometimes i don't receive some messages, i could reproduce the following scenario:
1. there is an open otr conversation, everything is fine
2. disconnect the account within loqui
3. close loqui
4. connect the account again
5. now i don't receive any messages from the opposite where the otr conversion is still open, until the opposite refreshes the otr session

Maybe the otr session should be closed by loqui (inform the opposite side)
- when disconnect the xmpp account and
- when run "clear chat"

another scenario: 
1. there is an open otr conversation, everything is fine
2. the opposite side closes the private otr chat
3. the opposite side sends unencrypted messages to me
4. now i don't receive any messages from the opposite until the opposite refreshes/opens the otr session again

Maybe the otr session should be closed by loqui
- when receiving a otr closing message (if there is any)

**Comment by ghost** [comment]
I can't reproduce this behavior with version v0.3.3a at all

Pidgin recognizes that a message could not delivered over Otr and resent the last message.
And Loqui recognize when a Otr connection is closed by the other chat client.

But when i close Loqui (the Otr session is not closed by Loqui) and a contact still sends messages over this open Otr session, i will not receive all messages from the contact, but the last message is resented after establish/refresh the Otr session again.

I still suggest to close all open Otr sessions when Loqui is closed or an account is disconnect.

**Comment by ghost** [comment]
I would suggest something like the following, but unfortunately the SEND command is sent after the account is disconnected. Any suggestion how to wait for the SENT command before disconnecting?

```
diff --git a/src/scripts/loqui/account.js b/src/scripts/loqui/account.js
index 05cf9eb..5054a2b 100644
--- a/src/scripts/loqui/account.js
+++ b/src/scripts/loqui/account.js
@@ -560,6 +560,11 @@ var Accounts = {
       var account = App.accounts[Accounts.find(li.data('jid'))];
       if (li.data('value') == 'true') {
         if (confirm(_('AccountDisable', {account: account.core.fullJid}))) {
+          for (var j in account.chats) {
+            if (account.chats[j].OTR) {
+              account.chats[j].OTR.endOtr();
+            }
+          }
           account.core.enabled = false;
           account.connector.disconnect();
         }
diff --git a/src/scripts/loqui/app.js b/src/scripts/loqui/app.js
index e391f8b..3ad89a8 100644
--- a/src/scripts/loqui/app.js
+++ b/src/scripts/loqui/app.js
@@ -214,6 +214,11 @@ var App = {
     for (var i in this.accounts) {
       var account = this.accounts[i];
       if (account.connector.isConnected()) {
+        for (var j in account.chats) {
+          if (account.chats[j].OTR) {
+            account.chats[j].OTR.endOtr();
+          }         
+        }
         account.connector.disconnect();
       }
       account.accountRender();
@@ -239,6 +244,11 @@ var App = {
   killAll: function () {
     this.settings.reconnect = false;
     for (var i in this.accounts) {
+      for (var j in accounts.chats) {
+        if (accounts[i].chats[j].OTR) {
+          accounts[i].chats[j].OTR.endOtr();
+        }
+      }
       this.accounts[i].connector.disconnect();
     }
   },
```

The debug output, endOtr() is called before "Disconnecting"

```
"Disconnecting"
"SENT" "jabberid@jabberdomain.tld" "<presence xmlns='jabber:client' type='unavailable'/>"
"SENT" "jabberid@jabberdomain.tld" "</stream:stream>"
"Disconnected"
"SAVING" "accountsCores" [object Array]
"SEND" "?OTR:..." [object Object]
```

**Comment by bdcomp** [comment]
@aesedepece Is this fixed by your https://github.com/loqui/im/commit/e89c575ead408bef6e4544a97e9e6c192e6f9efb

**Comment by aesedepece** [comment]
@bdcomp It needs some more work.
Now you can receive the messages but you don't get the first one (I'm still trying to figure out why).

**Comment by ghost** [comment]
@aesedepece I tested the latest dev version of LoquiIM from Github, i receive all messages, also when a contact is offline or i am offline and still sending messages with the open otr session. :+1: 

What do you mean with the "you don't get the first one"? Is that already fixed? I don't miss any messages.

**Comment by ghost** [comment]
And i am not sure if that is caused by your commit to fix this issue or if this is an older problem.

I added a new account and i am asked to create an otr key (cause my chat partner, try to start an otr session), i choose create. 
I am leaving the chat
And everytime i access the chat, again, i am ask to create an otr key (but the otr key creation is already running)

Expected behavior: Don't ask again for creating a otr key, if it is already doing one for the chosen  account

Also the otr session is not started after the key is created. Maybe an otr session should be started automatically after the key is done.

**Comment by ghost** [comment]
I did some more tests, when i tested the behavior before https://github.com/loqui/im/issues/443#issuecomment-57135644 my phone was connected to my computer, loading the battery and in a kind of "always online" mode, also i disconnected and connected the accounts manually

but when my phone is not connected via usb and i am chatting over an otr session, when the display of my phone is turning off after a minute Loqui is going in an away status. If i try to write some messages to my account (used on Loqui) the messages are delivered mostly. But back to my phone after some more minutes Loqui is not running anymore, i need to start Loqui again, the otr session is not started anymore and i need to wait some seconds (maybe 10s or more) for the otr chain in the background of the chat to appear, again. During this time messages from a contact are not delivered at all (some are lost), and/or otr error appear at the desktop client. And the otr session sometimes is reseted.

Also i miss the Otr button, why was it removed?

**Comment by aesedepece** [comment]
The OTR button has been replaced by a switch inside the contact's options.
As long as that switch is turned on, every time you enter the chat, Loqui negotiates an OTR session, accepts only ciphered messages and discards plain messages.
