### ISSUE TITLE
Problem using Whatsapp and XMPP (otr) at the same time

### ISSUE THREAD

**Issue by ghost** [loqui/im#444]
Loqui IM Github version on Firefox OS 1.2 (Alcatel one touch)

I am using a Whatsapp account and a XMPP account at the same time within Loqui IM

I accessed the Whatsapp account, and someone tries to opens a Otr XMPP conversation with me

Loqui asks me if i want to create an Otr certificate (i aleady have one for XMPP, but not for Whatsapp), i cancel that request.

But now there is a chat with the XMPP username who wanted to contact me within my Whatsapp account. (is this a feature or a bug?)

**Comment by aesedepece** [comment]
Thanks @bobcanthelpyou
