### ISSUE TITLE
Hide content until the L10n 'localized' event happens

### ISSUE THREAD

**Issue by bdcomp** [loqui/im#446]
While investigating #442, I found that in general, flickering happen when the app display non-localized strings and then update the strings.
We should hide content until the L10n 'localized' event happens (or just synchronously load L10n resources, if it's possible for Loqui).

Just to clarify - this issue relevant to all languages, even the English, as all the strings loads twice (non-localized and later localized).

Longer description from the l10n.js:
"Synchronously loading l10n resources significantly minimizes flickering from displaying the app with non-localized strings and then updating the strings. Although this will block all script execution on this page, we expect that the l10n resources are available locally on flash-storage.
As synchronous XHR is generally considered as a bad idea, we're still loading l10n resources asynchronously -- but we keep this in a setting, just in case... and applications using this library should hide their content until the 'localized' event happens."

**Comment by TitanNano** [comment]
I experienced a similar bug in Add-on development, so I decided to have no default strings inside the HTML. That minimized the issue to a minimum and you only have to wait a short moment sometimes until the string appears. I think it looks better than flickering from one language to a other, but I don't know if that would satisfy you...

**Comment by bdcomp** [comment]
@aesedepece @Gioyik What do you think?

The delay not sounds promising, although it's better than flickering...

**Comment by aesedepece** [comment]
The main reason for having a welcome screen is precisely avoiding the flickering to happen while the main interface is shown; which would be much worse.
