### ISSUE TITLE
Emoji icons not visible on Firefox OS notifications

### ISSUE THREAD

**Issue by bdcomp** [loqui/im#447]
0.3.1a on GP Peak, B2G 1.3.0 (build ID 20140705061248).

All the emoji icons displayed as gray square on Firefox OS notifications.

**Comment by aesedepece** [comment]
This is a system issue in old Firefox OS versions which didn't support special unicode characters.
As of Firefox OS 2.1, most of them are perfectly rendered.

**Comment by bdcomp** [comment]
OK.

Pretty strange to think about (the unreleased) B2G v2.0 as an old version :)

**Comment by TitanNano** [comment]
this is nothing that depends on loqui... maybe we can close this? 
There are so many open issues that aren't relevant, already fixed, etc...

**Comment by aesedepece** [comment]
I agree.
