### ISSUE TITLE
What does the green line means?

### ISSUE THREAD

**Issue by TitanNano** [loqui/im#452]
Hey,
What exactly does the green line in the message log mean? 
Does it mean the message was sent or that it is arrived or that it was read?

**Comment by aesedepece** [comment]
The green line is equivalent to the double-tick in WhatsApp. It means "delivered to recipient".

**Comment by TitanNano** [comment]
okay, thank you.

2014-07-10 17:08 GMT+02:00 Adán Sánchez de Pedro Crespo <
notifications@github.com>:
