### ISSUE TITLE
[WhatsApp] messages received twice

### ISSUE THREAD

**Issue by bdcomp** [loqui/im#453]
0.3.1a on GP Peak, B2G 1.3.0 (build ID 20140710061317).

Sometimes WhatsApp messages received twice.
It looks like after the first time the message received, Loqui lost connection. Later, after reconnect, the same message appears again.

**Comment by ghost** [comment]
I could confirm that behavior

**Comment by aesedepece** [comment]
The only reason for receiving the same message twice is because the ACK (acknowledged) answer couldn't be delivered to the server. This happens when connection is lost right after a message is received because the TCP socket is closed/broken in the very moment the ACK is sent.

**Comment by bdcomp** [comment]
@aesedepece Please take an additional look at the relevant code, as this issue happens a lot and only on the last version of Loqui.

**Comment by cmeerw** [comment]
I have seen this on my phone as well now. What appeared to be happening was that the message was delivered while the phone was sleeping - the phone only woke up to receive the message from the socket, but went to sleep again before being able to process the message. After the WhatsApp server didn't get any "ack" for 1 minute, it closed the connection. So when the phone woke up again, it finally processed the incoming message, but at the time the WhatsApp server connection had already been closed. On the following reconnect the message was delivered again.
I am currently testing a fix for this, fingers crossed...
