### ISSUE TITLE
App.killAll causes a CSP violation

### ISSUE THREAD

**Issue by TitanNano** [loqui/im#462]
When `App.killAll` is called it calls `XMPP.disconnect > Storphe.Connection.prototype.disconnect > Strophe.Bosh.prototype._disconnect > Strope.Bosh.prototype._sendTerminate` and `_sendTerminate` creates a new xhr request without `mozSystem : true`. So the termination request just gets blocked...

**Comment by Gioyik** [comment]
Thanks we are going to check it out.

**Comment by aesedepece** [comment]
I think this is the reason:
When you disconnect from the server on purpose, the session in closed and thus the BOSH server stops running CORS, so the last closing XMPP stanza comes without the `Access-Control-Allow-Origin: *` in the HTTP header wrapping it.
