### ISSUE TITLE
URL must not be altered by emoticons 

### ISSUE THREAD

**Issue by airon90** [loqui/im#463]
One of my friends sent me a YouTube link on Facebook (https://www.youtube.com/watch?v=XXXXXXXXXXX) and Loqui changed the ":/" of the protocol in a emoticon, making the link unopenable by just tapping it.

**Comment by airon90** [comment]
![blob](https://cloud.githubusercontent.com/assets/139841/3584841/0ec01d80-0c1f-11e4-9808-18c88aa6afc7.png)
I cutted the screenshot

**Comment by bdcomp** [comment]
The relevant code is in xmpp.js, line 694.

Is it OK to disable the conversion of ':/' to emoji, or should we resolve this smarter (by some js check if ':/' is not part of the url)?

**Comment by airon90** [comment]
IMHO the :/ emoji must not be disabled. It must not part of a protocol in order to be displayed

**Comment by ghost** [comment]
I am not sure how emoticons are used at all

Are emoticons which should be displayed always surrounded by whitespaces (space, new line, ..)? Or are they used between or near words/numbers/letters/.. without spaces?

I think that it should always not be interpreted as an emoticon when there are non-space characters on both sides (before and after the emoji code)

**Comment by airon90** [comment]
Instead I think that it should always be interpreted as an emoticon when there is a space character on the left side because sometimes the emoji is inserted at the end of the sentence ;)

**Comment by gargsms** [comment]
https://github.com/loqui/im/pull/537 solves this and a lot of others.
