### ISSUE TITLE
[WhatsApp] Loqui IM crash cause of group and/or group pictures

### ISSUE THREAD

**Issue by ghost** [loqui/im#465]
I was added to a new Whatsapp group, now Loqui IM crashes after trying to get the profile pictures. I am not sure if the pictures are causing the crash.

**Comment by ghost** [comment]
Loqui IM v0.3.1a (dev 20140711) / Firefox OS 1.2 / Alcatel one touch

can't reproduce this issue with 
Loqui IM v0.3.1a (marketplace) / Firefox OS 1.3 / Simulator 7.0pre9.20140401
(group picture is loaded normally)

**Comment by TitanNano** [comment]
I'm experiencing no problems and no one else seems to either... maybe we can close this?

**Comment by bdcomp** [comment]
In fact, Loqui crashed several times last weeks, although I am not sure why.

0.3.3a on GP Peak, B2G 2.0.0.0-pre, 14/11/2014 build.

**Comment by TitanNano** [comment]
I have no crashes on my Peak B2G 2.1 with 0.3.4a and my group pictures are downloaded and displayed properly... What do these crashes look like? the app just gets closed?

**Comment by bdcomp** [comment]
I think it's group related, as per original issue report.
My app crashed several times while I was reading/loading old messages of some group.

**Comment by ghost** [comment]
Maybe this issue is related to my low-end Firefox OS device, maybe out-of-memory problems

This issues hit me again, lately (cause of the 'false image reception bug'), i try to have a look at that issue again and provide some logs.

**Comment by TitanNano** [comment]
App crashes on Firefox OS are always related to memory pressure. Because apps can't crash, actually they get killed. 
The thing is, there is no difference between 1-on-1 chats and muc chats from a memory point of view.

@bdcomp well I don't know how old this messages were but it might be possible that you loaded that many messages chunks that your device ran out of memory.
