### ISSUE TITLE
sending files does not work

### ISSUE THREAD

**Issue by pravi** [loqui/im#466]
I can select an image from gallery and choose loqui im from share options. But when I choose a contact, it says only xmpp/jabber can share files, even when my account is xmpp/jabber.

**Comment by ghost** [comment]
Which Loqui IM and Firefox OS version and hardware do you use? Actually i can't select any images with a XMPP/Jabber account with Loqui IM v0.3.1a. It is only Emoji, Bolt and OTR available.

**Comment by pravi** [comment]
Loqui im 0.3.1a, Firefox OS 1.3.0 and ZTE Open C.

Open Gallery, choose an image and click on share button.

From loqui chat window only emoji, bolt and otr is visible when + button is pressed.

**Comment by aesedepece** [comment]
Loqui IM still doesn't support sending files via XMPP indeed, so the notification text should be something like "Only WhatsApp accounts can do this".
