### ISSUE TITLE
[XMPP] Flood of disco#info at reconnect

### ISSUE THREAD

**Issue by linkmauve** [loqui/im#475]
Hi,

A contact using LoquiIM just bombarded me of disco#info queries on the caps node of my client, it seems each time he gets disconnected/reconnected he sends one more (the last one I saw was from 3017 to 3071, so 54 different iqs, but it’s increasing):

<iq from="somecontact@hisserver/Loqui" to="me@myserver/poezio" type="get" id="3017:sendIQ"><query xmlns="http://jabber.org/protocol/disco#info" node="http://sleekxmpp.com/ver/1.2.5#ay5JZ4xVXZo9vXEmG6+Ym9l/knk=" /></iq>

I don’t know the exact version of LoquiIM he uses, so maybe this bug has been fixed in a newer version (and LoquiIM should answer iq:version, but this will be the object of a later bug).

**Comment by linkmauve** [comment]
Has this bug been fixed?  I had to block the presences from that contact, so maybe if he updated I wouldn’t have to anymore.

**Comment by aesedepece** [comment]
Yes, I believe this to be fixed by v0.4.0 to be released on FF Marketplace this week.
If you detect this behavior keeps on going, please tell me.

**Comment by linkmauve** [comment]
Thanks. :)
