### ISSUE TITLE
many empty group chats are created

### ISSUE THREAD

**Issue by pravi** [loqui/im#477]
There are many emty group chats in my list and there is no way to clear them up.

I have only a jabber account and I'm on 0.3.1a. My phone is ZTE open C. I think it is created when a new message arrives.

**Comment by pravi** [comment]
When you try to remove them it shows, there are no chats with this contact.

If you type a message, then the title changes to null and then you can clear chat with null. But you will have to repeat it for each instance.

**Comment by pravi** [comment]
And if you go to the groups view you can see a lot of null groups.

**Comment by pravi** [comment]
Screenshot http://bayimg.com/HApoGaaFH

**Comment by aesedepece** [comment]
I think this was reported in #422 and fixed by 786728a0b4f9ec8aefa4277f521f767241e40311.
Closing, let me know if I'm wrong!!! :facepunch:
