### ISSUE TITLE
WhatsAPP: Send/Verify code not working.

### ISSUE THREAD

**Issue by TonyStark** [loqui/im#479]
Hi
i hosted loqui IM in ubuntu/localhost.
i setup with `grunt`
but i can not able to get code into my mobile.
and your verification code page is not working after received code.
nothin happen after entering every detail...

**Comment by aesedepece** [comment]
What platform are you testing it in? (Firefox for desktop / B2G Emulator / Firefox OS phone / Android)
You have to know WhatsApp doesn't work on desktop browsers because they don't support the TCP Sockets API yet.

**Comment by TonyStark** [comment]
Firefox for Desktop.
(Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:30.0) Gecko/20100101 Firefox/30.0)
Is this possible to make config with username and password in whatsapp?
i have my account id and password.

**Comment by aesedepece** [comment]
I'm afraid not. Every connection to WhatsApp's servers need to be made through TCP sockets, and desktop browsers won't be able to connect until they support such API.

I'm closing this issue hoping Firefox for desktop implements the TCP API as soon as possible.
Thanks for your interest, please tell me if you have any other question regarding this issue or any else.

Best regards,
Adán
