### ISSUE TITLE
Contacts sorting

### ISSUE THREAD

**Issue by kkdeep** [loqui/im#48]
Are there any plans to implement the functionality of contacts sorting such as show only ONLINE contacs or/and mark them as favourites so that only selected contacts are visible?

**Comment by aesedepece** [comment]
Hello Krishna,

Contacts sorting is planned though not assigned yet to a certain release or milestone.

Showing only connected contacts is already supported. You just have to open the contextual menu by pressing the icon on the top left corner of the contacts list and then tap "Toggle disconnected contacts".

**Comment by kkdeep** [comment]
Hi Adan,
Thanks for the info.Nice to hear that its planned. I already checked those things bt may be because of terminology failed to understand. Normally in IM's "Toggle/Toggling" word is avoided. It would be much better  and intutive if instead of "Toggle disconnected contacts" "Show online contacts" is displayed. This is just a suggestion btw.

**Comment by radare** [comment]
Another feature request similar to this would be to favorite contacts and show them first in list if they are online.

Otherwise alphabetically listing online contacts would be the expected behaviour.

**Comment by aesedepece** [comment]
The "favorite contacts" feature possibility will be explored later. Everything else is already done :)
