### ISSUE TITLE
chat background per contact

### ISSUE THREAD

**Issue by TitanNano** [loqui/im#480]
Yesterday I tried the background feature and have to say that I really like it. 
But I realized that I would prefer not to use the same background for every contact... Maybe it could be changed so the background gets associated with a specific contact and not with the entire account?

**Comment by aesedepece** [comment]
Discussion: :thought_balloon: 
Do other messaging app allow to do so? Does the official WA app for Android/iOS?

I'm pretty sure this feature would be nice for many users. The bad point is that storing and loading full-screen background pictures for every contact (or even a few) would be too heavy for the IndexedDB backend. :hammer:

**Comment by TitanNano** [comment]
Are there limits in indexedDB? [MDN](https://developer.mozilla.org/de/docs/IndexedDB) says that there are no limits for the size of a DB in Gecko.

**Comment by Gioyik** [comment]
@aesedepece I don't think so. The way we do it it's the common in most of chat accounts.

Maybe we need more user stories (feedback) and see if this could be an appropriated change.

**Comment by aesedepece** [comment]
:+1: for waiting for more user stories.
