### ISSUE TITLE
"Synchronise phone" is misaligned in non-English languages.

### ISSUE THREAD

**Issue by pzwart** [loqui/im#482]
(The example is in Dutch) 
The button to synchronize the contacts is misaligned in normal orientation and in Dutch language. The button does not work either. When switching to to landscape mode the button has more room and is aligned okay and it works.
![2014-07-30-21-14-54](https://cloud.githubusercontent.com/assets/2669647/3754879/609b2044-181f-11e4-9830-2bf5e541e51f.png)
![2014-07-30-21-14-45](https://cloud.githubusercontent.com/assets/2669647/3754880/60c14cec-181f-11e4-8220-5d3e03e3a98d.png)

Tested on a Firefox Flame.
Version v0.31a

**Comment by aesedepece** [comment]
Ok, we have to trim that label. 
Which of these options do you think is the best?
- Telefoon sync
- Synchroniseren
- (Any other suggestion)

Thanks in advance for your feedback, @pzwart !

**Comment by pzwart** [comment]
I think "synchroniseren" would be fine. And I like the app so I love to help :-)

**Comment by ghost** [comment]
I am not sure but that affect other languages, too
![photo192797414471608238](https://cloud.githubusercontent.com/assets/4523264/4354560/5a1b7dc8-423f-11e4-8d8a-c5cee39056a9.jpg)

And other places are affected, too
![photo192797414471608239](https://cloud.githubusercontent.com/assets/4523264/4354564/5d3a3d00-423f-11e4-898b-87ee6a520505.jpg)

Is there no useful fix for this with Css?

1) Maybe just set the **width** to something like **200%** (**index.css: section#activity article header.beige**) but that is not nice at all.
![photo192797414471608241](https://cloud.githubusercontent.com/assets/4523264/4354840/c24ab776-4242-11e4-8e52-9d4e84c06021.jpg)
![photo192797414471608242](https://cloud.githubusercontent.com/assets/4523264/4354914/15dfbdae-4244-11e4-9ffe-5681a067c9bc.jpg)

2) It is also possible to divide the space to the elements in one line e.g. 2 elements is **width 50%** each (**index.css: section#activity article header.beige button**), could be set maybe dynamically with JS. But need some more enhancement with css
![photo192797414471608240](https://cloud.githubusercontent.com/assets/4523264/4354843/c812c25c-4242-11e4-858e-0b0186a47958.jpg)
![photo192797414471608244](https://cloud.githubusercontent.com/assets/4523264/4354915/19225b84-4244-11e4-8c2f-692fac7e4d09.jpg)

In the last screenshot is much more place for longer translations/texts not sure how to use the space in both views nicely.
