### ISSUE TITLE
Allow loqui to be used on desktop firefox

### ISSUE THREAD

**Issue by p91paul** [loqui/im#483]
I'd like to try loqui on the desktop, but I can't since it is not installable from the marketplace. What is exactly the reason to keep it on mobile only?
i know there are native IM clients for desktop, but maybe it's a zero effort to allow it to be installed on any platform!

**Comment by Gioyik** [comment]
We are working on a desktop client. We will keep everybody update.

**Comment by aesedepece** [comment]
Until then, you have https://demo.loqui.im (open with Firefox for desktop).
The version showed in this online simulator is v0.3.0, but we'll update it soon.
Notice that you can't use WhatsApp from desktop because normal web browsers don't support the TCP Sockets API yet.

**Comment by 0b10011** [comment]
:+1:

**Comment by Pablo2m** [comment]
:+1:

**Comment by singpolyma** [comment]
What are the blockers to this?  It looks like TCPSocket is available to desktop runtime apps.  What APIs are not available in the desktop runtime that loqui needs?

**Comment by singpolyma** [comment]
I decided to try the app on the desktop runtime.  I couldn't actually figure out how to do it... but just dropping the distribution index.html for firefoxos on my browser actually seems to work pretty well.  So I think it might just work... if I can figure out how to get my firefox to install/run the package.

**Comment by TitanNano** [comment]
You can't. at the moment there is no way to install privileged desktop apps
that are not distributed through the marketplace.

2015-02-14 23:09 GMT+01:00 Stephen Paul Weber notifications@github.com:

**Comment by singpolyma** [comment]
@TitanNano yeah, I just found that on the bugzilla... crazy oversight!  Hope that gets into a future firefox release so development on the desktop runtime becomes possible.

**Comment by yukulele** [comment]
:+1:

**Comment by AlexLikeRock** [comment]
:+1:

**Comment by p91paul** [comment]
apparently, this project moved to gitlab several years ago. Closing.
