### ISSUE TITLE
Certain emoticons are rendered with extra characters.

### ISSUE THREAD

**Issue by pzwart** [loqui/im#488]
Check the screenshot. With this certain emoticon extra  ", / and > characters are rendered.
Tested on v0.3.1a and a Firefox Flame.
![2014-08-03-17-11-02](https://cloud.githubusercontent.com/assets/2669647/3803786/74fc04d8-1c1e-11e4-97f0-d1e6d3ed97c6.png)

**Comment by TitanNano** [comment]
:+1: I'm experiencing that too
