### ISSUE TITLE
Attachments in one-on-one chats are received multiple times as separate messages

### ISSUE THREAD

**Issue by pzwart** [loqui/im#489]
When I receive attachments through the Whatsapp account I receive them more then once. I attached an example where you can see the attachments are received at different times. This happens with pictures and sounds. I think it only happens in one-on-one chats and not in groups. Tested on v0.3.1a and a Firefox Flame.
![voorbeeld](https://cloud.githubusercontent.com/assets/2669647/3804316/52122a8c-1c24-11e4-9c1f-c00710f11c8d.png)

**Comment by aesedepece** [comment]
This was fixed by commit 3e45a6dd5c98d592ee05a9264ce6c15d1550da4b. Thanks for noticing.
You should be able to update to Loqui IM v0.3.2, which is available since yesterday. Sorry for the inconveniences.
