### ISSUE TITLE
[XMPP] Groups created with offline contacts

### ISSUE THREAD

**Issue by ghost** [loqui/im#490]
Sometimes (not always) a group with the name of the contact is created when i send a message to a single offline contact.

Always a group with the name of the contact is created when i receive a message from an offline contact

Loqui IM / Firefox OS 1.2 / Alcatel one touch

**Comment by ghost** [comment]
I can't remove the groups, cause i can't access the profile picture. Nothing happens when clicking on the profile picture.

When i write a message in those groups the message is not delivered to the contact, i receive my message myself.

**Comment by ghost** [comment]
Loqui IM v0.3.2a

**Comment by aesedepece** [comment]
I take this issue.

**Comment by ghost** [comment]
If someone else could reproduce that issue open a new issue or pull request.
