### ISSUE TITLE
Loqui v0.3.2 gets frozen

### ISSUE THREAD

**Issue by uvox74** [loqui/im#491]
After updating to v3.2 the app is painfully slow, gets stuck or even crash. It becomes totally unusable.
It happens using Whatsapp on a ZTE OPEN with FFOS 1.1.

Reminds me a lot an issue that happened to me with v0.2.6

**Comment by aesedepece** [comment]
I think we implemented presence indicators for WhatsApp in v0.2.6, then dropped them in v0.3.0 and recovered again with v0.3.2. It seems to me that the ZTE Open isn't powerful enough to handle so many changes to the DOM along time, which could be causing this issue.

We need to test how it responses under different devices and make up a final decision on keeping or dropping this feature.

**Comment by TitanNano** [comment]
No problems on Geeksphone Peak with FxOS 2.0

**Comment by aesedepece** [comment]
No issues on Geeksphone Revolution with FirefoxOS 1.3 either.
I'll try to get a ZTE Open so that I can test this issue more accurately.

**Comment by aarizkuren** [comment]
It happens too with Geeksphone Keon with FOS 2.1
