### ISSUE TITLE
Meaning of the setting for hiding unavailable contacts?

### ISSUE THREAD

**Issue by unor** [loqui/im#492]
If I understand #381 correctly, the contact list is not supposed to show who is online, and there will be no roster with this functionality; so you’d have to open a chat with a specific contact to check if this contact is online. Correct?

If so, what exactly does the setting "Hide unavailable contacts" do? (I don’t know the actual English string for this setting; in German it’s "Verstecke nicht verfügbare Kontakte")

**Comment by aesedepece** [comment]
You are right, that option is pointless now. Let's remove it.
