### ISSUE TITLE
no option to disable otr once enabled

### ISSUE THREAD

**Issue by pravi** [loqui/im#502]
I have to remove the account to disable otr.

**Comment by aesedepece** [comment]
OTR is disabled and enabled in a chat using the same button.
We are changing this for a switch button in the chat options.

**Comment by pravi** [comment]
I was looking at disabling otr for an account. Now if we are disconnected during an otr session, other person gets an ots error and either I see no messages (I can see them typing, or i get encrypted text #505). I was hoping to disable otr support and fall back to plain text, but couldn't find such an option.

**Comment by ghost** [comment]
@pravi The button to enable and disable Otr is available with the "+" button next to the text input field. With that "+" button you could access Emoji, Bolt and OTR.

**Comment by aesedepece** [comment]
As @bobcanthelpyou saidm you can enable and disable OTR with the same button.

**Comment by pravi** [comment]
@aesedepece I was looking at an option to disable otr for the account, not just for a particular chat session.

**Comment by aesedepece** [comment]
@pravi Why would you want to do so?
