### ISSUE TITLE
Allow URL sharing

### ISSUE THREAD

**Issue by airon90** [loqui/im#508]
Is it possible to add URL sharing?

https://github.com/loqui/im/blob/dev/manifest.webapp#L67

Adding URL sharing it will be possible to send url to someone or to create a message with a url already inserted

Here is why I made this request: http://tracker.user1.be/SimpleRSS/64/#127

**Comment by aesedepece** [comment]
:+1:

**Comment by ghost** [comment]
Is this a duplicate of #534 ?
