### ISSUE TITLE
[XMPP] allow ssl certificate exceptions

### ISSUE THREAD

**Issue by pravi** [loqui/im#510]
currently we cannot connect to a server if it is using a self signed certificate (You can test this on sechat.org). On clients like pidgin, it asks if you want to add an exceptions and we can connect to the server after adding an exception.

Please add such an option to loqui so I can start using sechat.org as my xmpp server.

**Comment by pravi** [comment]
sechat.org is still a work in progress (integrating vines xmpp server with diaspora). But I think it would be a good test case for loqui to handle exceptions properly.

**Comment by pravi** [comment]
I can send messages to that account from loqui, but loqui does not show any replies. It could also be that yax.im server (my xmpp service provider) is refusing the messages because it cannot authenticate sechat.org via ssl certificate.

**Comment by TitanNano** [comment]
I don't think we can do this since SSL certificates are handled by Gecko. Reopen in case I'm wrong. (I don't think so).
