### ISSUE TITLE
unable to send a sms - whatsapp

### ISSUE THREAD

**Issue by Thalyn-** [loqui/im#513]
Hello,

good job for this app :)
my smartphone is reinitialized, i installed loqui im and at the time to add my whatsapp account, i have an error message.
The debug mode says:
sms isn't sent, reason:,old_version...

I have a ZTE OPEN C with FFOX 1.3
Yesterday i had no trouble with loqui im/whatsapp (before this morning:hard reboot).

Thanks and good day!
:)

**Comment by Thalyn-** [comment]
Oops sorry... 
I'm talking about the sms send by whatsapp for the verification of the n° (code)

**Comment by aesedepece** [comment]
Many users are reporting verification SMS sending problems lately.
We'll investigate if WhatsApp changed something in their verification protocol.

**Comment by aesedepece** [comment]
I've reached out Yowsup devs in order to cooperate in solving this as they are affected by this issue as well.

**Comment by aesedepece** [comment]
@aarizkuren Can you explain what's left to consider #514 a fix? Gracias Asier!!!

**Comment by aarizkuren** [comment]
@aesedepece i have been reading yowsup and whatsapi repos, and they say that is only that token was old (see: https://github.com/venomous0x/WhatsAPI/issues/915#issuecomment-53914130)
I change it, no more.
I test it and it works for me, maybe others can test it before

de nada

**Comment by aesedepece** [comment]
I'll try to test it later today and merge then. Let's react :wink:

**Comment by aarizkuren** [comment]
@aesedepece have you tested it? I think this issue is so important for the new users of loqui

**Comment by aesedepece** [comment]
Forgot to say: THANKS @mgp25 and @aarizkuren :100:

**Comment by Thalyn-** [comment]
Good job guys... Hope I could use it soon with the next update :)
