### ISSUE TITLE
[XMPP] loqui doesn't keep jabber account online

### ISSUE THREAD

**Issue by pravi** [loqui/im#516]
Even when autoreconnect option is selected, loqui can't keep me online.

Account status is yellow and only after I restart loqui I can go online.

Server is yax.im (i think they run prosody)
0.3.2a on zte open c, fxos 1.3

**Comment by ghost** [comment]
I have similar issues, sometimes restart Loqui IM does help

Sometimes i have to reconnect my mobile or wifi connection, other apps are offline, too (could be an Firefox OS issue or just an issue with the connection at all)

Maybe an error message during connection problems would be better than an yellow connection button

**Comment by ou-li** [comment]
I have the same problem. Running a prosody server.
ffos 2.0

**Comment by TitanNano** [comment]
I just setup a jabber account and I'm experiencing that too. I couldn't investigate it very much but it seems to me that the websocket server gets overloaded, drops the connection and loqui tries to reconnect. But the reconnect fails with a http 500 error and loqui does no further connection attempts.

**Comment by TitanNano** [comment]
this should be fixed with 656c9c6
