### ISSUE TITLE
[XMPP] can't receive Bolts 

### ISSUE THREAD

**Issue by ghost** [loqui/im#518]
I could send bolts from Loqui IM to a Pidgin client but i can't receive Bolts from a Pidgin client to Loqui IM

Is that a Loqui IM or a Pidgin issue?

Loqui IM v0.3.3a
Pidgin v2.10.9

**Comment by aesedepece** [comment]
You are right, Pidgin was never able to send Bolts to Loqui IM despite of being an advertised feature in Loqui's XMPP capabilities.

**Comment by ghost** [comment]
If someone else is still interested in that feature open a new issue or pull request.
