### ISSUE TITLE
Notifications with broke image link

### ISSUE THREAD

**Issue by jorrete** [loqui/im#52]
Hi,
On my ZTE Open ffos 1.0.1 (loqui pre-alpha v.0.0.11), notifications appears with broken image link instead an app icon or contact avatar.
The account used to test, doesn't have an associated avatar.
It should show an anonymous avatar or app icon on notifications instead a broken link.
Thanks for the app!

**Comment by aesedepece** [comment]
For some reason, despite of implementing default avatar, it keeps happening every time an image file route is assigned to a notification.
Nevertheless, when the contact has its own avatar, it recovers the base64-encoded image from `Store` and successfully show it.
So I think this has something to do with image file routes...

**Comment by aesedepece** [comment]
As read in MDN:

> One particular Firefox OS issue is that you can pass a path to an icon to use in the notification, but if the app is packaged you cannot use a relative path like /my_icon.png. You also can't use navigator.location.origin + "/my_icon.png" because navigator.location.origin is null in packaged apps. The manifest origin field fixes this, but it is only available in Firefox OS 1.1+. A potential solution for supporting Firefox OS <1.1 is to pass an absolute URL to an externally hosted version of the icon. This is less than ideal as the notification is displayed immediately with the icon missing, then the icon is fetched, but it works on all versions of Firefox OS.
