### ISSUE TITLE
WhatsApp auto reconnect problems

### ISSUE THREAD

**Issue by TitanNano** [loqui/im#522]
Actually this consists of two things:
1. this isn't really a bug rather than a UX problem. Whenever the app is in the background or the screen is turned off and the app has to reconnect, the "connected sound" should be played. However every time an app is in the background and tries to play a sound, the system will queue the playback until the user returns to the app. So for along time I thought that I wasn't connected before I returned to the app and just got reconnected. Of course this assumption was wrong, the sound just wasn't played until I opened the app. Can you please check if the app is currently visible and only play the sound if it is in the foreground? The current behavior leads to confusion.
2. Because I know that this app isn't completely stable I check every couple of hours if I'm still connected to WhatsApp. Most of the time I just experience the previous mentioned behavior. But sometimes I return to the app and everything seams fine. The account status is green checked. But if I tap a conversation, the app can't load the online status of my conversation partner. Then after a couple of seconds I hear a sound and the account indicator turns yellow, after some additional time (it always varies) an error notification pops up and tells me that the app was unable to connect. When the notification disappears the app reloads and connects successfully again. 
   It seams to me that the app isn't really aware that there are connection problems until I preformed an action like the fetching of the online status. Unfortunately I don't know the actual error, because I usually don't have my phone connected to the debugger when I hit this problem.

**Comment by TitanNano** [comment]
just wanted to bring this up again. This is a real problem, just now I had to determine that I missed a important message by about 1h 45min (thats the last time my contact was online in WhatsApp) cause Loqui didn't recognized that it wasn't connected any more. First entering a conversation made it aware of the disconnection.

**Comment by TitanNano** [comment]
I just did some tests and analyzed the data log in the console. I found two problems.
1. if there is no user interaction and the app is in the background the stream breaks (WhatsApp drops the connection?)  and no new data arrives. Only when a new stream write attempt (mostly the status change from unavailable to available) from Loqui results in a write error, the app does a reconnect. 
   So, two suggestions, try to catch the stream drop or maybe easier, regularly write something to the stream (request the contacts presence) so that WhatsApp doesn't drop the connection.
2. When my Peak isn't connected to the console, it constantly turns off the wifi after a couple of minutes, and back on when the phone gets unlocked. It didn't happen the entire time while the phone was connected, but I simulated the behavior  by manually turning wifi on and off. 
   If wifi gets turned off, loqui reconnects as soon as it recognizes that the stream got interrupted (as explained in 1).
   If wifi gets turned on, loqui wents crazy. I don't really know what exactly happens, but after the connection drop gets recognized, the app starts to send a lot of different messages, I didn't understand everything. but after some time the app just restarts and connects successfully.
   So maybe someone can investigate what exactly happens when wifi gets turned on and how this can be fixed...

**Comment by aesedepece** [comment]
Part 2 still remains unsolved

**Comment by aesedepece** [comment]
Let's track this at #359

**Comment by TitanNano** [comment]
@bdcomp maybe you should add #359 to the milestone...
