### ISSUE TITLE
Background empty at "Welcome to Loqui"-screen during first start

### ISSUE THREAD

**Issue by ghost** [loqui/im#525]
After installing Loqui on a device or simulator the background image is not shown at the "Welcome to Loqui" screen when Loqui IM is started for the first time.

**Comment by aesedepece** [comment]
I think it takes more time to load the image than loading the full app UI, so it's never shown.
When runned for the second time, the image is cached so it appears quickly.

**Comment by TitanNano** [comment]
Why is the image not stored in the app package?

**Comment by aesedepece** [comment]
The image is loaded remotely because we use it to get statistics and demographics about the app's usage.
