### ISSUE TITLE
Could you change the default image for an empty contact list?

### ISSUE THREAD

**Issue by marti1125** [loqui/im#53]
![2013-08-25-10-40-18](https://f.cloud.github.com/assets/223240/1022840/d6ee6e98-0db4-11e3-9bbf-2f2b4036da92.png)

**Comment by aesedepece** [comment]
Well, I've seen not everyone got the joke, so that pic will be dropped in next release :hushed:

**Comment by marti1125** [comment]
thanks :)
I found this message when loading all contacts

**Comment by Gioyik** [comment]
Is this necessary? I think that some fun is not bad.

**Comment by marti1125** [comment]
yes is necessary is  annoying .....
