### ISSUE TITLE
Visibly empty messages should not be sent

### ISSUE THREAD

**Issue by gargsms** [loqui/im#530]
If I type spaces '                            ' in the text box and send the message, it is delivered as is.
This should not happen.

**Comment by bdcomp** [comment]
@gargsms What is the behavior for this on over apps?

P.S. Space is not exactly empty message...

**Comment by gargsms** [comment]
@bdcomp Fixed the issue title.
AFAIK, WhatsApp, Facebook Messenger, GTalk do not allow only spaces to be sent.

**Comment by ghost** [comment]
What exactly is the problem to send only spaces to a chat? Why do other applications disallow that? And why should Loqui disallow that, too?

**Comment by gargsms** [comment]
@bobcanthelpyou I guess sending message with only spaces classify as spam.

**Comment by sergioad** [comment]
This can be used as add conversation function to add the contact to the recent conversations, I have used it on other IM clients like LINE or OpenWapp @Gamarus this is a good form to do that

**Comment by aesedepece** [comment]
Fixed by 995da0391d2e816914e513b70ae97f9e805f7814

**Comment by ghost** [comment]
@gargsms Is it really spam if someone what to impress himself with an 'empty' message?

**Comment by gargsms** [comment]
@bobcanthelpyou , I didn't get you properly.
If you meant to express yourself with a blank message, or maybe add a new person in the recent conversations, we can do that by sending just a simple '.'

The whole point of me putting this issue was because I slept over my phone and sent someone about 7 lines of gibberish, 3 of which were empty. :stuck_out_tongue:
