### ISSUE TITLE
Last message in chat overview screen is not the last message in the chat.

### ISSUE THREAD

**Issue by pzwart** [loqui/im#532]
Sometimes the message which is shown with a chat in the overview window is not the last message in the actual chat. As shown in the example, the 'hehe' message was sent at 08:46 and is shown in the overview but the last message was  'Poe, thanks!' at 09:47.  

I think it was caused when i turned the phone on in the morning and somehow the messages were received out of order because I noticed that the 'hehe' message arrived a second later than the other messages.  

The chat overview screen:
![sorting1](https://cloud.githubusercontent.com/assets/2669647/4361205/5e5ababe-4282-11e4-96ad-8adb2d1c3e2b.png)

The actual chat:
![sorting2](https://cloud.githubusercontent.com/assets/2669647/4361566/49e1a95a-4285-11e4-9a3f-81d2c15e97a5.png)

Tested on a Firefox Flame. OS version 1.3.0.0-prerelease. Loqui IM v0.3.2a

**Comment by TitanNano** [comment]
I can confirm that, I think it happens when messages arrive out of order. Loqui automatically sorts them but the last arrived message is not the latest one.

**Comment by lumimgardt** [comment]
Messages shown in preview are not shown in conversation.  Ie if i receive a message it is shown partly in the preview but wen i open the chat there's no new messege

**Comment by TitanNano** [comment]
@lumimgardt thats issue #719
