### ISSUE TITLE
support sharing links from browser via loqui

### ISSUE THREAD

**Issue by pravi** [loqui/im#534]
Currently it can only share via email app.

**Comment by ghost** [comment]
I tried that share function, i could choose Loqui IM within the share menu of the browser, but i can't use Loqui IM:

First an empty window
![addurl1](https://cloud.githubusercontent.com/assets/4523264/4456298/e3b0c74c-4888-11e4-9326-83b35aa32ac0.png)

Then i could choose an account:
![addurl2](https://cloud.githubusercontent.com/assets/4523264/4456299/e5052016-4888-11e4-99a4-f1a4075ceb4c.png)

Again an empty window:
![addurl3](https://cloud.githubusercontent.com/assets/4523264/4456300/ed1d6dc6-4888-11e4-9114-d7099cf6fa73.png)

**Comment by bdcomp** [comment]
Looks like something missing on the Loqui side.

@aesedepece Any idea?

**Comment by aesedepece** [comment]
That's what appears when you try to share something while Loqui is closed, so when the share activity inside Loqui is executed, the accounts haven't been loaded yet.

**Comment by TitanNano** [comment]
I experienced that too, could we just create a promise for the account loading to wait until we register the listener?

**Comment by ghost** [comment]
With the last fix i could share a link from the browser to Loqui correctly.

But if a account is deactivated i can't activate it within the account selection (not sure if that is a problem)
