### ISSUE TITLE
XMPP: input field for custom server does not appear at mucCreateForm

### ISSUE THREAD

**Issue by ghost** [loqui/im#539]
The input-tag for a custom server is at the wrong place and does not appear when i choose custom in the mucCreateForm

**Comment by bdcomp** [comment]
@bobcanthelpyou A screenshot will be appreciated.

**Comment by ghost** [comment]
@bdcomp 

choose 'custom' as server the input field is missing

![custom](https://cloud.githubusercontent.com/assets/4523264/4455243/c1c1122e-487c-11e4-987d-16ad212cec09.png)

should be fixed with #540 

![custom_fix](https://cloud.githubusercontent.com/assets/4523264/4455276/36983c94-487d-11e4-8e31-e152cb8494e2.png)

**Comment by bdcomp** [comment]
@bobcanthelpyou Thanks!
