### ISSUE TITLE
How to keep /src/index.html and /ubuntu-touch/www/index.html in sync?

### ISSUE THREAD

**Issue by ghost** [loqui/im#541]
There where some changes to the /src/index.html file lately 

But these changes where not applied for /ubuntu-touch/www/index.html

What should be different in the index.html for Ubuntu Touch?

**Comment by aesedepece** [comment]
Ping @Gioyik

**Comment by Gioyik** [comment]
I am thinking on way to keep those sync. I need to think a good way to develop for future platforms.

**Comment by ghost** [comment]
If someone else is still interested in that feature open a new issue or pull request.
