### ISSUE TITLE
multi-account

### ISSUE THREAD

**Issue by mautematico** [loqui/im#55]
I love loqui. And I wish it to be multiaccount.

**Comment by aesedepece** [comment]
Duplicate of https://github.com/waalt/loqui/issues/29

Anyway...  Good news! Loqui IM v0.1 will be released next week and it's multi-account.

**Comment by mautematico** [comment]
Great! :D

**Comment by aesedepece** [comment]
Closed by 7129fe9f3cc45f227e8303885cdcaae3b6400287.
