### ISSUE TITLE
how does Loqui get messages?

### ISSUE THREAD

**Issue by kramer65** [loqui/im#551]
Seeing that I'm interested in having Whatsapp on Ubuntu Touch, I was just wondering how Loqui gets whatsapp messages? Does the app poll the whatsapp servers (= slow and inefficient) or does Loqui employ its own server which polls the whatsapp servers for its users, after which it sends a push to the Loqui users? 

Any information on this would be welcome!

**Comment by aesedepece** [comment]
Loqui IM connects directly from the user phone to the WhatsApp servers via TCP sockets and listen for incoming messages. There's no need to poll :wink:

BTW there's already an effort to port Loqui IM to Ubuntu Touch, as you can see in our sourcecode:
https://github.com/loqui/im/tree/dev/platform/ubuntu-touch

**Comment by kramer65** [comment]
Awesome! I thought the port to Ubuntu was developed here: https://github.com/loqui/im/tree/ubuntu-touch , and since nothing was really happening there I figured that the Loqui2UTouch-effort was kinda dead..

I didn't know Ubuntu Touch was being implemented in the main source thouch. Would you have any information on how far the UTouch efforts are? Can it already be run on Ubuntu Touch, or is it still being worked on? Any more information on it would be welcome!

**Comment by nephilim1973** [comment]
We are 6 people, who bought a BQ Aquarius Ubuntu Phone. Very interested in getting LOQUI running on this device !
:-)

**Comment by kramer65** [comment]
@nephilim1973 - That is awesome to hear! I'm desperately waiting for Whatsapp support on Ubuntu Touch.
Note that [CODeRUS](https://github.com/CODeRUS) is also working on a Whatsapp client for Ubuntu Touch (a native Qt-version) for which he made a couple libraries:
- https://github.com/CODeRUS/libaxolotl
- https://github.com/CODeRUS/libwa

Maybe you can make use of them or learn from them.. :-)

Good luck with porting! I'll be cheering from the side! :-)
