### ISSUE TITLE
[Facebook] Messages are lost when connexion is bad

### ISSUE THREAD

**Issue by kit-ty-kate** [loqui/im#552]
If the connexion is bad (like on 2G) I don't receive new messages. Moreover, when I've again a good connexion, the messages are not fetched. It happens also with messages sent from another device.

Account type: Facebook
OS: Firefox OS 2.1
App status: up-to-date

**Comment by kit-ty-kate** [comment]
Is there someone who can confirm this ?

**Comment by uvox74** [comment]
I do. ZTE OPEN FFOS1.1

**Comment by uvox74** [comment]
I forgot to mention that The issue happens to me when using whatsapp

**Comment by ghost** [comment]
Have the same when using loqui with whatsapp on my zte open c ffos 1.3

**Comment by shokoshokoshoko** [comment]
same here (flame, ffos 2.0). I lose xmpp messages too!
