### ISSUE TITLE
"Message received" symbol / messages not send when wonky connection

### ISSUE THREAD

**Issue by ghost** [loqui/im#563]
It would be nice to have some sign that shows, if the message got actually send (official whatsapp does have such a feature), although i'm talking here for all kind of services.

It would be obsolete if messages would be sent ASAP instead of 'now or never'. 
Because if you have a wonky or no connection at all and try to send a message, it won't give you an error or a 'not sent' symbol. This will leave you in this awkward position of not knowing if your chat partner received your message or if it just vanished into the void, lost forever. (other chat clients for FFOS give you such a symbol that also functions as 're-send button'.)

FFOS 1.3 ZTE Open C

**Comment by TitanNano** [comment]
:+1: yes, it would be really nice to have such a feature.

**Comment by gargsms** [comment]
AFAIK, the lastAck line below the chats tell us if the message was delivered or not. But it is buggy. Also, there is not very clear distinction between the line that marks a bunch of 30 messages and the lastAck line.

It would be nice to have an indication of delivery. Maybe the same as the WhatsApp ticks, or some other form.
Also, WhatsApp now has the blue ticks which mark a message as read. 

Anyone implementing that?
I don't know how to get the JSON response parameters from WhatsApp servers. :disappointed: 
I will dig more, shouldn't be very hard.

**Comment by TitanNano** [comment]
#588 implements an message sent indicator:
- yellow message => trying to send the message
- red (default color) => message successfully sent
- gray with red border => failed to send the message

Note: If the message gets successfully sent but Loqui disconnects right after that and does not recive the sent ACK from WhatsApp, then the message still gets marked as failed. Eventually the message th
en changes to send when Loqui reconnects and receives the ACK.
