### ISSUE TITLE
[WhatsApp] Could not sent SMS (I had it working before)

### ISSUE THREAD

**Issue by 03927e9c** [loqui/im#565]
Hello, I started using Loqui several months ago and everything worked quite well -I only used WhatsApp- and in the same day I was chating perfectly I get an error, something like "authentication error". Tried disconnecting and reconnecting, but nothing, waited a couple of days to see if the problems gets fixed... nothing. Then I tried registering the account again, and that's when I get this message, even waiting more than two weeks.

Please help! Thanks!

**Comment by gargsms** [comment]
Did you use WhatsApp with the same number on some other device?
It can be an error in case you are trying to use more than one device at a time.

I would suggest you install a fresh version of Loqui and try again and see if it is resolved.

**Comment by sergioad** [comment]
I had this issue too, I do ot have the same number in other device, I have upgraded my Firefox OS rom

**Comment by 03927e9c** [comment]
Thanks for the replies. No, I do not have the same number in any other device and I forgot to mention that I also uninstalled and re-installed Loqui when I was trying to find a solution, but that didn't work neither.

**Comment by 03927e9c** [comment]
Nobody? Please I really need to fix this up!

**Comment by sergioad** [comment]
Same here, upgraded to FirefoxOS 2.1

**Comment by gargsms** [comment]
Seems like things have broken in the unstable builds of Firefox OS, 2.1 and 2.2
I will see if there are some leads into this.

For now, you can try using FxOS 2.0 It is stable.

**Comment by gargsms** [comment]
:grinning: Use my fork https://github.com/gargsms/im/tree/New-Version
Everything works with it. Plus you will get a few additional features that aren't merged yet.
It was due to the new WhatsApp version being rolled in. I am still not very sure why that was not a problem with older Firefox OS versions.
Tested on Firefox OS v2.0+

Source of fix: https://github.com/perezdidac/WhatsAPINet/pull/226

**Comment by aesedepece** [comment]
Hey @gargsms can you PR? Thanks.

**Comment by gargsms** [comment]
Yes, I will do that once I have verified that it works.
I tried in the emulators since I don't have Firefox OS 2.0 installed. I got the SMS sent message, but never received any SMS.
I need to try on a device.

**Comment by gargsms** [comment]
It works. Apparently not from an emulator but from a physical device.

Sadly I have multiple versions of Loqui installed now each having many chats to backup.
I will try to implement the backup and restore option at this weekend.

Sending a PR ASAP.

**Comment by 03927e9c** [comment]
Ok, sorry I don't get it. I have Firefox OS 2.0 simulator on my PC and I have this problem, are you saying your fork will solve it?

**Comment by gargsms** [comment]
I tried from simulators, both 2.0 and 2.1 but did not get any SMS even when I got the SMS sent popup.

I then installed it on a device and it worked. It simply did something in the background and I could use WhatsApp. No SMS, though.

@03927e9c try and see if this solves the issue completely. Worked for me (partially). We may need to apply some other fixes if it still persists.
Also, you can just use this repository now. All the changes have already been merged.

**Comment by 03927e9c** [comment]
Thanks for the help, but I'm a noob on this GitHub thing so I have two questions: how do I know your code is safe? And why people from Loqui haven't fixed this officially?

**Comment by TitanNano** [comment]
@03927e9c well this is how things get officially fixed here. @gargsms is a participant of this project and created the fix on his account. After he tested it, he created a pull request and @aesedepece merged the patch into the official code. Now the current code gets future tested and if everything works fine, a new package will be uploaded to the marketplace.

**Comment by 03927e9c** [comment]
I don't know how to intall it if it's not on MarketPlace, I tried reading the FAQ and Readme, but it doesn't say, I have the zip file but I don't know what to do with it?

**Comment by TitanNano** [comment]
@03927e9c at first you have to clone this repo. then you need to install grunt and run `grunt` in the repo root directory. After that, you can add (loqui repo dir)/dist/firefoxos as a packaged app to either the AppManager (< Firefox 35) or the new Web IDE (>= Firefox 35) and flash it to your device. To connect your device with the AppManager or WebIDE you need to enable USB debugging in the Developer Settings of your device.

**Comment by 03927e9c** [comment]
Any info on when the next version of Loqui will be released?

**Comment by gargsms** [comment]
I used #594 with an emulator (FxOS v2.2) 4 days ago and I got an SMS. But, when I installed the same code on the device, I did not get any SMS.
Today I flashed a new build to my Flame and installed the same code. It showed 'SMS sent', but no SMS till now.
There is WhatsApp v2.11.453 out now https://github.com/mgp25/WhatsAPI-Official/blob/master/src/token.php , and I cannot test if it is a problem with new B2G release on devices or with the API **because I need to wait 2 days to request a new code**.

@aesedepece Can you test it? Or tell me a method by which I can use WhatsApp interim. I am experimenting till then.

**Comment by aesedepece** [comment]
I get the same issue with 2.11.452 (message sent, but never recieved) in both simulator and actual device.
Let's try 2.11.453 and see what happens...

**Comment by gargsms** [comment]
I happened to receive a SMS when I sent it from emulator. Weird enough.

What if I try to cURL all 1,000,000 possible codes using the API? :stuck_out_tongue:

**Comment by aesedepece** [comment]
@gargsms Your deviceID will be banned after a few failed attempts :stuck_out_tongue_closed_eyes:

**Comment by aesedepece** [comment]
Ok, I got the SMS with both 2.11.452 and 2.11.453 from actual device but only for one of my testing lines from Pepephone carrier, but never received it on another one from Movistar.

**Comment by achintangal** [comment]
Same error here as well. Unless, I am wrong it looks like its the same case with other whatsapp clients too, like openwapp and connecta2

**Comment by 03927e9c** [comment]
Yeah I tried also ConnectA2 and I get something like "you are having a BLOCKED status, contact us at...."

**Comment by 03927e9c** [comment]
Okay so I just installed the latest version from Marketplace (v0.3.4) and I get exactly the same error. Was this supposed to be fixed?

**Comment by 03927e9c** [comment]
Hello? Anybody there? Why am I not getting any response? This bug hasn't' been fixed ¬¬

**Comment by TitanNano** [comment]
I tried it about two weeks ago after it got fixed and it worked for me.

> Yeah I tried also ConnectA2 and I get something like "you are having a BLOCKED status, contact us at...."

Did you do something about this? you're probably still blocked.

**Comment by 03927e9c** [comment]
Thanks for the reply, well I haven't done anything to get blocked, just random chatting with friends, not even sending videos or stuff, so I figured it would be another problem, not just me being blocked even more considering someone said he gets the same error that I get even in the other apps.

I'll contact people from ConnectA2, just to rule it out, but I don't think I'm blocked, at all.

**Comment by TitanNano** [comment]
Well I ca't tell either if you are blocked or not. But I received the SMS successfully multiple times.

**Comment by gargsms** [comment]
The thing is that no numbers get blocked by WhatsApp. I could not receive any messages from any WhatsApp distributions (not even the official ones) for about two days. The error never gave any try after time. So, I waited for a few days (around 4 I guess,) and then I could receive the SMS from https://wha.tools as well as from WhatsApp for Android.
I have to use WhatsApp from an Android VM for now as Loqui doesn't work properly for me.

**Comment by gargsms** [comment]
Works for me.
I used the most recent version from the Marketplace. Should we close this bug?

The Private Messages don't work, though. Any updates on the encryption thing?

**Comment by 03927e9c** [comment]
Still doesn't work for me here. Same as usual.

**Comment by gargsms** [comment]
It worked just one day. Repeating the same errors now. :(

**Comment by petzichen** [comment]
Yes... I can't get the sms, too. I flashed my flame again to ffos 2.0 and cant't log in to whatsapp :-/

**Comment by sergioad** [comment]
wee are banned because WhatsApp does not permit flashing nor cellphone change, they are so restrictive

**Comment by petzichen** [comment]
Whaa.... -.- But why it doesn't work on Alcatel One Touch Fire, too? It isn't flashed (only offical update to ffos 1.3 from Alcatel)..? O.o

**Comment by sergioad** [comment]
if you miss the files this is the ressult, also if you unninstall your WhatsApp client and re-install it, they does not care about that, they will block you

**Comment by 03927e9c** [comment]
Hmm, what does "flashed" stand for? What does it means?

Besides... I was using it with out a problem and all of a sudden stopped working, I never re-installed nothing, then I started re-installing to try it out.

**Comment by petzichen** [comment]
@03927e9c The 'Mozilla Flame' needs to be flashed...
https://developer.mozilla.org/en-US/Firefox_OS/Developer_phone_guide/Flame

I was using it without problems, too until 29 Dec... But now I can't get the sms (in all whatsapp-clients on ffos 2.0)... :-1: 
Other services are working perfect... (Jongla, Telegram, ...)
And the Alcatel OneTouch Fire isn't flashed... :o

**Comment by aesedepece** [comment]
All unofficial APIs and clients have broken registration at the moment as they changed something in the registering protocol on the server side.
We all are still trying to figure out how to solve it.

**Comment by cmeerw** [comment]
BTW, just tried registering in a simulator (with the loqui dev version) - got the SMS, but it didn't validate. Went back to the registration screen and selected verify via phone call - didn't get a phone call, but was successfully logged in...

**Comment by petzichen** [comment]
ConnectA2 and OpenWapp is working now again. I hope Loqui IM get an update in next time, too... :-/ It is my featured social app... :o

**Comment by TitanNano** [comment]
@petzichen the upcoming v4 branch will fix this issue.

**Comment by aesedepece** [comment]
Fixed in 8b2f79aa2c6374743c49c1ffff024145c334b638

**Comment by bordofr** [comment]
My whatsapp started having problem with my authentication please help.me

**Comment by bordofr** [comment]
If i send a msg it does not go true and a red box jux covers the msg

**Comment by JordanSBen** [comment]
Im using a Zen 105 Fire. I actually had Loqui IM working before i reset my phone. And after I installed it again, I keep on getting Authentication errors. The SMS wont go through.

Please Help!!!
Thanks

**Comment by narasimha6666** [comment]
I am using latest WART version, its throwing either bad_token or old_version. Please let me know, how to generate password.. struggling from three days.

**Comment by nfsprodriver** [comment]
I'm sorry to tell you this, but this is the wrong place to talk about. I 
think the WART project has been discontinued. But if you want to try, 
check, whether the token from here are working.


-- 
Mit Dekko von meinem Ubuntu-Gerät gesendet

**Comment by narasimha6666** [comment]
Thanks for the quick reply. Can you please let me know the below details for whatsapp 2.17.24 version.
I need signature, classesMd5, and key2 values. Thanks in advance.

**Comment by nfsprodriver** [comment]
You can find some values here: https://github.com/jlguardi/yowsup/blob/master/yowsup/env/env_android.py But it's not 2.17.24 yet. I can't view all forks of yowsup so there may be newer values in other forks.

**Comment by narasimha6666** [comment]
Hi @nfsprodriver ,

Thanks a lot, i could able to generated the password. But i am getting "Auth response error", can you please let me know how to solve this issues. Thanks in advance.

**Comment by UmairAnjum** [comment]
Hello Guys
I am tying to register new number from WART using C# Code but constantly getting Bad Token Error
Please help! Thanks!
