### ISSUE TITLE
Adding Whatsapp account  could not send SMS

### ISSUE THREAD

**Issue by Shyamacharan** [loqui/im#568]
When trying to add my Indian number as a WhatsApp acount, I get an error saying that the SMS could not been sent. I opened the console and no much information is shown.

I regularly use the same number in a different phone with WhatsApp.

**Comment by gargsms** [comment]
https://github.com/loqui/im/issues/565#issuecomment-63270371

Here, fixed it. :smile:

**Comment by TitanNano** [comment]
this can be closed, it's a duplicate of #565 anyway.
