### ISSUE TITLE
hide conversations from chats list

### ISSUE THREAD

**Issue by TitanNano** [loqui/im#575]
In the past I experienced that I have conversations in my chat list I don't want to show up anymore, but don't want to delete the messages I have sent to that contact or received from them.
I don't know if other Clients implement such a feature, but I know it from other messaging platforms. 
#### hiding a Conversation

the user navigates to the contact page of the chat partner he wants to hide. There he can enable the "hide conversation" switch.
Now the Conversation does not show up in the chats list anymore, but the message log can still be accessed by selecting the specific contact from the contact list.
#### unhide a Conversation

the user again navigates to the contact page. Here he can disable the "hide conversation" and this will bring the conversation back to the chats list.
#### automatically unhide a Conversation

if a new message from a hidden Conversation is received or the user sends a new message to that conversation, the chat turns visible.

What do you think of this feature? If everyone agrees with it, I would like to implement it.

**Comment by gargsms** [comment]
@TitanNano I was thinking of implementing the delete messages feature over this weekend because I need it. Maybe we can implement this as well. It shouldn't be that hard after all.
Anyway, what does the mute conversation feature do? Is it not the same?

Also the Import and Export features are missing. Got a lot to do this weekend. :smile:

**Comment by TitanNano** [comment]
@gargsms no, the mute feature mutes notifications. This would just hide them from the chats list, you still receive notifications for the conversation. If you have many conversations but barely talk with some of you contacts, this could be useful to clean up your conversations list.

You mean to delete a single message from a conversation? That would be nice.

I would be glad to implement this feature, I just wanted to know if there are any objections. I'm going to implement it in the next days. If anyone wants to add or change something on my small spec, I'll take it into account.

**Comment by gargsms** [comment]
Oh, I never used the Mute feature.

Yes, I meant the ability to select messages that you want and delete them. It is there in almost all client AFAIK. I just don't know how Loqui missed it.

The UI that I am thinking of will consist of a tasks button that once tapped will display a list of common options that can be applied to a chat.
![loquiim-tasks](https://cloud.githubusercontent.com/assets/5238955/5125089/33bc0370-70e6-11e4-9bb2-c57afaf25105.png)
The tasks I think to include as of now are
- Delete Messages
- Mute Conversation (moved from the contact info)
- Clear Chat
- Email Conversation ( would need a bit of research )
- Block Contact (there is no way to do so for now. Plenty of research needed)

If the user selects to Delete Messages, checkboxes will appear adjacent to the messages and the typing area will be covered by confirmation buttons to Delete or Cancel.
![loquiim-deletemessages](https://cloud.githubusercontent.com/assets/5238955/5126426/e34d3a28-70f2-11e4-9f38-a1e30227530a.png)

This and a few other things coming this weekend. Hopefully.

**Comment by TitanNano** [comment]
:+1: I think that are great improvements. But I think Mute Conversation, block contact and the new hide conversation could remain in the contact info. Instead we could move the file sharing (video, audio, image, location) To your new tasks menu, remove the plus menu and add an emoji button on the left side of the text box... What do you think of that?

**Comment by gargsms** [comment]
Seems reasonable.
Let's see what others suggest over time.

@aesedepece @bdcomp Any suggestions?

**Comment by Gioyik** [comment]
Hi,

I am agree with the feature of select messages and delete it from list. But not sure if the icon position is the best in terms of UX, on the plus button can be positioned correctly. If the list of features that opens the plus button is large vertically, we can set a vertical scroll and get a nice UX for that list of features.

If is posible to have images or something that show more clear the UX a final design, would be better to comment and give a clear point of view.

Keep the good work!

**Comment by gargsms** [comment]
Hey @Gioyik 

I thought of this earlier.
![loquiim-tasks-new](https://cloud.githubusercontent.com/assets/5238955/5178210/ceef9cda-748d-11e4-85e1-502fb3cdf53a.png)
But now I feel that the menu seems orphaned and hanging at a random place.

Also, I am not very sure what options I should keep in the menu. @TitanNano suggested to have an emoji button separately, which I guess will be awesome as people use them the most.
If we move the media options as is to this menu, it will become quite large vertically. Or we can group them in a Media option which further displays another submenu, but that will be one too many taps.

Where would you like the menu to be positioned? Over the plus button?

**Comment by aesedepece** [comment]
This was fixed long time ago thanks to @TitanNano . Closing now :smile:
