### ISSUE TITLE
A little lag loading contacts

### ISSUE THREAD

**Issue by Gioyik** [loqui/im#58]
In the new version there's a problem when you log in by first time (i used my GTalk account). It lag for a moment while it loads all the contacts. This does understand that the application has stopped or has stopped working. If you touch something else it doesn't respond.

**Comment by aesedepece** [comment]
I'll take a look with the profiler to see if there's a memory leak or something. Thanks for reporting ;)

**Comment by v3rlain3** [comment]
Se puede reportar bugs en español?, ya que no domino mucho el English

**Comment by aesedepece** [comment]
@v3rlain3 ¡Adelante! No te preocupes por la cuestión lingüística, para nosotros también es más fácil en español ;)

**Comment by Gioyik** [comment]
This happens when you had set up multiple accounts, and more lag if you have a lot of contacts. Probably this could be solved with an integration of WebSockets + SimplePUSH in order to save battery when multiple accounts are set up.

**Comment by Gioyik** [comment]
Este problema ya se ha mejorado con los ultimos cambios, no del todo, pero se ha recuperado la estabilidad de antes.
