### ISSUE TITLE
Contacts disappear

### ISSUE THREAD

**Issue by Gioyik** [loqui/im#59]
I had loaded all my contacts, if i lost the internet connection my contact list disappear too. Could we make something to have a king of "cache" for the contact list, and to refresh it when connection is back?

**Comment by aesedepece** [comment]
Contacts list is always loaded from asyncStorage, indeed. You may take a look at `App.accountsCores[0].roster` to see if it was stored properly.

**Comment by Gioyik** [comment]
I try it again and it is not a problem, is working as expected.
