### ISSUE TITLE
[WhatsApp] Messages from Android not working

### ISSUE THREAD

**Issue by moritzbuhl** [loqui/im#598]
Hi, I am using the newest version of Loqui IM (I just downloaded it from the repo) with Boot2Gecko 2.0.0.0-prerelease on a ZTE Open C. And I am having Issues with receiving messages from Android clients. I can receive pictures and sounds. And I can receive group messages. I can receive messages sent by an Iphone. 
![4Android](https://cloud.githubusercontent.com/assets/5376102/5239220/5a1a9008-78da-11e4-95ff-ed02e5429dfc.png)
![B2G](https://cloud.githubusercontent.com/assets/5376102/5239222/5ed401ec-78da-11e4-84c3-ef2003e7e732.png)
![B2G](https://cloud.githubusercontent.com/assets/5376102/5239223/60575b0e-78da-11e4-9239-629603600c80.png)
![Apple](https://cloud.githubusercontent.com/assets/5376102/5239224/64887794-78da-11e4-8111-5776a6d772a4.png)
![B2G](https://cloud.githubusercontent.com/assets/5376102/5239225/654dee98-78da-11e4-9df1-61700b5cf68f.png)

**Comment by aesedepece** [comment]
It could be related to Android's offical WhatsApp starting to encrypt messages. Let's investigate what's happening...

**Comment by gargsms** [comment]
There is this whole big discussion going on over the WhatsAPI official repo.

https://github.com/mgp25/WhatsAPI-Official/issues/109

Time to leave WhatsApp now. :frowning:

**Comment by moritzbuhl** [comment]
How are the devices talking to IOS then? Can't we tell Coseme to be an Iphone?

**Comment by gargsms** [comment]
iPhone clients are not encrypting the messages. The Android ones are.

CoSeMe can be anything. It is awesome.

**Comment by moritzbuhl** [comment]
Is it possible to imitate an Iphone client? And if it is, how?

**Comment by gargsms** [comment]
@GorgonzolaPasta The problem is in **receiving** the messages. Since the messages are encrypted, the library can't decipher it and you receive something that you can't read.

The messages you **send** are delivered just fine (because they are unencrypted) as I can see from the pictures above.
This problem is only with the newer WhatsApp clients, after 2.11.432 I guess.
The iPhone clients haven't got the encryption updates yet, so they send messages in plain text which are displayed correctly.

**Comment by moritzbuhl** [comment]
Ok. But if it is the TextSecure encryption, can't you take parts of it from the TextSecure Chromium Implementation?

**Comment by mgp25** [comment]
For now only Android clients is using encryption, other platforms will join that encryption soon. There is already a lib in c and python, so it will be easier for you to implement that. The hard part for us is to implement that library in php, that's why is taking us more time.

During the registration you should send 200 preKeys and 1 secretKey to WA Server, from then on you will receive encrypted messages. When you are going to chat with someone, the first message its send in plain text, then you will request his key to encrypt the messages to him.

They are using Curve25519 and Ed25519 for keys and signing, and axolotl for encrypted sessions.

Actually, you can avoid receiving encrypted messages and receive all in plain text if the number has never been registered with the WhatsApp client before.

**Comment by gargsms** [comment]
@mgp25 Link to the library? I could find the Java implementation of TextSecure on GitHub.

What do you mean not registered with WhatsApp client? Does registering with the API qualify as registering with client? Or can we make CoSeMe to emulate iPhone client behaviour thereby receiving plain text messages?

**Comment by mgp25** [comment]
@gargsms search for curve25519 and ed25519. I mean that the number is not registered in the WhatsApp client before, if you are using your number with loqui or any API and that number was registered before in the WhatsApp client then you will receive encrypted messages, if not was previously registered, then you will receive messages in plain text.

**Comment by gargsms** [comment]
@mgp25 What about emulating iPhone client like @GorgonzolaPasta suggested?

It seems likely that iPhone clients receive plain-text messages because they can't send encrypted ones. It can be a temporary solution for the time being.
We will see into the two libraries you suggested. :disappointed: I have exams this week.

**Comment by aesedepece** [comment]
Python Axolotl → https://github.com/rxcomm/pyaxo
Curve25519 + Ed25519 → http://www.flownet.com/ron/code/fast-djbec.js
Let's take a look at them and try to port/adapt them to client javascript.

**Comment by mgp25** [comment]
Emulate iPhone its just the same only you need to change user agent and version, i dont recommend that as its not a solution to this and soon will receive encrypted messages. It will be easier to you to implement that here as there is more support for low level languages, we have to do our own lib. But we got it working using the client data!

Don't worry i also have exams in university xd

**Comment by blaazetech** [comment]
@mgp25 i can help you with PHP coding, let me know.

**Comment by mgp25** [comment]
@blaazetech if you know about crypto feel free to contact with me.

**Comment by CharlesOkwuagwu** [comment]
@mgp25 Could you start from here? https://github.com/lt/PHP-Curve25519

**Comment by SikiFn** [comment]
@CharlesOkwuagwu we already know about this..  But it is not enough at all.. Still many many code to be written..

**Comment by CharlesOkwuagwu** [comment]
@SikiFn there are some "complete" .net libs for curve25519 

If you (or @mgp25) could give us a little heads up on what you have successfully done/are doing so far concerning the <enc>,,,</enc> messages (in PHP), we could all at least begin tying things out with WhatsAPINet and some variant of curve25519 for .Net

The collective effort might help speed things along ... just a thought.

Regards.
Charles.

**Comment by CharlesOkwuagwu** [comment]
@SikiFn  just saw your other reply.
https://github.com/mgp25/WhatsAPI-Official/issues/109#issuecomment-65223082

Thanks.

**Comment by vlnsnewton** [comment]
Hi All.. Please help

I am using https://github.com/mgp25/WhatsAPI-Official in php

and for receiving messages i am using following code:

$w = new WhatsProt($userPhone, $userIdentity, $userName, true);
$w->eventManager()->bind("onGetMessage", "onMessage");
$w->Connect();
$w->LoginWithPassword($password);
while($w->PollMessage());

But i am getting following encrypted message in browser:

tx  stream:features
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  /stream:features

tx  <auth mechanism="WAUTH-2" user="918010315455"></auth>

rx  <start from="s.whatsapp.net"></start>

rx  stream:features/stream:features

rx  <challenge>�����Oz_o��h���=</challenge>

tx  <response>hM�'����E'M7-{5J������S���'A��e6</response>

rx  <success t="1424088088" props="4" kind="free" status="active" creation="1421304049" expiration="1452840049">J�.a�ֹ���+ճ|���</success>

tx  <presence name="newton"></presence>

rx  <message from="919717474431@s.whatsapp.net" id="1424088032-2" offline="0" type="text" t="1424088088" notify="vlns newton">
rx    <enc v="1" type="pkmsg" av="Android/2.11.514">3���!��X�}{}�P\XyT7�Z^ �]�8xP����!q�b�������%�1��w®�!%|{ͨ�֧>"B3 !<�-pD���ϧ��C�W�qtH�&-�[    �WD��/("�E�J;���o��O>��aCcCE(Ψ��0</enc>
rx  </message>

tx  <receipt type="read" to="919717474431@s.whatsapp.net" id="1424088032-2" t="1424087845"></receipt>

rx  <ib from="s.whatsapp.net">
rx    <offline count="1"></offline>
rx  </ib>

rx  <presence from="918010315455@s.whatsapp.net"></presence>

rx  <presence from="919717474431@s.whatsapp.net"></presence>

rx  <ack from="919717474431@s.whatsapp.net" id="1424088032-2" class="receipt" type="read"></ack>

Please help me. @mgp25 

![encryption](https://cloud.githubusercontent.com/assets/10544407/6211659/7fac8f50-b602-11e4-8bc9-f17968a0702b.png)

**Comment by mgp25** [comment]
@vlnsnewton Please ask it in its proper repository: https://github.com/mgp25/WhatsAPI-Official

**Comment by ghost** [comment]
This doesn't seem to be an issue anymore. Working perfectly fine with the new v0.4 :)
ZTE Open C FFOS 1.3

**Comment by aesedepece** [comment]
Yes, it should be working as the UA we are using now is from Nokia S40 and thus encryption is not featured and incoming messages should be sent in plain text.

**Comment by mahmoudelbaz** [comment]
Dear all for c# I have the same problem any recommended  solutions wi be appretiated
