### ISSUE TITLE
Problems with scrolling

### ISSUE THREAD

**Issue by Gioyik** [loqui/im#60]
Este lo voy a escribir en Español para poder hacerme entender mejor.

Cuando tienes toda la lista de contactos completamente cargada, si deslizas hacia abajo o hacia arriba por mas de dos segundos, podria decirse que es un dislizado largo, abre la pagina de perfil del contacto, en donde se encuentra su informacion y si quieres borrar los chats con este contacto. Se comporta como si yo hubiese seleccionado el contacto por varios segundos (long tap), cuando yo lo unico que hago es un scroll para ver quien esta al final de mi lista de contactos.

Ademas de eso una vez que me aparece la pagina de perfil del usuario con el efecto del scroll/delizo antes mencionado, doy atras, hago scroll/deslizo de nuevo y este efecto desaparece, ya no se abre la pagina de perfil del usuario de nuevo con los delizados/scroll largos. Ademas de eso si intento hacer un seleccion sostenida (long tap) para que me aparazca de nuevo la pagina de perfil del usuario como tiene que ser y poder eliminar los chats y demas cosas, no hace nada. Si toco/selecciono en la parte inferior mi foto de perfil para que apareza otra pagina con detalles acerca de mi cuenta, tampoco funciona. Si toco en el menu principal, para agregar otra cuenta o en el boton de configuracion (el primero), tampoco hace nada.

Todo indica que una vez que haces el scroll/deslizado primeramente mencionado, se desabilita la navegacion entre <section> dejara de funcionar.

Puede alguien confirmar esto?

**Comment by Gioyik** [comment]
Bueno, he probado con otro telefono, en la version 1.3 y el problema con el scroll/deslizado largo persiste. Sin embargo sigue funcionando la navegacion entre <section>, alli si selecciono algun otro elemento despues de este efecto del scroll/deslizado, si me lleva a una page distinta. Puede que haga falta hacer debug para ver que pasa en realidad. Con el App-Manager ya es posible hacerlo desde el telefono :smile:

**Comment by aesedepece** [comment]
El problema con el swype+hold en realidad se trata de un bug de QuoJS, este en concreto → https://github.com/soyjavi/QuoJS/pull/67

Yo mismo lo arreglé hace meses pero debe de haber habido alguna regresión. Voy a hacer un fix en el instante.
