### ISSUE TITLE
[WhatsApp] can't keep connected

### ISSUE THREAD

**Issue by TitanNano** [loqui/im#600]
I wasn't in WhatsApp all day and now I just had to detect that i wasn't connected any more. I reconnected but Loqui is unable to keep the connection. It connects but already drops the connection really quickly just to reconnect. I don't know thats going on. everything worked fine when I went to bed last night.

I put a logcat output here: https://etherpad.mozilla.org/d8l5cFsNn8

Does anyone else encounter that problem too?

**Comment by cmeerw** [comment]
Seeing the same thing here...

**Comment by gargsms** [comment]
I did encounter the same a long time earlier. Now, I don't have WhatsApp anymore because my number seems to be blocked. :stuck_out_tongue_closed_eyes: 

Restarting my data, or Wi-Fi, and the phone worked fine for me.

**Comment by TitanNano** [comment]
I restarted my phone multiple times and switched from Wifi to mobile data and back. Does not work

**Comment by cmeerw** [comment]
Strangely enough, it appears to be fine again for me... Nothing has changed (just left the app stopped for the past hour).

**Comment by TitanNano** [comment]
okay unfortunately I uninstalled the app and tried to re auth at whatsapp
what didn't work either... I'll see if I get it back to work now...

2014-12-02 20:37 GMT+01:00 Christof Meerwald notifications@github.com:
