### ISSUE TITLE
[WhatsApp] "I have a code" verify button does not work

### ISSUE THREAD

**Issue by TitanNano** [loqui/im#602]
I already got a new code, but if I select I have a code and enter my phone number and code nothing happens. It seems like there is no event listener for this button anymore...

**Comment by moritzbuhl** [comment]
Had the same Problem. Just resent the code.

**Comment by TitanNano** [comment]
the problem is I don't receive any new codes :-/

**Comment by aesedepece** [comment]
This is fixed in v4 branch to be merged soon. Thanks for the feedback.
