### ISSUE TITLE
[XMPP] can't connect to websockets.loqui.im or bosh.loqui.im

### ISSUE THREAD

**Issue by TitanNano** [loqui/im#603]
Today I set up a XMPP account at duckgo.com and tired to login with Loqui. But when ever I try to add my account I get either `GET https://websockets.loqui.im/         [HTTP/1.1 101 Switching Protocols 462ms]` or when I change the host to https://bosh.loqui.im I get an `<body xmlns="http://jabber.org/protocol/httpbind" condition="bad-request" message="Invalid XML" type="terminate"/>`

**Comment by aesedepece** [comment]
I changed the BOSH/WS server yesterday, so this could happen because of lazy DNS propagation.
Please check if the issue still remains and if so I'll take a further look into it.

**Comment by TitanNano** [comment]
I still can't connect to the websocket :-/. Still getting the same message...
