### ISSUE TITLE
Better "welcome" screen.

### ISSUE THREAD

**Issue by FabianOvrWrt** [loqui/im#607]
The welcome screen looks really bad, so I took the new icon (also made by me) and made a better version.

![background](https://cloud.githubusercontent.com/assets/6712155/5087374/650b582c-6eed-11e4-902d-31c6c70e5333.jpg)

It's qHD and looks really better imo.

Also, to the index.css you should remove the transparent background [line 87, background-color from rgba(0, 0, 0, .7) to transparent].

**Comment by TitanNano** [comment]
You can create a pull request if you like to commit your work

**Comment by FabianOvrWrt** [comment]
Yes, I will. But I have one question.
Do I need to put my image inside the pull request or somebody will overwrite the old image (http://loqui.im/img/background.jpg) with this new one?

**Comment by aesedepece** [comment]
I will replace the file soon. Thanks @FabianOvrWrt !

**Comment by aesedepece** [comment]
Done! Thanks again @FabianOvrWrt !
