### ISSUE TITLE
Information in login fields saved

### ISSUE THREAD

**Issue by Gioyik** [loqui/im#61]
I log in with my account information (user and pass) and when i click on "Add another account" it shows me the page again to put the info (user and pass) for my new account but the fields are not empty, it had the data of the previous account that i added at first. Could be great to clear the info that you put in the fields once you log in, What you think?

**Comment by aesedepece** [comment]
Sure, I think the behaviour you described is the correct one.

**Comment by aesedepece** [comment]
Fixed by a5d72fdcfa9b8bc7d3b7956a03c85a15b1ec9769
