### ISSUE TITLE
[XMPP] send message even when contact is offline

### ISSUE THREAD

**Issue by pravi** [loqui/im#615]
Currently messages are sent only if the contact is online (messages are shown below the green line). If the contact's server supports offline messages, loqui should send the messages so even if I'm offline when the contact comes online again they will see the messages sooner. Some servers may (if not, it should) even push the messages even when offline using websockets.

**Comment by TitanNano** [comment]
hmmm no, I already sent messages to offline jabber accounts and they arrived when they went online...

**Comment by TitanNano** [comment]
just tested it again. Works perfectly fine for me.

**Comment by pravi** [comment]
@TitanNano so is it a notification issue? Did you try to be offline after you sent the message to offline contacts? Can some other visual notification be used in case we have sent the message already? Currently it shows the messages below the green line. May be add another color line for messages we have sent but not read/acked by the contact.

**Comment by TitanNano** [comment]
Actually as far as I know we don't have any acks for XMPP. Messages I sent are always displayed below the green line until we receive a message from the contact. #610 adds visual feedback if it was possible to send the message, but that still does not indicate that the contact also received the message.
I just did an other test, seems like strophe automatically resends message as soon as the user or the contact is online again.

**Comment by pravi** [comment]
http://xmpp.org/extensions/xep-0184.html implements message delivery receipts. I think loqui should implement this for better reliability of message delivery.

**Comment by TitanNano** [comment]
yes, we definitely should do this.

**Comment by aesedepece** [comment]
Loqui supports XEP-0184 since https://github.com/loqui/im/commit/22a9a88e0f15c0e40864aa6a0e416b921c66840f (May 25)

**Comment by TitanNano** [comment]
Okay, sorry for that confusion. then just my jabber client on my Laptop does not send the acks...

**Comment by TitanNano** [comment]
@aesedepece btw, does XMPP and loqui support a sent / "received by the server" ack? I couldn't find anything in the connector, but I'm not sure if I'm overlooked something....

**Comment by TitanNano** [comment]
So can we close this then?
