### ISSUE TITLE
Add a default avatar

### ISSUE THREAD

**Issue by Gioyik** [loqui/im#62]
When you add a new account, Loqui shows the profile image of the account, but if the account doesn't have an image, it shows a little white circle that means no image. Could be great to add a simple default avatar for images that doesn't have one.

This can be a complement of issue #52

**Comment by Gioyik** [comment]
This issue is solved by me :P 

@aesedepece could you check the commit 23f312bf74b7b01f5017d3708f4e527c1338d133 and see if you agree to close this issue?

Regards,
Gio

**Comment by aesedepece** [comment]
Nice! I have made only a small amend concerning tabbing  b9430b7cd46742a8f0de7dfa45361e5e2f6f535e

Ok to close it ;)
