### ISSUE TITLE
[Whatsapp] registration fails

### ISSUE THREAD

**Issue by ghost** [loqui/im#622]
Registration instantly gives an error-message.
Sms-registration: "Could not send SMS"
Phone-call-registration: "could not call your number"
tested with wifi & celldata.
Bug still persistent after reinstall of app an phone reboot.
German number (+49).
ZTE Open C [1.3].
Loqui.im 0.3.4a

had loqui working 2 months ago on same device, with same number. Used other whatsappclient (and still do) in the meantime.

**Comment by TitanNano** [comment]
you can't use more than one client at the same time.

**Comment by ghost** [comment]
I am aware of this. But usually, the currently used client would just stop working.

**Comment by TitanNano** [comment]
Okay. I never tired it. There are currently problems with the registration,
but you could connect your device with the webIDE and take a look at the
http request that is sent for requesting the SMS or phone call.

2015-01-17 19:29 GMT+01:00 JayVii notifications@github.com:

**Comment by ghost** [comment]
not too sure on how to do that. But I just took a look at the console-output in the app which says:
[object Object]
Could not sent phone call,Reason:,no_routes,with DID,kk0zuqe5jh

Not sure of that might help.

**Comment by gargsms** [comment]
The registration process fails on Loqui except for a few surprising times.
However, I was able to receive the registration code with OpenWapp on every try. OpenWapp doesn't work after the registration, though.

Tested on Flame with Gaia 2.0 production build.

**Comment by aesedepece** [comment]
I'll push this incoming week a new v0.4 branch where registration is working at last.

**Comment by gargsms** [comment]
The CoSeMe used in OpenWapp is using 2.11.453 as the version. I guess the no_routes error is related to us passing 000 as MCC and MNC.

OpenWapp uses MozMobileNetworkInfo and MozMobileConnectionInfo APIs to find the correct MCC and MNCs. Weirdly enough, the MDN pages for these APIs say that they are available only to Internal apps (which OpenWapp certainly is not), but OpenWapp uses them somehow.

@aesedepece I tried that in Loqui but the APIs were not available for us. How is OpenWapp achieving this privilege escalation?

**Comment by TitanNano** [comment]
maybe we should update our coseme too, the official repo has a some new updates.

**Comment by aesedepece** [comment]
I'll try to push the new branch later today. It makes use of the last CoSeMe version with updated tokens and S40 registration params.

**Comment by ghost** [comment]
For me, registration in all 3 clients (Loqui IM, OpenWapp, Connect A2) isn't working at all.
FireFox OS 1.3

**Comment by cmeerw** [comment]
Just for the record, registration didn't work for me at all yesterday (Loqui and OpenWapp - got no_routes error), but is working fine for me today (Loqui and OpenWapp). So not sure if mcc/mnc settings have anything to do with it...

**Comment by ghost** [comment]
Hm, did you change anything else? Rebooting the phone or something? Are you running FFOS 1.3 or a dev-version?

**Comment by cmeerw** [comment]
@JayVii I have actually done the Loqui registration test in a Firefox OS 2.1 simulator on my laptop (I have restarted that one, but nothing else has changed between yesterday and today).

@aesedepece I was actually working on syncing to the latest coseme version myself, there is a branch sync-coseme-with-upstream in cmeerw/im - testing it yesterday didn't seem to work, but it is working now... Are you working on more fundamental/additional changes?

**Comment by cmeerw** [comment]
@gargsms There is a mobilenetwork permission (Obtain mobile network information (MCC, MNC, etc.)) that can be requested by privileged apps according to https://developer.mozilla.org/en-US/Apps/Build/App_permissions - but looks like the MDN pages are a bit inconsistent as the paged linked to then says "internal apps only"...

**Comment by ghost** [comment]
Seems to 'kind of' work in connect a2 again. Still no luck with loqui. ('i already have a code' does not work, nor does sending a sms).
Do they use the same coseme-version?

**Comment by aesedepece** [comment]
Here it is, branch 0.4 with working registration → https://github.com/loqui/im/tree/v4

**Comment by aesedepece** [comment]
Warning: it's quite buggy by now. Please test it and report any issues! Thanks in advance.

**Comment by ghost** [comment]
When will this version be pushed to the market place? Can you already give an aproximate point of time?

**Comment by cmeerw** [comment]
@aesedepece just tried registering with the 0.4 branch and it failed with a "no_routes" error...

**Comment by aesedepece** [comment]
@JayVii I can guess it could be ready later this week.

@cmeerw I am really sorry to bring this news to you, but WhatsApp has started banning registration for some accounts and from some IPs. For example:
-  Account A, IP A: "no_routes"
-  Account B, IP A: "no_routes"
-  Account A, IP B: "no_routes"
-  Account B: IP B: "success"

In this example, account A is registration-blocked\* and IP A is banned.

Test if you can send SMS to random numbers from your same country.
-  If succeeds: your account has been blocked
-  If fails: your IP has been blocked

`*registration-blocked:  this means the account can log in and chat but can't be registered any more`.

**Comment by cmeerw** [comment]
@aesedepece no worries, that's just a test number anyway. But it also means that the 0.4 branch doesn't really fix any registration issues then. (btw, I tend to get my IP address assigned from 2 very different IP blocks - so looks like IP addresses from one of them work for WhatsApp registrations and the other doesn't)

**Comment by aesedepece** [comment]
Duplicate of #565, let's move there! :wink:
