### ISSUE TITLE
Make different received/sent messages

### ISSUE THREAD

**Issue by Gioyik** [loqui/im#63]
Is difficult to know which messages you sent and which messages you received because there's not a difference between them. Is necessary to make some modifications on this.

**Comment by Gioyik** [comment]
Ok i am testing and probably is not a problem at all, the first time that i test send/receive a message a get this error, not is working as expected. Tomorrow i will test again and confirm if this really needs a solution.

**Comment by aesedepece** [comment]
This is in fact https://github.com/waalt/loqui/issues/56

It's already solved and will push an OTA update with the bugfix ASAP.
