### ISSUE TITLE
account status

### ISSUE THREAD

**Issue by agnez** [loqui/im#637]
Hi
I did not find a way to set my account status or to stop the app in general.
I use jabber accounts on various machines, and some conversations get split up between loqui/im on phone and other chat clients on other devices, turned on at the same time.

Changing my account status on loqui migt solve this? 
Or maybe a switch off function could help.

At the moment I had to uninstall loqui, the situation was getting too complicated.
xx
ag

**Comment by TitanNano** [comment]
On the main sheet, tap the upper right button. there you can enable and disable accounts. If you want to quit Loqui you can do that there too.

**Comment by agnez** [comment]
thanks, found it.
