### ISSUE TITLE
Text is not visible in the settings page

### ISSUE THREAD

**Issue by LeTanque** [loqui/im#640]
The first time I used the demo, text was visible and everything looked as it should. 

After enabling developer options once, the text in the settings menu is no longer visible. 

This is the output from the dev console. 

```
...
SAVING,devsettings,[object Object]
Connection failed
Disconnecting
Disconnected
Connecting
Connected
SAVING,accountsCores,[object Object]
SAVING,accountsCores,[object Object]
SAVING,avatars,[object Object]
SAVING,devsettings,[object Object]
SAVING,devsettings,[object Object]
SAVING,devsettings,[object Object]
```
##### Update

Did an `apt-get update && apt-get upgrade` for other reasons, restarted firefox, and the problem is no longer present. 
###### My Setup

> CPU~Dual core Intel Core i7-2640M (-HT-MCP-) clocked at Min:841.203Mhz Max:1091.343Mhz 
> Kernel~3.16.0-30-generic x86_64 Up~2:42 
> Mem~1982.5/7867.4MB
> HDD~271.6GB(33.3% used)
> Procs~235 Client~Shell 
> Mozilla Firefox 35.0.1

![2015-02-07 19 17 06](https://cloud.githubusercontent.com/assets/7180772/6095122/24d9a926-af01-11e4-8ebf-e819e08eb0b7.png)

**Comment by ghost** [comment]
I also have seen the settings screen showing up like this (maybe two times since i use Loqui) on my FirefoxOS 1.3 device. Not sure what could be the reason for it.

**Comment by TitanNano** [comment]
Anyone who still experiences this??
