### ISSUE TITLE
Google hangouts doesn't show SMS messages

### ISSUE THREAD

**Issue by LeTanque** [loqui/im#641]
Not sure if this is a feature request or an actual bug. Hangouts within gmail, through the Chrome app, and through the hangouts firefox extension all show the SMS messages associated with my gmail account. 

Loqui, unfortunately, doesn't show those messages. I never noticed just how many messages I receive are actually SMS because after running for a day, I hadn't received a single message. At first, i thought it was something other than loqui, but I tested it with another gmail hangout instance and it worked just fine. 

At present, loqui only posts messages. SMS messages that are normally shown in hangouts do not post in the loqui web client.

CPU~Dual core Intel Core i7-2640M (-HT-MCP-) clocked at Min:841.203Mhz Max:1091.343Mhz Kernel~3.16.0-30-generic x86_64 Up~2:42
Mem~1982.5/7867.4MB
HDD~271.6GB(33.3% used)
Procs~235 Client~Shell
Mozilla Firefox 35.0.1

**Comment by aesedepece** [comment]
I've just updated the demo to v0.4.0, can you try now? Thanks!

**Comment by TitanNano** [comment]
is this still relevant?
