### ISSUE TITLE
could not register by using flame device

### ISSUE THREAD

**Issue by amjadm61** [loqui/im#644]
I can't register on loqui im by using my flame device, the app showing couldnot send message and call.
In my device, I didn't installed any other whatsapp client and also I didn't used my account in any other device at that moment. But later I tried with connect A2 and open wapp and I can use whatsapp with these 2 apps.
I tried with fxOS 2.0, 2.2,3.0

**Comment by gargsms** [comment]
This issue is fixed with v4 AFAIK.
WFM.

**Comment by ghost** [comment]
Does anyone know, when the v0.4 branch will be pushed to the marketplace? Seems like it's almost finished, as everything got merged from v4 to dev.
Can we hope for a release this week? :)

**Comment by amjadm61** [comment]
@gargsms that is really cool...
When will you upload the new version to marketplace?
Or can I install the app from somewhere else? I mean by downloading the source code? If so, plaza guide me for that...

-thanks

**Comment by amjadm61** [comment]
@gargsms any update on my query?

**Comment by gargsms** [comment]
@amjadm61 Sorry man, almost forgot to reply.
I am not the owner of the app, so I won't be updating anything on the Marketplace.

However, @aesedepece said that this version will be updated by the next week. Let's see.

You can use the latest app by downloading this repository, and building it.
Or if you don't want to build it - just download, then make a new folder, let's say 'Loqui IM', and copy the contents of the src folder into it. And then paste the manifest.webapp file from the platform/firefoxos into the folder as well. Now you can use WebIDE to load this folder and install it on your Flame.

Cheers!
