### ISSUE TITLE
[v4] [WhatsApp] Unable to access the memory card. [...]

### ISSUE THREAD

**Issue by petzichen** [loqui/im#645]
Whenever I click on "Verify via SMS"/"Verify via phone call" I get this error-message: 
"Unable to access the memory card. Check that this is not being used as a USB storage medium." - But my Flame isn't connected to my computer via USB... I'm using a normal microSD-Card [32GB] and ffos 2.0.

**Comment by TitanNano** [comment]
did you grant the SD Card permission to loqui? I'd suggest to got the
settings app and check it.

2015-02-14 10:00 GMT+01:00 Kevin Hartmann notifications@github.com:

**Comment by petzichen** [comment]
Oh.. Thata right. There was an bug in the first installation. Now it works very well. Good job :-)

**Comment by siyaskp** [comment]
@ TitanNano,i have the same problem.i didnt give permission to grant SD card.and i using Loqui in windows Xp pc

**Comment by gargsms** [comment]
@siyaskp Do you mean you are using it in a Firefox OS Simulator on Windows XP?

In any case, you should grant the permission to access SD card or Loqui will not work properly.

**Comment by TitanNano** [comment]
you don't have SD card simulation in the FxOS simulator. They only support the different media storages.

**Comment by gargsms** [comment]
AFAIK, I have had no such problems with a simulator as absence of SD card. I use Linux and my simulator will use my hard drive folders as the SD Card.
@siyaskp explicitly said that the permission was not granted. You should do that first.
