### ISSUE TITLE
[v4][XMPP] Chat history overwritten by an other chat

### ISSUE THREAD

**Issue by ghost** [loqui/im#646]
Today i tested Loqui IM v0.4.0a with XMPP and the following problem occurs 

I (bob(at)...) was chatting with a contact (ca...(at)...) and had an other test conversation with a different XMPP account (some...(at)...) of myself, where i just enabled/disabled Otr and sent some messages

The chats where in this order:
1. test account (some...(at)...)
2. chat contact (ca...(at)...)

Then the chat contact answered, the chat contact has duplicated itself and the chat history of the test account disappeared.
1. chat contact (ca...(at)...)
2. chat contact (ca...(at)...)

I wrote a message from my test account (some...(at)...) to my XMPP account (bob@...) and a new chat appears (the chat history was empty)
1. test account (some...(at)...)
2. chat contact (ca...(at)...)
3. chat contact (ca...(at)...)

![2015-02-17-00-46-26](https://cloud.githubusercontent.com/assets/4523264/6221659/d8ea3b78-b646-11e4-9b81-4d8dbbe16413.png)

I start testing with a second test account (bobcanthelpyou(at)...) and tried to find a way to reproduce the problem. The history of the chat contact (ca...(at)...) disappeared completely and my own account (bob(at)...) appeared in the chat list.

![2015-02-17-01-24-33](https://cloud.githubusercontent.com/assets/4523264/6221726/76a2739e-b647-11e4-9281-fb684cd95c59.png)

After i closed Loqui IM and started it again, there where some changes in the chat list, too

![2015-02-17-01-29-45](https://cloud.githubusercontent.com/assets/4523264/6221727/7a1973a6-b647-11e4-8ced-b0fe37bfcfe3.png)

Not sure how to reproduce this issue exactly, but it happens to me .. i am a little bit confused ..

**Comment by TitanNano** [comment]
wow, this looks bad. would it be possible for you to connect your device
with the WebIDE and provide some logs? You did take the marketplace version
or your own dev branch build?

2015-02-17 2:16 GMT+01:00 bobcanthelpyou notifications@github.com:

**Comment by ghost** [comment]
I am using the marketplace version of Loqui on FirefoxOS 1.3. I tried to reproduce the problems with the the FirefoxOS simulator 1.3.

**my own account is showing up**
on the last screenshot of my first comment, my own account is showing up in the chat list and i don't know why. I could reproduce that with one of my XMPP accounts (out of three)
1. start Loqui
2. add your XMPP account to Loqui
3. start a chat with someone
4. quit Loqui
5. start Loqui, again
6. a chat with myself appears

I can't remove the chat / can't access the profile 

```
TypeError: chat.core.participants is undefined messenger.js:172
"SHOW" "chatInfo" [object HTMLSpanElement] undefined menu.js:297
"SHOW" "muc" undefined undefined menu.js:297
```

**a chat is overwritten by an other chat**
That appeared after i create an Otr key, had 2 chats open, both with Otr enabled. 
1. Open Loqui
2. Start chatting with 2 contacts
3. try to start an Otr session with one of the contacts
4. create an Otr key
5. start an Otr session with both contacts
6. write some stuff with both contacts
7. Quit Loqui
8. Start Loqui, again
9. one of the contact chat should be disappeared, one should be displayed twice, if that is not true, retry to send some Otr messages and restart Loqui again

When a chat appears two times, i could access the profile but can't remove them

```
TypeError: this.connection is undefined xmpp.js:268
"SHOW" "chatInfo" [object HTMLSpanElement] undefined menu.js:297
"SHOW" "contact" undefined undefined menu.js:297
"SHOW" "contactRemove" [object HTMLButtonElement] undefined menu.js:297
```

**Comment by TitanNano** [comment]
okay from your screen shots and the first log snippet it looks like this chat is handled as a group chat. I guess it's not a group chat?

**Comment by ghost** [comment]
I started only normal chats, no group chats

What log information do you need? Do you need everything until the Issue occurs?

**Comment by TitanNano** [comment]
could you provide me a log of all the steps you described? Remove all chats and reproduce the bug, logging everything.

**Comment by ghost** [comment]
add account and chatting with two other accounts
http://pastebin.com/M6hPmw2j 
one of the other chat account is offline now and the chat was overwritten by the other online account
http://pastebin.com/J3sPYK2a
i still could access the contact profile and could clear the chat
http://pastebin.com/HSfyRzS2

**Comment by TitanNano** [comment]
Okay, thank you. I can't see any errors in the log. This only happens when you switch to OTR right?

**Comment by tt123456** [comment]
I can confirm this, i have the same issue:
1. Chat logs with contact A+B visible(both with otr enabled).
2. Wrote a message to contact B(offline, so no otr), checked back later on, then i had chatlog of contact A twice(no new messages from A), and chatlog with contact B disappeared.

It happened before that i had a chatlog twice but i thought it might have been because the contact was online with two resources, but even if this was the case again it shouldn't overwrite other logs.

**Comment by pravi** [comment]
I experienced this issue as well.

**Comment by tt123456** [comment]
Could you please take a look at this issue? It makes XMPP quite unusable if chat logs are overwritten all the time.
What i know about this issue:
-Duplicated chats show the same name/date/text, which means that either both logs are updated or they point to the same log.
-Sometimes it's fine, but after restarting loqui, duplicate shows up. But duplicates also show up without restart
-Chats can be duplicated more than once(eg same chat displayed 3 times)
-Status is displayed only for one of the duplicates(the original one i guess), the rest(name,date,text seems to be identical between duplicates). 
So i think loqui somehow still looks for the correct jid and displays correct status, but name,date,text are fetched/stored wrong.

I tried to search for what causes this issue in the source, but i couldn't figure it out. For example i have pretty much no idea what the this.postreceive() function in message.js does, also i didn't understand how the messages are stored(what's blockindex/index/chunkindex, and where/how is it set?)

**Comment by TitanNano** [comment]
okay I hooked my phone to the debugger now. If anyone is online right now, send me messages at titannano@jabber.de and I will see if I can reproduce this bug.

**Comment by TitanNano** [comment]
I don't know if this actually solves the problem. I couldn't reproduce the bug. Reopen if the issue still exists.
