### ISSUE TITLE
[Whatsapp] Status not available

### ISSUE THREAD

**Issue by ghost** [loqui/im#648]
So, I noticed, that in the new LoquiIM version (0.4), statuses of other people are not visible anymore "Not available".
In older versions of the app, there used to be a bug, where it was only visible, once you already chatted with the contact for a bit. Now, it isn't there whatever I do.

**Comment by TitanNano** [comment]
statuses are only downloaded at the connection setup, means every time you reconnect to whatsapp. did you reconnect since you started to chat with a contact?

**Comment by ghost** [comment]
yes, multiple times. I even had a full phone-reboot (because empty battery :D) and the issue persisted.

**Comment by TitanNano** [comment]
okay. would it be possible for you to provide me the console output from the webIDE? I'd need the log from the connection time. simply connect your device, open the devtools, disable whatsapp and enable it again. then provide me the log.

**Comment by kingcraig** [comment]
WhatsApp hack tool download <a href="http://whatsapphacktool.wix.com/whatsapphacktool">Whats App Hack Tool Download 2015</a>
