### ISSUE TITLE
GUI broken

### ISSUE THREAD

**Issue by ghost** [loqui/im#650]
After updating Loqui IM on my Zte Open (v1.1) today, almost everything renders badly, the settings menu isn't showing (only the shadow), the font size is way smaller than the preview and it randomly stops to retrieve messages.
Is FFOSv1.1 still supported by this app?
With the previous version everything worked fine.

**Comment by gargsms** [comment]
The new version got a big overhaul. I guess v1.1 is not properly supported now.

NI @aesedepece

Anyway, you should consider upgrading to at least v2. Mozilla itself recommends so.

**Comment by ghost** [comment]
I see... The things that worked (whatsapp registration and receiving messages) looked really good :+1: .
Sadly, since I have the ZTE Open TME (it doesn't have fastboot) I don't thing I'm able to upgrade it to v2 though.
