### ISSUE TITLE
open my loqui im

### ISSUE THREAD

**Issue by shukriya** [loqui/im#666]
Please support my loqui im aap

**Comment by shukriya** [comment]
My aap not support my device

**Comment by shukriya** [comment]
I want qtr and all support

**Comment by shukriya** [comment]
Please support my devise.
Thanks

**Comment by ghost** [comment]
@shukriya what kind of device do you use?

**Comment by gargsms** [comment]
@shukriya Can you please describe in detail and not increase the thread count by using GitHub like Twitter?
