### ISSUE TITLE
[XMPP] never get a double green tick with conversations

### ISSUE THREAD

**Issue by pravi** [loqui/im#667]
I think conversations and yax.im has the required xeps implemented but I only get one green tick indicating only successful sending. What could be the issue with acks?

**Comment by TitanNano** [comment]
~~@aesedepece implemented this for XMPP and looking at the XMPP connector shows that we only record "received" stanzas, which we receive only once when a message has been sent to the server...~~

**Comment by TitanNano** [comment]
Okay so I investigated a little and I realized, I was wrong. We actually do support the double ticks / message delivered acks, but at the moment we have a bug in the message marking process for xmpp messages. I hope we can fix this soon.

**Comment by TitanNano** [comment]
fixed 😉
