### ISSUE TITLE
welcome message for new account misses 'she'

### ISSUE THREAD

**Issue by pravi** [loqui/im#670]
Now when a new account is setup, the chat windows shows,

There are no chats yet
Why don't you ask a friend how he is doing.

This assumes only men contacts will be present. In cases like this neutral plural forms are used. It can be changed to,

Why don't you ask a friend how they are doing?

He/she or (s)he are also used sometimes. I feel the plural form is better.

**Comment by TitanNano** [comment]
I agree let's change the string.

**Comment by TitanNano** [comment]
fixed
