### ISSUE TITLE
[General] Issues with asyncStorage

### ISSUE THREAD

**Issue by gargsms** [loqui/im#671]
Background:
I am using v4 latest from the repo. I had multiple accounts set up. One WhatsApp, one Jabber and one other XMPP. I was added to some shitty group by some stranger on WhatsApp and I obviously wanted to remove myself from that. And then this happens.

Steps to reproduce:
1. Open the 'shitty' group (or any other chat).
2. Swipe right twice to move to the chat roster and then to the accounts aside.
3. Select a different account from the one having the shitty group. This is now the 'current' account.
4. Swipe left once to find that you are back at the shitty group which you hate the most in your life and curse it. Remember not to open any other chat in this account.
5. Open the information section for the group or chat by tapping on the group picture.
6. Use the "Exit from this group" button. Confirm the dialogue asking "Do you want to exit from 'the shitty group(TM)?' "
7. Voila! You have the first chat in the 'current' account removed instead of the shitty one.
8. Hate your life for finding this bug and losing an important chat.
9. Repeat the steps in order to confirm that this happens.
10. Hate your life more because bad things happen to good people.

This thing has cost me a very important chat, and is 100% reproducible.

Also, I was trying to implement the 'Delete individual messages' feature last weekend but couldn't understand the asyncStorage (Store?) implementation. Strangely it only works fine with the app and not in the debugger. All the keys return the same info. And sometimes nothing.

:sob: :cry: Life's hard. :disappointed:

**Comment by TitanNano** [comment]
Okay I'll see if I can take a look at this on the weekend.
For the individual message deletion create a new issue and I can provide you any information you need about the Storage Object there 😊

**Comment by TitanNano** [comment]
okay so I think I can fix this tomorrow. This is just some UI tweaking. 

@gargsms I think I can recover your chats (similar thing happened to me) but no promisses. I have to fix #190 to make it save, afterwards I can provide some recovery code ;)

**Comment by gargsms** [comment]
@TitanNano The UI tweaking would be a dirty fix, but it will solve the reproduction. See if you can fix it to the core.

And I will try if the backup using WebIDE works.

**Comment by TitanNano** [comment]
@gargsms well the problem is that you can still access the chat through the gesture even when you switched the account. So I'll set the chat section hidden as soon as you switch the account 😀

**Comment by gargsms** [comment]
Yes, that's what I meant. That is a quick fix. Put this for the time being.

**Comment by TitanNano** [comment]
yea, but do you have any other suggestions to fix this?

**Comment by TitanNano** [comment]
@gargsms okay so to recover your chats. when you delete a chat loqui only removes the Chat object for that chat, not the chunks storing the messages for that chunk. 
If you run the following code in the console, it will go though all the chunks stored on your device and sort the chat message chunks by your various chat partners jids. 
At the end you'll get the public Object Chats where you can find a hole bunch of chat objects. e.g. phonenumber@whatsapp.net. You can now add these chats to your account by pushing them into `account.chats` or replace a existing chat `account[i].chat[x]= Chats[username@jabber.de];`

``` JavaScript
var Chats = {
};
var accountIds= App.accounts.map(account => {
  return account.core.fullJid;
});
for (var i = 0; i < Store.size; i++) {
  (function(i){
  Store.recover(i, function (chunk) {
    if (chunk instanceof Array && 'from' in chunk[0] && 'to' in chunk[0]) {
      if(accountIds.indexOf(chunk[0].from) > -1 || accountIds.indexOf(chunk[0]) > -1){
        var jid = (accountIds.indexOf(chunk[0].from) > -1) ? chunk[0].to : chunk[0].from;
      }else if(chunk[0].to == 'undefined@s.whatsapp.net'){
        var jid = chunk[0].from;
      }else{
        var jid = chunk[0].to;
      }
      if (!(jid in Chats)) {
        var contact = (function(){
          for(var ac = 0; ac < App.accounts.length; ac++){
            var account= App.accounts[ac];
            var x = Lungo.Core.findByProperty(account.core.roster, 'jid', jid);
            console.log(jid, x);
            if(x) return x;
          }
        })();
        Chats[jid] = new Chat({
          jid: jid,
          title: contact ? contact.name || jid : jid,
          chunks: [
          ],
          muc: false
        }, Accounts.current);
      }
//      Chats[jid].core.chunks.push(chunk);
      Chats[jid].core.chunks.push(i);
    }
  });
  })(i);
}
```
