### ISSUE TITLE
[XMPP] list of implemented XEPs like conversations

### ISSUE THREAD

**Issue by pravi** [loqui/im#673]
does Loqui implement all the XEPs implemented by conversations? https://github.com/siacs/Conversations

**Comment by gargsms** [comment]
@pravi The supported XEPs can be easily found here.
https://github.com/loqui/im/blob/dev/src/scripts/loqui/connectors/xmpp.js#L125-L132

**Comment by pravi** [comment]
It would be better if it is in README or in wiki for easy reference.

**Comment by pravi** [comment]
that means many of the important XEPs implemented by Conversations is not yet available in Loqui. XEP 0198, XEP 0313 are critical for a bad network like I have.

**Comment by TitanNano** [comment]
@gargsms created a wiki entry

**Comment by pravi** [comment]
please share the wiki link

**Comment by TitanNano** [comment]
https://github.com/loqui/im/wiki/FAQ
