### ISSUE TITLE
source option is invalid for gem

### ISSUE THREAD

**Issue by pravi** [loqui/im#679]
You passed :source as an option for gem 'rails-assets-diaspora_jsxc', but it is
invalid. Valid options are: group, groups, git, path, name, branch, ref, tag,
require, submodules, platform, platforms, type

This is ruby 2.1.0.1
$ gem --version
2.2.2

Is it a newly introduced option?

**Comment by TitanNano** [comment]
this project does not use any ruby.

**Comment by pravi** [comment]
Oops! Sorry, autocomplete brought the wrong project.
