### ISSUE TITLE
[xmpp] even when account is offline loqui shows red border with grey background

### ISSUE THREAD

**Issue by pravi** [loqui/im#681]
It should keep them as yellow and should attempt when account comes online. There is no way loqui will recieve an acknowledgement if offline. Timeout is meaningful only when the account is online.

**Comment by pravi** [comment]
So I have to manually check if the account is online and then manually reconnect when I don't see any replies for some time.

**Comment by TitanNano** [comment]
We decided to do it this way. I'll change the behavior in the future when I'm going to improve the message re-send functionality. 
Right now messages do get re-send when the account is not connected at the time you send your message. 

The red border is absolutely valid, please read the [FAQ](https://github.com/loqui/im/wiki/FAQ), the red border means we were unable to send your message to your providers server and thats the case if you're currently offline.

**Comment by TitanNano** [comment]
your message will be marked as sent after we resent it 😉
