### ISSUE TITLE
Stuck at Whatsapp validate code? [Firefox OS 2.0]

### ISSUE THREAD

**Issue by ghost** [loqui/im#686]
Hi,

So I received an SMS for the validation code, but every time I enter it, it just pops up a 'Validating Code' for 10 seconds, and then nothing happens. I tried switching off my mobile internet and restarting my phone. Still didn't help.

**Comment by ghost** [comment]
@anweshm4 How did you fixed this issue?

**Comment by gargsms** [comment]
Similar thing happens for me.The way I work around is by requesting for code once, killing the app, and then using the "I have a code" option.

**Comment by aesedepece** [comment]
This is fixed in v0.4.1, yet to be published to Marketplace.

**Comment by tomjaguarpaw** [comment]
Happens in 0.5.5 for me.
