### ISSUE TITLE
Emojis and Thunder bar hide all workspace.

### ISSUE THREAD

**Issue by githubtefo** [loqui/im#687]
Is it any way to hide this bar? Because in my device fills all the available space for chatting.
Thanks!
st.-

**Comment by TitanNano** [comment]
yes, tap the plus button or unfocus the message text box.

2015-04-13 3:43 GMT+02:00, githubtefo notifications@github.com:

> Is it any way to hide this bar? Because in my device fills all the available
> space for chatting.
> Thanks!
> st.-
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/loqui/im/issues/687

## 

-- Jovan

**Comment by githubtefo** [comment]
Thanks for your answer @TitanNano
I tap the plus button and the bar disappears. But when I start to write the bar returns and I cant see what I'm typing. It's very annoying. Is anything that I can do to disable always this bar?

**Comment by TitanNano** [comment]
no, right now you can't disable it. what device do you use?

**Comment by gargsms** [comment]
The problem was quite evident in earlier version of Loqui when used in landscape mode.With lock orientation enabled, it disappeared for me.
Anyway, I am assuming you use a device with 480px high screen. In that case, about 210px goes to the Keyboard, which is actually sad (the keyboard should have been adjusting). It is not ATM.

**Comment by githubtefo** [comment]
I'm using the ZTE Open II, with Firefox OS 1.3 and lock orientation enabled. I've got a jabber account.
More on, when I try tap the plus button in presence of the keyboard, Loqui crashes.

**Comment by TitanNano** [comment]
can you provide us screen shoots?

**Comment by githubtefo** [comment]
Yes, off course @TitanNano 
![2015-06-08-07-43-59](https://cloud.githubusercontent.com/assets/11220103/8033306/8579816e-0db3-11e5-982f-385c65663dca.png)
![2015-06-08-07-47-12](https://cloud.githubusercontent.com/assets/11220103/8033307/857f48d8-0db3-11e5-956c-a5ac5bad1ff5.png)
Thanks!

**Comment by TitanNano** [comment]
@acidicX wants to work on this. He is not a team member yet so we can't assign him, but it's his bug now. 

Solution for the problem is: 
hide the features bar if the available screen height is to small.

**Comment by acidicX** [comment]
I tested it with the fixes applied on my Flame, works like a charm!
