### ISSUE TITLE
I can't connect with a XMPP/Jabber account.

### ISSUE THREAD

**Issue by githubtefo** [loqui/im#691]
Hi!
since yesterday I can not connect to my XMPP/Jabber account using Loqui IM trough my ZTE Open II. The account works well when I use Pidgin.
I reinstall Loqui and now I can't even configure the account.
Any ideas? Someone has the same problem?
Thanks!

**Comment by TitanNano** [comment]
yes, same problem here. probably BOSH server issues.

**Comment by aesedepece** [comment]
Ooops...

bosh.loqui.im uses an invalid security certificate.
The certificate expired on 17/04/15 07:32. The current time is 18/04/15 22:53.
(Error code: sec_error_expired_certificate)

I'll issue a new cert asap.

**Comment by githubtefo** [comment]
I see that you corrected the BOSH problem, @aesedepece. Thanks!
Should I wait the update of the marketplace's package?
Is there any other alternative easier than manual compiling? I might don't have any problem to do it, but some people which I currently talk over XMPP/Loqui perhaps yes.

**Comment by TitanNano** [comment]
@githubtefo no the only way to get a copy of loqui beside downloading it from the marketplace is downloading it.

**Comment by aesedepece** [comment]
v0.4.1 is awaiting for approval in Firefox Marketplace :wink:

**Comment by githubtefo** [comment]
ok, thanks guys.
v0.4.1 includes the last recent changes, doesnt it?
In that case we should wait for the approval at Marketplace to use Jabber again.

**Comment by ghost** [comment]
Hi! Still does not work even with bugfix. 

Provider: xmpp.jp Fxos: 2.2.0-pre

**Comment by vandys** [comment]
I can confirm that as of April 21st, Firefox OS 2.0 on my Revolution got a new download, and the app still didn't work.  I removed and reinstalled and verified that the current bits from Firefox OS marketplace do not address the issue.

Update 4/22: the part of the CDN I reached must have finally updated or something.  After
waiting another day, reinstall got me working again.

**Comment by githubtefo** [comment]
In my case I uninstalled the v0.4.0 and add from the marketplace the last (v0.4.1) and now I can add again my Jabber account (with @suchat.org domain; OS 1.3; ZTE Open II). Thanks to the developers for solve the issue so quickly!

**Comment by ghost** [comment]
Hey! New developments: After unknown 1.3mb update that was crippled, I've finally received this 2.0mb big 0.4.1a & Jabber came back from ashes. (=

Huge congratz to the dev team.

Shitty geo region marketplace skew.

**Comment by aesedepece** [comment]
Cool. Have XMPP fun, bros!
