### ISSUE TITLE
Lock screen downs data connection, all versions

### ISSUE THREAD

**Issue by hectogram** [loqui/im#694]
As soon as the screen locks data connection/ wifi  drops. This is a major showstopper for people who want to be allways reachable, e.g. sysadmins interfacing to their servers through xmpp.

Would it be possible to include a wake lock for data connection in the app ?

**Comment by gargsms** [comment]
I don't think that is a Loqui problem. Anyway, are you sure you haven't kept the 'Wi-Fi sleep' feature in FxOS on?I have been constantly using my data connection on locked screen by tethering.Also, Loqui keeps receiving messages just fine regardless of the screen state.

**Comment by githubtefo** [comment]
Yes, Ive got the same problem. And I also think the reason is the wifi is turning off when the screen blocks. How can we change this setting?

**Comment by gargsms** [comment]
You can change the Wi-Fi sleep setting from the Firefox OS Settings app. It is there under Wi-Fi menu.

**Comment by githubtefo** [comment]
@gargsms, in my case (ZTE Open II; Firefox OS 1.3) on the Wifi menu Ive just got turn on/off Wifi, Available networks, search again, and network management (where I can only drop known networks or join to a hidden one).

**Comment by gargsms** [comment]
@githubtefo Oh. That option is not available before FxOS v2.2 AFAIK. For your case, I am not sure about it.I will need to search places.

**Comment by TitanNano** [comment]
this is in no way related to loqui. If wifi is disabled, you always have to possibility to fall back on mobile data connection and we try to reconnect as soon as the connections is switched.
