### ISSUE TITLE
WhatsApp: authentication failed on login, registration fails with reason old_version

### ISSUE THREAD

**Issue by cmeerw** [loqui/im#698]
just noticed that it doesn't let me login to WhatsApp any more.

Tried to register and that fails as well with reason "old_version".

**Comment by TitanNano** [comment]
@cmeerw I'm looking into this issue right now. I can't authenticate either. where do you see that "old_version" reason? I can't find it in my log...

**Comment by aesedepece** [comment]
I have no time to fix it in Loqui right now, but for reference here you have the Pull Request fixing it in Yowsup: tgalal/yowsup#748

**Comment by TitanNano** [comment]
oh well I already fixed it  😊 I just had to update the version from 2.12.60 to 2.12.67

**Comment by aesedepece** [comment]
Thanks a lot, @TitanNano. 
We should push 0.4.2 as soon as possible, right?
Is there some other urgent issues we should deal with or can we make the release?

**Comment by TitanNano** [comment]
@aesedepece no as far as I know we don't have any other open urgent issue at the moment.

**Comment by bdcomp** [comment]
@aesedepece Hi!
Just wondering if WhatsApp group creation not possible is a known issue (I found only #560 , an old and not related to WhatsApp)?

I think it's should be high priority.

**Comment by TitanNano** [comment]
@bdcomp well creating a whatsapp group is quite buggy but it works for me, I just tired it. I don't think this is a urgent issue we need to be fixed along with the essential new WhatsApp version. But maybe you could file a bug for that?

**Comment by bdcomp** [comment]
If so, I will wait for the new version of Loqui.
I will try to create a group and file a new bug if it's still not working.

**Comment by TitanNano** [comment]
it's working for me :)

**Comment by ghost** [comment]
@aesedepece now there is an issue with Whatsapp and the confirm SMS, again #701 #702

**Comment by holztest08** [comment]
It's not working for me, using 4.2a, on FOS 2.2 (Flame).

**Comment by ghost** [comment]
Not working for me either. Loqui 0.4.2a, FxOS1.3
(on a sidenote: openwapp doesn't work either, same problem?)

**Comment by holztest08** [comment]
Yes, same problem with openwapp.
https://github.com/mozillahispano/openwapp/issues/118

**Comment by TitanNano** [comment]
hello @JayVii  and @holztest08 are you talking of the registration process or the simple authentication with an excising account? My phone here is properly connected to WhatsApp using the latest build. 
If you still can't connect to whatsapp, I'd like to ask you to provide me logs from the failing authentication so we can try to figure out why it isn't working for you.

**Comment by keerthana1997** [comment]
I am not able to register watsapp through old version..i am pissed off using dis..

**Comment by ghost** [comment]
@keerthana1997 which Loqui IM version do you use?
