### ISSUE TITLE
Can't receive SMS or phone call to use Whatsapp

### ISSUE THREAD

**Issue by airon90** [loqui/im#701]
Hi, I have just installed Loqui IM in rder to use Whatsapp but when I press the "Verify via SMS" button, "Waiting for SMS..." is shown and an error appears: "Could not send SMS!".

Same situation if I press "Verify via phone call": "Waiting for  phone call..." and then "Could not call your number!".

I'm using latest Firefox OS (3.0) with latest Loqui (0.4.1).

I don't know what to do. Please help me!

**Comment by ghost** [comment]
Maybe the problem is related to #698

**Comment by 03927e9c** [comment]
I have the same problem... it's https://github.com/loqui/im/issues/565 all over again.

**Comment by TitanNano** [comment]
we are working on this as fast as possible!

**Comment by TitanNano** [comment]
wasn't intended to get closed, we need tests first. every one how experiences this, please flash a new build and retry. thanks ~

**Comment by gargsms** [comment]
Works for me.

**Comment by TitanNano** [comment]
thanks +1 I'm glad this is fixed.

2015-05-02 16:45 GMT+02:00 Sukant Garg notifications@github.com:

**Comment by airon90** [comment]
I can receive a new code from Whatsapp but now I can't log in because it says "Validating code" and then nothing happens.

**Comment by ghost** [comment]
It works for my Firefox OS 2.0 device.

**Comment by gargsms** [comment]
@Airon90 If that happens for you, note down the code that you have received and use 'I have a Code' option. You would need to kill the app first, though.

**Comment by airon90** [comment]
PS: I own a Flame with latest Firefox OS (3.0 Nightly)

**Comment by airon90** [comment]
I tried with "I have a code" but nothing works. Then I tried the same code with OpenWapp but it didn't work. So I uninstalled Loqui and reinstalled it, I granted manually all permissions, and tried again "I have a code" with the last code I received but nothing happened.

I set up XMPP and all worked well and tried again to set up Whatsapp but nothing happened again.

**Comment by gargsms** [comment]
@Airon90 For me this happens when I am on Wi-Fi network. Since the Wi-Fi is firewalled, I believe for me this has to do with the network itself. (The official WhatsApp clients work just fine on the network, though.)
When I switch to mobile data, everything just works. Do you happen to have a similar issue?

**Comment by TitanNano** [comment]
Would it possible for you to provide us some logs?

2015-05-02 17:18 GMT+02:00 Michael Moroni notifications@github.com:

**Comment by airon90** [comment]
I would be glad to do it if you tell me what to do because I never provided logs from Firefox OS apps! ^^'

**Comment by airon90** [comment]
@gargsms I can't test it on mobile connection because it is not included in my phone tariff plan. I always used WA on my wifi connection and never had problems

**Comment by ghost** [comment]
@Airon90 enable Developer mode under Settings / Features and Debug mode under Settings / Developer

Open Loqui on your phone and open the console of WebIDE (F12)

**Comment by TitanNano** [comment]
sure. Go into your firefox OS device. select the settings app, go into
device info, more info and enable the developer menu at the bottom. Go back
to the main menu of the settings app and select the developer menu. there
you have to enable ADB and DevTools debugging.

Now you are ready to connect your device with your computer and start your
firefox. where you can select the webIDE from the menu on the right. Inside
the webIDE you should be able to select your device on the right. after you
connected with your device you can select loqui from the apps list on the
left and open the console in the middle top of the screen.

2015-05-02 17:22 GMT+02:00 Michael Moroni notifications@github.com:

**Comment by gargsms** [comment]
@Airon90 I had it working properly till v3.4 of Loqui. Then something weird happened and I can't use it.
@bobcanthelpyou WebIDE will be opened by Shift + F8, though.

**Comment by airon90** [comment]
It seems that I tried many times (WTF):

```
"Request: https://v.whatsapp.net/v2/register?cc=39&in=MYTELEPHONENUMBER&code=335039&id=%98%0B%FC%99%9E%95%FD%4F%99%54%8A%31%9E%32%9C%17%93%91%97%B3 ~ _doRequest@app://d7789b4d-72e1-44b0-b0c1-76500735b4ad/scripts/mozillahispano/coseme.js:5747:7 [http]"

"{"status":"fail","reason":"too_many_guesses","retry_after":84650} ~ _doRequest/xhr.onload@app://d7789b4d-72e1-44b0-b0c1-76500735b4ad/scripts/mozillahispano/coseme.js:5752:9 [http]"
```

I will try again tomorrow.
I don't know why Loqui doesn't tell me that I guessed the code many times and I have to wait 24 hours...

**Comment by TitanNano** [comment]
hmm I'm sorry. It should tell you :/

2015-05-02 17:47 GMT+02:00 Michael Moroni notifications@github.com:

**Comment by airon90** [comment]
Uh! There is an error, when it finish to send the code, too:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://bosh.loqui.im/. (Reason: CORS header 'Access-Control-Allow-Origin' missing).`

**Comment by TitanNano** [comment]
ah, no thats not related to whatsapp :) it's a issue that sometimes occurs
while using XMPP, but nothing to worry about.

2015-05-02 17:57 GMT+02:00 Michael Moroni notifications@github.com:

**Comment by airon90** [comment]
Ah, ok!
See you tomorrow on the issue #701! :D
