### ISSUE TITLE
WhatsApp activation hasn't been fixed

### ISSUE THREAD

**Issue by 03927e9c** [loqui/im#705]
As described in https://github.com/loqui/im/issues/701 the problem still persits in latest version of Loqui dated (01/05/2015). It shouldn't be closed.

**Comment by TitanNano** [comment]
thats not right. The new token string I patched yesterday fixed the problem that you couldn't  receive a code by SMS or phone call. If there are additional issues, let me know.

**Comment by gargsms** [comment]
I believe what @03927e9c means is that the Marketplace version is not fixed yet. @TitanNano can you push the latest one to Marketplace?

**Comment by TitanNano** [comment]
I'm sorry, I don't have access.

**Comment by gargsms** [comment]
@aesedepece To the rescue.

**Comment by 03927e9c** [comment]
@gargsms exactly, that's what I meant.

**Comment by TitanNano** [comment]
@03927e9c well we close issues when they are patched, not when a new package is published on the marketplace.

**Comment by aesedepece** [comment]
I'll publish 0.4.2b to the Marketplace asap.

**Comment by TitanNano** [comment]
:+1:

**Comment by aesedepece** [comment]
Done. It should be available in the Marketplace soon.
