### ISSUE TITLE
can't start new chat

### ISSUE THREAD

**Issue by danielePala** [loqui/im#707]
When I try to start a chat with a new contact, the chat page is not shown, instead I see the main page, with the list of previous chats. Using version 0.42

**Comment by gargsms** [comment]
Not very sure if this will work because I haven't tried yet, but try swiping to the left. This should open the chat.

**Comment by danielePala** [comment]
Ah ok! this works. Thanks a lot!

Daniele

**Comment by gargsms** [comment]
I can confirm this.

**Comment by ghost** [comment]
@gargsms how to reproduce it?

**Comment by TitanNano** [comment]
@gargsms yes, how can we reproduce it? works fine for me :-/

**Comment by gargsms** [comment]
@bdcomp @TitanNano I haven't checked if it is there in the latest version but I guess it was there at least one release earlier. When you start a new chat, instead of the chat window opening, you were redirected to your chat list. If you swiped left (to access your previous chat) it would show the chat window.
It only occurs when starting a new chat. I haven't checked it now. I will later today.

**Comment by TitanNano** [comment]
I went to my roster in whatsapp and xmpp to select a contact I'm not chatting with... each time I was directed to the chat, not the main section....

**Comment by gargsms** [comment]
@danielePala Is this applicable to you anymore?

**Comment by danielePala** [comment]
Yes, I can confirm that this is applicable to me...using version 0.4.2b, on a flame with ffos version 3...

**Comment by danielePala** [comment]
Might be an OS issue?

**Comment by TitanNano** [comment]
No, I don't think thats possible. would you be able to provide some logs?

**Comment by danielePala** [comment]
I can try...just need to enable debug mode in loqui right?

**Comment by TitanNano** [comment]
yes and also make sure Firefox OS dev mode is enabled too. Then connect your device with the webIDE.

**Comment by danielePala** [comment]
Sorry for the late reply, I really don't have much time in these days...I've just started playing a bit with webIDE, a first obvious thing I see is:
- when I select a contact with an existing chat, the <section> with id='chat' gets class='fix head show forth'
- when I select a contact without existing chat, the <section> with id='chat' gets class='fix head prev back'

from this, I can tell:
-the only place where the class 'forth' gets set is in loqui/chungo.js, in the Router.section function

with a little more debug, I can see that:
- when I select a contact with an existing chat, the Router.section function is called with argument 'chat'
- when I select a contact without existing chat, the above call doesn't take place

By grepping the js code, I can see that Lungo.Router.section('chat') is called in two places:
- in loqui/bindings.js, where it seems tied to a 'swipeLeft' thing, so the on that is working for me
- loqui/chat.js, probably this is where it is not called with contacts without existing chat?

Hope this first quick code grep can help!

Daniele

**Comment by TitanNano** [comment]
hmm I still don't know how this is happening. It's working for me and I have no idea what's going on

**Comment by danielePala** [comment]
ok the problem for me is located in the function presenceRender (loqui/account.js). In particular, at the end of the function there is a for loop (line 399):

for (var [key, val] in this.core.chats) {
          if(!val.muc){
            contactPresenceRender(val.jid);
          }
        }

however I can see that in this loop val is undefined. I changed the code to:

this.core.chats.forEach( function(chat) {
          if(!chat.muc){
            contactPresenceRender(chat.jid);
          }
        });

and all works fine.

Daniele
