### ISSUE TITLE
can't access and no automatic remove of Firefox OS notifications

### ISSUE THREAD

**Issue by ghost** [loqui/im#710]
When i receive a new message it is shown at the Firefox OS notifications
- It is not possible to access the chat over the Firefox OS notifications
- The notification is not removed when i access the chat manually

Is it possible to make the notifications of Loqui IM somehow like the notifications for short messages?

Firefox OS v2.0 / Loqui IM v0.4.2b

**Comment by TitanNano** [comment]
notifications are implemented to work like other notifications. They should close and lead you to the particular chat. 

One problem still exists though. If any App gets closed or killed, the event listeners for the messages get lost and we can't handle your interaction anymore. 
Is it possible that this applies to your notifications?

**Comment by ghost** [comment]
I receive notifications e.g. when i am not using my phone and when i unlock my phone Loqui is not running anymore / can't access the messages with the help of the notifications. But a second before i got the notifications.

**Comment by TitanNano** [comment]
yes this is a platform issue. notifications do not restart their app and you also can't reregister a event listener to them. As far as I know, there are two bugs for that on Bugzilla.

**Comment by TitanNano** [comment]
okay I finally found the right solution for this.
