### ISSUE TITLE
Is Skype for Business (formaly Lync) supported?

### ISSUE THREAD

**Issue by ghost** [loqui/im#713]
I read some articles about Microsoft Lync is Skype for Business now.

https://technet.microsoft.com/en-us/library/dn913785.aspx
https://en.wikipedia.org/wiki/Microsoft_Lync

Does anyone knows if Skype for Business supports XMPP connections like Lync does?

**Comment by TitanNano** [comment]
well I would just give it a try?

**Comment by TitanNano** [comment]
it can support XMPP, see https://technet.microsoft.com/en-US/library/dn933894.aspx
