### ISSUE TITLE
Can't create new chat

### ISSUE THREAD

**Issue by MarkTr** [loqui/im#714]
Installed loqui on may 11. Can't write to contact. I can click on the pen symbol and chose a contact but no window for writing opens. Device is Mozilla Flame

**Comment by TitanNano** [comment]
Which provider are you using? what happens? just nothing? do you get directed back to the main view?

**Comment by MarkTr** [comment]
I tried with whatsapp and Google hangouts.I can reply to existing chats. Yes it gets me to the providers main view

**Comment by TitanNano** [comment]
okay this is a duplicate of #707 you can find a workaround over there.
