### ISSUE TITLE
common web app running: "asyncStorage: can't open database:" "InvalidStateError"

### ISSUE THREAD

**Issue by ghost** [loqui/im#721]
Hi,

I put the loqui application in a web server, and I'm opening it with the Firefox (iceweasel) of my laptop (is not working with Chromium). [src/index.html]. I'm using a custom XMPP server (Prosody) that I have configured in a private network.

XMPP providers.js part (where test.org is a fake /etc/hosts domain in client and server):

```
    'xmpp': {
      longName: 'XMPP/Jabber',
      connector: {
        type: 'XMPP',
        host: 'http://test.org:5280/http-bind/',
        timeout: 300
      },
      autodomain: 'test.org',
      features: ['muc', 'presence'],
```

I can connect to the server and load the two test contacts of my contact list. I can only receive one chat from one contact, or send one. After that, every new message I receive this error from javascript console:

"asyncStorage: can't open database:" "InvalidStateError"

mozilla/async_storage.js lines 12, 14

I know this is not the intended use. But I thought it was interesting to discuss a possible generalization of this application. It is an easy patch? Is a big change from its design?

Thanks,

**Comment by TitanNano** [comment]
may I ask which Gecko version you are using?

**Comment by ghost** [comment]
I expect this is the gecko version, if not let me know: Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.7.0

**Comment by TitanNano** [comment]
well yes your Gecko version is 31.0. The latest stable gecko version
released for desktop systems is 36.0. You should update before you do any
future tests.

2015-05-21 20:10 GMT+02:00 pedro-nonfree notifications@github.com:

**Comment by bdcomp** [comment]
38.0.1, in fact:
https://www.mozilla.org/en-US/firefox/38.0.1/releasenotes/

**Comment by TitanNano** [comment]
yes you are right! I didn't download the latest update.

2015-05-21 20:31 GMT+02:00 Boaz Dodin notifications@github.com:

**Comment by ghost** [comment]
I tried with last version and happened the same. I also think that there is a problem with connectivity with bosh, prosody... I would like to try with websockets, but I don't have more time. I will reopen the issue later.
