### ISSUE TITLE
while using loqui im its showing authentication failed

### ISSUE THREAD

**Issue by pavithrashankar** [loqui/im#727]

**Comment by TitanNano** [comment]
well if your account credentials are correct and this still happens we're sorry. Due connection issues it's possible that sometimes the authentication fails.

**Comment by pavithrashankar** [comment]
How to fix it

**Comment by TitanNano** [comment]
you can't fix it. As I said, sometimes there are connection issues and the
application is unable to authenticate. Usually it reconnects as soon as
possible.

2015-05-24 13:11 GMT+02:00 pavithrashankar notifications@github.com:

**Comment by tibtab** [comment]
This issue happens quite often to me. It's really annoying, when you're writing a message and the app suddenly sais "authenfication failed" and restarts and all you've written is lost.
Is there a way that at least the app doesn't restart?

**Comment by TitanNano** [comment]
okay as far as I know this happens when the bosh server is really busy. so maybe @aesedepece can do something about this, but I don't know.

**Comment by lumimgardt** [comment]
My authentication too keeps failing though with good network. Pls need this problem solved

**Comment by bordofr** [comment]
Me too but how do we solve it

**Comment by bordofr** [comment]
I canect even comnect anymore becouse after entering my number the comfermation doesnt come

**Comment by cmeerw** [comment]
I believe the original problem described here has been fixed in v0.4.4 with the WhatsApp protocol updates and reconnect handling updates.

**Comment by bordofr** [comment]
My problem is it looks like this my number is blocked because i cant
register whatsup with it. The number is +233240165458
