### ISSUE TITLE
[xmpp] unable to add new accounts

### ISSUE THREAD

**Issue by pravi** [loqui/im#728]
I could not add a third xmpp account. The account is working fine when logged in with conversejs.org. It gives up after 'Synchronizing' step and does not proceed. This is a brand new account with no contacts.

**Comment by pravi** [comment]
0.4.2b version

**Comment by tibtab** [comment]
i think it's a duplicate of  #591  and #459 
you have to add a VCard to the account

**Comment by TitanNano** [comment]
yes probably
