### ISSUE TITLE
iam using connecta2 app these days iam not receiving messages

### ISSUE THREAD

**Issue by pavithrashankar** [loqui/im#729]

**Comment by TitanNano** [comment]
would it possible to provide some more detailed informations about your issue?

**Comment by pavithrashankar** [comment]
Yes i was using the messaging app connecta2. all went good but some days after i didnt receive any messages sent to me and its shows unable to purse can you fix it

**Comment by TitanNano** [comment]
This is the repository and bug tracker for the mobile application Loqui IM. We are not related to connecta2 in any way.

**Comment by pavithrashankar** [comment]
How can i contact them could u help me

**Comment by TitanNano** [comment]
Please use their contact form. http://www.justapps4all.com/contact.html You can also find it on the ConnectA2 marketplace page.
