### ISSUE TITLE
No way to keep the app closed

### ISSUE THREAD

**Issue by aesedepece** [loqui/im#73]
Some users dib't like being always online and ask for a way to sign out or kill the app and prevent it from spawning/resurrecting.

I think we could put a "Power off" button below the "Add account" one in the accounts aside menu,

**Comment by Gioyik** [comment]
Assign me this is issue. I have a code for this and i have time this night to make a push to the code with a fix. I will make the push in master branch, it's ok?

**Comment by aesedepece** [comment]
Thanks! Tell me if you have any doubt.

**Comment by aesedepece** [comment]
I think that once this issue is closed we could fix three or four little ones more and push a OTA update with 0.1.3 "Halloween Edition" (custom icon included).

**Comment by Gioyik** [comment]
Great! Which issues do you think we need to have closed by the date? Probably i can help you with one of them. We can create a milestone for v0.1.3. :)

**Comment by Gioyik** [comment]
I am seeing this milestone (https://github.com/waalt/loqui/issues?milestone=3) and it will finish in 3 days. Probably those are the issues for the v0.1.3, i am right?

**Comment by Gioyik** [comment]
Please, add an icon for the new button in `img/providers/squares/close.svg`.

**Comment by Gioyik** [comment]
Well, this is not solved, when i tried it works, but now i am seeing that Loqui continue opening. I am going to send a fix for this tomorrow in the morning.

**Comment by willyaranda** [comment]
Hey @Gioyik , I just answer you here:

Loqui seems to be using alarms (at least they are defined on the manifest). So for really closing your app you need:
1. Remove ALL pending alarms you might have scheduled in the future. (see https://developer.mozilla.org/en-US/docs/Web/API/MozAlarmsManager.getAll )
2. `window.close()`

**Comment by aesedepece** [comment]
Icon has been added.

**Comment by Gioyik** [comment]
Hi @willyaranda 

Thanks so much, the information that you provide me help me to solve this issue. I did a commit with the fix this and now it's working as expected.

@aesedepece Thanks for adding the icon, could you check the commit to see if everything is working and to close this issue?

**Comment by aesedepece** [comment]
I have edited it so that it asks for user confirmation in order to avoid accidental close of the app.
