### ISSUE TITLE
Possible to integrate IRC?

### ISSUE THREAD

**Issue by ghost** [loqui/im#730]
I know, it's not that kind of chat-systems, that are currently available in Loqui, however I'd love to see IRC on the list as well.
The enable/disable buttons would make it possible to connect on demand, so that could work :)

There are some IRC-clients for FxOS (for example: FoxkehChat) and it's also possible to use the web-client KIWI. An integration in Loqui is not urgent, but would definitely cool to have (if possible).

Any response is greatly appreciated.

**Comment by ghost** [comment]
At the moment Loqui seems to support XMPP 'networks' only.

Could you try to use a XMPP transport for IRC?

**Comment by mcepl** [comment]
I think the better way is to install some IRC transport on your Jabber server. Some ([ejabberd](https://www.process-one.net/docs/ejabberd/guide_en.html#htoc48)) have such transport built-in, [some](http://prosody.im/) have the [third-party modules](https://github.com/hashbang/mod_muc_irc), some need to use some [external transports](http://spectrum.im/). Generally, in the XMPP world, what can be solved server-side, should be.

**Comment by TitanNano** [comment]
I close this because of the mentioned server-side solutions
