### ISSUE TITLE
Can't connect to my XMPP account.

### ISSUE THREAD

**Issue by githubtefo** [loqui/im#735]
Hi guys.
Since this morning I can't loggin to my XMPP account with Loqui (0.4.2b in ZTE II FxOS 1.3 and also in LG FireWeb FxOS 1.2).
I tried to log in with pidgin and the account is working without problems.
Any idea?
Thanks!

**Comment by TitanNano** [comment]
probably bosh server issues.

2015-05-30 3:16 GMT+02:00 githubtefo notifications@github.com:

**Comment by githubtefo** [comment]
Now I can!
I re-open in case it repeats.
Have a good weekend.

**Comment by githubtefo** [comment]
Guys! Again I can't login to my XMPP account with Loqui.

**Comment by TitanNano** [comment]
for how long are you now not able to login?

**Comment by githubtefo** [comment]
Since this morning I can connect to my XMPP account again. The problem has began at Saturday night.

**Comment by TitanNano** [comment]
yes there are a lot of issues with the server, probably due to heavy usage.
