### ISSUE TITLE
Port Loqui for Tizen

### ISSUE THREAD

**Issue by rhasan516** [loqui/im#739]
Hi Loqui community,
I am new to Javascript and web programming in general. I want to know what would it take to port Loqui for Tizen which uses Webkit.
Has anyone tried to make Loqui work on Chrome? (as it uses webkit too).
When I load the firefoxos version in Chrome none of the javascript seems to work until I remove the version (1.7) from script tags (in index.html). But then I run into a bunch of syntax errors and other issues. But Chrome supports version 1.7 from what I understand (http://stackoverflow.com/questions/300185/google-chrome-javascript-version). So, I am confused as to why these errors are occuring.
If anyone can give me me an idea of what needs to be done to make Loqui work on Chrome it would be great. 

Sorry if I asked a duplicate question.

thanks,
Raquibul

**Comment by TitanNano** [comment]
yes, because we use a lot of destructive assignments. you need to replace these with some old ES 5 syntax.

**Comment by rhasan516** [comment]
can you please give me some example? Thanks TitanNano.

**Comment by TitanNano** [comment]
well, you get the syntax errors in the browser console? they also tell you the line in the source file 😉

**Comment by acidicX** [comment]
Chrome has it's own engine called Blink - it is _not_ webkit anymore. This means that even if loqui would run with Chrome, it does not necessarily need to run on Safari or other webkit-derived browsers.
I think you can enable some ES6 features ("Experimental JavaScript") in Chrome Flags. Maybe that will already make it work?

Also, you could try and compile loqui as a Cordova App for tizen:
https://cordova.apache.org/docs/en/5.0.0/guide_platforms_tizen_index.md.html#Tizen%20Platform%20Guide

**Comment by TitanNano** [comment]
I don't think you will need to make any usage of Cordova. There are just a few destructing assignments and let statements. simply replace them and it should work.

**Comment by rhasan516** [comment]
Thanks acidicX and TitanNano. We are making ES5 compliant code for Chrome. But we are still hitting some issues (even in Firefox) for which I'll open separate issues.
