### ISSUE TITLE
People don't know how to connect to Facebook

### ISSUE THREAD

**Issue by Gioyik** [loqui/im#74]
Hi, 

Seeing the reviews in Marketplace, i can see that people don't know the difference between username on Facebook and the username that the use normally to log in on Facebook. We need to say to people that is not the problem of Loqui that didn't work connecting to facebook accounts. We could add a text with a link in the setup account section that help people to understand how to log in.

I have a fix for this i will make a pull. :)

**Comment by Gioyik** [comment]
I will add it to the milestone @aesedepece, is not a big problem and i have a fast solution. If you disagree, please tell me and remove it from the milestone.

**Comment by Gioyik** [comment]
Sorry, i am seeing that there's a description that helps to understand where to get the user name. Probably we could add a link to this site: 

https://www.facebook.com/help/www/211813265517027

Most of the reviews in the Firefox Marketplace are related to "failed to connect to Facebook"

**Comment by aesedepece** [comment]
Another useful link:
https://www.facebook.com/username

**Comment by Gioyik** [comment]
How can we add the links in the text? I was trying something like this, to use <a> tag to insert the link:

https://github.com/fabi1cazenave/webL10n#innerhtml

But is not clear to me the process with l10n.js, I can't make it work with that example in the link. :S

**Comment by aesedepece** [comment]
I think you can put `<a href="wherever"></a>` directly in the translated text.
Not very elegant but close enough...

**Comment by Gioyik** [comment]
If i add in `l10n/en.ini` :

`facebookNotice = <a href="https://www.facebook.com/help/www/211813265517027">link</a>`

It shows it as a plain text. It's not rendered as link.

**Comment by aesedepece** [comment]
In `scripts/waalt/providers.js`, line 128:

``` javascript
        article.append($('<small/>').text(_(provider + 'Notice')));
```

Change it for:

``` javascript
        article.append($('<small/>').html(_(provider + 'Notice')));
```

**Comment by Gioyik** [comment]
It was my fault, i have changed `text` for `html`, but i didn't save the changes. For that reason it didn't work to me. Now i push a commit with the changes, take a look and tell me if you agree to close the issue, if not you can change whatever you think is necessary.

**Comment by aesedepece** [comment]
af963fcd1b4f766baac840210684340ae933d306 Changes some words in the Facebook notice
548e19bd38f8722e7ecf1b666b26054a19bdc3b3 Introduces some CSS for highlighting the links in the notice text.

This has been closed in just 17h! :clock1:
