### ISSUE TITLE
[WhatsApp] media buttons disappear

### ISSUE THREAD

**Issue by tibtab** [loqui/im#741]
Sometimes, when I'm logged in with Whatsapp and XMPP, the media buttons disappear in Whatsapp. Instead the XMPP flash appears. When I close the connection to XMPP, everything is normal again.

**Comment by TitanNano** [comment]
as a work around, go to the side menu and select your WhatsApp account again.

**Comment by tibtab** [comment]
ok, that works

**Comment by tibtab** [comment]
I think it is fixed by pull #812
