### ISSUE TITLE
Loqui  IM not scroll in conversations FirefoxOS 2.1

### ISSUE THREAD

**Issue by sergioad** [loqui/im#742]
Hello, well; there is not more to say, I can not scroll in the  Loqui IM conversations

**Comment by TitanNano** [comment]
go to your devices developer settings and turn off async zoom and hardware-composer, then reboot. The issue should be gone.

**Comment by sergioad** [comment]
But hardware composition is better for the device, this will not affect it's efficiency?

**Comment by TitanNano** [comment]
yes it is better, but on my deivce I couldn't tell any difference. It's a system bug, I experienced the same issue with Loqui and other messaging apps.

**Comment by sergioad** [comment]
I  see
