### ISSUE TITLE
make landscape mode usable

### ISSUE THREAD

**Issue by acidicX** [loqui/im#744]
I noticed that the change from 0.3 to 0.4 disabled landscape mode. Is there any specific reason for that? Any issue blocking re-enabling landscape mode?

A big keyboard area is often essential for communicating via text... :-)

**Comment by TitanNano** [comment]
go to your App settings and enable it ^^

**Comment by acidicX** [comment]
lol right, I seem to have overlooked that.
Is this a new default setting? Why?

**Comment by TitanNano** [comment]
yes it is. because it is annoying to use loqui in landscape mode. And often when you use the Application in a laying position the UI switches. If you don't agree feel free to disable it.

**Comment by acidicX** [comment]
I rarely have a problem with "wrong" UI switching. Maybe this is a phone-specific issue?
On a Flame it works fine for me.

I agree with the issues in landscape mode though. It's far from ideal - because the keyboard is too high (this is a gaia issue though). What do you think about two improvements:

1) For new users: display a notification the first time loqui is put in landscape mode ("you can enable it in the settings"). New users otherwise might just assume the feature is not available (as in the SMS and email app of gaia), just as I did.

2) Hide the black bar with emoticons and bolt when in landscape. If you have a big keyboard, it's easy enough to enter emoticons (and there are already emoji keyboards for FxOS!). If you really want to send a bolt, you can do it in portrait mode. This leaves way more space for the text.

Should be easy enough, so I could try and make my first contribution ;-)

**Comment by TitanNano** [comment]
1) we disable landscape mode, so you can not show a message when you enter it. Maybe we could show it at first launch, but we don't have anything like this yet.

2) we already have a ticket for this. #687 feel free to work on it. I can assign you.

**Comment by acidicX** [comment]
Sure! I'll give it a try.
to 1) 
You can still read the accelerometer data and detect if the device is held in a certain position. Of course, for performance reasons, this detection should only run as long as the message has not been displayed.

**Comment by TitanNano** [comment]
yea I don't know. sounds a little over the top.
