### ISSUE TITLE
[WhatsApp] media always displayed with grey background

### ISSUE THREAD

**Issue by tibtab** [loqui/im#745]
sent media is always displayed with a grey background and maximum with one green tick, although I know it was recieved.

by the way: could you use a smaller icon for audio messages, i think it's a little bit oversized?

**Comment by TitanNano** [comment]
Works fine for me, sent just now:
![2015-07-16-20-26-40](https://cloud.githubusercontent.com/assets/4500858/8731675/458b5fe6-2bf9-11e5-8b8f-9f89c53f1741.png)

**Comment by tibtab** [comment]
but your picture only has a red border, no red background. Sometimes it 
works, sometimes not. I often don't really know if my chat partner received 
the message
----- Original Message -----
