### ISSUE TITLE
"new messages" message at wrong position

### ISSUE THREAD

**Issue by ghost** [loqui/im#748]
While testing today, i was online with two Loqui IM clients but the receiver didn't received "message37 38 39" i decided to restarted the Loqui IM client, when the client was off i sent 3 more messages "message40 41 42", the messages were received correctly when Loqui IM was started again but the "6 new messages" message was at the wrong position. It should be before "messages37". 
![png image 320 x 510 pixels 2](https://cloud.githubusercontent.com/assets/4523264/8144385/dc8ac918-11dc-11e5-8941-64bc2c179a11.png)

**Comment by TitanNano** [comment]
can you reproduce this?

**Comment by ghost** [comment]
No
