### ISSUE TITLE
not able to change cursor position, copy & paste blocked

### ISSUE THREAD

**Issue by acidicX** [loqui/im#749]
I cannot change the cursor position in the loqui textarea. This also blocks copy&paste actions...
// edit:
This seems to be a regression, works in the current stable release but not in dev.

**Comment by TitanNano** [comment]
yes thats the problem. The copy paste feature does not work properly on
content editable elements.
Lungo is not related to the input field in anyway. We should try to replace
the div with an text input.

2015-06-14 15:51 GMT+02:00 Carsten notifications@github.com:
