### ISSUE TITLE
Cannot close the app

### ISSUE THREAD

**Issue by irisdominguez** [loqui/im#75]
Sometimes I just want to close the app and leave it closed. But everytime I "close" it (close button on the app switcher), it just reconnects by itself after some time. I find this behavior extremely annoying. If I wanted it to run on the background, I would just leave it there running.

It would be nice having the option to close it, or at least to deactivate the accounts, if this kind of zombie behavior is intended.

And thanks for your work ^_^

**Comment by Gioyik** [comment]
Hi,

This is fixed in the next version v0.1.3, there's other issue mentioning this #73, and it is solved, today we push some code to add this feature. Wait the update of Loqui from the Marketplace in a few days to start using this feature.

Thanks for report this issue.

Regards,
Gio
