### ISSUE TITLE
"Quit" is not working

### ISSUE THREAD

**Issue by sumikundu** [loqui/im#750]
Hello, 
I am trying to port Loqui for Tizen but facing some problems,though I have already
changed all destructive assignments.
After signing in google hangout I can't log out.
I am facing the same problem while using Loqui in firefox.
In both case I can't come back to the provider list page.
stack in this page:
![capture](https://cloud.githubusercontent.com/assets/12890898/8154702/a5a02c80-135e-11e5-86ac-6710bf944c7d.PNG)

console for firefox is given :

![loqui_erroe](https://cloud.githubusercontent.com/assets/12890898/8154603/9e4673fa-135d-11e5-9d1f-f8ecdd0cb11b.PNG)

**Comment by TitanNano** [comment]
okay, if you want to see the providers list, tap add accounts. Quit should Quit the Application. This is not possible on Firefox Desktop.
