### ISSUE TITLE
loqui on android just shows a blank screen after using it for a while

### ISSUE THREAD

**Issue by pravi** [loqui/im#751]
I bought a new Yu Yuphoria CyanogenMod phone and I wanted to continue testing loqui im. It worked beautifully after installed, notifications were working too (using fennec from fdroid, and CM 12). But after sometime it just turned blank screen. I removed the app and reinstalled, the same behaviour repeated after some time.

**Comment by TitanNano** [comment]
Yes I had the same problem with a virtual android tablet. I don't really know what's the problem. Maybe it's a platform issue.

**Comment by gargsms** [comment]
I am not very sure if I am following the discussion here.
Loqui is not available for Android AFAIK. 
Are you using the website for testing purposes?
How do you install Loqui on Android? I am about to buy an Android phone too.

**Comment by TitanNano** [comment]
Loqui is available for android. Install Firefox for Android -> navigate to marketplace.firefox.com -> search for loqui -> click install

**Comment by gargsms** [comment]
Ah, like that. Thanks.

**Comment by ghost** [comment]
Is it possible to have a look at the debug console? Not sure if that works for apps on Firefox for Android, too.

https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_for_Android_with_WebIDE

**Comment by pravi** [comment]
It seems to be working now with firefox 40.

**Comment by eklavya** [comment]
This has never worked for me (on Android 5.1 now). I keep on trying every month in the hope that it might have started working. I just get a blank screen as soon as I start the app every time. No matter which firefox version (currently 41).

**Comment by gargsms** [comment]
I can confirm this. I have Cyanogen Mod 12 over Android 5.1.2. Loqui just shows a blue screen and freezes there forever.
I will try to debug this in the next few days.

**Comment by TitanNano** [comment]
:+1: great! I wanted to debug this, but I don't have a android phone for
this.

2015-11-02 11:44 GMT+01:00 Sukant Garg notifications@github.com:
