### ISSUE TITLE
[WhatsApp] when connecting to it after deleting the account, no Groupchats are loaded

### ISSUE THREAD

**Issue by tibtab** [loqui/im#752]
Groupchats are first loaded when someone writes a message in them, but even then they have no name and i can't enter the settings for the groupchat. I think it's some problem with the server because it just happened connecting to the account last saturday without any changes on my side.

**Comment by holztest08** [comment]
The same Problem here:
https://github.com/mozillahispano/openwapp/issues/132

**Comment by TitanNano** [comment]
I will take a look into it as soon as I can.

2015-06-24 14:36 GMT+02:00 holztest08 notifications@github.com:

**Comment by TitanNano** [comment]
fixed see  #755
