### ISSUE TITLE
Can not type Chat message after porting in Tizen

### ISSUE THREAD

**Issue by ayub79** [loqui/im#753]
Hello,
We are porting this loqui IM in Tizen platform. Currently we can login using google account but can not type chat message in Chat window. <div id="text" contenteditable></div> is being used as chat message input. When I tap in that input field, cursor / keypad is not displaying. We have been trying for a long time to find out the cause but still couldn't.

Can anyone please suggest me what can be the reason of this issue?

**Comment by TitanNano** [comment]
Does Tizen support the HTML "contenteditable" attribute?

2015-06-25 5:04 GMT+02:00 ayub79 notifications@github.com:

**Comment by ayub79** [comment]
Dear TitanNano,
thanks for your reply. Tizen supports HTML "contenteditable" attribute.

**Comment by TitanNano** [comment]
Can you give me more details on your issue?

**Comment by TitanNano** [comment]
is this still relevant? otherwise I'd like to close it
