### ISSUE TITLE
"WhatsApp" account create in Tizen

### ISSUE THREAD

**Issue by sumikundu** [loqui/im#754]
Hello,
We are trying to port "Loqui" in Tizen.
It is working fine for Google Hangout but when we trying to create account in "WhatsApp" 
and select "verify via SMS" it shows the following error :
![whtsapp](https://cloud.githubusercontent.com/assets/12890898/8352270/af7779d0-1b55-11e5-9094-3834e79ef5a1.PNG)

**Comment by TitanNano** [comment]
Well it clearly says what's the problem. Tizen doesn't support json response types.
