### ISSUE TITLE
[WhatsApp] Being in a group and receiving messages, but I can't see the members

### ISSUE THREAD

**Issue by 03927e9c** [loqui/im#755]
I've been in a group for a while, and in the top I always saw "8 participants", now all of the sudden I only see "1 participant", and when I click on the group profile picture, I can't access the other options, suchs as "clear chat, mute this chat, exit, etc".

**Comment by tibtab** [comment]
related to #752
but would be nice when someone cares about this problem. It also causes that you can't create a new group.
it may have to do with an update whatsapp made some days ago

**Comment by 03927e9c** [comment]
Well, this only happens with this group in particular, I'm in other 3 groups and this doesn't happen at all.

**Comment by TitanNano** [comment]
It's not that we don't care about the bugs of this Project. But we also have other things to do. As I said in #752 I will take a look at it as soon as possible.

**Comment by 03927e9c** [comment]
Now this just happened with another 2 groups, and it's because they've added another member. Now I just see "1 participant" and I can't access the other options. The same problem.

**Comment by TitanNano** [comment]
yes, it's something in how we process the incoming group info.

**Comment by 03927e9c** [comment]
Any news on when this is gonna be fix?

**Comment by TitanNano** [comment]
no sorry, I'm quite busy recently and I don't know if anyone else has the time to look into this.

**Comment by 03927e9c** [comment]
Ok.

OFF TOPIC: I'm still waiting for the false image reception fix to be on Market Place, can you please tell the guy in charge woud be great to have it uploaded. Thanks.

**Comment by TitanNano** [comment]
I'm sorry but @aesedepece hasn't been around in a while. I'm sure he will take action as soon as he is available.

**Comment by TitanNano** [comment]
fixed
