### ISSUE TITLE
WhatsApp "bad_token" error

### ISSUE THREAD

**Issue by sumikundu** [loqui/im#758]
The following error  is showing when trying to register new account in WhatsApp from Bangladesh

![capture](https://cloud.githubusercontent.com/assets/12890898/8492672/241a1e18-216f-11e5-91ae-544a8d482d3d.PNG)

**Comment by TitanNano** [comment]
new whatsapp version. @aesedepece can you extract the new token?

**Comment by sumikundu** [comment]
Hello ,Is there any update about this issue...

**Comment by TitanNano** [comment]
no not yet, we need the new token

**Comment by ghost** [comment]
@TitanNano could everyone extract it? Is therefore a special phone needed? How to do that?

**Comment by TitanNano** [comment]
@bobcanthelpyou you would need the whatsapp package for the Nokia S40, but  I don't know how it's done. @aesedepece did it the last time. Maybe someone of the CoSeMe team knows how to do it.

**Comment by cmeerw** [comment]
I was just able to register a new UK number in Loqui with our current version...

Having said that, updating the token shouldn't hurt, maybe take the data from https://github.com/WHAnonymous/Chat-API/commit/7b1473718d40df3adc7da4c5791630ec4c299e00

**Comment by kaank** [comment]
Hi,

Please change this class in whatsappapi.dll 

  class WaToken {
        public static string GenerateToken(string number) {
            string s = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1430860548912" + number;
            byte[] bytes = Encoding.ASCII.GetBytes(s);
            byte[] value = MD5.Create().ComputeHash(bytes);
            return BitConverter.ToString(value).Replace("-", string.Empty).ToLower();
        }
        private static List<byte> GetFilledList(byte item, int length) {
            List<byte> list = new List<byte>();
            for (int i = 0; i < length; i++) {
                list.Add(item);
            }
            return list;
        }
    }
