### ISSUE TITLE
ERROR DE AUTENTICACION (FACEBOOK CHAT)

### ISSUE THREAD

**Issue by CesarSilva92** [loqui/im#759]
tengo un ZTE open 2 con firefos os 1.3  cofigure wattsap y hangout pero facebook no logro me sale un mensaje que dice error de autenticacion, cambie la configuracion de mi cuenta  y he tratado generando contraseñas para aplicaciones donde me piden el nombre de la aplicacon probe LoquiIM, loquiim, loqui.im, Loqui IM, pero nada funciona me podrian ayudar?

**Comment by TitanNano** [comment]
Please translate to English!

2015-07-04 3:39 GMT+02:00 CesarSilva92 notifications@github.com:

**Comment by 03927e9c** [comment]
@TitanNano 
"I have zte open 2 with FF OS 1.3, I config'd whatsapp and hangout but I can't mange to work it out with facebook, it says authentication error, I changed my account config and I've tried generating passwords for the applications where it asks the app name, I tried  LoquiIM, loquiim, loqui.im, Loqui IM, but nothing works, can you help me"

**Comment by TitanNano** [comment]
We don't support Facebook anymore.
