### ISSUE TITLE
Messages not being marked as read

### ISSUE THREAD

**Issue by aesedepece** [loqui/im#76]
When you are in a chat and you receive a message from other part:
- The incoming message should automatically be marked as read
- The "unread marker" for the chat should be reset to 0.

(I have experimented this before, and some users complains about it, but I'm not able to reproduce it with last master).

**Comment by Gioyik** [comment]
I can reproduce this with the latest master.

**Comment by aesedepece** [comment]
Does it always happen?

I have double-checked the condition for marking a message as unread and it seems to be OK:

``` javascript
if(!($('section#chat').hasClass('show') && $('section#chat').data('jid') == this.core.from && !document.hidden)){
  chat.core.unread++;
}
```

The logic flow is as follows:

> ¬A ∨ ¬B ∨ C → D
> ¬(A ∧ B ∧ ¬C) → D

A = Chat section is being displayed

``` javascript
$('section#chat').hasClass('show')
```

B = The jid of the chat in front is the same as the one from the incoming message

``` javascript
$('section#chat').data('jid') == this.core.from
```

C = App is backgrounded

``` javascript
document.hidden
```

D = Increment number of unread messages for this chat

``` javascript
chat.core.unread++
```

**Comment by Gioyik** [comment]
Let me check again, cloning again the repo.

**Comment by Gioyik** [comment]
I can reproduce it with the latest in master branch. Other things that i am seeing are:
- If you receive a message in Loqui and you see it, is not marked as read in Facebook.
- Open Loqui from a notification message and continue the conversation. later if you go back to the chat list section it will show you that you have X number of messages not read. The number of message notifications that you receive before and you answer (Probably this depends on #76).

**Comment by aesedepece** [comment]
Have you tested the patch in https://github.com/waalt/loqui/commit/dd8fef9845b4a61ca5e650b29dfe701f9af9c49f ?

**Comment by Gioyik** [comment]
No, i am going to test it.

**Comment by Gioyik** [comment]
OK, I tested and seems that everything is working and the problems before mentioned are not present now with the commit in 76 branch. Ready to push to master :D
