### ISSUE TITLE
[WhatsApp] Audio files are downloaded but won't play

### ISSUE THREAD

**Issue by 03927e9c** [loqui/im#761]
When I click on it, I can see the download progress bar, but when finish and it jumps to the player, it won't play anything.

**Comment by TitanNano** [comment]
Which device are you using?

**Comment by 03927e9c** [comment]
FF OS simulator 2.0

**Comment by TitanNano** [comment]
it's definetely not a issue in our Application. It's looks like an codec
issue to me.

2015-07-12 8:08 GMT+02:00 03927e9c notifications@github.com:

**Comment by 03927e9c** [comment]
I'm on Linux and I can play absolutely every type of file.

**Comment by TitanNano** [comment]
but Firefox can't play every type of file ;-)

2015-07-12 8:35 GMT+02:00 03927e9c notifications@github.com:

**Comment by 03927e9c** [comment]
This happened with I installed 2.0, I was on 1.3 or 1.4 (cant remember) several months ago.

**Comment by TitanNano** [comment]
I can't say whats the actual issue. I just experienced the same problem on
my Peak, but other people told me they can play the files on their Flame.

2015-07-12 8:38 GMT+02:00 03927e9c notifications@github.com:

**Comment by 03927e9c** [comment]
I'm sorry, I don't know what Peak or Flame is.

**Comment by TitanNano** [comment]
oh okay so I'm talking of FxOS devices the Geeksphone Peak and the Mozilla
Flame.

2015-07-12 8:42 GMT+02:00 03927e9c notifications@github.com:

**Comment by TitanNano** [comment]
I close this because it's not an issue of loqui

**Comment by 03927e9c** [comment]
Yes it is, look up the reviews on Market Place, a lot of people complain about the audio files (most of them are in spanish, sorry).

**Comment by TitanNano** [comment]
if you can send me a example audio file you received I will test if I can listen to it okay? just upload it somewhere (drive, drop box, etc.) and post the link on here.

**Comment by 03927e9c** [comment]
Well first I'll have to wait someone to send an audio file, but I'm not sure if I can get the file to then upload it, recording a video or some screenshots might be better. I'll post it.

**Comment by TitanNano** [comment]
yes maybe you can ask someone to send you something. The thing is I need the file. I have to check if I can play it...

**Comment by 03927e9c** [comment]
Two screenshots, I really don't know how I can get the audio file.
![pantallazo-ventana sin titulo](https://cloud.githubusercontent.com/assets/9679446/8782709/a25f4560-2eed-11e5-8957-007aa09dd4c9.png)
![pantallazo-ventana sin titulo-1](https://cloud.githubusercontent.com/assets/9679446/8782714/acafef9c-2eed-11e5-8987-69d19f0d67ab.png)

**Comment by TitanNano** [comment]
it's on your SD card in /loqui/files/.

2015-07-20 19:43 GMT+02:00 03927e9c notifications@github.com:

**Comment by 03927e9c** [comment]
I have FF OS simulator :S

**Comment by TitanNano** [comment]
go to your firefox profile directory, go into your extensions dir and find the simulator directory, there somewhere should be a profile directory and in there you find the storage directory. There you can find your "SD Card".

windows : %appdata%/Mozilla/Firefox/your-profile-dir/extensions/your-simulator-dir/profile/storage/
OS X: ~/Library/Application Support/Firefox/your-profile-dir/extensions/your-simulator-dir/profile/storage/
Linux: ~/.mozilla/Firefox/your-profile-dir/extensions/your-simulator-dir/profile/storage/

**Comment by 03927e9c** [comment]
that linux dir doesnt exits, are you sure?

**Comment by ghost** [comment]
it should exist, my storage directory looks like this:

```
~/.mozilla/firefox/egzt29s7.dev/extensions/fxos_2_0_simulator@mozilla.org/profile/storage
```

**Comment by ghost** [comment]
But normally there is not 'SD Card' within the Firefox OS simulator 2.0

You have to create the 'SD Card' (a folder) manually
https://developer.mozilla.org/en-US/docs/Tools/Firefox_OS_Simulator#SD_card_emulation

**Comment by 03927e9c** [comment]
well i just found all the mp3s in the "fake-sdcard" folder, and I can play them all perfectly. so it is a loqui problem, like i said, go read the reviews on the market place, plenty of people are complaining about this problem

**Comment by TitanNano** [comment]
please provide a file please. It's not a loqui issue since as you said, the files are downloaded perfectly fine. It's the platform which can't play it. I will try if I can play them on my device.

**Comment by 03927e9c** [comment]
what's weird that I could play them when I was on 1.3 or 1.4 (cant remember exactly), here it goes, sorry for the shitty music:
http://www39.zippyshare.com/v/esgImDEC/file.html

**Comment by TitanNano** [comment]
Firefox Flame with FxOS 2.2
![2015-07-22-07-11-53](https://cloud.githubusercontent.com/assets/4500858/8819713/e0655e50-304e-11e5-9b11-091fc207b3c3.png)

**Comment by TitanNano** [comment]
the file is perfectly fine, it's the system which can't play it. We always just hand the audio file to the system media player.
