### ISSUE TITLE
Notifications for Android

### ISSUE THREAD

**Issue by Keelan** [loqui/im#764]
Does this support notifications for android?

If the app is open i get the ding but nothing in my notification bar and nothing if the app is closed

**Comment by TitanNano** [comment]
I think it should yes.

2015-07-14 2:59 GMT+02:00 Keelan notifications@github.com:

**Comment by Keelan** [comment]
Hmm, i cannot get push notifications to work.

If the app is closed and i received a message the only way to know is if i open the app.

**Comment by TitanNano** [comment]
but the message arrives properly? you are connected all the time? Mozilla says that the Notification API is supported by Firefox for Android...

**Comment by TitanNano** [comment]
hello, I didn't get any feedback from you in a while. Is this still relevant?

**Comment by Keelan** [comment]
Hi, I haven't tried it lately to be honest. When I was using this app in would never get notifications.

**Comment by TitanNano** [comment]
> If the app is closed

was the application just not visible, but still running in the background or actually closed / quit?

**Comment by Keelan** [comment]
Closed completely. I was hoping it would run "headless".

**Comment by TitanNano** [comment]
no, the Gecko engine doesn't support headless services by now. 
It will at some point in the future but not at the moment. 

On Firefox OS the app restarts it self in case it gets killed. I don't know if that applies to Android too.
