### ISSUE TITLE
[WhatsApp] Read messages kept getting marked as unread, re-installed Loqui, now lost all my groups

### ISSUE THREAD

**Issue by 03927e9c** [loqui/im#765]
So, today I kept getting already read messages as unread (red numbers), and re installed Loqui to see if that fixes it, but I lost all my group chats.

And then I receive a message from a group, and the group chat appeared... but without the group name (just the long number ID) and the options disabled.

**Comment by TitanNano** [comment]
we aware of the group chat information issue. what about the wrongly marked messages, are these 1-on-1 or group chats?

**Comment by 03927e9c** [comment]
For now just group chats.

**Comment by TitanNano** [comment]
yes thats because whatsapp introduced additional acknowledgments. You don't have just three like sent, received, read but one sent and a received and read for every group member. Loqui doesn't handle them right yet

**Comment by 03927e9c** [comment]
Another thing, I'm receiving messages with a terrible delay, and some messages don't even appear, I can see them in the chat list, but when I click on the chat window they don't appear.

**Comment by TitanNano** [comment]
#719 see this

**Comment by 03927e9c** [comment]
Now I can't receive SMS for activation neither phone call... this keeps getting worse SMH

**Comment by TitanNano** [comment]
See #758
