### ISSUE TITLE
Push new version to marketplace

### ISSUE THREAD

**Issue by cmeerw** [loqui/im#778]
Ok, with all the debugging and protocol fixes I have done over the past week, I think it would make sense to get a new version up on the marketplace. Can people test the current code to see if the stability has improved and if there are any showstopper bugs/breakages.

BTW, is @aesedepece still the only one who can publish new versions on the marketplace?

**Comment by ghost** [comment]
@cmeerw I want to test your changes, but i can't enter my phone number on the 'Setting up WhatsApp' page #779

**Comment by cmeerw** [comment]
I have now reverted the offending layout changes that caused the breakage on older Firefox OS versions

**Comment by bordofr** [comment]
The old issues happening again now if i send a msg then a red box covers it nd the msg doesnt go through at all

**Comment by cmeerw** [comment]
@bordofr what's that issue? What Firefox OS version? (I don't seem to see that issue with either Firefox OS 1.4 or 2.2)...

**Comment by cmeerw** [comment]
Ok, I believe what we currently have in git is better than v0.4.3, so I am intending to push this to the marketplace over the weekend unless someone finds a breakage compared to v0.4.3.

@bordofr please create a new issue including information about your Firefox OS version and screenshots (vague one-line comments are not sufficient to analyse the issue) - I am assuming that the current behaviour is the same as v0.4.3.

**Comment by cmeerw** [comment]
v0.4.4 has been uploaded to the marketplace now, awaiting review...

**Comment by bordofr** [comment]
Am using firefox os 2.1

**Comment by bordofr** [comment]
Hello please on my market place i still have the v 4.3 instead od the
v 4.4 so what do i do

**Comment by cmeerw** [comment]
@bordofr it's still awaiting review as I mentioned.

**Comment by bordofr** [comment]
this is what happens to me now please i cannot whatsapp again because
i cant get the code

**Comment by cmeerw** [comment]
@bordofr what loqui version are you using, what exactly do you mean by "this" and do you have any debug logs?
