### ISSUE TITLE
Can't enter phone number

### ISSUE THREAD

**Issue by ghost** [loqui/im#779]
I want to try the dev branch of Loqui IM but it is not possible for me to enter my phone number at the 'Setting up WhatsApp' screen. The keyboard appear but i can't enter anything.

![im](https://cloud.githubusercontent.com/assets/4523264/9288964/8321a990-4360-11e5-9917-44d2d64ffa5a.png)

Loqui IM 1fd4fc6e5ecdbb841aff9c29b60136bfa8e1584e / Firefox OS Simulator 2.0 and Firefox OS 2.0 device

**Comment by cmeerw** [comment]
It works with Firefox OS 2.2... Just tried with a Firefox OS 1.4 simulator and I can reproduce it there. Seems to be related to commit 38b5df26a62310645a4d38fe8d14dbc0edfecf45 as it's fine if I revert those changes.

**Comment by ghost** [comment]
Firefox OS 1.3 is affected, too
Firefox OS 2.1 is not affected like 2.2
