### ISSUE TITLE
Show actions depending on the account

### ISSUE THREAD

**Issue by Gioyik** [loqui/im#78]
In #44 we talked about a way to show Emojis depending on the account. I think that we need a way to show different actions depending on the account. Same problem with #54 that will only work in Loqui Jabber accounts (By first, probably more people create other services to provide support for WebRTC too), so the Call and Video call only should be work in Loqui Jabber accounts. By the way, i am not sure if #69 will work, for example, in Facebook accounts.

So, you have an idea about how to do this? If you have an idea i can complement an pull a commit with solution.

I was thinking in an ugly solution. Create a section for each kind of account. But it think that there are better ways to do this.

**Comment by aesedepece** [comment]
There is already a method for telling if an account supports certain features:

``` javascript
// Inside account context
var supported = this.supports('feature');
```

It returns `true` when the feature does not appear in the "lacks" array from its matching provider entry in `providers.js`.
I.e., for Facebook:

``` javascript
lacks: ['multi', 'avatarChange', 'statusChange', 'attention', 'rosterMgmt']
```

Even buttons and other interface elements can be showed/hidden depending on support:

``` CSS
section#me.lacks_feature {
  display: none;
}
```

**Comment by Gioyik** [comment]
Hi,

For example, to fix the problem in the Emojis for different accounts. This is a possible solution, not sure if it works, i didn't test:

``` javascript
  emojiRender: function () {
    var ul = $('section#chat article#emoji ul').empty();
    if (ul.supports('EmojiXMPP')) {
      for (var i in EmojiList) {
        var emoji = EmojiList[i];
        var main = emoji[0];
        var li = $('<li/>').append($('<img />').attr('src', 'img/emoji/xmpp/'+main+'.png'))
        li.data('emoji', main);
        li.on('tap', function () {
          Plus.emoji(this.dataset.emoji);
        });
        ul.append(li);
      }
    } else if (ul.supports('EmojiFB')) {
      for (var i in EmojiListFB) {
        var emoji = EmojiListFB[i];
        var main = emoji[0];
        var li = $('<li/>').append($('<img />').attr('src', 'img/emoji/facebook/'+main+'.png'))
        li.data('emoji', main);
        li.on('tap', function () {
          Plus.emoji(this.dataset.emoji);
        });
        ul.append(li);
      }
    }  
    else {
      Lungo.Notification.error(_('NoSupport'), 'exclamation-sign', 3);
    }
  },
```

This will work? To be more clear, this is a correct way to implement: 

``` javascript
var supported = this.supports('feature');
```

For sure, is necessary create a new template for facebook emojis named EmojiFB.

**Comment by aesedepece** [comment]
As of 0.2, the emoji map depends on the account provider.

If we want to use a different emoji map for Facebook, we only have to ad it to `/scripts/waalt/connectors/xmpp.js` and change the emoji provider under Facebook section in ```/scripts/waalt/providers.js´´´.

Now buttons and other interface elements can be showed/hidden in CSS like this:

``` CSS
section#me[data-lacks~='feature'] element.class {
  display: none;
}
```

In other words, this is FIXED! :D
