### ISSUE TITLE
[XMPP] Connect directly via TCP instead of BOSH/Websockets

### ISSUE THREAD

**Issue by cmeerw** [loqui/im#782]
I have been looking into using a TCP socket connection for XMPP transports and actually already had some success (still need to look at StartTLS support...). But I guess the main problem will be configuration as we would ideally want to do a DNS SRV lookup for _xmpp-client._tcp, but I don't think that can be done in Firefox OS (or at least not in all the versions we want to support).

So I guess that only leaves to option of letting the user manually configure the server and provide some good guesses. Any other thoughts? Anyone want to volunteer for the GUI side?

**Comment by cmeerw** [comment]
Ok, looks like it's pretty much impossible to implement StartTLS support on Firefox OS. Well, the TCPSocket object has a "upgradeToSecure" method that should in theory be sufficient, but it isn't. Problem is that as TCPSocket.open wouldn't do a DNS SRV lookup, the hostname you need to pass to TCPSocket.open wouldn't then usually match the hostname in the SSL certificate.

**Comment by cmeerw** [comment]
If anyone is interested: https://github.com/cmeerw/im/tree/update-strophejs but this only works with a very limited number of xmpp servers due to missing DNS SRV support (and you have to manually configure the host in providers.js) - i have filed https://bugzilla.mozilla.org/show_bug.cgi?id=1198006 for this.

**Comment by TitanNano** [comment]
I will take a look at it. I think we should get this to work as soon as the platform gives us the possibility for it.

**Comment by TitanNano** [comment]
can we fake this DNS look up? maybe we can find a service that can do this for us so we don't need to do it on the device.

**Comment by cmeerw** [comment]
Unfortunately, that won't help either as the SSL certificate won't match the host name...

For example, if you have a gmail.com JID you'll want to connect to xmpp.l.google.com port 5222, but the SSL certificate still says gmail.com. So if you pass gmail.com as the host name to TCPSocket you can't connect (as TCPSocket is just doing an A/AAAA lookup on gmail.com), but if you pass xmpp.l.google.com as the host name to TCPSocket the SSL handshake will fail as the name on the certificate doesn't match.

**Comment by TitanNano** [comment]
can we maintain a list of configurations for provides who have a SSL certificate that fits our requirements (SSL certificate domain and actual XMPP server domain need to match if I got that right)?

Our users then would be able to enter their JID and we check if we know the provider. 
If we have a configuration preset we use it. Otherwise we offer the user to enter advanced settings (domain and port) or to continue by connecting through the BOSH server.

**Comment by cmeerw** [comment]
That would be an option, just not sure if it's worth the effort... (it won't work for Google Talk - and that's probably our biggest problem because they don't like the unexpected connection from the BOSH server). Another option would be to check if a Jabber server offers its own BOSH or Websocket server to connect to.

BTW, I should hear back from Mozilla next week if they can help in some way (maybe by escalating the issue internally - although I don't expect any short-term solution)...

**Comment by cmeerw** [comment]
I have implemented a simple service for [XEP-0156](http://xmpp.org/extensions/xep-0156.html) _xmppconnect DNS lookups at http://xmppconnect.cmeerw.net, for example http://xmppconnect.cmeerw.net/jabber.at.json returns:

```
{ "links": [
  {
    "rel": "urn:xmpp:alt-connections:websocket",
    "href": "wss://http.jabber.at:443/ws/"
  },
  {
    "rel": "urn:xmpp:alt-connections:xbosh",
    "href": "https://http.jabber.at/http-bind/"
  }
]}
```

**Comment by TitanNano** [comment]
that looks good. can we also add the direct TCP url?

**Comment by cmeerw** [comment]
I have now added the SRV lookup result as well, e.g.

```
{ "links": [
  {
    "rel": "urn:xmpp:alt-connections:tcp",
    "href": "tcp:xmpp.jabber.at:5222"
  },
  {
    "rel": "urn:xmpp:alt-connections:tcp",
    "href": "tcp:xmpp.jabber.at:443"
  },
  {
    "rel": "urn:xmpp:alt-connections:websocket",
    "href": "wss://http.jabber.at:443/ws/"
  },
  {
    "rel": "urn:xmpp:alt-connections:xbosh",
    "href": "https://http.jabber.at/http-bind/"
  }
]}
```

**Comment by TitanNano** [comment]
yes really cool.

**Comment by cmeerw** [comment]
I have checked in some code for this in #905 - this needs some testing...

**Comment by bobcanthelpyou** [comment]
I tried several XMPP accounts to connect to ```https://bosh.loqui.im/``` and ```https://jabber.ccc.de/http-bind/``` (needs permanent exception for the self signed certificate, first), but it doesn't work

Is there an easy way to enable the debug output without an account?
