### ISSUE TITLE
otr still broken on 0.4.4a

### ISSUE THREAD

**Issue by pravi** [loqui/im#783]
Loqui on android and conversations. OTR is enabled in loqui but conversations received plain text message only. Conversations showed waiting untill I turned off and turned on otr. Conversation showed the message as delivered, but loqui did not show any message. Even after clearing chat and turning off otr, no messages are shown in loqui. So not just otr, message receiving is broken completely.

**Comment by cmeerw** [comment]
@pravi Any chance we can get some debug logs for this?

**Comment by cmeerw** [comment]
Just tested OTR here and it's working fine, so we need some logs to figure out why it's not working for you.

**Comment by tibtab** [comment]
I thought as well that it is broken, but it's working it's only showing the messages gray with a red border around.
Maybe that could be fixed? I never saw an Otr-message by now which was marked properly with a red background.

**Comment by TitanNano** [comment]
@tibtab if you give your jid to me I'll send you some test messages
and figure out whats wrong.

2015-08-28 16:53 GMT, tibtab notifications@github.com:

> I thought as well that it is broken, but it's working it's only showing the
> messages gray with a red border around.
> Maybe that could be fixed? I never saw an Otr-message by now which was
> marked properly with a red background.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/loqui/im/issues/783#issuecomment-135831102

## 

-- Jovan

**Comment by tibtab** [comment]
testaccountfortib@jabber.de

**Comment by TitanNano** [comment]
okay, I sent you a test message.

**Comment by tibtab** [comment]
okey, answered you. Do you received it?

**Comment by TitanNano** [comment]
no, unfortunately not. I'm working on some patches because a few things with OTR are broken.

**Comment by TitanNano** [comment]
this should be fixed by d99cdcef
