### ISSUE TITLE
[whatsApp] "last seen" shows false time and date

### ISSUE THREAD

**Issue by tibtab** [loqui/im#784]
The "last seen" notice shows false time and date, which additionally changes after each quit and reentering the chat.
For example a friend wrote a message to me on the 23.08 at 10:12 but the "last seen" notice shows "31.07 at 17:32"

**Comment by cmeerw** [comment]
I have noticed that one too, but we are just showing what we are getting from WhatsApp - and it appears we are getting random numbers from WhatsApp

**Comment by tibtab** [comment]
What about stopping to show these random numbers until you recognized what's 
the problem, it's a little bit confusing whan you see false dates.

**Comment by cmeerw** [comment]
fixed in #785
