### ISSUE TITLE
Add support to Google Apps accounts

### ISSUE THREAD

**Issue by Gioyik** [loqui/im#79]
Hi,

We have at Mozilla Hispano the members accounts @mozilla-hispano.org that are linked to the Google Apps service. So we can use Hangouts and thinks like that. At this moment you can't log in with an account linked to Google Apps Service. For example:

I like to log in with this account:

gioyik@mozilla-hispano.org

but it recognizes it as my other account:

gioyik@gmail.com

Because it deletes the @mozilla-hispano.org thanks to the auto fill function. This happens trying to log in in the Google Hangout section.

Regards,
Gio

**Comment by aesedepece** [comment]
I suggest two different approaches for fixing this:
1. Removing this line from Hangouts entry in `/scripts/waalt/providers.js`:

``` javascript
      autodomain: 'gmail.com',
```
1. Adding a new provider entry for Google Apps.

I vote for number 2 because it does not break the autodomain functionality for Hangouts.

**Comment by Gioyik** [comment]
Yes i was thinking the same, let me make the changes and make a push with a fix for this. Btw, i will update devel branch that is outdate.

**Comment by aesedepece** [comment]
First progress → https://github.com/waalt/loqui/commit/e6c2d3e0329450e1c61fe908a88dc4ca984eae35
I have yet to make the icons.

Can you test it?

**Comment by Gioyik** [comment]
I was working in the first progress too :( I will make a push when you sent the yours :P

I tested and i can't log in with my @mozilla-hispano.org account or with any other Google Apps account. For the icon i think that is more convenient keep using the same Hangouts icon, because is same the Gmail chat and the Google Apps chat, it's Hangouts! (Google monopoly). It will confusing if has a different icon, and for people that have email accounts linked to Google Apps will know where to log in. :)

Regards,
Gio

**Comment by aesedepece** [comment]
Please see https://github.com/waalt/loqui/issues/32

**Comment by aesedepece** [comment]
I'm disabling this for v0.1.4, let's get it ready for next release when it has been tested enough.

**Comment by iamed2** [comment]
Now that releases have moved along, can we get Apps support? I had thought I had problems connecting but I guess this feature was just not available.

**Comment by mcorteel** [comment]
I have the same problem, I can't connect to a google apps account (which is silly because it uses normal gtalk servers, only with "user@domain.ext" as a login instead of "user" on the "domain.ext" server...).

**Comment by Gioyik** [comment]
Yes, we know about this issue. We are working on implement OAuth authentication to solve this and update our way to connect to servers.

**Comment by Gioyik** [comment]
The fix for this is talked on #122. Lets discuss it there.

**Comment by Cabalo** [comment]
Currently I can connect as described in https://translate.google.es/translate?sl=es&tl=en&js=y&prev=_t&hl=es&ie=UTF-8&u=http%3A%2F%2Fwww.mabingenieros.com%2Fconversar-mediante-gtalk-o-hangouts-con-firefox-os.htm&edit-text=
but I wish I could do it without any configuration on my domain 
How is the situation now?
