### ISSUE TITLE
Updater

### ISSUE THREAD

**Issue by tibtab** [loqui/im#790]
Would it be possible to provide any way, that you don't have to remove and reinstall the program each time there is an new update?

**Comment by cmeerw** [comment]
It should get properly updated via the Firefox Marketplace - is that not working for you? What device/firmware are you using?

**Comment by tibtab** [comment]
Oh ok, when I open the Marketplace it shows me that the programm is 
downloaded  and I see that there is a new version at the marketplace, but 
there is only an "open"-button.
Im using ZTE OpenC with FOX 1.3. I think Im using the current version of the 
Marketplace.

**Comment by cmeerw** [comment]
Ok, this is a known issue with the ZTE Open C firmware - the Settings app is supposed to have a "Check for Updates" button, but this has been removed by ZTE, also see https://bugzilla.mozilla.org/show_bug.cgi?id=1030626

See comment 18 https://bugzilla.mozilla.org/show_bug.cgi?id=1030626#c18 in that bug report - as this can only be done by a certified app, you'll need to install it from your local PC (it can't be distributed via the marketplace).

**Comment by tibtab** [comment]
Amazing, thank you! :)
