### ISSUE TITLE
Chat notifications will not open Loqui

### ISSUE THREAD

**Issue by Gioyik** [loqui/im#80]
You receive the notifications of 10 messages, You need to click/touch the last message notification to open Loqui and answer the conversation. If you click the any other of the 9 notifications before the last notification message, Loqui will not open.

Example to example better the problem:
- Notification 1 = First message notification, If you click/touch this message notification Loqui will not open.
- Notification 2 = Second message notification, If you click/touch this message notification Loqui will not open.
- Notification 3 = First message notification, If you click/touch this message notification Loqui will not open.
- Notification 4 = Same behavior here.
- Notification 5 = Same behavior here.
- Notification 6 = Same behavior here.
- Notification 7 = Same behavior here.
- Notification 8 = Same behavior here.
- Notification 9 = Same behavior here.
- Notification 10 = Last message notification. If you click/touch this message notification Loqui will open correctly now.

Not sure if this is a problem of Loqui or just a problem of Firefox OS.

**Comment by aesedepece** [comment]
I think this is caused by holding last notification in `App.lastNot`. When a new notification is created, it overwrites the previous one and thus it loses its events.

**Comment by bdcomp** [comment]
WFM - received 3 notifications, Loqui IM opened after a click on the first notification.

0.2.5 on GP Peak, B2G 1.1.1.0hd-GP (stable).

**Comment by bdcomp** [comment]
While just yesterday I tried to reproduce the issue, just now, surprisingly something similar happened:
I received 7 Loqui IM notifications and after it a SMS notification.
All Loqui IM notifications were grey (like inactive) and clicking on all of them, even the last Loqui IM notification not opened Loqui IM.
Only the last received SMS notification opened SMS app.
