### ISSUE TITLE
Chat section UX improvement

### ISSUE THREAD

**Issue by TitanNano** [loqui/im#809]
I'm going to change the chat window to this:
![2015-09-05-20-46-41](https://cloud.githubusercontent.com/assets/4500858/9701298/fbd4d2fe-5422-11e5-8440-65319792f68a.png)
![2015-09-05-20-46-55](https://cloud.githubusercontent.com/assets/4500858/9701299/fbd673ac-5422-11e5-8e8f-71a90b0b4ce5.png)
![2015-09-05-22-57-27](https://cloud.githubusercontent.com/assets/4500858/9701300/fbe6c72a-5422-11e5-99b2-0526ddc271b5.png)
Feel free to leave comments. If there is no objection i will land the patch in three days.

**Comment by FabianOvrWrt** [comment]
This looks really good, but the emoji should be a bit bigger because sometimes it's hard to select them on the One Touch Fire.

**Comment by TitanNano** [comment]
okay, I'll increase the size a little,

**Comment by cmeerw** [comment]
Doesn't seem to render correctly for me - this is how it looks like on my Firefox OS 2.2 phone:
![2015-09-09-19-24-57](https://cloud.githubusercontent.com/assets/6730977/9770596/e25a4e7c-5728-11e5-9ba6-8bfd9bfef922.png)
![2015-09-09-19-25-20](https://cloud.githubusercontent.com/assets/6730977/9770612/efaebdce-5728-11e5-88b7-3c18d161c3ed.png)

**Comment by TitanNano** [comment]
oh oh seems there is something wrong with the google font. Which phone / FxOS version do you have?

**Comment by TitanNano** [comment]
I just tried the current version with the simulators for 1.3, 1.4, 2.0 and 2.1 it works with every one.

**Comment by cmeerw** [comment]
Sorry, my fault, somehow the style sheet got missing...

**Comment by TitanNano** [comment]
:+1: alright
