### ISSUE TITLE
Implementation of Telegram

### ISSUE THREAD

**Issue by Sergio-Muriel** [loqui/im#811]
Hi,

It would be great to integrate the free "whatsapp" alternative: telegram.
It has an open API, so i guess it could be easyier than the whatsapp implementation.

https://core.telegram.org/

**Comment by TitanNano** [comment]
there is already a great Telegram port for FxOS know as [Webogram](zhukov/webogram). 
Implementing a connector for Loqui would be redundant and a waste of time.

**Comment by rodneyrod** [comment]
Has this issue been looked at since? FFOS is no longer being developed and I don't think Ubuntu has a native Telegram client.

**Comment by nfsprodriver** [comment]
Of course UT has a native Telegram Client. It is developed by the Ubuntu team and deployed to the stock system. It's one of the best UT apps.
