### ISSUE TITLE
[WhatsApp] Strange order of chats and crash of loqui

### ISSUE THREAD

**Issue by tibtab** [loqui/im#818]
The order of chats is really strange for me. There are three sections: In the first there are some of the personal chats in right order (newest at the top), in the second are most of the group chats without any order and in the third are the other personal chats and a few group chats in right order. I have this order when I selected the whatsapp account in the list, and when I open loqui (whatsapp is the first account for me which is loaded).
So when I opened loqui I first have this order, then the xmpp account gets connection and I have a new order (with the whatsapp list still open). Then I usually receive the messages for whats app, still with the second order and the chat with the most messages jumps to the top and so on, so I think I have the right order then, but I can't send media. So I have to select whatsapp in the menu and I get the strange order I described above. But before I can do this loqui usually crashes

**Comment by TitanNano** [comment]
it would help if you'd provide screenshots

**Comment by tibtab** [comment]
The first section and the top of the second 
![2015-09-12-15-02-08](https://cloud.githubusercontent.com/assets/11966750/9831659/5e864d82-5960-11e5-8508-a0d674feeba8.png)
a piece of the second section in the middle
![2015-09-12-15-02-34](https://cloud.githubusercontent.com/assets/11966750/9831660/5fbfb81e-5960-11e5-8f51-54316f17f49d.png)
The third section at the bottom
![2015-09-12-15-03-03](https://cloud.githubusercontent.com/assets/11966750/9831661/61146b92-5960-11e5-8173-47750df862ff.png)

**Comment by TitanNano** [comment]
okay, wait until 0.4.5 and then tell me if the issue still persists.

**Comment by tibtab** [comment]
When do you will push 0.4.5 to the marketplace?

**Comment by TitanNano** [comment]
@cmeerw needs to do that, but maybe he already did and we're just waiting for the review.

**Comment by cmeerw** [comment]
I have uploaded 0.4.5 last Friday and it's still in the review queue...loqui/im wrote:@cmeerw needs to do that, but maybe he already did and we're just waiting for the review.

**Comment by cmeerw** [comment]
0.4.5 has now been approved on the marketplace

**Comment by tibtab** [comment]
same with 0.4.5

**Comment by ghost** [comment]
I could also confirm that order behavior of chats and group chats

The easies way to reproduce that is opening loqui offline (Firefox OS not connected) and go online after that.

e.g. order offline
- Chat 3 09/17
- Groupchat 2 09/16
- Chat 2 09/15
- Chat 1 09/15
- Groupchat 1 without date

e.g. order online:
- Groupchat 2 09/16
- Groupchat 1 without date
- Chat 3 09/17
- Chat 2 09/15
- Chat 1 09/15

The order changed but no new messages where received

**Comment by TitanNano** [comment]
I can't reproduce this since I don't have empty groups. I hope 05477b3 will fix this.

**Comment by TitanNano** [comment]
is it okay now?

**Comment by tibtab** [comment]
Because I don't want to lose all my chat histories I'm still using version 0.4.6a for whatsapp. So I still have this problem.

**Comment by TitanNano** [comment]
you can use `App.exportData()` to backup your userdata.

**Comment by tibtab** [comment]
Okay thanks, but after exporting the data and then importing it in the self compiled loqui version with `App.importData()`
I still have the same strange order of groups and chats. Furthermore I get this error:

```
An IndexedDB transaction that was not yet complete has been aborted due to page navigation. async_storage.js:10:0
Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. material-icons.css:33:25
Selector expected.  Ruleset ignored due to bad selector. material-icons.css:39:0
Selector expected.  Ruleset ignored due to bad selector. material-icons.css:45:0
Selector expected.  Ruleset ignored due to bad selector. material-icons.css:49:0
Unknown property 'will-animate'.  Declaration dropped. chungo.css:216:14
Error in parsing value for 'height'.  Declaration dropped. index.css:358:28
Unknown property 'user-select'.  Declaration dropped. index.css:809:13
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create quo.js:25:6
TypeError: setting a property that has only a getter dsa-webworker.js:7:4
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ l10n.js:125:0
```

**Comment by ghost** [comment]
Installed v0.4.6a today and can't reproduce the behavior as i reported before. But maybe the issue of @tibtab is different. All chats seem to be in the correct order by date and time (but i only have a very small amount of chats and groups).

**Comment by TitanNano** [comment]
yes same here.

**Comment by tibtab** [comment]
Maybe I have to delete the accounts and reconnect them because loqui is porting the old false chat order when updating?

**Comment by TitanNano** [comment]
No, we sort the chats each time a account gets saved. And we save the account when ever we update a chat.

**Comment by TitanNano** [comment]
For sorting we use the latest time stamp or 0.

**Comment by tibtab** [comment]
Hm ok, because the order of chats gets more and more confused the longer I'm using loqui (since the last delete of all chats through new installation)

**Comment by TitanNano** [comment]
@tibtab this problem still exists?

**Comment by tibtab** [comment]
After i deleted the empty groups, the problem with the strange order of groups dissappeared. But loqui still sometimes crashes.loqui/im schrieb:@tibtab this problem still exists?

**Comment by TitanNano** [comment]
which device are you using?

**Comment by tibtab** [comment]
OpenC with fxos Prerelease 2.2

**Comment by TitanNano** [comment]
@tibtab apps on FxOS usually "crash" because they killed due to memory pressure (there is no free RAM left). Could this be possible in your case?

**Comment by cmeerw** [comment]
@tibtab I noticed crashes on my Open C with 2.2 as well - but no more crashes with 2.6 nightlies.loqui/im wrote:OpenC with fxos Prerelease 2.2

**Comment by tibtab** [comment]
I use the mozfr-builds, do you also use them? I'm not sure if they are still developed. The last file was from the 25 of November.loqui/im schrieb:@tibtab I noticed crashes on my Open C with 2.2 as well - but no more crashes with 2.6 nightlies.loqui/im wrote:OpenC with fxos Prerelease 2.2

**Comment by cmeerw** [comment]
I am also using the mozfr builds (I believe the 2.2 branch builds stopped sometime in August) - there are still daily builds for 2.6 in http://builds.firefoxos.mozfr.org/opencebay/nightly/ (I am currently using the nightly from 23rd December)

**Comment by tibtab** [comment]
Ok thanks, are the nightly builds more or less stable?loqui/im schrieb:I am also using the mozfr builds (I believe the 2.2 branch builds stopped sometime in August) - there are still daily builds for 2.6 in http://builds.firefoxos.mozfr.org/opencebay/nightly/ (I am currently using the nightly from 23rd December)
