### ISSUE TITLE
Loqui deleted everything

### ISSUE THREAD

**Issue by tibtab** [loqui/im#830]
After restarting my phone, Loqui forgot all accounts (and messages). OpenC with fxos 2.2. Loqui 0.4.5a

**Comment by TitanNano** [comment]
can you provide a log? There has to be an error!

**Comment by tibtab** [comment]
ok when I start loqui this appears in the WebIde:

```
asyncStorage: can't open database: QuotaExceededError 
    at withStoreOnError (app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/mozilla/async_storage.js:14:8) async_storage.js:14:8
withStoreOnError() async_storage.js:14
```

**Comment by TitanNano** [comment]
Good! I assumed this. This means your loqui DB reached it maximum size. To fix this you can open "Device Preferences" and search for quota. Add some zeros to each of the numbers and restart your device. Then loqui should be able to access the DB again.

**Comment by tibtab** [comment]
Do you mean in the WebIde?
This?:
dom.indexedDB.warningQuota  
dom.quotaManager.testing  
dom.storage.default_quota  
offline-apps.quota.warn

**Comment by TitanNano** [comment]
yes, I can't remember the initial values, but if you increase some of the numbers it will work again. I think it was default_quota.

**Comment by tibtab** [comment]
Ok thanks, its working again now
