### ISSUE TITLE
[Whatsapp] After receiving a sound, next typed message does not appear in chat 

### ISSUE THREAD

**Issue by jcerdan** [loqui/im#839]
Hi,

After receiving a sound message (don't know if the same for video...), if I type a message, it does not appear on chat window. I suspect the message is sent.

I just have activated the console and in the next error I will expand this issue.

best,

**Comment by FabianOvrWrt** [comment]
This issue also affects me. But if you close the app before sending the message it works normally. I don't know if that's useful at all, but I think it's something to consider.

**Comment by TitanNano** [comment]
We need a log.

**Comment by TitanNano** [comment]
duplicate of #847 / that one is more general and covers all media types
