### ISSUE TITLE
Startscreen - Not more!?

### ISSUE THREAD

**Issue by petzichen** [loqui/im#845]
Hi,
in last days I installed Loqui more than once. All time I can't start the app correctly: I can see only the Loqui-Logo....
It's looking like this, sothat I can't set up a new account (and more):
http://l1nks.de/NVR3z

[Device: Mozilla Flame]

**Comment by TitanNano** [comment]
please provide some logs.

**Comment by petzichen** [comment]
TypeError: App is undefined bindings.js:91:3
TypeError: App is undefined bindings.js:97:12
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create quo.js:25:7
ReferenceError: Renderers is not defined blaze.js:18346:5
TypeError: setting a property that has only a getter dsa-webworker.js:7:5
unreachable code after return statement coseme.js:6989:10
unreachable code after return statement coseme.js:7000:10
ReferenceError: Blaze is not defined app.js:15:3
ReferenceError: Blaze is not defined account.js:752:3
TypeError: App is undefined bindings.js:277:7
TypeError: Template.settings_features is undefined helpers.js:5:1
TypeError: Template.settings_features is undefined events.js:5:1
TypeError: App is undefined xmpp.js:5:1
TypeError: App is undefined coseme.js:5:1
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ l10n.js:125:0
[l10n] #contactAdd is undefined. l10n.js:68:7
TypeError: App is undefined bindings.js:27:5

**Comment by TitanNano** [comment]
how did you install the application?

**Comment by petzichen** [comment]
1. Downloaded .zip here on github
2. Exracted the files
3. Copied the manifest.webapp-file from /platform/firefoxos/ to /src/ - So as always...
4. WebIDE -> New Project -> Install
   -> As far as I can see successfull... Only that I can't see anything except screenshot on the screenshot.

**Comment by TitanNano** [comment]
you can't do that. You need to build the source. See the wiki for that.

**Comment by petzichen** [comment]
Damn... Sorry 😫
