### ISSUE TITLE
Whatsapp: communication problems after sending/receiving multimedia

### ISSUE THREAD

**Issue by MaleCat** [loqui/im#847]
This problem occures since upgrading Loqui from 0.4.4 to (current) 0.4.6, mobile is a ZTE Open C with FireFox OS 1.3.0.0 running

Each time after a multimedia part (voice message, or video or pic and so on) in whatsapp was sent or received no further "usually" sending or receiving is possible or is not properly processed.

Everything is fine again after the app was terminated and started new again.

How can be solved this?

Thanks a lot for developing this app. It was the most stable one to work with whatsapp at my cellphone and became a favorit of mine

**Comment by TitanNano** [comment]
I guess there is some error happening at receiving the media. can you provide us logs around the time you receive the media?

**Comment by cmeerw** [comment]
hopefully fixed (at least seems to work for me now), please retest

BTW, I didn't see any issue with sending media, only for receiving (actually downloading)...
