### ISSUE TITLE
whatsapp

### ISSUE THREAD

**Issue by mahmoudmohey** [loqui/im#852]
The program can't work without wi-fi and it can't work with mobile internet data

**Comment by TitanNano** [comment]
Loqui works pretty fine with mobile data.

**Comment by mahmoudmohey** [comment]
On alcatel one touch klif it doesn't work :(

**Comment by cmeerw** [comment]
In what way doesn't it work? log files? screenshots? any other relevant details?

**Comment by mahmoudmohey** [comment]
It cannot send anything
on alcatel one touch klif

**Comment by TitanNano** [comment]
are you connected?

**Comment by mahmoudmohey** [comment]
I'm using all programs but loqui no

**Comment by jesobreira** [comment]
You mean... you can't send messages? What about receiving? Could you register?
