### ISSUE TITLE
[All]Not working

### ISSUE THREAD

**Issue by itsfolf** [loqui/im#855]
When I add an account "sychronizing" disapear after some time and nothing appens

**Comment by itsfolf** [comment]
And one question: loquiim use/send notifications?

**Comment by ghost** [comment]
Which FirefoxOS version and device do you use? Could you reproduce the same behavior with FirefoxOS Simulator?

**Comment by itsfolf** [comment]
Im using firefox OS1.1 because I can't update, im waiting for firefox2.5 (november) to try to update again, I will try FirefoxOs simulator when I turn on the PC

**Comment by itsfolf** [comment]
@bobcanthelpyou I try in the Simulator and it not works too.

**Comment by TitanNano** [comment]
which provider is your account from?

**Comment by itsfolf** [comment]
@TitanNano  I tryed Facebook and Google Hangouts (I alredy know that facebook not work more), but Hangouts isn't working too,

**Comment by TitanNano** [comment]
@checkplys I just tried it. I can setup my google account with Loqui. Maybe google is blocking the connection for your account.

**Comment by TitanNano** [comment]
@checkplys check this if you have issues with google hangouts https://github.com/loqui/im/wiki/FAQ#suspicious-login-report

**Comment by itsfolf** [comment]
I'm trying now to setup Whatsapp now and It says "Could not send SMS!"

**Comment by cmeerw** [comment]
Can you get a console log from the WebIDE and let us know which country you are in please?

**Comment by itsfolf** [comment]
I don't know how to see the log, and I'm from Portugal

**Comment by cmeerw** [comment]
If you are using the simulator you just need to select the app in the WebIDE (there is a drop-down list on the left hand side - and maybe then also click on the debug app icon)

**Comment by comzeradd** [comment]
Same happens here. I'm on FxOS 2.5 (prerelease) and I see "Connecting" and sometimes "Synchronizing Contacts" and then nothing. I just tried this on Simulator (2.2) and I get the same behavior.

Through the console I can see that a connection is being made with bosh.loqui.im but nothing ever returns.

**Comment by TitanNano** [comment]
yes the bosh server is down see #878

**Comment by TitanNano** [comment]
but WhatsApp should work fine.

**Comment by comzeradd** [comment]
Yes, I'm using loqui specifically for xmpp.

**Comment by cmeerw** [comment]
What XMPP server are you using (or trying to use)?

**Comment by comzeradd** [comment]
Self-hosted. It's based on Prosody.

**Comment by cmeerw** [comment]
@comzeradd Depending on how your SSL certificates are set up (see https://bugzilla.mozilla.org/show_bug.cgi?id=1198006) you might be able to connect directly to your server (by setting 'host' in provider.js to your server, e.g. 'tcp:yourserver.example.com')
