### ISSUE TITLE
[Whatsapp] Cannot Receive or Send VCard (Contact Card)

### ISSUE THREAD

**Issue by tripad** [loqui/im#857]
(I hope this is not a duplicate issue)
If someone sends a contact card it comes as a blank message.

Device: ZTE Open C
2.5.0.0 Nightly

**Comment by cmeerw** [comment]
also see #664
BTW, I have already worked on this and I think I have the functionality working (just need to test interoperability with a real WhatsApp client)...

**Comment by tripad** [comment]
@cmeerw send me build if have something ready - i can try and test
