### ISSUE TITLE
[im] provide line breaks

### ISSUE THREAD

**Issue by tibtab** [loqui/im#866]
this would be nice for the formatting of messages

**Comment by TitanNano** [comment]
:+1:

**Comment by gargsms** [comment]
I tried a solution once, and added an eventListener for the enter key.It worked in my Flame and the simulator I tested on. Maybe there is a commit in there somewhere, too.
But @TitanNano reverted it because it didn't work in his Keon, or ZTE C maybe.Let's see. I will look for alternative, better solutions.

```
 On Monday, 2 November 2015 7:52 PM, Jovan Gerodetti <notifications@github.com> wrote:
```

**Comment by TitanNano** [comment]
As far as I remember there was an issue with older versions of Gecko where the Shift property wasn't set.
Do you want to re implement it? Otherwise I'll implement some solution.

**Comment by gargsms** [comment]
If you want, it's great. I will see for alternatives.

**Comment by cmeerw** [comment]
This change completely breaks rendering of media messages in chats with error "TypeError: html.replace is not a function" (message.js, line 505). Reopening...

**Comment by TitanNano** [comment]
@Honk2 can you please look into this?

**Comment by Honk2** [comment]
Ok.

**Comment by Honk2** [comment]
@TitanNano I just opened a pull request with a sulotion

**Comment by cmeerw** [comment]
seems to work for me now, closing

**Comment by tibtab** [comment]
not working with current pull any more

**Comment by tibtab** [comment]
sry made a mistake, I forgot to activate it before
