### ISSUE TITLE
[XMPP] No connection: Using BOSH instead of WS

### ISSUE THREAD

**Issue by ghost** [loqui/im#878]
When I try to connect to my XMPP server, the button turns yellow and stays that way, Loqui never connects.

Checking the console, I that the stanza includes xmlns.xmpp='urn:xmpp:xbosh'
For a websocket connection, it should be urn:xmpp:alt-connections:websocket,as far as I know.

I have never turned on BOSH on my server since I switched from ejabberd to Prosody. It worked fine with Loqui up until maybe a few days ago (stopped working already before today's update).

Why is it not using websockets (anymore)? Is there a way to make it manually do that?

**Comment by TitanNano** [comment]
The web socket server wasn't working properly so we went back to BOSH.
@all The BOSH server and the website (loqui.im) are down for a few days now. What should we do? Can anyone fix this? Can we find an alternative?

**Comment by cmeerw** [comment]
I guess the best we can do at the moment is to at least let the user configure the ws/bosh server manually (with some help of https://github.com/loqui/im/issues/782#issuecomment-140682939)
