### ISSUE TITLE
[XMPP] contacts not imported

### ISSUE THREAD

**Issue by oschlies** [loqui/im#88]
Hello, I would like to report the follwing bug: when you register with an existing xmpp account, existing contacts are not imported. the contact list stays totally empty.

**Comment by aesedepece** [comment]
What device / FxOS version / XMPP provider?

Thanks!

**Comment by oschlies** [comment]
Hello,

Thanks for the quick reply! -device is an Alcatel One Touch Fire, FxOS version 1.1.0.0, XMPP provider: jabber.ccc.de

**Comment by Gioyik** [comment]
Do you have this problem in latest versions? Could you give us a log or logcat that shows us what could be happening?
