### ISSUE TITLE
I cant scroll inside the chat window

### ISSUE THREAD

**Issue by gutentach** [loqui/im#881]
Open the window with the messages/chat window (whatssapp) the scroll bar disappear after one second. i cant scroll back to the older messages. This happend since the first day  loqui 0.4.5 (?)
It this general? Can you Help?

Thank you 

Loqui Im 0.4.9b
Zte open c     B2g 2.1   http://builds.firefoxos.mozfr.org/doc/en/devices/zte-open-c-eu

**Comment by TitanNano** [comment]
disable Hardware Composer, reboot and try again. In most cases this fixes the issue.

**Comment by gutentach** [comment]
Hardware composer was disable. I enable hardware composer and reboot. Dont help. Disable and reboot the same. I can not scroll

**Comment by TitanNano** [comment]
This is a platform issue. You can try to enable / disable other graphic features such as low quality rendering and async zoom.

**Comment by gutentach** [comment]
Yes, yes yes. Now it works. -)
THANK YOU

**Comment by TitanNano** [comment]
No problem.

**Comment by pkay22** [comment]
TitanNano please I have the same problem I can't scroll down my whatsapp chats please help me out thanks

**Comment by pkay22** [comment]
My loqui version is 0.5.7a
