### ISSUE TITLE
Bugs on FxOS 1.1

### ISSUE THREAD

**Issue by jesobreira** [loqui/im#894]
I tried running it on LG Fireweb (Firefox OS 1.1 - the only version of FxOS being sold in many countries, like mine) and I noticed some bugs. No sure if these bugs exist only on v1.1. I've used the latest version as of today (just downloaded it).
- **The chat log does not show:** when chatting or opening a chat with someone, it's not possible to see the sent/received messages. The chat history is always blank. However, when I send a message, my phone plays a song and the message is sent (but I can't see it, while my contact can read it).
- **Unable to receive messages:** I can't receive any message. No notification is showed, no sound is played. Nothing appears on screen. The chat log is always blank.
- **Unable to receive registration code through SMS:** I could receive it through call only. In the same day, I could received the code by SMS using OpenWapp.
- **Sidebar not working:** When I click the hamburger menu icon, the whole screen darkers a bit. But nothing appears. When I touch the dark overlay, suddenly the sidebar shows up, going to hide itself on the left side of the screen.

**Comment by TitanNano** [comment]
I don't think Loqui can run on v1.1 anymore. 1.1 is deprecated for years.

**Comment by jesobreira** [comment]
Hi! Thanks for your response!

Sad to know that 1.1 is already considered deprecated. Actually 1.1 is the only FxOS version being sold on many countries, like mine (Brazil).

But it's ok, not Loqui's fault and not Mozilla's fault too. But it would be interesting if you guys could add FxOS > 1.1 as requeriment on Marketplace, so people at SuMo (mainly pt-BR) stop saying bad things about FxOS whereas it's the manufacturers that aren't accomplishing with the compromise of updating their devices. OpenWapp is still working on 1.1.. I just hope it works for enough time until [someone make a build](https://github.com/FxOSBuilds/fxosbuilds.github.io/issues/9).

**Comment by TitanNano** [comment]
@cmeerw can you add an hint that v1.1 is not supported anymore? I will test other versions and see if they still work.

**Comment by cmeerw** [comment]
I have added "Supported on Firefox OS 1.3 or later" to the description. @jesobreira could you have a look at the portuguese description and let me know what to add there?

**Comment by jesobreira** [comment]
Sure! In portuguese, that sentence could be "Compatível com Firefox OS 1.3 ou superior".

**Comment by cmeerw** [comment]
Text has been added to portuguese marketplace description, closing...
