### ISSUE TITLE
[whatsapp] groups blocked for others

### ISSUE THREAD

**Issue by LeaFin** [loqui/im#896]
On whatsapp groups in which i'm member, no one apart from me can send messages since the whatsapp update last week. They get my messages but not each others. Any clue?

**Comment by LeaFin** [comment]
I'm on firefox os 2.0 and the newest loqui version on marketplace

**Comment by TitanNano** [comment]
What WhatsApp versions are the other participants are using? e.g. WhatApp for Android v2.12.366

**Comment by cmeerw** [comment]
There is a real problem with groups and encrypted messages... Just noticed myself that I get some messages in a group only encrypted (and the "plaintext-only" workaround doesn't seem to work here).

It's actually very weird. One person posted messages in 2 different groups - in one group I got a plaintext message and in the other group I got an encrypted messsage. So not entirely sure what it depends on whether the message is sent encrypted/plaintext.

**Comment by Honk2** [comment]
I just want to confirm, that I have the same problem. Since a week ago, I am the only one who can write plain text into groups. 
The others (all running Android) actually can only write to the group, when they post am image and write a comment to that image. But I will only receive the image, not the text. When I leave the group or they kick me out of the group everything is normal again.

I tried to runn Loqui in the emulator in WebIDE and it worked for some time, but not today.
I tried OpenWapp on my phone and It works. Everyone can write into the groups.

Installing OpenWapp in the emulator I noticed a difference to Loqui (not sure if this is important neither is a hint): Loqui can be installed and activated by receiving a SMS on another phone (not even a smartphone). But OpenWapp will complain that the carrier cannot be determined and that running OpenWapp on a differemt device could cause unpredictable problems.

**Comment by cmeerw** [comment]
@Honk2 I am still not sure I understand you correctly - how is a "comment to an image" different to any other text message in the group? What happens if they want to write a text message in a group that isn't a comment to an image?

**Comment by Honk2** [comment]
If you send an image with the official client, you can add some text to that image before you send it. Image and text a send together.
If they try to send a plain text message, the message is not send, that is no check mark is showing next to the text.
Maybe the encryption is different (on/off) if sending other contend than plain text?

**Comment by cmeerw** [comment]
Thanks for the clarification, that makes some sense now.

Media/image messages are not encrypted at all.

**Comment by Honk2** [comment]
Thus this is an encryption issue?
The console ouput in #895 is taken from a conversation where this happend. Maybe it can help?

**Comment by Honk2** [comment]
Another hint:
With the last WhatsApp update my online status became visible to the others.
Before the online status was not avaiable to them.

**Comment by cmeerw** [comment]
Ahh ok, I can see why OpenWapp still works for group conversations.
Loqui currently identifies itself as S40-2.13.20 whereas OpenWapp
identifies itself as S40-2.13.9. This makes the WhatsApp servers
believe that Loqui supports encrypted group messages which it doesn't.
Unfortunately, there is no real fix for this (other than implementing
encryption support which is a lot of work) as at some point in the
near future WhatsApp will stop allowing connections with S40-2.13.9
and OpenWapp will need to update and have the same issue with group
conversations.

**Comment by Honk2** [comment]
So there is no real alternativ than implement encryption?
But what I do not understand is why do the others cannot write in the groups? They are all using the official client.
Even now when I am not loged in/ Loqui not installed and running, others cannot write.

**Comment by Honk2** [comment]
By the way: what is S40-2.13.x?
The current WhatsApp version is 2.12.367

**Comment by cmeerw** [comment]
Who created the group? you or someone with an Android phone?

S40-2.13.x is the WhatsApp version for Nokia S40

**Comment by Honk2** [comment]
The groups were all created by androids.
I will try later what happens with groups created by Loqui.

**Comment by Honk2** [comment]
I just made some tests for completeness:
- Android creates a group, all can write until a Loqui user joins.
- OpenWapp creates a group, same result.
- Loqui creates a group, no one can write.

@cmeerw You are right, it seems to be the missing encryption excepted by Version 2.13.x
You mentioned that encryption support is a lot of work. How can I help?

**Comment by cmeerw** [comment]
The workaround is to set tokenData "r" to "2.13.9" (but still keep the version numbers in "v" and "u" up to date) - I might even do that for the marketplace version.

For encryption there is https://github.com/joebandenburg/libaxolotl-javascript which appears to implement the underlying protocol (and there is, of course, https://github.com/tgalal/yowsup/ ), so it might "just" be a case of integrating it into Loqui.

**Comment by Honk2** [comment]
Just tested the 'r' tokenData work around  and it works fine.

**Comment by TitanNano** [comment]
I'm closing this, since everything seems to work fine now. Feel free to reopen if the issue still occurs.
