### ISSUE TITLE
Improve UI using Lungo

### ISSUE THREAD

**Issue by nukeador** [loqui/im#9]
After investigating about mobile app frameworks, I was amazed about the speed and versatility of creating the UI using Lungo (instead of jquery mobile):

http://lungo.tapquo.com/

There is also a hangout in Spanish presenting it:

https://www.youtube.com/watch?v=EwmJ88Nq600

I think this could speed up the UI creation for loqui :D

**Comment by aesedepece** [comment]
At the moment no UI framework is being used by LOQUI.
But I do really like what I've seen so far from Lungo, so I personally agree to your suggestion and study the feasibility of adopting it in short.
Thanks for all!

**Comment by aesedepece** [comment]
I've started porting LOQUI to Lungo in a separated branch. It's delightful! 
You'll see Lungo in the master branch as soon as possible :D

**Comment by aesedepece** [comment]
Just finished preliminary port to Lungo ;)
