### ISSUE TITLE
Can't turn off app

### ISSUE THREAD

**Issue by soapdog** [loqui/im#90]
The 'turn off' icon on the left side icon bar is disabled. The app is logged on facebook and uses alarm API to keep itself alive. I can't turn off the app. The application came back up even after I reboot the phone. The only way I found to turn the app off was to uninstall the app.

**Comment by Gioyik** [comment]
Which version are you using? Can you debug it and coy here what you are seeing?

**Comment by soapdog** [comment]
I've removed the app, that was the only way to quit it. I will reinstall it. The quit button should never be disabled. There should always be a way to cancel the Alarm API scheduling.

After reinstalling I will try to produce some logs.

**Comment by aesedepece** [comment]
The quit button is never intentionally disabled. Only case in which it may become unresponsive is when any unhandled Javascript exception occurs (this stops every touch event by default).

I mean: this is indeed a symptom of some other bug. I'd appreciate if you could provide some logs. Thanks.

**Comment by Gioyik** [comment]
@soapdog Could you reproduce it again? Could you post us some logs if you reproduce this?

**Comment by cristodcgomez** [comment]
I can't use button also on custom compilation of Firefox OS 1.1 over a huawei ascend G300... maybe UI bug?

I'll try to put logcat whne i arrive to home.

**Comment by Gioyik** [comment]
@soapdog & @cristomc could you provide logs related to this issue? Is important to know if this is a issue or not to include or not a fix in the next version.

Thanks

**Comment by Gioyik** [comment]
News about this issue? Could you/both provide us a logcat that shows us the possible problem with the button? In the last version you continue having this problem?

**Comment by Gioyik** [comment]
The UI is changed and nobody reports this problem anymore. If this happens again, comment this issue to reopen it.
