### ISSUE TITLE
Scrolling issues on chat with fx0

### ISSUE THREAD

**Issue by FabianOvrWrt** [loqui/im#910]
I bought an fx0 and I obviously installed loqui, but I can't move on any conversation unless I disable APZ. Isn't there a workaround for this?

**Comment by TitanNano** [comment]
Which OS version are you on? For me disabling the hardware composer solved the problem on the Geeksphone Peak.

**Comment by FabianOvrWrt** [comment]
I'm on 2.1, I also tried to disable the hardware composer, but it doesn't work. The only way to solve this on the fx0 is to disable the Async Pan/Zoom. But that leaves me with slow scrolling with some lag.

**Comment by TitanNano** [comment]
can you try to upgrade? I don't know what's available for the fx0. you can also try to enable the low quality rendering to get more speed at scrolling...

**Comment by FabianOvrWrt** [comment]
No, latest working version is 2.1, the only way to fix the scrolling is disabling Async Pan/Zoom.
Low quality rendering comes enabled by default.

**Comment by TitanNano** [comment]
I added a new layout structure for FxOS 2.1+ I don't know if this changes anything. But if you want you can give it an other try after you got the latest update from the marketplace, it will be approved soon I assume.

**Comment by FabianOvrWrt** [comment]
I used the git version and nothing changed. I still have the same problem.
Actually many apps do not work, so maybe it's a system issue.

**Comment by TitanNano** [comment]
yes it is indeed.

**Comment by FabianOvrWrt** [comment]
I've discovered something. If you put a character on the chat text field the scrolling starts working.
It's really weird, but it could explain why scrolling doesn't work and maybe you could be able to make a workaround for this in the meantime.
