### ISSUE TITLE
showing profile pictures

### ISSUE THREAD

**Issue by tibtab** [loqui/im#918]
Sometimes when I click on the pb of one of my friends it is displayed to me in the sice of my screen, but sometime it is only displayed very small. This is different from user to user and only can change if someone changes his pb.

**Comment by cmeerw** [comment]
Doesn't that just depend on the size of the picture the user has
uploaded as the profile picture? I'd guess loqui just displays what it
gets as the profile picture (in its original size). Not sure what else
it should do?

**Comment by tibtab** [comment]
no, I asked these persons, if they set in any way, that their profile pcture is only displayed small. And a friend with a 'normal' whatsapp can display the same persons pb large.

**Comment by TitanNano** [comment]
for WhatsApp we save the original picture and a resized version (96x96). When displaying the avatar in full size, we first try to access the original image but I case that's not available we fall back on the resized version. 
Each avatar for a WhatsApp contact in `App.avatars` should contain two properties, `original` and `chunk`.

**Comment by tibtab** [comment]
for somme contacts for me ´´´´original´´´´ is not false but missing

**Comment by tibtab** [comment]
for some persons for me, `original` is not false but simply missing

**Comment by TitanNano** [comment]
is it possible that these contacts didn't update their profile picture for a long time? 
The only reason I can think of is that these avatars never got upgraded...

**Comment by tibtab** [comment]
no, it's more the opposite. these contacts set their profile picture only a few days ago. But it can't have something to do with that, because I had this problem already for monthes

**Comment by TitanNano** [comment]
@tibtab next time your contact changes his / her picture the full size pic should be available.

**Comment by tibtab** [comment]
Ok, that works now, thanks

**Comment by tibtab** [comment]
After the fix, I was able to see all profile pictures in the size of my screen, even when the contacts had not updated them. But now some have and I can only see their profile pics in small size again.
