### ISSUE TITLE
Error en la hora en Whatsapp / Time error on Whatsapp

### ISSUE THREAD

**Issue by mautematico** [loqui/im#92]
¡Hola!
Al chatear conmigo mismo, veo que hay un error en la hora que loqui reporta.

Mientras que en Android, whatsapp dice que estoy en línea,
Loqui IM dice "Última vez: Hoy a las 22:55", y curiosamente 22:55 es la hora actual, +6.
Curiosamente, en México estamos en GMT-6, entonces sospecho que LoquiIM está reportando algo así como la hora GMT.

Adjunto capturas. :)

![shot_000059](https://f.cloud.github.com/assets/1238928/1642414/c9536d2a-5881-11e3-8e75-d6e07846cfc7.png)
![loquiim](https://f.cloud.github.com/assets/1238928/1642415/d0bda864-5881-11e3-809a-ab37a7034d4d.png)

**Comment by mautematico** [comment]
He notado, además, que la hora de "Last seen" no siempre se actualiza.

**Comment by aesedepece** [comment]
Ok, resulta que tenemos dos funciones distintas para las marcas de tiempo, una para la hora local y otra para GMT. En algún lugar se han debido de cruzar y muestra GMT. 

En las pruebas no lo noté por eso de vivir a pocos kilómetros del meridiano de Greenwhich... pero mañana mismo lo arreglo ;)

¡Gracias!

**Comment by mautematico** [comment]
Algo así imaginé. Mientras tanto, será divertido que los amigos escriban desde el futuro. :P

¡Gracias a ti por el excelente trabajo!
