### ISSUE TITLE
[WhatsApp] Authentication failed

### ISSUE THREAD

**Issue by cmeerw** [loqui/im#925]
This is very bad now. WhatsApp doesn't seem to allow logins with "S40-2.13.9" as the resource string any more. Updating the resource string to something current like "S40-2.13.30" kind of works, but results in encryption being turned on for group messages (which we can't handle). Using an invalid or empty resource string still appears to work, but I am not sure if this would have other side effects (maybe increase the likelihood of getting blocked completely at some point?), so am a bit reluctant to do this...

**Comment by 03927e9c** [comment]
Yes I cant log in... tried re-sending SMS and it's the same.

**Comment by sotitrox** [comment]
Me too can't login anymore

**Comment by jambolo1970** [comment]
Me too "login faillure" is the message with alcatel fire e from italy

**Comment by decode-dev** [comment]
Cannot Login.
If many attempts done. 
You get locked for a small fixed time.

**Comment by luizbills** [comment]
+1

**Comment by divyaadupala** [comment]
Iam also facing the problem that athentication failed in watsapp

**Comment by Boersenfeger** [comment]
All Users are affected.
We have to wait until the developers have found a solution.
Other applications for WhatsApp also not work.
Read the Comment from cmeerw on Top of this Page....

**Comment by 03927e9c** [comment]
They won't find a solution if they don't look for it....

**Comment by cmeerw** [comment]
@03927e9c comments like yours make me think it's not worth spending my time on this. I have already outlined the options in my initial post, none of these are perfect - I was actually looking for some ideas or comments on these, but haven't seen any so far. The only thing I see is people complaining - very disappointing!

**Comment by sotitrox** [comment]
Please, we dont are developers, please we dont have another application :(

**Comment by Boersenfeger** [comment]
@cmeerw : Maybe, he means, that WhatsApp Developers are not interested for finding Solution. On the other hand, take my thanks and recognition as an incentive.
BTW: The new Version of OpenWapp works... at this Time.

**Comment by JordanSBen** [comment]
Well even I'm having the same issue ever since i reset my phone and installed Loqui IM again :(

**Comment by Honk2** [comment]
@cmeerw and all other contributors please do not get too frustrated by comments like above. I really appreciate your affort and work. 
imho most people do not see the complexity of the problem or the root cause and simply blame the effect.
please go on! I do not want to use any other phone not running Firefox OS.

**Comment by cmeerw** [comment]
So the good news is that 2.13.21 (this is the version OpenWapp uses) does still work. The bad news is that this will just delay the time when we will have a major issue.

And the other bad news is that the Firefox Marketplace is still broken, see https://bugzilla.mozilla.org/show_bug.cgi?id=1241270

**Comment by cmeerw** [comment]
BTW, here is something that everyone can do: start Loqui in WebIDE and then do

CoSeMe.config.tokenData.r = 'S40-2.13.30'

and reconnect. And then test if they can still receive group messages (some of them might be missing). And compare that with:

CoSeMe.config.tokenData.r = 'S40-2.13.21'

Feel free to test with any other strings/versions and report results.

**Comment by gutentach** [comment]
No problem with v0.4.14a. group messages work to for me.
Thank you

**Comment by cmeerw** [comment]
@gutentach are you able to test with other version numbers in tokenData.r as well? Because at some point 2.13.21 will stop working (current version is actually 2.13.30) and then we really don't know what to do any more...

**Comment by gutentach** [comment]
@cmeerw   i start loqui in webide, but i dont now how i chance or insert the CoSeMe.config.tokenData.r = 'S40-2.13.30'

**Comment by cmeerw** [comment]
@gutentach there is a "Debug App" button in the toolbar which should give you a JavaScript console - just paste the code at the prompt and then reconnect.

**Comment by Honk2** [comment]
.30 is working fine for me.
Also groupchats seem to work.

**Comment by Honk2** [comment]
@cmeerw you mentioned libaxotol-js some while ago. Would it work? What needs to be done to use it? Can you splitt the needed work into smaller parts?

**Comment by cmeerw** [comment]
@Honk2 the thing with the group chats is that it seems to depend on the sender and on the group (messages from the same sender arrived encrypted in one group, but plain text in another group).

regarding libaxotol-js - I still believe it should do most of the hard work, but there is still quite a bit of work to integrate it into loqui/coseme. Main thing is that loqui will need to store keys and handle any messages to do with key generation and key updates for other users. But I haven't really looked into any details...

**Comment by 03927e9c** [comment]
When will it be pushed to MP?

**Comment by cmeerw** [comment]
As stated in https://github.com/loqui/im/issues/925#issuecomment-174310579 once https://bugzilla.mozilla.org/show_bug.cgi?id=1241270 has been fixed.

**Comment by RomiZur** [comment]
What can I do if I want the app works?? Can somebody help me?? Thanks

**Comment by AlexLikeRock** [comment]
if market place not work.
how to input NEW VESION to my firefox?
cloud you add a tutorial / link tutorial ?
please. tankyou

**Comment by Chris78** [comment]
Regrettably I cannot connect since last weekend as well. 
Good luck to the developers here. I hope you can find a fix for this. Keep it up!

@AlexLikeRock: For me the following works: After a reboot of my phone (GP Revolution, FFOS 2.0) I get notified about updates for apps like Loqui, Calculator, Notices, etc.). So try to restart your device.

**Comment by sagardahale** [comment]
Please just tell me, how much time you will take to upload latest version of loqui on marketplace!

**Comment by sagardahale** [comment]
Plz tell me exact time

**Comment by cmeerw** [comment]
@sagardahale exact time will be Friday 29th January 18:43:27 GMT and then it will stay in the review queue till 9th March 21:11:52 GMT by which time the fix will be obsolete.

Does anyone ever read the previous comments here? Like https://github.com/loqui/im/issues/925#issuecomment-174310579

**Comment by sagardahale** [comment]
@cmeerw can you help me, so that v0.4.12a will work?
Thank you.

**Comment by cmeerw** [comment]
@sagardahale get the release from https://github.com/loqui/im/releases or read the other comments, i.e. https://github.com/loqui/im/issues/925#issuecomment-174310940

**Comment by sagardahale** [comment]
@cmeerw can i install v0.4.14a from release?
Thank you.

**Comment by Chris78** [comment]
Don't know if this could be some helpful information but I just installed "OpenWapp" via Marketplace and it was no problem to connect to WhatsApp. 
Maybe you could have a look at the authentication part of the code of https://github.com/mozillahispano/openwapp 

Also I do not see any recent commit regarding authentication problems there. 

I just cloned the openwapp repo and grep-ed for "S40" and also for "User-Agent". No matches (exept one test).

**Comment by Boersenfeger** [comment]
.. it works since Sunday... read my Comment :-))

**Comment by Chris78** [comment]
@Boersenfeger: Oops! tldr ;)

**Comment by sagardahale** [comment]
@Boersenfeger i downloaded openwapp..but whenever i open it, screen gets black...now how can i fix it?

**Comment by Chris78** [comment]
@sagardahale: https://github.com/mozillahispano/openwapp/issues/198

**Comment by sagardahale** [comment]
@chris78 its latest version...1.9.5

**Comment by Chris78** [comment]
@sagardahale: You're in the wrong place here. Please post your experience under mozillahispano/openwapp#198

**Comment by sagardahale** [comment]
Can anyone tell me, how much time will be take to fix loqui im login problem?

**Comment by Chris78** [comment]
No, nobody will be able to tell you, since it depends on https://bugzilla.mozilla.org/show_bug.cgi?id=1241270 
So watch that bug.

**Comment by Honk2** [comment]
@sagardahale as mentioned above, connect phone to PC, start WebIDE, enable ADB on your phone, connect with WebIDE, start loqui, open console use command mentioned above.
Read on MDN for a detailed how to.
Or read the wiki: how to build loqui and copy that version to your phone using WebID.

**Comment by sagardahale** [comment]
Can you help me to do it step by step...because its all new for me...

**Comment by sagardahale** [comment]
Can i fix loqui v0.4.12a authentication fail problem using webIDE? please someone tell me how

**Comment by cmeerw** [comment]
0.4.14 is now available from the Marketplace

**Comment by 03927e9c** [comment]
Thanks @cmeerw now I don't get an error but the SMS won't arrive.

**Comment by Chris78** [comment]
Hmm, got the update (0.4.14a) but unfortunately I still get the authentication error (tested on GP Revolution with FFOS 2.0). Do I need to reinstall the app or remove the whatapp account and register again via SMS?

**Comment by Chris78** [comment]
Ah yes, after removing the WhatsApp account inside Loqui and adding it again, SMS etc. I can connect again!
_applause_ and muchas gracias, cmeerw!

**Comment by cmeerw** [comment]
I have checked in some code now to allow Loqui to update the tokenData information on the fly... Only problem is I am not sure if it will be of much help, as I am not sure we will be able to find a working string once the current one stops working...

**Comment by YunitoMH** [comment]
It happened again now on FFOS and OpenWapp doesn't work neither.

Could you check it?

**Comment by tibtab** [comment]
Same Issue here #982
