### ISSUE TITLE
Whatsapp Authentication Error/Failed

### ISSUE THREAD

**Issue by JordanSBen** [loqui/im#927]
Hey guys. I have a Zen 105 Fire and I'm having trouble with Whatsapp Authentication. It's happened ever since I reset my phone and installed Loqui IM again. The Authentication SMS wont go through. 

Please help!!!!
Thanks

**Comment by petzichen** [comment]
https://github.com/loqui/im/issues/925

**Comment by petzichen** [comment]
Duplicate: https://github.com/loqui/im/issues/925

**Comment by JordanSBen** [comment]
#petzichen  Thanks for the help :).  Well unfortunately it wont do me any good :(.  

Thanks anyway
