### ISSUE TITLE
Message text area too small when keyboard is present

### ISSUE THREAD

**Issue by nukeador** [loqui/im#93]
Font size on message text area box is too small when the keyboard is visible, in fact all app text is reduced when the keyboard is present.

**Comment by aesedepece** [comment]
¿FirefoxOS version? I saw this happening with the first 1.2 releases, but I think it was already fixed.

**Comment by nukeador** [comment]
Keon 1.3 nightly.

**Comment by aesedepece** [comment]
I'll take a look. 1.3 nightly on Peak is OK.

**Comment by Gioyik** [comment]
I tested on Peak 1.3 and Keon 1.3 and seems to be OK. Some nightly's from geeksphone had broken features, to me, nightly's sometimes shows me a black screen in the middle of the display when I use the browser.

**Comment by willyaranda** [comment]
Keon 1.2 from GP affected also.

**Comment by Gioyik** [comment]
Could someone provide a screenshot? @nukeador @willyaranda

**Comment by nukeador** [comment]
For some reason my Keon 1.3 is unable to save screenshots :S

**Comment by nukeador** [comment]
Screenshot
![small-text](https://f.cloud.github.com/assets/531906/1649677/0d653d68-5a1c-11e3-928a-17f555ec245a.png)

**Comment by Gioyik** [comment]
This happens to me in landscape screen in v1.3. I thought that it was a FirefoxOS problem. 

![2013-11-30-19-48-50](https://f.cloud.github.com/assets/1834718/1649732/d561a0da-5a22-11e3-9635-1da24d3bd36a.png)

**Comment by aesedepece** [comment]
Landscape in 1.2/1.3 is broken for me as well, portrait is just fine.

I'm pretty sure the bug resides in Gaia. It isn't calculating the screen dot-per-inch properly, so the screen width is reported to be greater than 960, which is the limit for the media query that fits qHD mobile devices like Peak.

**Comment by Gioyik** [comment]
Yah! Can we close it? Is a problem in Gaia and not a problem with Loqui.

**Comment by aesedepece** [comment]
We can implement a provisional workaround and the only problem would be getting bigger screen elements when used on PC with screen width over 960px. Virtually nobody uses Loqui on PC or tablets, so I think it's not such a problem.

**Comment by Gioyik** [comment]
Sometimes i use Loqui on PC and it works perfectly.

![captura de pantalla de 2013-11-30 22 01 24](https://f.cloud.github.com/assets/1834718/1649831/e706aaa8-5a34-11e3-8d28-65ec8dbe6f01.png)
