### ISSUE TITLE
Whatsapp not working

### ISSUE THREAD

**Issue by jeancayron** [loqui/im#931]
Since 25/01/2016 it is not possible any more to connect to Whatsapp.
It constantly says "Authorisation failed". If you remove your account, it is not possible to reinstall it on loqui want it gives the same message after pushing on verify code or verify by SMS.

Whould Whatsapp have changed something on their API?

**Comment by cmeerw** [comment]
0.4.14 has been uploaded to the Marketplace today, please re-test with that version.

**Comment by jeancayron** [comment]
Sorry. I didn't check the closed issues. Thanks for the update.
