### ISSUE TITLE
Facebook chat not working

### ISSUE THREAD

**Issue by jeancayron** [loqui/im#932]
Since december 2015 it is not possible any more to connect to Whatsapp.
It constantly says "Authorisation failed".
The same problem occurs on my Linux system with telepathy. Facebook might have changed something to their API?

**Comment by cmeerw** [comment]
do you mean facebook or WhatsApp, in case of facebook it's a duplicate of issue #700

**Comment by jeancayron** [comment]
I meant Facebook. Sad thatit can't be solved.
Thanks.
