### ISSUE TITLE
Area code problem, Dominican Republic

### ISSUE THREAD

**Issue by mundosmart** [loqui/im#934]
Hi,

Im from Dominican Republic, here we use 3 differents area codes(809, 829, 849), when i tried to request the SMS confirmation it only shows 849 as area code. There's a way to change it 809 or 829???

**Comment by TitanNano** [comment]
what are the differences between these codes? We will add then to the list.

**Comment by mundosmart** [comment]
809 wasn't enough because the population grew a lot, the government created 829 and 849 to avoid any future problem if the 809 run out of numbers available

Enviado desde mi iPhone

**Comment by TitanNano** [comment]
I see, but which areas are these codes associated with?

**Comment by cmeerw** [comment]
I guess a workaround would be select US as the country and enter 809 as part of the number.
