### ISSUE TITLE
whats up registration code not recived

### ISSUE THREAD

**Issue by saurabh1103** [loqui/im#948]
please check  registration code not recieved    error shown ( could not sent) while phone & sms verification done    error   ( could not send sms or call for code  )

**Comment by cmeerw** [comment]
do you have any debug logs?

**Comment by stollr** [comment]
Same problem here. Here's my console output:

> "Request: https://v.whatsapp.net/v2/exist?cc=49&in=1xx9xx39xx&id=%F9%88%55%DF%98%0C%7F%44%DB%9A%80%6E%CF%7D%61%17%C3%A7%E4%15&lg=en&lc=GB&token=3cd71732ad5ea3dea68ad20b3d32fc09 ~ _doRequest@app://28712e5a-2bd5-446a-a72b-a6c8d903aba5/scripts/mozillahispano/coseme.js:6008:7 [http]" coseme.js:3561:4
> 
> {"status":"fail","reason":"blocked"} ~ _doRequest/xhr.onload@app://28712e5a-2bd5-446a-a72b-a6c8d903aba5/scripts/mozillahispano/coseme.js:6013:9 [http] coseme.js:3561:4
> 
> "Request: https://v.whatsapp.net/v2/code?cc=49&in=1xx9xx39xx&lc=GB&lg=de&sim_mcc=000&sim_mnc=000&method=sms&token=3cd71732ad5ea3dea68ad20b3d32fc09&id=%F9%88%55%DF%98%0C%7F%44%DB%9A%80%6E%CF%7D%61%17%C3%A7%E4%15 ~ _doRequest@app://28712e5a-2bd5-446a-a72b-a6c8d903aba5/scripts/mozillahispano/coseme.js:6008:7 [http]" coseme.js:3561:4
> 
> {"status":"fail","reason":"blocked"} ~ _doRequest/xhr.onload@app://28712e5a-2bd5-446a-a72b-a6c8d903aba5/scripts/mozillahispano/coseme.js:6013:9 [http] coseme.js:3561:4
> 
> [l10n] #SMSreason_blocked is undefined. l10n.js:68:6

It seems lika I have been blocked by WhatsApp. Is there anything I can do about it?

**Comment by stollr** [comment]
I have sent a mail to WhatsApp support with the request to reactivate my account.

**Comment by cmeerw** [comment]
Closing, nothing that can be done if account is blocked...

**Comment by gabriel-lucas** [comment]
Same issue here.

@naitsirch did you managed to get your account reactivated?

qml: [JS](file:///opt/click.ubuntu.com/com.ubuntu.loqui.im.loqui/0.5.9/www/scripts/mozillahispano/coseme.js:3561) Request: https://v.whatsapp.net/v2/exist?cc=34&in=XXX&id=%06%45%EB%4C%E9%96%4A%35%56%1C%B5%12%D6%A8%07%7A%45%53%D9%7F&lg=en&lc=GB&token=c9c25f32b52d3eb7cedf6e8588871e21 ~     at Logger.CoSeMe.namespace.Logger.log (file:///opt/click.ubuntu.com/com.ubuntu.loqui.im.loqui/0.5.9/www/scripts/mozillahispano/coseme.js:3477:10) [http]
qml: [JS](file:///opt/click.ubuntu.com/com.ubuntu.loqui.im.loqui/0.5.9/www/scripts/mozillahispano/coseme.js:5995) Refused to set unsafe header "User-Agent"
qml: [JS](file:///opt/click.ubuntu.com/com.ubuntu.loqui.im.loqui/0.5.9/www/scripts/mozillahispano/coseme.js:3561) {"status":"fail","reason":"blocked","login":"XXX"} ~     at Logger.CoSeMe.namespace.Logger.log (file:///opt/click.ubuntu.com/com.ubuntu.loqui.im.loqui/0.5.9/www/scripts/mozillahispano/coseme.js:3477:10) [http]
qml: [JS](file:///opt/click.ubuntu.com/com.ubuntu.loqui.im.loqui/0.5.9/www/scripts/mozillahispano/coseme.js:3561) Request: https://v.whatsapp.net/v2/code?cc=34&in=XXX&lc=us&lg=en&sim_mcc=000&sim_mnc=000&method=sms&reason=&token=c9c25f32b52d3eb7cedf6e8588871e21&id=%06%45%EB%4C%E9%96%4A%35%56%1C%B5%12%D6%A8%07%7A%45%53%D9%7F ~     at Logger.CoSeMe.namespace.Logger.log (file:///opt/click.ubuntu.com/com.ubuntu.loqui.im.loqui/0.5.9/www/scripts/mozillahispano/coseme.js:3477:10) [http]
qml: [JS](file:///opt/click.ubuntu.com/com.ubuntu.loqui.im.loqui/0.5.9/www/scripts/mozillahispano/coseme.js:5995) Refused to set unsafe header "User-Agent"
qml: [JS](file:///opt/click.ubuntu.com/com.ubuntu.loqui.im.loqui/0.5.9/www/scripts/mozillahispano/coseme.js:3561) {"status":"fail","reason":"blocked","login":"XXX"} ~     at Logger.CoSeMe.namespace.Logger.log (file:///opt/click.ubuntu.com/com.ubuntu.loqui.im.loqui/0.5.9/www/scripts/mozillahispano/coseme.js:3477:10) [http]
qml: [JS](file:///opt/click.ubuntu.com/com.ubuntu.loqui.im.loqui/0.5.9/www/scripts/fabi1cazenave/l10n.js:68) [l10n] #SMSreason_blocked is undefined.

**Comment by stollr** [comment]
Yes, it was reactivated after some time (something about two months).
But I have changed my OS to CyanogenMod, as Firefox OS 2.2 had too many bugs for me. Now I am using the official WhatsApp client.
