### ISSUE TITLE
Formato de número de Whatsapp en México (y quizás otros)

### ISSUE THREAD

**Issue by mautematico** [loqui/im#96]
En México, hay un problema con los números de Whatsapp.

Los números nacionales en México son de diez dígitos, y el código internacional oficial de México es +52, formando asi un número de 12 dígitos. Pero en la práctica es necesario agregar un decimotercero.

Según puedo ver en la ficha de contacto que Loqui pone a mis contactos de Whatsapp, cuando éstos son identificados así:
520123456789@s.whatsapp.net no reciben los mensajes. De hecho, en este caso Loqui muestra "No disponible"
Experimenté a agregar el 1 en la ajenda de contactos, y ahora Loqui los identifica así:
5210123456789@s.whatsapp.net y sí llegan los mensajes.

Además, cuando desde mi Android escribí a mi Firefox OS, Loqui dijo que el mensaje era de un tal "5210123456789@s.whatsapp.net", de 13 dígitos.

Cosas importantes a considerar:
En México acostumbramos a guardar los números de celular de nuestros compatriotas de alguna de estas tres formas:
0123456789
52 0123456789
52 1 0123456789
En ese orden de popularidad.

Sugiero entonces que Loqui revise si el usuario usa un número de México, y al sincronzar los contactos (si corresponde) agregue el 1 o no. En resumen, que a los contactos con número de México los "transforme" en su formar de 13 dígitos, que al parecer es como los identifica Whatsapp.

Nota: Sospecho que en otros paises ocurrirá algo similar. Esta podría ser la causa de que muchos usuarios reportan que "no llegan" los mensajes, y quizás hasta los SMS de confirmación en algunos paises.

**Comment by mautematico** [comment]
Propongo esta **solución temporal** para quienes usan Loqui IM en México y ven que sus contactos están "No disponibles":

En la agenda de contactos, modifica los contactos de tus amigos que usan Whatsapp y agrega un 1 al inicio, para que quede de **11 dígitos**, ejemplo:

**Antes de la modificación:**     55 5555 5555
**Después de la modificación:** 1 55 5555 5555

**Comment by mautematico** [comment]
Creo que la salida rápida para este y el caso potencial en otros países será usar un fake.internationalcode.
En este caso, sería reemplazar +52 por +521, que es lo que han hecho los de ConnectA2.

No es la mejor solución, pero resolvería el problema para buena parte de los casos. Y daría tiempo a diseñar una solción más pulida.

**Comment by cargabsj175** [comment]
Hola, en Venezuela se presenta algo distinto, aunque ahora toma de forma correcta 58xx, genera un guión (-) generando un número como este, 584xx-yyyzzzz@whatsapp.net en lugar de 584xxyyyzzzz@whatsapp.net que sería el correcto.

Saludos.

**Comment by gps1mx** [comment]
Me parece que la forma de solucionar el problema sería modificar /scripts/goles/countries.json en la línea 136 y cambiar "52" por "521".

**Comment by aesedepece** [comment]
Para más info: #99

**Comment by ActiveMeX** [comment]
Cómo puedo modificar el archivo /scripts/goles/countries.json ?, tengo un Alcatel OneTouch.

Saludos !!!

**Comment by aesedepece** [comment]
@ActiveMeX No va a hacer falta, hemos cambiado de librería de formateo de números y en la próxima versión 0.2.6 ya debería aceptar perfectamente los números de Mexico y otros países problemáticos.

**Comment by gps1mx** [comment]
@aesedepece pues parece que el cambio en la librería de formatéo de números no funcionó para México (al menos para mi). :(

Alguna alternativa?

**Comment by octaviobernalquiroz** [comment]
Confirmo que el formateo de números no funcionó para México

**Comment by Albertobenz** [comment]
Hola, aunque ha pasado algo de tiempo desde el ultimo posteo, para reportar que al parecer aun no funciona el formateo de números para México, o tal vez me falte alguna actualizacion, tengo la version 0.2.6 de Loqui IM, si uso la solución temporal de poner un 1 antes del numero de mi contacto no puedo realizar llamadas normales. Saludos desde México

**Comment by aesedepece** [comment]
Esto queda totalmente arreglado no sólo para México sino para cualquier otro al añadir la función de sincronización nativa de WhatsApp (commit ce0e6cde6bb2dc9bcfe85d84e5d7ad39f21d3349).
