### ISSUE TITLE
Loqui IM identifica únicamente el primer número de la ficha de contacto para Whatsapp, e ignora el resto.

### ISSUE THREAD

**Issue by mautematico** [loqui/im#97]
En mi agenda de contactos tengo varios con varios números de teléfono.
En algunas ocasiones, varios de esos números son números válidos de Whatsapp.

Loqui IM, al sincronizar los contactos, aparentemente revisa sólo si el primero de esos números es o no de Whatsapp, e ignora los números restantes.

**Comment by aesedepece** [comment]
¿Cuál crees que debería ser el comportamiento más natural para ese caso? De momento no se ha tomado una decisión al respecto...

**Comment by mautematico** [comment]
Incluso me parece un caso con prioridad baja.
Apostaría que entre los usuarios de android un caso como el que expongo es más bien poco frecuente. Es decir... ¿quién tiene más de un número de Whatsapp? ¿quién tiene más de un número de contacto para la misma persona?

Pero esos casos existen. Lo que hace Whatsapp apara android es, para cada contacto, revisar cada cada número, y si lo tiene registrado lo agrega.
Luego, cuando en Whatsapp para android ves la lista de contactos, verás el mismo nombre aparecer varias veces (una vez para cada "identidad").
Además de lo anterior, Whatsapp tiene una ficha de contacto donde agrupa a todos estos repetidos y los muestra juntos, y te muestra todos sus números permitiéndote: SMS, llamada, Whatsapp.

No es el comportamiento más natural, pero es el comportamiento que ya adoptó Whatsapp para Android.

**Comment by willyaranda** [comment]
Yo soy de esas personas que tendrían un "Adán Sánchez" con 2 teléfonos y no un "Adán Sánchez CASA" y "Adrán Sánchez MÓVIL". Aunque la verdad, no sé qué usará la gente de forma más normal (creo que lo segundo, pero bueno, voy a preguntar).

Igualmente, creo recordar, que WhatsApp permite comprobar si un número de teléfono está o no en su sistema, por lo que podrías iterar en un worker (para no joder la UI) mirando qué contactos tienen teléfonos y si están en el sistema (no importar todos, por ejemplo).

La putada (como hay en otro issue), es la "normalización" de números. Andreas Gal hizo una librería para normalizar, pero no sé si vale para los números de whatsapp o no, la verdad.

Puedo mirar más ambas cosas, y darte una solución

**Comment by willyaranda** [comment]
Resultados de la encuesta científica:

1) Me ha comentado gente (amigos de toda la vida, de mi pueblo, todos usuarios de WA) que tienen contactos duplicados, de la manera: "Adán Casa" y "Adán Móvil"

2) Pero la gente de Madrid, todos tienen el "Adán" con dos números dentro :)

Creo que entonces habría que comprobar por cada contacto todos los teléfonos y mostrar aquellos que tienen WA (que como digo, creo que hay una API para comprobarlo).
