### ISSUE TITLE
Loqui IM malinterpreta los números en formato internacional.

### ISSUE THREAD

**Issue by mautematico** [loqui/im#99]
Relacionado con #96 

Es usual que los contactos en el teléfono estén en formato nacional, pero también a veces están en formato internacional, agregando el prefijo internacional del país.

En mi caso particular, tenía un contacto de México en formato internacional (mi número es también de México).

Número nacional: 0123456789 (diez dígitos).
Código internacional: +52

Número que tenía guardado: +52 0123456789 (doce dígitos).

Número que interpretó Loqui IM:
52 52 0123456789 @ s.whatsapp.net (catorce dígitos)
Número que debió interpretar Loqui IM:

52 1 0123456789 @ s.whatsapp.net (trece dígitos, notar el **1** que está entre el código internacional y el número nacional)

**Comment by aesedepece** [comment]
Sí, directamente le añade el prefijo internacional (52 en tu caso) sin comprobar si ya lo tienen aplicado.

Estoy hay que corregirlo también en breve. Gracias de nuevo.

**Comment by mautematico** [comment]
El comportamiento esperado sería el siguiente:

Si el número **no** inicia con "+",
--verificar si es un caso como el #96 y hacer las modificaciones necesarias.
--añadir el prefijo internacional del país que el usuario indicó al instalar.
Ahora tenemos el número en formato internacional.

**Comment by deimidis** [comment]
Algo similar ocurre con los números en Argentina, que se les agrega un 9 entre el internacional y el nacional. Por ejemplo, para enviar un mensaje al 11 5555 5555 hay que hacerlo al +54 9 11 5555 5555 (siendo el 11 la característica de la provincia/estado). En mi caso no está entendiendo los números (aunque si los grupos, que los tomó perfectamente)

**Comment by mautematico** [comment]
@deimidis mira el #96, sospecho que lo que ocurre es similar.

Vayamos armando una lista exhaustiva de países en los que se reporta este problema, que han de ser varios.

**Comment by willyaranda** [comment]
https://github.com/andreasgal/PhoneNumber.js

**Comment by deimidis** [comment]
Probé esta solución. Compré una sim nueva, para probar con un nuevo teléfono. Recibí el mensaje de Whatsapp con el código, pero el círculo aparece siempre gris y en lugar de como aparece el número cuando sirve, le saca el 9 en la representación. El número además no aparece como ususario registrado cuando agrego el contacto en otro teléfono

**Comment by Gioyik** [comment]
@deimidis Si le envias un mensaje a ese numero nuevo, te llega?

**Comment by deimidis** [comment]
No, no llega a aparecer como conectado. Y no lo reconoce Whatsapp (si te referís a un SMS si llega)

**Comment by aesedepece** [comment]
I think this can now be closed.
@mautematico can you test if the @aarizkuren's patch works to you?

**Comment by juaneladio** [comment]
Confirmo que el mismo problema ocurre en Perú. Tenía números con código internacional (usando +51, que es el código para Perú) y en el contacto de Whatsapp aparece 5151(número). También probé sin incluir 51 como contacto e igual vuelve a pasar.

**Comment by juaneladio** [comment]
![2013-11-30-22-53-49](https://f.cloud.github.com/assets/547722/1651780/2dde2ad2-5aee-11e3-88f0-b0a69dca12c8.png)

**Comment by ThePhoenixBird** [comment]
Venezuela tenemos codigo +58 y numero de teléfono de 11 dígitos (041x-xxx-xx-xx), es normal que tengamos en la agenda de contactos los numeros en formato nacional, pero en discado internacional no se coloca el prefijo 0 que tienen todos los números lo cual quedaría como: +58 41x xxx xx xx

**Comment by Gioyik** [comment]
@juaneladio Podrias probar Loqui desde el codigo que tenemos en master en este momento que ha enviado @aarizkuren? Para saber si el problema se ha solucionado con el fix que se ha enviado :)

**Comment by isalcedo** [comment]
¿Como puedo aplicar el Patch a la aplicación instalada en mi OT4012 (Alcatel Fire)?

**Comment by juaneladio** [comment]
@Gioyik confirmó que la versión actual (acabo de bajar y probar) es una solución parcial. 

Me explicó: en mi país (Peru) el código es 51.
- Si el nro añadido tiene +51(nro-de-movil) entonces lo añade correctamente.
- si el nro añadido tiene +57(nro-de-movil) (57 es el código de Colombia) el contacto se genera mal en Whatsapp: 5157(nro-de-movil).

En resumen, la solución propuesta sólo funciona para números 'nacionales', no internacionales.

**Comment by aesedepece** [comment]
Ayer estuve probando con la librería que mencionó @willyaranda pero tampoco conseguí que funcionase 100% con algunos números de Venezuela o México por las incomprensibles normas de tener que quitar o poner "1" entre el prefijo internacional y el número nacional.

**Comment by willyaranda** [comment]
@aesedepece voy a preguntar a ver si alguien de mi grupo conoce bien el tema de normalización de números y puede comentar algo.

**Comment by borjasalguero** [comment]
@aesedepece Nosotros usamos https://github.com/andreasgal/PhoneNumber.js para normalizar los números y en principio está funcionando sin problema. Para la normalización tienes que recuperar correctamente el par MCC/MNC de la SIM (cuidado que hay dos valores para esto! El de la SIM y el de la RED, y pueden no coincidir -por ejemplo en Roaming-).
Para probar:
http://logofid.es/phonenumberjs_test/

Si no funciona prueba esta otra https://code.google.com/p/libphonenumber/ que es el porting de la que usan en Android a JS. La usamos durante un tiempo y estuvo funcionando también (pero ocupa mucho más espacio).
Para probar tienes:
http://libphonenumber.googlecode.com/svn/trunk/javascript/i18n/phonenumbers/demo-compiled.html

Espero que te sirva! Gracias @willyaranda !

**Comment by aesedepece** [comment]
@borjasalguero Muchas gracias por la explicación. El problema ahora es que PhoneNumber.js contiene un `eval()` y por lo tanto la bloquea la CSP, tal y como he reportado en este issue: https://github.com/andreasgal/PhoneNumber.js/issues/32
