### ISSUE TITLE
Sent messages do not appear in the conversation.

### ISSUE THREAD

**Issue by Zeus76** [loqui/im#994]
When I send a message to a recipient it did not appear in the conversation. When the recipient sends me a message if I get.

[Loqui050.txt](https://github.com/loqui/im/files/195779/Loqui050.txt)

Waiting for news.

**Comment by Zeus76** [comment]
![captura de pantalla de 2016-03-30 16 47 01](https://cloud.githubusercontent.com/assets/15674458/14146854/7add3a32-f699-11e5-96f3-247de618701d.png)
![captura de pantalla de 2016-03-30 16 47 05](https://cloud.githubusercontent.com/assets/15674458/14146865/84bd995c-f699-11e5-81ed-e1f0f45b3ceb.png)

**Comment by cmeerw** [comment]
Interesting... What version of Firefox OS (simulator) are you using?

**Comment by Zeus76** [comment]
I'm using Firefox 1.3. I have same problem in my phone. (Alcatel One Fire C, Firefox 1.3).

**Comment by Zeus76** [comment]
This problem only occurs with a recipient. In other recipients appear the message when I send.

**Comment by Zeus76** [comment]
![2016-03-31-16-12-23](https://cloud.githubusercontent.com/assets/15674458/14179118/14fde8b8-f75e-11e5-9b30-457f5cdff544.png)

Solved. The recipient had an old version of Loqui IM and updated. I've reinstalled. I'm sending messages appear.
